In [1]:
import glob
from pathlib import Path
import pandas as pd
import polars as pl

import aw
import job_search.jobs as jb
import job_search.config as conf
import job_search.scrape as sc
from job_search.config import P_RAW, P_INTERIM
from job_search.utils import now, reload
from job_search.scrape import DA_SF, DS_SF, DA_HEALTH, HEALTH

_now = now(time=False, days=0)
# _now = '2026-04-20'
P_raw_date = P_RAW / _now.replace('-', '/')
P_interim_date = P_INTERIM / _now.replace('-', '/')

In [409]:
reload(sc)

In [414]:
glob_prefix = '../data/interim/2026/05/**'
health_df = sc.load_json_gz(glob_health := f'{glob_prefix}/{HEALTH}/*.json.gz', metadata=True)
ds_sf_df = sc.load_json_gz(glob_ds_sf := f'{glob_prefix}/{DS_SF}/*.json.gz', metadata=True)
da_health_df = sc.load_json_gz(glob_da_health := f'{glob_prefix}/{DA_HEALTH}/*.json.gz', metadata=True)
da_sf_df = sc.load_json_gz(glob_da_sf := f'{glob_prefix}/{DA_SF}/*.json.gz', metadata=True)

In [411]:
health_df.shape[0], ds_sf_df.shape[0], da_health_df.shape[0], da_sf_df.shape[0]

(8809, 8869, 4227, 6683)

In [412]:
from markdownify import markdownify as md

def _process_df(jobs_df):
    jobs_df['_url'] = jb.VIEW_JOB_HTTPS + jobs_df['requisition_id']
    jobs_df['_hash'] = jobs_df['requisition_id']
    jobs_df['_md'] = jobs_df['description']
    jobs_df = (jb.load_jobs(jobs_df)
        .sort_values('estimated_publish_date', ascending=False)
        .dropna(subset='_hash')
        .drop_duplicates(subset='_hash')
        .reset_index(drop=True)
    )#[[*jb.COLS, 'location_latitudes', 'location_longitudes']]
    jobs_df['_md'] = jobs_df['description'].fillna('').map(md)
    return jobs_df

In [428]:
health_df.dropna(subset='requisition_id')[health_df.dropna(subset='requisition_id')['description'].isna()]['st_mtime'].min()

Timestamp('2026-05-16 02:30:17.313909531')

In [421]:
health_df[health_df['description'].isna()]['st_mtime'].min()

Timestamp('2026-05-03 00:33:14.987561941')

In [330]:
health_parquet_df = _process_df(health_df)
health_parquet_df.to_parquet(f'../data/cache/{HEALTH}.parquet')

In [365]:
ds_sf_parquet_df = _process_df(ds_sf_df)
ds_sf_parquet_df.to_parquet(f'../data/cache/{DS_SF}.parquet')

In [361]:
da_sf_parquet_df = _process_df(da_sf_df)
da_sf_parquet_df.to_parquet(f'../data/cache/{DA_SF}.parquet')

In [362]:
da_health_parquet_df = _process_df(da_health_df)
da_health_parquet_df.to_parquet(f'../data/cache/{DA_HEALTH}.parquet')

In [441]:
all_df = (pd.concat([
    health_df,
    ds_sf_df,
    da_sf_df,
    da_health_df,
]).sort_values(['st_mtime', 'estimated_publish_date'], ascending=True)
    .dropna(subset='requisition_id')
    .drop_duplicates(subset='requisition_id')
    .reset_index(drop=True)
)
# all_df['st_mtime'].mean()
all_df.drop_duplicates(subset='requisition_id')
all_df

,st_mtime,st_size,requisition_id,job_id,board_token,source,apply_url,collapse_key,is_expired,title,...,company_tagline,company_organization_type,company_latest_funding_investors),company_latest_funding_type,company_latest_funding_year,company_latest_funding_amount,company_stock_exchange,company_stock_symbol,location_longitudes,location_latitudes
0,2026-05-03 00:31:34.858393908,350676,309eiqubmllkwa14,grnhse___elementbiosciences___5728046004,elementbiosciences,grnhse,https://job-boards.greenhouse.io/elementbiosci...,be4d74a6e10c2c0da07a720d20c754918e33b310662f39...,False,Sr Embedded Systems Engineer,...,Develops modular DNA sequencing platforms for ...,Private,[Wellington Management],Series D,2024.0,277000000.0,None,None,[-117.1611],[32.7157]
1,2026-05-03 00:31:34.858393908,350676,19la7bfe9xlznd5t,grnhse___flatironhealth___7511628,flatironhealth,grnhse,https://flatiron.com/careers/open-positions/jo...,455c79b0c777c9102be4660c38b8cfd82b2fb18bd5138c...,False,Senior Data Engineer,...,Provides oncology software and clinical data f...,Public,None,None,NaN,NaN,SIX Swiss Exchange,ROG,[-74.006],[40.7128]
2,2026-05-03 00:31:34.858393908,350676,llorpv5d02n7r8y8,utipro___wom1000whf___2f4bcf30-0e2d-4c6d-82e3-...,wom1000whf_2f4bcf30-0e2d-4c6d-82e3-d7e885e672ea,ultipro,https://recruiting2.ultipro.com/wom1000whf/Job...,4ab38394944d9df62aeab2c7c27ec08716ecf9e6faea3f...,False,BI Developer II - Information Systems,...,Specialty hospital providing healthcare for wo...,Non-Profit,None,None,NaN,NaN,None,None,[-91.037856],[30.3855]
3,2026-05-03 00:31:34.858393908,350676,m6cg3i25t85v4noc,grnhse___flatironhealth___7681161,flatironhealth,grnhse,https://flatiron.com/careers/open-positions/jo...,455c79b0c777c9102be4660c38b8cfd82b2fb18bd5138c...,False,Software Engineer (Contractor),...,Provides oncology software and clinical data f...,Public,None,None,NaN,NaN,SIX Swiss Exchange,ROG,[-74.006],[40.7128]
4,2026-05-03 00:31:34.858393908,350676,96ustvxzv9cn7cpc,grnhse___zocdoc___7736528,zocdoc,grnhse,https://job-boards.greenhouse.io/zocdoc/jobs/7...,d4dc3fe353aa194dbcd683834bb10dbadce6fe37300c50...,False,Senior Site Reliability Engineer,...,Online platform for searching and booking heal...,Private,[Francisco Partners],Series E,2021.0,150000000.0,None,None,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11109,2026-05-29 18:28:53.492630243,144490,nyheyceukdtek57s,ashby___brightwheel___588834a1-4c36-4bd0-92f5-...,brightwheel,ashby,https://jobs.ashbyhq.com/brightwheel/588834a1-...,faccdecca48065be66243b21ae9999a105a0261f8e4440...,False,AI Campaign Operations Specialist,...,Provides an all-in-one management platform for...,Private,"[Addition, Bessemer Venture Partners]",Series C,2022.0,50000000.0,None,None,[],[]
11110,2026-05-29 18:28:53.492630243,144490,z9h2jdub2jg3rq7p,lever___get-vocal-pbc___552b5a34-a0e0-4e2a-b0a...,get-vocal-pbc,lever,https://jobs.lever.co/get-vocal-pbc/552b5a34-a...,14fe011c61efac4d12d524df589afc33a3540d40549bb6...,False,Research Analyst,...,Strategic influencer marketing for social impa...,Private,[Higher Ground Labs],Angel,2023.0,500000.0,None,None,[],[]
11111,2026-05-29 18:28:53.492630243,144490,lirwzbs8jo4edw7n,ashby___jellyfish___a7aa0e73-e3f9-4bcd-9886-dc...,jellyfish,ashby,https://jobs.ashbyhq.com/jellyfish/a7aa0e73-e3...,f35f2c8e81b4a8900adf995b0d6ec09dbfa761efc317a3...,False,Staff Data Architect,...,Analytics platform for tracking software engin...,Private,"[Accel, Insight Partners, Tiger Global]",Series C,2022.0,71000000.0,None,None,[],[]
11112,2026-05-29 18:28:53.492630243,144490,fe0iv95uxwfdt1hr,grnhse___birdygrey___5145569007,birdygrey,grnhse,https://job-boards.greenhouse.io/birdygrey/job...,896e2ea101e9b93bd1548a0005b858ed2efeb6eb0bde19...,False,Senior Strategy Associate,...,Direct-to-consumer brand selling affordable br...,Private,"[Bling Capital, BAM Ventures, Labora Group]",Seed,2019.0,2500000.0,None,None,[],[]
11113,2026-05-29 18:28:53.492630243,144490,e97ozk2yyfmxqz4f,grnhse___chime___8565199002,chime,grnhse,https://boards.greenhouse.io/chime/jobs/856519...,2f9e36995dad03ed85dd3ea7ef9c14cd8cc38d7f0f8570...,False,"Insights Analyst, Dispute Experience",...,Provides mobile banking and financial tools fo...,Public,None,None,NaN,NaN,Nasdaq,CHYM,[],[]

In [429]:
all_parquet_df = (pd.concat([
        health_parquet_df,
        ds_sf_parquet_df,
        da_sf_parquet_df,
        da_health_parquet_df,
    ]).sort_values('estimated_publish_date', ascending=False)
        .dropna(subset='_hash')
        .drop_duplicates(subset='_hash')
        .reset_index(drop=True)
    )
all_df.to_parquet(f'../data/cache/ALL.parquet')

## Save JSON descriptions

In [465]:
# health_df[health_df['description'].isna()].sort_values('st_mtime', ascending=False)[lambda x: x['company_name'].fillna('').str.contains('Tempus')]

In [460]:
health_df[health_df['description'].isna()].sort_values('st_mtime', ascending=False)
# all_df[all_df['description'].isna()].sort_values('st_mtime', ascending=False)

,st_mtime,st_size,requisition_id,job_id,board_token,source,apply_url,collapse_key,is_expired,title,...,company_tagline,company_organization_type,company_latest_funding_investors),company_latest_funding_type,company_latest_funding_year,company_latest_funding_amount,company_stock_exchange,company_stock_symbol,location_longitudes,location_latitudes
8808,2026-05-29 18:25:41.462252378,146092,ln9dcblqjxza1q7e,dayforce___nant___candidateportal___1033,nant___candidateportal___en-us,dayforce,https://jobs.dayforcehcm.com/en-US/nant/candid...,ee1fa4206e4ea3537fdd8f49e7807ef726b875041ff585...,False,Senior Systems Analyst | Remote | NantHealth,...,Developing personalized medical treatments and...,Private,[Allscripts],Corporate Round,2015.0,200000000.0,None,None,[-98.4945922],[29.4251905]
8751,2026-05-29 18:25:41.462252378,146092,511cnhej7r441szd,csod___uisystemoffice___2984,uisystemoffice___5,csod,https://uisystemoffice.csod.com/ux/ats/careers...,e4830b78258eb92a81f2c459ee0991ed316e8f9467c969...,False,Data Analyst - Remote,...,"Provides higher education, research, and healt...",Government,None,None,NaN,NaN,None,None,[-88.20727],[40.1105881]
8742,2026-05-29 18:25:41.462252378,146092,wt7m18kf34cev5vq,workday___streamlinehealthcare-wd501-streamlin...,streamlinehealthcare-wd501-streamline_healthca...,workday,https://streamlinehealthcare.wd501.myworkdayjo...,17b7bad6abcdfdbd39ffa65672657d1cf3140b30a548cd...,False,Software Engineer,...,Provides electronic health record software for...,Private,[],Private Equity,2023.0,15400000.0,None,None,[],[]
8743,2026-05-29 18:25:41.462252378,146092,lqlwhzoslqqa38tq,workday___streamlinehealthcare-wd501-streamlin...,streamlinehealthcare-wd501-streamline_healthca...,workday,https://streamlinehealthcare.wd501.myworkdayjo...,17b7bad6abcdfdbd39ffa65672657d1cf3140b30a548cd...,False,Software Engineer,...,Provides electronic health record software for...,Private,[],Private Equity,2023.0,15400000.0,None,None,[],[]
8744,2026-05-29 18:25:41.462252378,146092,3vovhx5k0m2unuzi,workday___streamlinehealthcare-wd501-streamlin...,streamlinehealthcare-wd501-streamline_healthca...,workday,https://streamlinehealthcare.wd501.myworkdayjo...,17b7bad6abcdfdbd39ffa65672657d1cf3140b30a548cd...,False,Lead AI Software Engineer,...,Provides electronic health record software for...,Private,[],Private Equity,2023.0,15400000.0,None,None,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5515,2026-05-16 02:30:17.313909531,157299,fwz5q453mt0quu54,smartrecruiters___abbvie___a3a02346-1f0a-4459-...,abbvie,smartrecruiters,https://jobs.smartrecruiters.com/AbbVie/374399...,6f4d122a6f9c4b5685fa20dabcef73ed2bcc0f8b9c0d04...,False,Data Science Program Lead I,...,Develops and sells innovative pharmaceutical a...,Public,None,None,NaN,NaN,NYSE,ABBV,[-74.3893296],[40.7881053]
5516,2026-05-16 02:30:17.313909531,157299,862zn43jecjm9f00,utipro___vor1001vori___e5f59222-eab9-4772-8e33...,vor1001vori_e5f59222-eab9-4772-8e33-f436c4f4a1f6,ultipro,https://recruiting.ultipro.com/vor1001vori/Job...,235ccf0eb154cbe9370fede0ccf2bb41a564bf25e9f8c9...,False,Senior Data Integration Engineer (100% Remote),...,Virtual-first medical practice specializing in...,Private,[New Enterprise Associates],Series B,2025.0,53000000.0,None,None,[-86.76582],[36.1059]
5438,2026-05-16 02:30:17.313909531,157299,7y3lzczsc9ra8ywu,oraclecloud___ecvz.fa.us2___63752,ecvz.fa.us2,oraclecloud,https://ecvz.fa.us2.oraclecloud.com/hcmUI/Cand...,ccb17ca98ec57867d3a343a43321976b861e7ce3e25317...,False,"Clinical Laboratory Scientist, Full Time, Nigh...",...,Faith-based healthcare provider offering hospi...,Non-Profit,None,None,NaN,NaN,None,None,[-123.80592],[39.44672]
4150,2026-05-08 21:41:37.239470005,1258,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,...,None,NaN,None,None,NaN,NaN,None,None,[],[]
1768,2026-05-03 00:33:14.987561941,1257,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,...,None,NaN,None,None,NaN,NaN,None,None,[],[]

In [654]:
len([p for p in (jb.P_CACHE / 'json').iterdir()])

2402

In [470]:
proxy = False
driver = sc.init_driver(proxy=proxy, headless=False)

errors = []
for _hash in tqdm(all_df[all_df['description'].isna()].sort_values('st_mtime', ascending=False)['requisition_id']):
    # P_url = jb.P_CACHE / 'json' / f'2xztjhutpo56dvg9.json.gz'
    P_url = jb.P_CACHE / 'url' / f'{_hash}.html'
    P_json = jb.P_CACHE / 'json' / f'{_hash}.json.gz'
    if P_url.exists():
        continue

    # url = jb.VIEW_JOB_HTTPS + _hash
    url = jb.JOB_HTTPS + _hash
    print(url)

    # url_get_content = sc.selenium_get(url, driver=driver)
    try:
        url_get_content = sc.requests_get(url)
    except Exception:
        url_get_content = sc.selenium_get(url, driver=driver)

    root = lxml.html.fromstring(url_get_content)
    _next_data_list = root.xpath("//script[@id='__NEXT_DATA__']")
    if len(_next_data_list) == 0:
        jobs_dict = {}
        errors.append(url)
        print(url)
        continue
    else:
        _next_data = root.xpath("//script[@id='__NEXT_DATA__']")[0]
        jobs_dict = json.loads(_next_data.text_content())
        jobs_dict = jobs_dict.get('props', jobs_dict)

    sc.write_data(P_json, jobs_dict)
    with open(P_url, "w", encoding="utf-8") as f:
        f.write(url_get_content)
    sc.sleep(0.2, 0.5)

  0%|          | 0/2404 [00:00<?, ?it/s]

https://hiring.cafe/job/e97ozk2yyfmxqz4f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e97ozk2yyfmxqz4f.json.gz

  0%|          | 1/2404 [00:01<53:33,  1.34s/it]

https://hiring.cafe/job/d3ddzqwxd22qwbjk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d3ddzqwxd22qwbjk.json.gz

  0%|          | 2/2404 [00:02<52:23,  1.31s/it]

https://hiring.cafe/job/8vumggkw7wsd54ga
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8vumggkw7wsd54ga.json.gz

  0%|          | 3/2404 [00:04<54:41,  1.37s/it]

https://hiring.cafe/job/893cfsjedy51k0jo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\893cfsjedy51k0jo.json.gz

  0%|          | 4/2404 [00:05<51:50,  1.30s/it]

https://hiring.cafe/job/pds6m7p38g8aq1j8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pds6m7p38g8aq1j8.json.gz

  0%|          | 5/2404 [00:06<54:42,  1.37s/it]

https://hiring.cafe/job/99emutxs6eznyzmz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\99emutxs6eznyzmz.json.gz

  0%|          | 6/2404 [00:08<1:00:57,  1.53s/it]

https://hiring.cafe/job/y928f753y1z3ecib
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y928f753y1z3ecib.json.gz

  0%|          | 7/2404 [00:11<1:14:06,  1.85s/it]

https://hiring.cafe/job/w13y7blvv9gi8h3h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w13y7blvv9gi8h3h.json.gz

  0%|          | 8/2404 [00:15<1:42:40,  2.57s/it]

https://hiring.cafe/job/i57es88grtek6hix
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i57es88grtek6hix.json.gz

  0%|          | 9/2404 [00:16<1:26:39,  2.17s/it]

https://hiring.cafe/job/5gps6d04cqc067eu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5gps6d04cqc067eu.json.gz

  0%|          | 10/2404 [00:17<1:13:22,  1.84s/it]

https://hiring.cafe/job/pfy64nqj4t4uiuxl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pfy64nqj4t4uiuxl.json.gz

  0%|          | 11/2404 [00:18<1:05:41,  1.65s/it]

https://hiring.cafe/job/k9swirc2mxvqwy67
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k9swirc2mxvqwy67.json.gz

  0%|          | 12/2404 [00:19<57:56,  1.45s/it]

https://hiring.cafe/job/rswztl2x95k7uxgo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rswztl2x95k7uxgo.json.gz

  1%|          | 13/2404 [00:21<56:20,  1.41s/it]

https://hiring.cafe/job/t9zkzrvtxj0fhydd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t9zkzrvtxj0fhydd.json.gz

  1%|          | 14/2404 [00:22<51:57,  1.30s/it]

https://hiring.cafe/job/lf0uz6y4ynlribjd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lf0uz6y4ynlribjd.json.gz

  1%|          | 15/2404 [00:23<50:29,  1.27s/it]

https://hiring.cafe/job/e4frg1of421zemaz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e4frg1of421zemaz.json.gz

  1%|          | 16/2404 [00:24<51:30,  1.29s/it]

https://hiring.cafe/job/qybfktw8fm64d23m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qybfktw8fm64d23m.json.gz

  1%|          | 17/2404 [00:25<47:56,  1.21s/it]

https://hiring.cafe/job/ark0s0kdoq70q2w3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ark0s0kdoq70q2w3.json.gz

  1%|          | 18/2404 [00:27<48:53,  1.23s/it]

https://hiring.cafe/job/fe0iv95uxwfdt1hr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fe0iv95uxwfdt1hr.json.gz

  1%|          | 19/2404 [00:28<47:19,  1.19s/it]

https://hiring.cafe/job/lirwzbs8jo4edw7n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lirwzbs8jo4edw7n.json.gz

  1%|          | 20/2404 [00:29<44:31,  1.12s/it]

https://hiring.cafe/job/nyheyceukdtek57s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nyheyceukdtek57s.json.gz

  1%|          | 21/2404 [00:30<46:39,  1.17s/it]

https://hiring.cafe/job/z9h2jdub2jg3rq7p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z9h2jdub2jg3rq7p.json.gz

  1%|          | 22/2404 [00:32<52:03,  1.31s/it]

https://hiring.cafe/job/5n3fumpg5myh6vsl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5n3fumpg5myh6vsl.json.gz

  1%|          | 23/2404 [00:33<48:45,  1.23s/it]

https://hiring.cafe/job/cv4gd116lqwhr7z2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cv4gd116lqwhr7z2.json.gz

  1%|          | 24/2404 [00:34<49:25,  1.25s/it]

https://hiring.cafe/job/1gsgt17pp0d2cht2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1gsgt17pp0d2cht2.json.gz

  1%|          | 25/2404 [00:35<49:48,  1.26s/it]

https://hiring.cafe/job/0ojg1pyinkuu2uhe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ojg1pyinkuu2uhe.json.gz

  1%|          | 26/2404 [00:36<50:25,  1.27s/it]

https://hiring.cafe/job/f7r6780omn7vgo7v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f7r6780omn7vgo7v.json.gz

  1%|          | 27/2404 [00:37<47:02,  1.19s/it]

https://hiring.cafe/job/zn9kthkpo83igqdr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zn9kthkpo83igqdr.json.gz

  1%|          | 28/2404 [00:39<46:58,  1.19s/it]

https://hiring.cafe/job/r7m5ltovxt5j52tr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r7m5ltovxt5j52tr.json.gz

  1%|          | 29/2404 [00:40<45:01,  1.14s/it]

https://hiring.cafe/job/9fdrvbo99ad8moc1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9fdrvbo99ad8moc1.json.gz

  1%|          | 30/2404 [00:41<45:13,  1.14s/it]

https://hiring.cafe/job/n3v3f8g1qv30b6ih
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n3v3f8g1qv30b6ih.json.gz

  1%|▏         | 31/2404 [00:42<47:05,  1.19s/it]

https://hiring.cafe/job/3tb5vbhvlebritpa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3tb5vbhvlebritpa.json.gz

  1%|▏         | 32/2404 [00:43<48:56,  1.24s/it]

https://hiring.cafe/job/29g3pc7v1wvzj0n0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\29g3pc7v1wvzj0n0.json.gz

  1%|▏         | 33/2404 [00:45<50:08,  1.27s/it]

https://hiring.cafe/job/e1w76lo9swpf767d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e1w76lo9swpf767d.json.gz

  1%|▏         | 34/2404 [00:46<50:03,  1.27s/it]

https://hiring.cafe/job/tkuit3hdcw0muyag
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tkuit3hdcw0muyag.json.gz

  1%|▏         | 35/2404 [00:47<50:02,  1.27s/it]

https://hiring.cafe/job/gepjxh473pdaoaf3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gepjxh473pdaoaf3.json.gz

  1%|▏         | 36/2404 [00:49<52:47,  1.34s/it]

https://hiring.cafe/job/dikkttb3kkwd1771
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dikkttb3kkwd1771.json.gz

  2%|▏         | 37/2404 [00:50<51:36,  1.31s/it]

https://hiring.cafe/job/z8lgu9qurw5efe66
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z8lgu9qurw5efe66.json.gz

  2%|▏         | 38/2404 [00:51<51:32,  1.31s/it]

https://hiring.cafe/job/xa8lpaejmv309if4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xa8lpaejmv309if4.json.gz

  2%|▏         | 39/2404 [00:53<52:10,  1.32s/it]

https://hiring.cafe/job/zvcci238ut8hb6ir
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zvcci238ut8hb6ir.json.gz

  2%|▏         | 40/2404 [00:54<49:34,  1.26s/it]

https://hiring.cafe/job/7atvqhvshndp7elr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7atvqhvshndp7elr.json.gz

  2%|▏         | 41/2404 [00:55<46:31,  1.18s/it]

https://hiring.cafe/job/bmg7pbghpi5gcqin
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bmg7pbghpi5gcqin.json.gz

  2%|▏         | 42/2404 [00:56<45:49,  1.16s/it]

https://hiring.cafe/job/ygf4wqvyi2zap0v9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ygf4wqvyi2zap0v9.json.gz

  2%|▏         | 43/2404 [00:57<44:43,  1.14s/it]

https://hiring.cafe/job/g0vt3kylrvmxeqfj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g0vt3kylrvmxeqfj.json.gz

  2%|▏         | 44/2404 [00:58<47:35,  1.21s/it]

https://hiring.cafe/job/w8ixdi9nj7jgb9y1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w8ixdi9nj7jgb9y1.json.gz

  2%|▏         | 45/2404 [01:00<46:37,  1.19s/it]

https://hiring.cafe/job/jjm65t8e1aazyg0y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jjm65t8e1aazyg0y.json.gz

  2%|▏         | 46/2404 [01:01<45:20,  1.15s/it]

https://hiring.cafe/job/inje9qstnszh18ar
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\inje9qstnszh18ar.json.gz

  2%|▏         | 47/2404 [01:02<48:01,  1.22s/it]

https://hiring.cafe/job/5r1fatio8171v31p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5r1fatio8171v31p.json.gz

  2%|▏         | 48/2404 [01:03<48:39,  1.24s/it]

https://hiring.cafe/job/kcwser3nh26p8pea
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kcwser3nh26p8pea.json.gz

  2%|▏         | 49/2404 [01:05<49:49,  1.27s/it]

https://hiring.cafe/job/0beyijbt68or2nwk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0beyijbt68or2nwk.json.gz

  2%|▏         | 50/2404 [01:06<51:54,  1.32s/it]

https://hiring.cafe/job/5ek7jfi2olvone67
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ek7jfi2olvone67.json.gz

  2%|▏         | 51/2404 [01:07<50:21,  1.28s/it]

https://hiring.cafe/job/s4pr724li92fg8zu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s4pr724li92fg8zu.json.gz

  2%|▏         | 52/2404 [01:08<47:47,  1.22s/it]

https://hiring.cafe/job/12ba03w1x4v3uugl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\12ba03w1x4v3uugl.json.gz

  2%|▏         | 53/2404 [01:10<49:49,  1.27s/it]

https://hiring.cafe/job/5trpmm1ukzgxyi37
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5trpmm1ukzgxyi37.json.gz

  2%|▏         | 54/2404 [01:11<50:07,  1.28s/it]

https://hiring.cafe/job/ibxvrqo25rqprjra
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ibxvrqo25rqprjra.json.gz

  2%|▏         | 55/2404 [01:12<48:44,  1.25s/it]

https://hiring.cafe/job/ripwoxxfmdowzhuf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ripwoxxfmdowzhuf.json.gz

  2%|▏         | 56/2404 [01:13<45:50,  1.17s/it]

https://hiring.cafe/job/c5w1lrzil58i8aed
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c5w1lrzil58i8aed.json.gz

  2%|▏         | 57/2404 [01:14<45:44,  1.17s/it]

https://hiring.cafe/job/g4212zqdce9nrogb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g4212zqdce9nrogb.json.gz

  2%|▏         | 58/2404 [01:15<44:39,  1.14s/it]

https://hiring.cafe/job/nnnquez59nk2blpv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nnnquez59nk2blpv.json.gz

  2%|▏         | 59/2404 [01:17<45:41,  1.17s/it]

https://hiring.cafe/job/shml08v03h4d35dq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\shml08v03h4d35dq.json.gz

  2%|▏         | 60/2404 [01:18<45:20,  1.16s/it]

https://hiring.cafe/job/6jpt1p6kcu91ip6f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6jpt1p6kcu91ip6f.json.gz

  3%|▎         | 61/2404 [01:19<44:57,  1.15s/it]

https://hiring.cafe/job/nlku0m3h8vv5x0li
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nlku0m3h8vv5x0li.json.gz

  3%|▎         | 62/2404 [01:20<42:30,  1.09s/it]

https://hiring.cafe/job/znpdy3xmczcqlg24
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\znpdy3xmczcqlg24.json.gz

  3%|▎         | 63/2404 [01:21<44:01,  1.13s/it]

https://hiring.cafe/job/gweth3w9uc7y3eso
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gweth3w9uc7y3eso.json.gz

  3%|▎         | 64/2404 [01:22<43:09,  1.11s/it]

https://hiring.cafe/job/rgj6hhyqck8h2re5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rgj6hhyqck8h2re5.json.gz

  3%|▎         | 65/2404 [01:23<42:31,  1.09s/it]

https://hiring.cafe/job/861hxa2ujgn193te
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\861hxa2ujgn193te.json.gz

  3%|▎         | 66/2404 [01:24<42:35,  1.09s/it]

https://hiring.cafe/job/8tcr3sr557zgeadv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8tcr3sr557zgeadv.json.gz

  3%|▎         | 67/2404 [01:25<42:44,  1.10s/it]

https://hiring.cafe/job/6pdj25p9ck05pffi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6pdj25p9ck05pffi.json.gz

  3%|▎         | 68/2404 [01:27<45:55,  1.18s/it]

https://hiring.cafe/job/q2ek8bhcxwoz5hn5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q2ek8bhcxwoz5hn5.json.gz

  3%|▎         | 69/2404 [01:28<44:11,  1.14s/it]

https://hiring.cafe/job/3vggfr16jwzdlt3g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3vggfr16jwzdlt3g.json.gz

  3%|▎         | 70/2404 [01:29<46:34,  1.20s/it]

https://hiring.cafe/job/b6b0nrra9e5xjemy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b6b0nrra9e5xjemy.json.gz

  3%|▎         | 71/2404 [01:31<48:48,  1.26s/it]

https://hiring.cafe/job/9k4b14kqofx9v2wu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9k4b14kqofx9v2wu.json.gz

  3%|▎         | 72/2404 [01:32<47:40,  1.23s/it]

https://hiring.cafe/job/jo4p9kr0l4ix8649
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jo4p9kr0l4ix8649.json.gz

  3%|▎         | 73/2404 [01:33<45:42,  1.18s/it]

https://hiring.cafe/job/qahdxg8fh13zcgrv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qahdxg8fh13zcgrv.json.gz

  3%|▎         | 74/2404 [01:34<48:23,  1.25s/it]

https://hiring.cafe/job/wi5zjk59xk3ccj8l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wi5zjk59xk3ccj8l.json.gz

  3%|▎         | 75/2404 [01:35<47:59,  1.24s/it]

https://hiring.cafe/job/oevltipm9muhmm89
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oevltipm9muhmm89.json.gz

  3%|▎         | 76/2404 [01:38<1:01:52,  1.59s/it]

https://hiring.cafe/job/x1sbbwkw28y6qvrz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x1sbbwkw28y6qvrz.json.gz

  3%|▎         | 77/2404 [01:40<1:05:27,  1.69s/it]

https://hiring.cafe/job/5iixbdufqb8hezq5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5iixbdufqb8hezq5.json.gz

  3%|▎         | 78/2404 [01:41<1:00:42,  1.57s/it]

https://hiring.cafe/job/v0c5ix4ov945fxix
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v0c5ix4ov945fxix.json.gz

  3%|▎         | 79/2404 [01:42<52:45,  1.36s/it]

https://hiring.cafe/job/ar5s9a7yrfzjt7ka
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ar5s9a7yrfzjt7ka.json.gz

  3%|▎         | 80/2404 [01:43<48:06,  1.24s/it]

https://hiring.cafe/job/arezn6ca3jybqoeo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\arezn6ca3jybqoeo.json.gz

  3%|▎         | 81/2404 [01:44<47:22,  1.22s/it]

https://hiring.cafe/job/6o4o5ft4895vs8ty
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6o4o5ft4895vs8ty.json.gz

  3%|▎         | 82/2404 [01:45<49:40,  1.28s/it]

https://hiring.cafe/job/wtvwpisqcolxz62l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wtvwpisqcolxz62l.json.gz

  3%|▎         | 83/2404 [01:47<47:59,  1.24s/it]

https://hiring.cafe/job/7e255ui5ol0f09jz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7e255ui5ol0f09jz.json.gz

  3%|▎         | 84/2404 [01:48<46:34,  1.20s/it]

https://hiring.cafe/job/u5f67k5usr5w3mhl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u5f67k5usr5w3mhl.json.gz

  4%|▎         | 85/2404 [01:49<44:37,  1.15s/it]

https://hiring.cafe/job/7wmoq0karlx9w4p2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7wmoq0karlx9w4p2.json.gz

  4%|▎         | 86/2404 [01:50<42:28,  1.10s/it]

https://hiring.cafe/job/04rqkho3vsvivizy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\04rqkho3vsvivizy.json.gz

  4%|▎         | 87/2404 [01:51<43:56,  1.14s/it]

https://hiring.cafe/job/8kn9xnu1csuypdik
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8kn9xnu1csuypdik.json.gz

  4%|▎         | 88/2404 [01:52<44:48,  1.16s/it]

https://hiring.cafe/job/9wblh9xnn8ah4hh7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9wblh9xnn8ah4hh7.json.gz

  4%|▎         | 89/2404 [01:53<45:22,  1.18s/it]

https://hiring.cafe/job/bpzx09iaf6zmmiop
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bpzx09iaf6zmmiop.json.gz

  4%|▎         | 90/2404 [01:55<45:20,  1.18s/it]

https://hiring.cafe/job/9c7ygh3a92g9uv39
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9c7ygh3a92g9uv39.json.gz

  4%|▍         | 91/2404 [01:56<46:32,  1.21s/it]

https://hiring.cafe/job/5pedkxpd1b0uldl4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5pedkxpd1b0uldl4.json.gz

  4%|▍         | 92/2404 [01:57<47:16,  1.23s/it]

https://hiring.cafe/job/bxkb15t0f6e7nztn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bxkb15t0f6e7nztn.json.gz

  4%|▍         | 93/2404 [01:58<46:23,  1.20s/it]

https://hiring.cafe/job/tyxf8u9hdcx734wr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tyxf8u9hdcx734wr.json.gz

  4%|▍         | 94/2404 [01:59<44:44,  1.16s/it]

https://hiring.cafe/job/lh68u3jc694rxnoz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lh68u3jc694rxnoz.json.gz

  4%|▍         | 95/2404 [02:01<47:38,  1.24s/it]

https://hiring.cafe/job/1bqydw6k5k30xyh8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1bqydw6k5k30xyh8.json.gz

  4%|▍         | 96/2404 [02:02<48:27,  1.26s/it]

https://hiring.cafe/job/9ucahmwu9kmav4hw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9ucahmwu9kmav4hw.json.gz

  4%|▍         | 97/2404 [02:04<51:21,  1.34s/it]

https://hiring.cafe/job/v9vfr6lvj0a11tmb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v9vfr6lvj0a11tmb.json.gz

  4%|▍         | 98/2404 [02:05<50:33,  1.32s/it]

https://hiring.cafe/job/t8f1c73dvs2c1p8y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t8f1c73dvs2c1p8y.json.gz

  4%|▍         | 99/2404 [02:06<52:28,  1.37s/it]

https://hiring.cafe/job/yuy1a9ni7ulxxn65
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yuy1a9ni7ulxxn65.json.gz

  4%|▍         | 100/2404 [02:08<55:08,  1.44s/it]

https://hiring.cafe/job/e71sr5agmqmlquvh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e71sr5agmqmlquvh.json.gz

  4%|▍         | 101/2404 [02:09<49:00,  1.28s/it]

https://hiring.cafe/job/m8de3t3dzlllsugv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m8de3t3dzlllsugv.json.gz

  4%|▍         | 102/2404 [02:10<49:09,  1.28s/it]

https://hiring.cafe/job/e77b206s544fpahs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e77b206s544fpahs.json.gz

  4%|▍         | 103/2404 [02:12<51:28,  1.34s/it]

https://hiring.cafe/job/ovqx6yyrrrhq03qx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ovqx6yyrrrhq03qx.json.gz

  4%|▍         | 104/2404 [02:13<47:51,  1.25s/it]

https://hiring.cafe/job/d7ef9j5rt3nn31gt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d7ef9j5rt3nn31gt.json.gz

  4%|▍         | 105/2404 [02:13<43:44,  1.14s/it]

https://hiring.cafe/job/e8060x4603uly7ru
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e8060x4603uly7ru.json.gz

  4%|▍         | 106/2404 [02:15<44:42,  1.17s/it]

https://hiring.cafe/job/6wdpdd5wnv8kbvdl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6wdpdd5wnv8kbvdl.json.gz

  4%|▍         | 107/2404 [02:16<43:51,  1.15s/it]

https://hiring.cafe/job/8s704cvptkfm577y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8s704cvptkfm577y.json.gz

  4%|▍         | 108/2404 [02:17<48:45,  1.27s/it]

https://hiring.cafe/job/m0ls0cwnrwrbxrl8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m0ls0cwnrwrbxrl8.json.gz

  5%|▍         | 109/2404 [02:19<47:23,  1.24s/it]

https://hiring.cafe/job/4kqyo630i4ug0s6h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4kqyo630i4ug0s6h.json.gz

  5%|▍         | 110/2404 [02:20<48:59,  1.28s/it]

https://hiring.cafe/job/z6ebxvjyfvy7admn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z6ebxvjyfvy7admn.json.gz

  5%|▍         | 111/2404 [02:21<51:42,  1.35s/it]

https://hiring.cafe/job/dvh5ps0fv7z87abj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dvh5ps0fv7z87abj.json.gz

  5%|▍         | 112/2404 [02:23<51:32,  1.35s/it]

https://hiring.cafe/job/sdrmdb1we2wui2uj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sdrmdb1we2wui2uj.json.gz

  5%|▍         | 113/2404 [02:24<55:07,  1.44s/it]

https://hiring.cafe/job/7x1hl91jmka0vaxh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7x1hl91jmka0vaxh.json.gz

  5%|▍         | 114/2404 [02:26<57:21,  1.50s/it]

https://hiring.cafe/job/g5zy4wsokqfad5pb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g5zy4wsokqfad5pb.json.gz

  5%|▍         | 115/2404 [02:27<52:41,  1.38s/it]

https://hiring.cafe/job/zs96xay6rrl1x9ra
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zs96xay6rrl1x9ra.json.gz

  5%|▍         | 116/2404 [02:28<51:42,  1.36s/it]

https://hiring.cafe/job/iuplvfkcl2ntu91q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iuplvfkcl2ntu91q.json.gz

  5%|▍         | 117/2404 [02:30<51:54,  1.36s/it]

https://hiring.cafe/job/5pfma89yaikk0kkj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5pfma89yaikk0kkj.json.gz

  5%|▍         | 118/2404 [02:31<50:19,  1.32s/it]

https://hiring.cafe/job/te7dx43gqyb7bshp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\te7dx43gqyb7bshp.json.gz

  5%|▍         | 119/2404 [02:32<50:09,  1.32s/it]

https://hiring.cafe/job/4jrvbcryzk9uroeg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4jrvbcryzk9uroeg.json.gz

  5%|▍         | 120/2404 [02:33<47:35,  1.25s/it]

https://hiring.cafe/job/58qijb5lp8sd69ta
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\58qijb5lp8sd69ta.json.gz

  5%|▌         | 121/2404 [02:35<46:19,  1.22s/it]

https://hiring.cafe/job/w8jduglp1q340zwi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w8jduglp1q340zwi.json.gz

  5%|▌         | 122/2404 [02:36<46:57,  1.23s/it]

https://hiring.cafe/job/i4nfq4vcciyjrla5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i4nfq4vcciyjrla5.json.gz

  5%|▌         | 123/2404 [02:37<47:03,  1.24s/it]

https://hiring.cafe/job/4qwwt92q2rjt78cg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4qwwt92q2rjt78cg.json.gz

  5%|▌         | 124/2404 [02:39<50:11,  1.32s/it]

https://hiring.cafe/job/9r5np13s480zaklj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9r5np13s480zaklj.json.gz

  5%|▌         | 125/2404 [02:40<50:54,  1.34s/it]

https://hiring.cafe/job/fmqv5tmcetskk6bn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fmqv5tmcetskk6bn.json.gz

  5%|▌         | 126/2404 [02:41<48:39,  1.28s/it]

https://hiring.cafe/job/llnoqjbfktma6qzz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\llnoqjbfktma6qzz.json.gz

  5%|▌         | 127/2404 [02:42<47:33,  1.25s/it]

https://hiring.cafe/job/6ghe1glszrtg4rhs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6ghe1glszrtg4rhs.json.gz

  5%|▌         | 128/2404 [02:44<51:25,  1.36s/it]

https://hiring.cafe/job/z2juhpavlcy56rai
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z2juhpavlcy56rai.json.gz

  5%|▌         | 129/2404 [02:45<53:14,  1.40s/it]

https://hiring.cafe/job/wuuu0h37oc84pgb9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wuuu0h37oc84pgb9.json.gz

  5%|▌         | 130/2404 [02:47<50:00,  1.32s/it]

https://hiring.cafe/job/uoyrn3sqz459adfv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uoyrn3sqz459adfv.json.gz

  5%|▌         | 131/2404 [02:48<49:50,  1.32s/it]

https://hiring.cafe/job/zr9rb2tpgrqf0jvh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zr9rb2tpgrqf0jvh.json.gz

  5%|▌         | 132/2404 [02:49<45:38,  1.21s/it]

https://hiring.cafe/job/ee8ua6ucqu1rfhve
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ee8ua6ucqu1rfhve.json.gz

  6%|▌         | 133/2404 [02:50<43:35,  1.15s/it]

https://hiring.cafe/job/ha1lv36eyp0lll6u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ha1lv36eyp0lll6u.json.gz

  6%|▌         | 134/2404 [02:51<43:00,  1.14s/it]

https://hiring.cafe/job/phsin6byw6xo9bk9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\phsin6byw6xo9bk9.json.gz

  6%|▌         | 135/2404 [02:52<44:17,  1.17s/it]

https://hiring.cafe/job/egnheh0ntuqhspsa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\egnheh0ntuqhspsa.json.gz

  6%|▌         | 136/2404 [02:53<41:58,  1.11s/it]

https://hiring.cafe/job/9cmozq2liqjp8gjk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9cmozq2liqjp8gjk.json.gz

  6%|▌         | 137/2404 [02:54<40:56,  1.08s/it]

https://hiring.cafe/job/1yb72r5d2hrgkyg5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1yb72r5d2hrgkyg5.json.gz

  6%|▌         | 138/2404 [02:55<40:42,  1.08s/it]

https://hiring.cafe/job/m30s5h4mg19aofk1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m30s5h4mg19aofk1.json.gz

  6%|▌         | 139/2404 [02:56<38:36,  1.02s/it]

https://hiring.cafe/job/ih1wjlrebfovc39x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ih1wjlrebfovc39x.json.gz

  6%|▌         | 140/2404 [02:57<40:57,  1.09s/it]

https://hiring.cafe/job/9g9j3tvyuy2iggbt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9g9j3tvyuy2iggbt.json.gz

  6%|▌         | 141/2404 [02:59<42:14,  1.12s/it]

https://hiring.cafe/job/agiidclnp17lz4qd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\agiidclnp17lz4qd.json.gz

  6%|▌         | 142/2404 [03:00<42:37,  1.13s/it]

https://hiring.cafe/job/t35wwgcsrnko7935
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t35wwgcsrnko7935.json.gz

  6%|▌         | 143/2404 [03:01<39:58,  1.06s/it]

https://hiring.cafe/job/546druq13i2ztd6c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\546druq13i2ztd6c.json.gz

  6%|▌         | 144/2404 [03:02<42:16,  1.12s/it]

https://hiring.cafe/job/t6h4cgjhi428xst2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t6h4cgjhi428xst2.json.gz

  6%|▌         | 145/2404 [03:03<44:32,  1.18s/it]

https://hiring.cafe/job/69d5gp96u8w3rdpk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\69d5gp96u8w3rdpk.json.gz

  6%|▌         | 146/2404 [03:04<44:28,  1.18s/it]

https://hiring.cafe/job/l7kak45ayaxd6xpq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l7kak45ayaxd6xpq.json.gz

  6%|▌         | 147/2404 [03:06<45:28,  1.21s/it]

https://hiring.cafe/job/ytirs0ipjinzoo81
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ytirs0ipjinzoo81.json.gz

  6%|▌         | 148/2404 [03:07<46:42,  1.24s/it]

https://hiring.cafe/job/5oz0av8slxp6kmgu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5oz0av8slxp6kmgu.json.gz

  6%|▌         | 149/2404 [03:08<45:55,  1.22s/it]

https://hiring.cafe/job/phe1idxqdub9msaj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\phe1idxqdub9msaj.json.gz

  6%|▌         | 150/2404 [03:09<46:25,  1.24s/it]

https://hiring.cafe/job/9xmcbnibd2jjjgpx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9xmcbnibd2jjjgpx.json.gz

  6%|▋         | 151/2404 [03:11<46:47,  1.25s/it]

https://hiring.cafe/job/ewkeo6ianb701rm0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ewkeo6ianb701rm0.json.gz

  6%|▋         | 152/2404 [03:12<45:34,  1.21s/it]

https://hiring.cafe/job/zq8wm43wkmwrsujz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zq8wm43wkmwrsujz.json.gz

  6%|▋         | 153/2404 [03:13<45:33,  1.21s/it]

https://hiring.cafe/job/lfu6xm6x9sx9lxb4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lfu6xm6x9sx9lxb4.json.gz

  6%|▋         | 154/2404 [03:14<43:49,  1.17s/it]

https://hiring.cafe/job/s69zpskp7gxynjno
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s69zpskp7gxynjno.json.gz

  6%|▋         | 155/2404 [03:15<43:56,  1.17s/it]

https://hiring.cafe/job/b94edmxawu201i38
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b94edmxawu201i38.json.gz

  6%|▋         | 156/2404 [03:16<40:49,  1.09s/it]

https://hiring.cafe/job/c8xef0d1kwtfvnsw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c8xef0d1kwtfvnsw.json.gz

  7%|▋         | 157/2404 [03:17<41:42,  1.11s/it]

https://hiring.cafe/job/ygclwuklb8wy3u4n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ygclwuklb8wy3u4n.json.gz

  7%|▋         | 158/2404 [03:19<42:28,  1.13s/it]

https://hiring.cafe/job/ugmbo1naddsfzc4x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ugmbo1naddsfzc4x.json.gz

  7%|▋         | 159/2404 [03:20<44:45,  1.20s/it]

https://hiring.cafe/job/0x10mrl23pvaz9vr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0x10mrl23pvaz9vr.json.gz

  7%|▋         | 160/2404 [03:21<42:51,  1.15s/it]

https://hiring.cafe/job/of8kivnxthvwf2oi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\of8kivnxthvwf2oi.json.gz

  7%|▋         | 161/2404 [03:22<41:58,  1.12s/it]

https://hiring.cafe/job/f8vx2rv4r9akdf45
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f8vx2rv4r9akdf45.json.gz

  7%|▋         | 162/2404 [03:23<42:53,  1.15s/it]

https://hiring.cafe/job/bti85lszgsgwomg7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bti85lszgsgwomg7.json.gz

  7%|▋         | 163/2404 [03:24<42:54,  1.15s/it]

https://hiring.cafe/job/h8y0wrjx87x5vs64
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h8y0wrjx87x5vs64.json.gz

  7%|▋         | 164/2404 [03:26<45:53,  1.23s/it]

https://hiring.cafe/job/ow9f3oghzjpad5d4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ow9f3oghzjpad5d4.json.gz

  7%|▋         | 165/2404 [03:27<43:55,  1.18s/it]

https://hiring.cafe/job/swbxe2i3k9re2we5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\swbxe2i3k9re2we5.json.gz

  7%|▋         | 166/2404 [03:28<42:13,  1.13s/it]

https://hiring.cafe/job/k20xs442r9tpbjf4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k20xs442r9tpbjf4.json.gz

  7%|▋         | 167/2404 [03:29<44:54,  1.20s/it]

https://hiring.cafe/job/yamgqksqgtl2nqvz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yamgqksqgtl2nqvz.json.gz

  7%|▋         | 168/2404 [03:30<43:27,  1.17s/it]

https://hiring.cafe/job/5snnqkuevffhwkg9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5snnqkuevffhwkg9.json.gz

  7%|▋         | 169/2404 [03:32<43:51,  1.18s/it]

https://hiring.cafe/job/u1bwh47ocdupiuoc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u1bwh47ocdupiuoc.json.gz

  7%|▋         | 170/2404 [03:32<40:53,  1.10s/it]

https://hiring.cafe/job/p9xl2wziy71ireeq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p9xl2wziy71ireeq.json.gz

  7%|▋         | 171/2404 [03:34<40:59,  1.10s/it]

https://hiring.cafe/job/rarsb9h1u78jdho4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rarsb9h1u78jdho4.json.gz

  7%|▋         | 172/2404 [03:35<40:56,  1.10s/it]

https://hiring.cafe/job/ctg40f8re10jh3hs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ctg40f8re10jh3hs.json.gz

  7%|▋         | 173/2404 [03:36<41:07,  1.11s/it]

https://hiring.cafe/job/scl5gb9gt7ix1pnv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\scl5gb9gt7ix1pnv.json.gz

  7%|▋         | 174/2404 [03:37<39:15,  1.06s/it]

https://hiring.cafe/job/5md5c91lq3gl9g0a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5md5c91lq3gl9g0a.json.gz

  7%|▋         | 175/2404 [03:38<38:22,  1.03s/it]

https://hiring.cafe/job/0yuh5xfioot26t6r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0yuh5xfioot26t6r.json.gz

  7%|▋         | 176/2404 [03:39<37:31,  1.01s/it]

https://hiring.cafe/job/8s3tgm7ne1plu5bk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8s3tgm7ne1plu5bk.json.gz

  7%|▋         | 177/2404 [03:40<37:16,  1.00s/it]

https://hiring.cafe/job/u8trzbhk1e4kjgzk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u8trzbhk1e4kjgzk.json.gz

  7%|▋         | 178/2404 [03:41<41:20,  1.11s/it]

https://hiring.cafe/job/r4eacsu2jkt5epp8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r4eacsu2jkt5epp8.json.gz

  7%|▋         | 179/2404 [03:42<41:59,  1.13s/it]

https://hiring.cafe/job/ede79qw5wzotwpg4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ede79qw5wzotwpg4.json.gz

  7%|▋         | 180/2404 [03:43<39:28,  1.07s/it]

https://hiring.cafe/job/hcjr753pvgunv4g3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hcjr753pvgunv4g3.json.gz

  8%|▊         | 181/2404 [03:44<37:27,  1.01s/it]

https://hiring.cafe/job/9alzfv06dil4d0ot
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9alzfv06dil4d0ot.json.gz

  8%|▊         | 182/2404 [03:45<38:18,  1.03s/it]

https://hiring.cafe/job/cq6m9mkarb09slu7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cq6m9mkarb09slu7.json.gz

  8%|▊         | 183/2404 [03:46<41:30,  1.12s/it]

https://hiring.cafe/job/w2qni4zzdlzv9n9w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w2qni4zzdlzv9n9w.json.gz

  8%|▊         | 184/2404 [03:48<42:47,  1.16s/it]

https://hiring.cafe/job/ybcmyvolpb8jo0gk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ybcmyvolpb8jo0gk.json.gz

  8%|▊         | 185/2404 [03:49<41:54,  1.13s/it]

https://hiring.cafe/job/s5eyg0y0axm4pqlm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s5eyg0y0axm4pqlm.json.gz

  8%|▊         | 186/2404 [03:50<41:42,  1.13s/it]

https://hiring.cafe/job/gvd67t8ztdmpnaap
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gvd67t8ztdmpnaap.json.gz

  8%|▊         | 187/2404 [03:51<41:40,  1.13s/it]

https://hiring.cafe/job/yuje98hnsftz8dva
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yuje98hnsftz8dva.json.gz

  8%|▊         | 188/2404 [03:52<44:44,  1.21s/it]

https://hiring.cafe/job/04pnz4az1jgyne2g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\04pnz4az1jgyne2g.json.gz

  8%|▊         | 189/2404 [03:53<43:32,  1.18s/it]

https://hiring.cafe/job/ciu2c7uxcv7bwj9j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ciu2c7uxcv7bwj9j.json.gz

  8%|▊         | 190/2404 [03:54<41:19,  1.12s/it]

https://hiring.cafe/job/bpa8c88w1bljx9mj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bpa8c88w1bljx9mj.json.gz

  8%|▊         | 191/2404 [03:56<41:29,  1.13s/it]

https://hiring.cafe/job/i9560d46y8sbd9ok
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i9560d46y8sbd9ok.json.gz

  8%|▊         | 192/2404 [03:57<40:57,  1.11s/it]

https://hiring.cafe/job/ua599h0mxjnim9fq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ua599h0mxjnim9fq.json.gz

  8%|▊         | 193/2404 [03:58<37:43,  1.02s/it]

https://hiring.cafe/job/ljf81ihp6a8hosus
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ljf81ihp6a8hosus.json.gz

  8%|▊         | 194/2404 [03:59<37:54,  1.03s/it]

https://hiring.cafe/job/57htwqe85zyjqukr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\57htwqe85zyjqukr.json.gz

  8%|▊         | 195/2404 [04:00<38:00,  1.03s/it]

https://hiring.cafe/job/zya3pn4d53yp72qk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zya3pn4d53yp72qk.json.gz

  8%|▊         | 196/2404 [04:01<39:00,  1.06s/it]

https://hiring.cafe/job/pwv8i91p8a8woib9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pwv8i91p8a8woib9.json.gz

  8%|▊         | 197/2404 [04:02<39:52,  1.08s/it]

https://hiring.cafe/job/mkfmxbvu0cy5nwqe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mkfmxbvu0cy5nwqe.json.gz

  8%|▊         | 198/2404 [04:03<41:49,  1.14s/it]

https://hiring.cafe/job/6mtewc5a46zedmdh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6mtewc5a46zedmdh.json.gz

  8%|▊         | 199/2404 [04:05<44:56,  1.22s/it]

https://hiring.cafe/job/7kdm78p5nf9xn9hi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7kdm78p5nf9xn9hi.json.gz

  8%|▊         | 200/2404 [04:06<44:49,  1.22s/it]

https://hiring.cafe/job/hxkq61hqsrj03och
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hxkq61hqsrj03och.json.gz

  8%|▊         | 201/2404 [04:07<43:54,  1.20s/it]

https://hiring.cafe/job/ts814vsiby44k42b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ts814vsiby44k42b.json.gz

  8%|▊         | 202/2404 [04:08<41:05,  1.12s/it]

https://hiring.cafe/job/98ou67x7knw9dsqp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\98ou67x7knw9dsqp.json.gz

  8%|▊         | 203/2404 [04:09<44:01,  1.20s/it]

https://hiring.cafe/job/9u630y6ibtcsbfhn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9u630y6ibtcsbfhn.json.gz

  8%|▊         | 204/2404 [04:10<41:49,  1.14s/it]

https://hiring.cafe/job/s9vi50ueiu0osi8x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s9vi50ueiu0osi8x.json.gz

  9%|▊         | 205/2404 [04:11<42:50,  1.17s/it]

https://hiring.cafe/job/m2tu570rnekrt2g1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m2tu570rnekrt2g1.json.gz

  9%|▊         | 206/2404 [04:13<41:51,  1.14s/it]

https://hiring.cafe/job/fv9jmij90efjspne
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fv9jmij90efjspne.json.gz

  9%|▊         | 207/2404 [04:14<44:02,  1.20s/it]

https://hiring.cafe/job/lpdr8t236jjarx7h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lpdr8t236jjarx7h.json.gz

  9%|▊         | 208/2404 [04:15<42:39,  1.17s/it]

https://hiring.cafe/job/js3m91egmt53bx6b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\js3m91egmt53bx6b.json.gz

  9%|▊         | 209/2404 [04:16<40:56,  1.12s/it]

https://hiring.cafe/job/8a7yvc9drym6aorl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8a7yvc9drym6aorl.json.gz

  9%|▊         | 210/2404 [04:17<40:03,  1.10s/it]

https://hiring.cafe/job/xhphoj4urzh9le2x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xhphoj4urzh9le2x.json.gz

  9%|▉         | 211/2404 [04:18<43:41,  1.20s/it]

https://hiring.cafe/job/pd1l9p7ceysh65be
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pd1l9p7ceysh65be.json.gz

  9%|▉         | 212/2404 [04:19<41:33,  1.14s/it]

https://hiring.cafe/job/t0smj40o9szlrgk5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t0smj40o9szlrgk5.json.gz

  9%|▉         | 213/2404 [04:20<40:26,  1.11s/it]

https://hiring.cafe/job/i3h6vlimtmmdc66z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i3h6vlimtmmdc66z.json.gz

  9%|▉         | 214/2404 [04:21<39:18,  1.08s/it]

https://hiring.cafe/job/28p5thalscuv9ony
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\28p5thalscuv9ony.json.gz

  9%|▉         | 215/2404 [04:23<41:31,  1.14s/it]

https://hiring.cafe/job/bidsafh8r5j1bojd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bidsafh8r5j1bojd.json.gz

  9%|▉         | 216/2404 [04:24<41:54,  1.15s/it]

https://hiring.cafe/job/f2n5ofdu1swxjk38
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f2n5ofdu1swxjk38.json.gz

  9%|▉         | 217/2404 [04:25<44:27,  1.22s/it]

https://hiring.cafe/job/93rtt6up2sw4ot5i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\93rtt6up2sw4ot5i.json.gz

  9%|▉         | 218/2404 [04:27<45:39,  1.25s/it]

https://hiring.cafe/job/jhfy71yh0b8q4c02
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jhfy71yh0b8q4c02.json.gz

  9%|▉         | 219/2404 [04:28<42:15,  1.16s/it]

https://hiring.cafe/job/mbep6sy7s5jfoj1l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mbep6sy7s5jfoj1l.json.gz

  9%|▉         | 220/2404 [04:29<41:34,  1.14s/it]

https://hiring.cafe/job/buhptiy47tii3idr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\buhptiy47tii3idr.json.gz

  9%|▉         | 221/2404 [04:30<43:18,  1.19s/it]

https://hiring.cafe/job/3z5otxfz79kxmnyg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3z5otxfz79kxmnyg.json.gz

  9%|▉         | 222/2404 [04:31<42:48,  1.18s/it]

https://hiring.cafe/job/a3419ikvv4beittm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a3419ikvv4beittm.json.gz

  9%|▉         | 223/2404 [04:32<43:57,  1.21s/it]

https://hiring.cafe/job/hjh33wqm61z00nmt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hjh33wqm61z00nmt.json.gz

  9%|▉         | 224/2404 [04:33<41:37,  1.15s/it]

https://hiring.cafe/job/z02m4mkcjqgfs7eu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z02m4mkcjqgfs7eu.json.gz

  9%|▉         | 225/2404 [04:35<42:03,  1.16s/it]

https://hiring.cafe/job/h8gdqb738rq5dfmb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h8gdqb738rq5dfmb.json.gz

  9%|▉         | 226/2404 [04:36<42:38,  1.17s/it]

https://hiring.cafe/job/yqphloqx8caf7kri
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yqphloqx8caf7kri.json.gz

  9%|▉         | 227/2404 [04:37<45:45,  1.26s/it]

https://hiring.cafe/job/5ika212t248ifiqz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ika212t248ifiqz.json.gz

  9%|▉         | 228/2404 [04:39<45:14,  1.25s/it]

https://hiring.cafe/job/33w320xpg9jxme9x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\33w320xpg9jxme9x.json.gz

 10%|▉         | 229/2404 [04:40<45:11,  1.25s/it]

https://hiring.cafe/job/i4xfxetfwm86hc96
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i4xfxetfwm86hc96.json.gz

 10%|▉         | 230/2404 [04:41<46:10,  1.27s/it]

https://hiring.cafe/job/yg1hfvk5z967wd4l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yg1hfvk5z967wd4l.json.gz

 10%|▉         | 231/2404 [04:42<45:11,  1.25s/it]

https://hiring.cafe/job/ly104leupdyztzje
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ly104leupdyztzje.json.gz

 10%|▉         | 232/2404 [04:44<48:15,  1.33s/it]

https://hiring.cafe/job/2o2l3a0fm2aezqsm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2o2l3a0fm2aezqsm.json.gz

 10%|▉         | 233/2404 [04:45<45:46,  1.27s/it]

https://hiring.cafe/job/dtgv80goqtakoc6q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dtgv80goqtakoc6q.json.gz

 10%|▉         | 234/2404 [04:46<47:52,  1.32s/it]

https://hiring.cafe/job/gvzwvg72km53edua
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gvzwvg72km53edua.json.gz

 10%|▉         | 235/2404 [04:48<45:57,  1.27s/it]

https://hiring.cafe/job/117xqx5llfnnhrcn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\117xqx5llfnnhrcn.json.gz

 10%|▉         | 236/2404 [04:49<44:26,  1.23s/it]

https://hiring.cafe/job/vleul22l363qxcnd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vleul22l363qxcnd.json.gz

 10%|▉         | 237/2404 [04:50<42:23,  1.17s/it]

https://hiring.cafe/job/gcuaalnom80jscem
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gcuaalnom80jscem.json.gz

 10%|▉         | 238/2404 [04:51<40:39,  1.13s/it]

https://hiring.cafe/job/etl9whhomlhwv3w0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\etl9whhomlhwv3w0.json.gz

 10%|▉         | 239/2404 [04:52<38:37,  1.07s/it]

https://hiring.cafe/job/dab7t379kjlfm0rf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dab7t379kjlfm0rf.json.gz

 10%|▉         | 240/2404 [04:53<37:31,  1.04s/it]

https://hiring.cafe/job/11zfmypk86fau8pf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\11zfmypk86fau8pf.json.gz

 10%|█         | 241/2404 [04:54<37:52,  1.05s/it]

https://hiring.cafe/job/6gj035jz6ily2ta8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6gj035jz6ily2ta8.json.gz

 10%|█         | 242/2404 [04:55<40:11,  1.12s/it]

https://hiring.cafe/job/tabjjnp4gejmq3he
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tabjjnp4gejmq3he.json.gz

 10%|█         | 243/2404 [04:56<40:24,  1.12s/it]

https://hiring.cafe/job/hwcd5e3i8tylr417
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hwcd5e3i8tylr417.json.gz

 10%|█         | 244/2404 [04:57<40:14,  1.12s/it]

https://hiring.cafe/job/04a5tu46sinhnlqf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\04a5tu46sinhnlqf.json.gz

 10%|█         | 245/2404 [04:58<41:35,  1.16s/it]

https://hiring.cafe/job/64rpd0fq889gg9cx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\64rpd0fq889gg9cx.json.gz

 10%|█         | 246/2404 [05:00<44:16,  1.23s/it]

https://hiring.cafe/job/vlqqrf8hlf1b0iun
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vlqqrf8hlf1b0iun.json.gz

 10%|█         | 247/2404 [05:01<42:49,  1.19s/it]

https://hiring.cafe/job/0eiq0er8hyvgg9zd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0eiq0er8hyvgg9zd.json.gz

 10%|█         | 248/2404 [05:02<44:59,  1.25s/it]

https://hiring.cafe/job/ycd733mt79nr84bg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ycd733mt79nr84bg.json.gz

 10%|█         | 249/2404 [05:04<44:34,  1.24s/it]

https://hiring.cafe/job/lvkn98o83romfadr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lvkn98o83romfadr.json.gz

 10%|█         | 250/2404 [05:05<42:38,  1.19s/it]

https://hiring.cafe/job/e4qhlennds6zp4k3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e4qhlennds6zp4k3.json.gz

 10%|█         | 251/2404 [05:06<44:47,  1.25s/it]

https://hiring.cafe/job/ch1b83ngeyc7ywyw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ch1b83ngeyc7ywyw.json.gz

 10%|█         | 252/2404 [05:07<44:36,  1.24s/it]

https://hiring.cafe/job/8bgjbx5yl5yz63tm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8bgjbx5yl5yz63tm.json.gz

 11%|█         | 253/2404 [05:08<42:45,  1.19s/it]

https://hiring.cafe/job/04kqkmcr903e0g1a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\04kqkmcr903e0g1a.json.gz

 11%|█         | 254/2404 [05:09<40:35,  1.13s/it]

https://hiring.cafe/job/56vqe4pr767k2qvc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\56vqe4pr767k2qvc.json.gz

 11%|█         | 255/2404 [05:11<42:59,  1.20s/it]

https://hiring.cafe/job/rzji5z7zbs3yvm92
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rzji5z7zbs3yvm92.json.gz

 11%|█         | 256/2404 [05:12<44:29,  1.24s/it]

https://hiring.cafe/job/ixtzzzdukuwy34r4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ixtzzzdukuwy34r4.json.gz

 11%|█         | 257/2404 [05:13<46:11,  1.29s/it]

https://hiring.cafe/job/0ln763glul01dp5d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ln763glul01dp5d.json.gz

 11%|█         | 258/2404 [05:15<45:22,  1.27s/it]

https://hiring.cafe/job/7ggmsu2yzqkb77yr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7ggmsu2yzqkb77yr.json.gz

 11%|█         | 259/2404 [05:16<45:50,  1.28s/it]

https://hiring.cafe/job/ik794lha6iq82hx1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ik794lha6iq82hx1.json.gz

 11%|█         | 260/2404 [05:17<46:01,  1.29s/it]

https://hiring.cafe/job/gcvyaxxl6ln647qv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gcvyaxxl6ln647qv.json.gz

 11%|█         | 261/2404 [05:18<44:24,  1.24s/it]

https://hiring.cafe/job/jpzqxa050gr1xlph
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jpzqxa050gr1xlph.json.gz

 11%|█         | 262/2404 [05:20<43:40,  1.22s/it]

https://hiring.cafe/job/tot560dzwrspayf7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tot560dzwrspayf7.json.gz

 11%|█         | 263/2404 [05:21<43:48,  1.23s/it]

https://hiring.cafe/job/j4qiltkx6gk32kl3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j4qiltkx6gk32kl3.json.gz

 11%|█         | 264/2404 [05:22<44:12,  1.24s/it]

https://hiring.cafe/job/xum8dengw4nl1klg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xum8dengw4nl1klg.json.gz

 11%|█         | 265/2404 [05:23<45:09,  1.27s/it]

https://hiring.cafe/job/j2cm6x3prsn1jcki
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j2cm6x3prsn1jcki.json.gz

 11%|█         | 266/2404 [05:25<46:51,  1.31s/it]

https://hiring.cafe/job/bagx52d2aeru3uge
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bagx52d2aeru3uge.json.gz

 11%|█         | 267/2404 [05:26<43:34,  1.22s/it]

https://hiring.cafe/job/pfrztk7d74tthp84
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pfrztk7d74tthp84.json.gz

 11%|█         | 268/2404 [05:27<42:11,  1.19s/it]

https://hiring.cafe/job/z4b3t618y5lbo6f4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z4b3t618y5lbo6f4.json.gz

 11%|█         | 269/2404 [05:28<43:26,  1.22s/it]

https://hiring.cafe/job/51xc7599nx6ob3fd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\51xc7599nx6ob3fd.json.gz

 11%|█         | 270/2404 [05:29<42:03,  1.18s/it]

https://hiring.cafe/job/dcum8ibyfqz8oj8z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dcum8ibyfqz8oj8z.json.gz

 11%|█▏        | 271/2404 [05:31<44:24,  1.25s/it]

https://hiring.cafe/job/wej8zs848xcu01ta
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wej8zs848xcu01ta.json.gz

 11%|█▏        | 272/2404 [05:32<42:58,  1.21s/it]

https://hiring.cafe/job/x8n7kwr98dyea13o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x8n7kwr98dyea13o.json.gz

 11%|█▏        | 273/2404 [05:33<42:19,  1.19s/it]

https://hiring.cafe/job/2avjs06zjto0t0gz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2avjs06zjto0t0gz.json.gz

 11%|█▏        | 274/2404 [05:34<41:11,  1.16s/it]

https://hiring.cafe/job/5ua0o59irxb7whi6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ua0o59irxb7whi6.json.gz

 11%|█▏        | 275/2404 [05:35<41:31,  1.17s/it]

https://hiring.cafe/job/v70i3571tooemrp3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v70i3571tooemrp3.json.gz

 11%|█▏        | 276/2404 [05:37<44:31,  1.26s/it]

https://hiring.cafe/job/nevt7hnlfgyye89a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nevt7hnlfgyye89a.json.gz

 12%|█▏        | 277/2404 [05:38<43:44,  1.23s/it]

https://hiring.cafe/job/67sj83nw2hvg04bj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\67sj83nw2hvg04bj.json.gz

 12%|█▏        | 278/2404 [05:39<42:42,  1.21s/it]

https://hiring.cafe/job/95v6bhnptu4wubci
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\95v6bhnptu4wubci.json.gz

 12%|█▏        | 279/2404 [05:40<44:16,  1.25s/it]

https://hiring.cafe/job/c3v5asw6ktztzz40
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c3v5asw6ktztzz40.json.gz

 12%|█▏        | 280/2404 [05:42<43:47,  1.24s/it]

https://hiring.cafe/job/n1y09upndpbfig41
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n1y09upndpbfig41.json.gz

 12%|█▏        | 281/2404 [05:43<43:42,  1.24s/it]

https://hiring.cafe/job/bux5u5ubiihjy26y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bux5u5ubiihjy26y.json.gz

 12%|█▏        | 282/2404 [05:44<42:45,  1.21s/it]

https://hiring.cafe/job/ddx9ydz2berdg1tj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ddx9ydz2berdg1tj.json.gz

 12%|█▏        | 283/2404 [05:45<42:43,  1.21s/it]

https://hiring.cafe/job/bbc88kv6xqk7tbyl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bbc88kv6xqk7tbyl.json.gz

 12%|█▏        | 284/2404 [05:46<42:43,  1.21s/it]

https://hiring.cafe/job/hu80rzkjcatc3o5f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hu80rzkjcatc3o5f.json.gz

 12%|█▏        | 285/2404 [05:48<43:01,  1.22s/it]

https://hiring.cafe/job/gj4dkh2545sp9noa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gj4dkh2545sp9noa.json.gz

 12%|█▏        | 286/2404 [05:49<43:03,  1.22s/it]

https://hiring.cafe/job/howoporb5jtjafg8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\howoporb5jtjafg8.json.gz

 12%|█▏        | 287/2404 [05:50<41:05,  1.16s/it]

https://hiring.cafe/job/0ztxfm23ymtflipb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ztxfm23ymtflipb.json.gz

 12%|█▏        | 288/2404 [05:51<40:09,  1.14s/it]

https://hiring.cafe/job/131ib4cbv4e3syax
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\131ib4cbv4e3syax.json.gz

 12%|█▏        | 289/2404 [05:52<39:50,  1.13s/it]

https://hiring.cafe/job/ai6ql1oyw29q1oti
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ai6ql1oyw29q1oti.json.gz

 12%|█▏        | 290/2404 [05:54<42:47,  1.21s/it]

https://hiring.cafe/job/gd2w66evq8po8m3y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gd2w66evq8po8m3y.json.gz

 12%|█▏        | 291/2404 [05:55<42:02,  1.19s/it]

https://hiring.cafe/job/ix0jf6oszbj2a4r3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ix0jf6oszbj2a4r3.json.gz

 12%|█▏        | 292/2404 [05:56<44:42,  1.27s/it]

https://hiring.cafe/job/lqlwhzoslqqa38tq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lqlwhzoslqqa38tq.json.gz

 12%|█▏        | 293/2404 [05:57<44:47,  1.27s/it]

https://hiring.cafe/job/ll28hj36j5vwaqfe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ll28hj36j5vwaqfe.json.gz

 12%|█▏        | 294/2404 [05:59<43:29,  1.24s/it]

https://hiring.cafe/job/hmo2y1vp0b0xjeaa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hmo2y1vp0b0xjeaa.json.gz

 12%|█▏        | 295/2404 [06:00<44:05,  1.25s/it]

https://hiring.cafe/job/jwd1lg1bk1yj0j7z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jwd1lg1bk1yj0j7z.json.gz

 12%|█▏        | 296/2404 [06:01<42:05,  1.20s/it]

https://hiring.cafe/job/q5oi2x03wukwppmq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q5oi2x03wukwppmq.json.gz

 12%|█▏        | 297/2404 [06:02<41:06,  1.17s/it]

https://hiring.cafe/job/woxqpbzoepgz2yqc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\woxqpbzoepgz2yqc.json.gz

 12%|█▏        | 298/2404 [06:03<40:49,  1.16s/it]

https://hiring.cafe/job/01zx8b7ph4jcotsx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\01zx8b7ph4jcotsx.json.gz

 12%|█▏        | 299/2404 [06:05<43:29,  1.24s/it]

https://hiring.cafe/job/f2w6dfgu68vmuwun
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f2w6dfgu68vmuwun.json.gz

 12%|█▏        | 300/2404 [06:06<43:23,  1.24s/it]

https://hiring.cafe/job/wt7m18kf34cev5vq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wt7m18kf34cev5vq.json.gz

 13%|█▎        | 301/2404 [06:07<41:18,  1.18s/it]

https://hiring.cafe/job/x4gsylgpf7ma361k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x4gsylgpf7ma361k.json.gz

 13%|█▎        | 302/2404 [06:08<40:27,  1.15s/it]

https://hiring.cafe/job/s1czee8w3gcdoty6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s1czee8w3gcdoty6.json.gz

 13%|█▎        | 303/2404 [06:09<38:49,  1.11s/it]

https://hiring.cafe/job/511cnhej7r441szd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\511cnhej7r441szd.json.gz

 13%|█▎        | 304/2404 [06:10<38:16,  1.09s/it]

https://hiring.cafe/job/8vpuowtgl3wpyqes
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8vpuowtgl3wpyqes.json.gz

 13%|█▎        | 305/2404 [06:11<36:27,  1.04s/it]

https://hiring.cafe/job/76x05al1q9iid6fg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\76x05al1q9iid6fg.json.gz

 13%|█▎        | 306/2404 [06:12<37:08,  1.06s/it]

https://hiring.cafe/job/j6w9urzdyswle0l0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j6w9urzdyswle0l0.json.gz

 13%|█▎        | 307/2404 [06:13<39:17,  1.12s/it]

https://hiring.cafe/job/ztyhgr4idn21no0v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ztyhgr4idn21no0v.json.gz

 13%|█▎        | 308/2404 [06:14<37:40,  1.08s/it]

https://hiring.cafe/job/lit1w2x9vj4sk4qm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lit1w2x9vj4sk4qm.json.gz

 13%|█▎        | 309/2404 [06:16<43:31,  1.25s/it]

https://hiring.cafe/job/dfoa5j9svre2mro0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dfoa5j9svre2mro0.json.gz

 13%|█▎        | 310/2404 [06:17<42:02,  1.20s/it]

https://hiring.cafe/job/fvlf1l65pit3e6ns
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fvlf1l65pit3e6ns.json.gz

 13%|█▎        | 311/2404 [06:18<43:06,  1.24s/it]

https://hiring.cafe/job/qeadtt7gev8ezuci
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qeadtt7gev8ezuci.json.gz

 13%|█▎        | 312/2404 [06:20<44:38,  1.28s/it]

https://hiring.cafe/job/4v1xbrbxkxnc4c9q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4v1xbrbxkxnc4c9q.json.gz

 13%|█▎        | 313/2404 [06:21<44:36,  1.28s/it]

https://hiring.cafe/job/n7n2umbnkhwpgujs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n7n2umbnkhwpgujs.json.gz

 13%|█▎        | 314/2404 [06:22<42:13,  1.21s/it]

https://hiring.cafe/job/k91ikld09uu096ut
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k91ikld09uu096ut.json.gz

 13%|█▎        | 315/2404 [06:23<44:17,  1.27s/it]

https://hiring.cafe/job/csskksjemxttm3ho
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\csskksjemxttm3ho.json.gz

 13%|█▎        | 316/2404 [06:25<44:28,  1.28s/it]

https://hiring.cafe/job/k1s5rcq8q11sb25v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k1s5rcq8q11sb25v.json.gz

 13%|█▎        | 317/2404 [06:26<43:57,  1.26s/it]

https://hiring.cafe/job/3gerhss1ccu7ouqu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3gerhss1ccu7ouqu.json.gz

 13%|█▎        | 318/2404 [06:27<41:18,  1.19s/it]

https://hiring.cafe/job/39j5ca6tprp24i48
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\39j5ca6tprp24i48.json.gz

 13%|█▎        | 319/2404 [06:28<40:48,  1.17s/it]

https://hiring.cafe/job/6n5pzjpyz8er86hc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6n5pzjpyz8er86hc.json.gz

 13%|█▎        | 320/2404 [06:29<38:33,  1.11s/it]

https://hiring.cafe/job/jlz62g91b04tctcf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jlz62g91b04tctcf.json.gz

 13%|█▎        | 321/2404 [06:30<39:22,  1.13s/it]

https://hiring.cafe/job/pjr8ozsiwsgjlzkc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pjr8ozsiwsgjlzkc.json.gz

 13%|█▎        | 322/2404 [06:32<40:09,  1.16s/it]

https://hiring.cafe/job/no2s27wv7olyokkn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\no2s27wv7olyokkn.json.gz

 13%|█▎        | 323/2404 [06:33<39:04,  1.13s/it]

https://hiring.cafe/job/ezm53bk9gne6zv7d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ezm53bk9gne6zv7d.json.gz

 13%|█▎        | 324/2404 [06:34<37:43,  1.09s/it]

https://hiring.cafe/job/0uawpcs8d8irgym9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0uawpcs8d8irgym9.json.gz

 14%|█▎        | 325/2404 [06:35<38:08,  1.10s/it]

https://hiring.cafe/job/lmi9nnxa5isbiixo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lmi9nnxa5isbiixo.json.gz

 14%|█▎        | 326/2404 [06:36<38:02,  1.10s/it]

https://hiring.cafe/job/3tmaywkdtudtpkhs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3tmaywkdtudtpkhs.json.gz

 14%|█▎        | 327/2404 [06:37<41:32,  1.20s/it]

https://hiring.cafe/job/jcs7k6vufjq5ppfa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jcs7k6vufjq5ppfa.json.gz

 14%|█▎        | 328/2404 [06:38<39:58,  1.16s/it]

https://hiring.cafe/job/2u4087kv4wkh91y8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2u4087kv4wkh91y8.json.gz

 14%|█▎        | 329/2404 [06:40<40:40,  1.18s/it]

https://hiring.cafe/job/g2zc05h4ookchpz4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g2zc05h4ookchpz4.json.gz

 14%|█▎        | 330/2404 [06:41<39:03,  1.13s/it]

https://hiring.cafe/job/13xo0m2fee8m7g6k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\13xo0m2fee8m7g6k.json.gz

 14%|█▍        | 331/2404 [06:42<42:52,  1.24s/it]

https://hiring.cafe/job/6lnrj3c603z8ia0b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6lnrj3c603z8ia0b.json.gz

 14%|█▍        | 332/2404 [06:43<42:11,  1.22s/it]

https://hiring.cafe/job/r3w9o6ogevy8obm9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r3w9o6ogevy8obm9.json.gz

 14%|█▍        | 333/2404 [06:44<39:26,  1.14s/it]

https://hiring.cafe/job/q91bxn00zl3dzl76
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q91bxn00zl3dzl76.json.gz

 14%|█▍        | 334/2404 [06:45<39:00,  1.13s/it]

https://hiring.cafe/job/4jx5ypswbkgk85go
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4jx5ypswbkgk85go.json.gz

 14%|█▍        | 335/2404 [06:47<42:05,  1.22s/it]

https://hiring.cafe/job/ro7eew2g5mz9g05h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ro7eew2g5mz9g05h.json.gz

 14%|█▍        | 336/2404 [06:48<40:21,  1.17s/it]

https://hiring.cafe/job/e1xnnt2wcddns4a0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e1xnnt2wcddns4a0.json.gz

 14%|█▍        | 337/2404 [06:49<39:35,  1.15s/it]

https://hiring.cafe/job/nfutupcgec6god78
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nfutupcgec6god78.json.gz

 14%|█▍        | 338/2404 [06:50<39:51,  1.16s/it]

https://hiring.cafe/job/lud6n3jyylx001tb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lud6n3jyylx001tb.json.gz

 14%|█▍        | 339/2404 [06:51<40:29,  1.18s/it]

https://hiring.cafe/job/92kfy6c7lsadfhhz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\92kfy6c7lsadfhhz.json.gz

 14%|█▍        | 340/2404 [06:52<38:03,  1.11s/it]

https://hiring.cafe/job/7sy3bvzrjdx516w3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7sy3bvzrjdx516w3.json.gz

 14%|█▍        | 341/2404 [06:53<39:08,  1.14s/it]

https://hiring.cafe/job/apx2cee23uog7twu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\apx2cee23uog7twu.json.gz

 14%|█▍        | 342/2404 [06:55<39:33,  1.15s/it]

https://hiring.cafe/job/8tc7y0ny9qqnkhx0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8tc7y0ny9qqnkhx0.json.gz

 14%|█▍        | 343/2404 [06:56<41:26,  1.21s/it]

https://hiring.cafe/job/ois58c4tuba49jgh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ois58c4tuba49jgh.json.gz

 14%|█▍        | 344/2404 [06:57<38:01,  1.11s/it]

https://hiring.cafe/job/7cog6uwg8ehrbh22
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7cog6uwg8ehrbh22.json.gz

 14%|█▍        | 345/2404 [06:58<36:32,  1.06s/it]

https://hiring.cafe/job/2vspsf5ek5fkp4ue
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2vspsf5ek5fkp4ue.json.gz

 14%|█▍        | 346/2404 [06:59<39:27,  1.15s/it]

https://hiring.cafe/job/8c6t4bnu39cuqgio
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8c6t4bnu39cuqgio.json.gz

 14%|█▍        | 347/2404 [07:00<39:06,  1.14s/it]

https://hiring.cafe/job/q7cjssxph01etlnz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q7cjssxph01etlnz.json.gz

 14%|█▍        | 348/2404 [07:01<39:40,  1.16s/it]

https://hiring.cafe/job/470zd02a2aoklv1w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\470zd02a2aoklv1w.json.gz

 15%|█▍        | 349/2404 [07:03<40:57,  1.20s/it]

https://hiring.cafe/job/0x03d7jopeieu4yy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0x03d7jopeieu4yy.json.gz

 15%|█▍        | 350/2404 [07:04<37:28,  1.09s/it]

https://hiring.cafe/job/4533yejei3hdtemv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4533yejei3hdtemv.json.gz

 15%|█▍        | 351/2404 [07:05<37:01,  1.08s/it]

https://hiring.cafe/job/svdpbu7l2elnvkxa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\svdpbu7l2elnvkxa.json.gz

 15%|█▍        | 352/2404 [07:06<37:57,  1.11s/it]

https://hiring.cafe/job/z85vsvmoqt0ph7dg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z85vsvmoqt0ph7dg.json.gz

 15%|█▍        | 353/2404 [07:07<37:54,  1.11s/it]

https://hiring.cafe/job/wixgdlzmeijy4nlz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wixgdlzmeijy4nlz.json.gz

 15%|█▍        | 354/2404 [07:08<37:52,  1.11s/it]

https://hiring.cafe/job/kd4wyrxrajuy07vi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kd4wyrxrajuy07vi.json.gz

 15%|█▍        | 355/2404 [07:09<38:36,  1.13s/it]

https://hiring.cafe/job/3wjpi01y5jv85s92
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3wjpi01y5jv85s92.json.gz

 15%|█▍        | 356/2404 [07:11<41:09,  1.21s/it]

https://hiring.cafe/job/1zi0wmeduet8wi5f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1zi0wmeduet8wi5f.json.gz

 15%|█▍        | 357/2404 [07:12<43:15,  1.27s/it]

https://hiring.cafe/job/sdbxw6z1yts133yu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sdbxw6z1yts133yu.json.gz

 15%|█▍        | 358/2404 [07:13<41:29,  1.22s/it]

https://hiring.cafe/job/cqx0a2o8oyzv2csw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cqx0a2o8oyzv2csw.json.gz

 15%|█▍        | 359/2404 [07:15<45:45,  1.34s/it]

https://hiring.cafe/job/lul4uas29r43w5g0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lul4uas29r43w5g0.json.gz

 15%|█▍        | 360/2404 [07:17<52:08,  1.53s/it]

https://hiring.cafe/job/07kcj1a4ltg2u3gl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\07kcj1a4ltg2u3gl.json.gz

 15%|█▌        | 361/2404 [07:19<58:37,  1.72s/it]

https://hiring.cafe/job/hpa7q18rl4rti4kw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hpa7q18rl4rti4kw.json.gz

 15%|█▌        | 362/2404 [07:21<1:05:08,  1.91s/it]

https://hiring.cafe/job/0hwjgickb1uen4e2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0hwjgickb1uen4e2.json.gz

 15%|█▌        | 363/2404 [07:24<1:09:45,  2.05s/it]

https://hiring.cafe/job/3sozitlq1ca8or8l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3sozitlq1ca8or8l.json.gz

 15%|█▌        | 364/2404 [07:25<1:04:35,  1.90s/it]

https://hiring.cafe/job/mehosaiigdo9w5l2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mehosaiigdo9w5l2.json.gz

 15%|█▌        | 365/2404 [07:30<1:34:00,  2.77s/it]

https://hiring.cafe/job/va8rlouhup4lvu5t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\va8rlouhup4lvu5t.json.gz

 15%|█▌        | 366/2404 [07:31<1:18:41,  2.32s/it]

https://hiring.cafe/job/dd4ez3j8qu3jpblh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dd4ez3j8qu3jpblh.json.gz

 15%|█▌        | 367/2404 [07:32<1:07:00,  1.97s/it]

https://hiring.cafe/job/rfjwf0n2zwpg8ow9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rfjwf0n2zwpg8ow9.json.gz

 15%|█▌        | 368/2404 [07:34<59:24,  1.75s/it]

https://hiring.cafe/job/qshtzsf14gaajt9x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qshtzsf14gaajt9x.json.gz

 15%|█▌        | 369/2404 [07:35<51:51,  1.53s/it]

https://hiring.cafe/job/sf6mirc9nji8jdrf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sf6mirc9nji8jdrf.json.gz

 15%|█▌        | 370/2404 [07:36<47:27,  1.40s/it]

https://hiring.cafe/job/ls5ujx9tmllgq5ds
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ls5ujx9tmllgq5ds.json.gz

 15%|█▌        | 371/2404 [07:37<44:24,  1.31s/it]

https://hiring.cafe/job/tw57fqj3tckv78kb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tw57fqj3tckv78kb.json.gz

 15%|█▌        | 372/2404 [07:38<42:39,  1.26s/it]

https://hiring.cafe/job/15kreo5jr70xgfx1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\15kreo5jr70xgfx1.json.gz

 16%|█▌        | 373/2404 [07:39<43:49,  1.29s/it]

https://hiring.cafe/job/0e3efjrjrziq9zfu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0e3efjrjrziq9zfu.json.gz

 16%|█▌        | 374/2404 [07:40<40:12,  1.19s/it]

https://hiring.cafe/job/impsfcslt5fi60yt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\impsfcslt5fi60yt.json.gz

 16%|█▌        | 375/2404 [07:41<40:36,  1.20s/it]

https://hiring.cafe/job/v1q5alc010mqhbyu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v1q5alc010mqhbyu.json.gz

 16%|█▌        | 376/2404 [07:43<40:34,  1.20s/it]

https://hiring.cafe/job/cm00chk4nn5aadgk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cm00chk4nn5aadgk.json.gz

 16%|█▌        | 377/2404 [07:44<40:04,  1.19s/it]

https://hiring.cafe/job/rvhpur3txae171kg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rvhpur3txae171kg.json.gz

 16%|█▌        | 378/2404 [07:45<37:34,  1.11s/it]

https://hiring.cafe/job/gyt7h7y6rti4kctu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gyt7h7y6rti4kctu.json.gz

 16%|█▌        | 379/2404 [07:46<39:28,  1.17s/it]

https://hiring.cafe/job/3hts654ickzzrhkf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3hts654ickzzrhkf.json.gz

 16%|█▌        | 380/2404 [07:47<40:56,  1.21s/it]

https://hiring.cafe/job/pnfjz16vkl23hry7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pnfjz16vkl23hry7.json.gz

 16%|█▌        | 381/2404 [07:49<40:55,  1.21s/it]

https://hiring.cafe/job/drnayp9ouwjncc6x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\drnayp9ouwjncc6x.json.gz

 16%|█▌        | 382/2404 [07:50<41:07,  1.22s/it]

https://hiring.cafe/job/9gahob0zkdfqo6uq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9gahob0zkdfqo6uq.json.gz

 16%|█▌        | 383/2404 [07:51<40:45,  1.21s/it]

https://hiring.cafe/job/ybsy1bva96231eyn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ybsy1bva96231eyn.json.gz

 16%|█▌        | 384/2404 [07:52<42:43,  1.27s/it]

https://hiring.cafe/job/r4yph24mqiw188wc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r4yph24mqiw188wc.json.gz

 16%|█▌        | 385/2404 [07:54<44:13,  1.31s/it]

https://hiring.cafe/job/2088o97utnxvifqo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2088o97utnxvifqo.json.gz

 16%|█▌        | 386/2404 [07:55<42:12,  1.25s/it]

https://hiring.cafe/job/n3hwxrkwbw178o7x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n3hwxrkwbw178o7x.json.gz

 16%|█▌        | 387/2404 [07:56<38:21,  1.14s/it]

https://hiring.cafe/job/jipg0dqvtik1wqkr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jipg0dqvtik1wqkr.json.gz

 16%|█▌        | 388/2404 [07:57<40:01,  1.19s/it]

https://hiring.cafe/job/syouci9t4i3tat3u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\syouci9t4i3tat3u.json.gz

 16%|█▌        | 389/2404 [07:59<41:46,  1.24s/it]

https://hiring.cafe/job/f5uqlktxfo88si2s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f5uqlktxfo88si2s.json.gz

 16%|█▌        | 390/2404 [08:00<41:38,  1.24s/it]

https://hiring.cafe/job/2f8ph29pfftibgvs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2f8ph29pfftibgvs.json.gz

 16%|█▋        | 391/2404 [08:01<40:29,  1.21s/it]

https://hiring.cafe/job/8ga0xjpoq7x0iuvx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8ga0xjpoq7x0iuvx.json.gz

 16%|█▋        | 392/2404 [08:02<41:44,  1.24s/it]

https://hiring.cafe/job/obyt0rukjsx12k9a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\obyt0rukjsx12k9a.json.gz

 16%|█▋        | 393/2404 [08:03<40:35,  1.21s/it]

https://hiring.cafe/job/awb5d1vdh5o7wczo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\awb5d1vdh5o7wczo.json.gz

 16%|█▋        | 394/2404 [08:04<39:16,  1.17s/it]

https://hiring.cafe/job/5zmx6t1kavty4763
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5zmx6t1kavty4763.json.gz

 16%|█▋        | 395/2404 [08:06<39:28,  1.18s/it]

https://hiring.cafe/job/6mwhdr46e2ycya38
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6mwhdr46e2ycya38.json.gz

 16%|█▋        | 396/2404 [08:07<39:50,  1.19s/it]

https://hiring.cafe/job/uiaynzi5f6urzd58
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uiaynzi5f6urzd58.json.gz

 17%|█▋        | 397/2404 [08:08<39:10,  1.17s/it]

https://hiring.cafe/job/11i4p4mweww5ywrx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\11i4p4mweww5ywrx.json.gz

 17%|█▋        | 398/2404 [08:09<41:06,  1.23s/it]

https://hiring.cafe/job/lpf5dow0rk2njvwo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lpf5dow0rk2njvwo.json.gz

 17%|█▋        | 399/2404 [08:11<40:41,  1.22s/it]

https://hiring.cafe/job/xmv7auvxiawgbphf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xmv7auvxiawgbphf.json.gz

 17%|█▋        | 400/2404 [08:12<39:26,  1.18s/it]

https://hiring.cafe/job/7yicj2cdt86jg3d3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7yicj2cdt86jg3d3.json.gz

 17%|█▋        | 401/2404 [08:13<37:11,  1.11s/it]

https://hiring.cafe/job/zdqq02fnz1ggl7gh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zdqq02fnz1ggl7gh.json.gz

 17%|█▋        | 402/2404 [08:14<40:30,  1.21s/it]

https://hiring.cafe/job/ytm9fmziydfbuyd2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ytm9fmziydfbuyd2.json.gz

 17%|█▋        | 403/2404 [08:15<41:11,  1.23s/it]

https://hiring.cafe/job/k32rsd53gvy03zjh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k32rsd53gvy03zjh.json.gz

 17%|█▋        | 404/2404 [08:17<43:44,  1.31s/it]

https://hiring.cafe/job/zdum6x3g5z5iv8jr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zdum6x3g5z5iv8jr.json.gz

 17%|█▋        | 405/2404 [08:18<43:55,  1.32s/it]

https://hiring.cafe/job/w6yo9iq712m415vl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w6yo9iq712m415vl.json.gz

 17%|█▋        | 406/2404 [08:19<41:18,  1.24s/it]

https://hiring.cafe/job/kovpndnf91aljp62
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kovpndnf91aljp62.json.gz

 17%|█▋        | 407/2404 [08:20<38:01,  1.14s/it]

https://hiring.cafe/job/dm2chv3z9s2kmncv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dm2chv3z9s2kmncv.json.gz

 17%|█▋        | 408/2404 [08:21<38:08,  1.15s/it]

https://hiring.cafe/job/noelorqwb7kkab7t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\noelorqwb7kkab7t.json.gz

 17%|█▋        | 409/2404 [08:22<38:42,  1.16s/it]

https://hiring.cafe/job/estwq6qygcs52px4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\estwq6qygcs52px4.json.gz

 17%|█▋        | 410/2404 [08:24<37:18,  1.12s/it]

https://hiring.cafe/job/xjc4whqx7vhaieyn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xjc4whqx7vhaieyn.json.gz

 17%|█▋        | 411/2404 [08:24<35:49,  1.08s/it]

https://hiring.cafe/job/6bhpzu5sy2ue75ng
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6bhpzu5sy2ue75ng.json.gz

 17%|█▋        | 412/2404 [08:26<36:13,  1.09s/it]

https://hiring.cafe/job/b7mtb1hw7z9r6upy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b7mtb1hw7z9r6upy.json.gz

 17%|█▋        | 413/2404 [08:27<38:52,  1.17s/it]

https://hiring.cafe/job/tpuw1osc7pau7v1r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tpuw1osc7pau7v1r.json.gz

 17%|█▋        | 414/2404 [08:28<38:18,  1.15s/it]

https://hiring.cafe/job/sdb20h5bb87p3k9f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sdb20h5bb87p3k9f.json.gz

 17%|█▋        | 415/2404 [08:29<37:47,  1.14s/it]

https://hiring.cafe/job/qvbmei2jio3erz45
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qvbmei2jio3erz45.json.gz

 17%|█▋        | 416/2404 [08:30<38:03,  1.15s/it]

https://hiring.cafe/job/xkqwgo5842bduo6s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xkqwgo5842bduo6s.json.gz

 17%|█▋        | 417/2404 [08:32<40:05,  1.21s/it]

https://hiring.cafe/job/iohikrbigmby2tgq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iohikrbigmby2tgq.json.gz

 17%|█▋        | 418/2404 [08:33<38:50,  1.17s/it]

https://hiring.cafe/job/p3vqx9j2xl4gx8j2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p3vqx9j2xl4gx8j2.json.gz

 17%|█▋        | 419/2404 [08:34<40:54,  1.24s/it]

https://hiring.cafe/job/2iqcvnk39ugzq7p6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2iqcvnk39ugzq7p6.json.gz

 17%|█▋        | 420/2404 [08:35<38:06,  1.15s/it]

https://hiring.cafe/job/9h5lb64361aqijk8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9h5lb64361aqijk8.json.gz

 18%|█▊        | 421/2404 [08:36<39:47,  1.20s/it]

https://hiring.cafe/job/g6afeafxv0hgxu5t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g6afeafxv0hgxu5t.json.gz

 18%|█▊        | 422/2404 [08:37<38:07,  1.15s/it]

https://hiring.cafe/job/nmjmntkfxhldycpp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nmjmntkfxhldycpp.json.gz

 18%|█▊        | 423/2404 [08:39<37:33,  1.14s/it]

https://hiring.cafe/job/7iv0yxrk8onrhrnh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7iv0yxrk8onrhrnh.json.gz

 18%|█▊        | 424/2404 [08:40<36:07,  1.09s/it]

https://hiring.cafe/job/i6b8knp02lxma3de
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i6b8knp02lxma3de.json.gz

 18%|█▊        | 425/2404 [08:41<37:07,  1.13s/it]

https://hiring.cafe/job/kir2189e2qb4fez9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kir2189e2qb4fez9.json.gz

 18%|█▊        | 426/2404 [08:42<40:52,  1.24s/it]

https://hiring.cafe/job/gj4vhm9rav0estem
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gj4vhm9rav0estem.json.gz

 18%|█▊        | 427/2404 [08:43<38:41,  1.17s/it]

https://hiring.cafe/job/bvyx2j46agoz6xq0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bvyx2j46agoz6xq0.json.gz

 18%|█▊        | 428/2404 [08:44<38:38,  1.17s/it]

https://hiring.cafe/job/xt6l03la0p8r7fn7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xt6l03la0p8r7fn7.json.gz

 18%|█▊        | 429/2404 [08:46<39:49,  1.21s/it]

https://hiring.cafe/job/zg7qv3rexrueejym
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zg7qv3rexrueejym.json.gz

 18%|█▊        | 430/2404 [08:47<37:21,  1.14s/it]

https://hiring.cafe/job/6thigovrvjc98tx6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6thigovrvjc98tx6.json.gz

 18%|█▊        | 431/2404 [08:48<40:11,  1.22s/it]

https://hiring.cafe/job/60ymsipq98le6y1m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\60ymsipq98le6y1m.json.gz

 18%|█▊        | 432/2404 [08:49<39:28,  1.20s/it]

https://hiring.cafe/job/fasg1ovvbrp284vt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fasg1ovvbrp284vt.json.gz

 18%|█▊        | 433/2404 [08:50<38:51,  1.18s/it]

https://hiring.cafe/job/pk5esvsoyxx612o2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pk5esvsoyxx612o2.json.gz

 18%|█▊        | 434/2404 [08:52<39:11,  1.19s/it]

https://hiring.cafe/job/fnl01wefixebfynn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fnl01wefixebfynn.json.gz

 18%|█▊        | 435/2404 [08:53<38:34,  1.18s/it]

https://hiring.cafe/job/8x6r9q85563sayf9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8x6r9q85563sayf9.json.gz

 18%|█▊        | 436/2404 [08:54<38:30,  1.17s/it]

https://hiring.cafe/job/0n5scndjqy541l8m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0n5scndjqy541l8m.json.gz

 18%|█▊        | 437/2404 [08:55<38:47,  1.18s/it]

https://hiring.cafe/job/h4lmix56idlo8i55
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h4lmix56idlo8i55.json.gz

 18%|█▊        | 438/2404 [08:57<40:28,  1.23s/it]

https://hiring.cafe/job/yr66zsfnotcgmlz8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yr66zsfnotcgmlz8.json.gz

 18%|█▊        | 439/2404 [08:58<40:47,  1.25s/it]

https://hiring.cafe/job/459t9gaqb9umtx4w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\459t9gaqb9umtx4w.json.gz

 18%|█▊        | 440/2404 [08:59<41:28,  1.27s/it]

https://hiring.cafe/job/fmijvqreefw8y3hd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fmijvqreefw8y3hd.json.gz

 18%|█▊        | 441/2404 [09:00<39:53,  1.22s/it]

https://hiring.cafe/job/5j9cpydgfrw051qe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5j9cpydgfrw051qe.json.gz

 18%|█▊        | 442/2404 [09:01<38:55,  1.19s/it]

https://hiring.cafe/job/5a1zi2b3vn9uqkv5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5a1zi2b3vn9uqkv5.json.gz

 18%|█▊        | 443/2404 [09:02<37:44,  1.15s/it]

https://hiring.cafe/job/tl1k80aoa48eqxwc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tl1k80aoa48eqxwc.json.gz

 18%|█▊        | 444/2404 [09:04<38:25,  1.18s/it]

https://hiring.cafe/job/os7vjvspkcdqboho
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\os7vjvspkcdqboho.json.gz

 19%|█▊        | 445/2404 [09:05<39:55,  1.22s/it]

https://hiring.cafe/job/ulmybn0w4si9clmu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ulmybn0w4si9clmu.json.gz

 19%|█▊        | 446/2404 [09:06<38:17,  1.17s/it]

https://hiring.cafe/job/mcg19cmj7pbtb206
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mcg19cmj7pbtb206.json.gz

 19%|█▊        | 447/2404 [09:07<39:47,  1.22s/it]

https://hiring.cafe/job/08p4szq9gdhc6ele
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\08p4szq9gdhc6ele.json.gz

 19%|█▊        | 448/2404 [09:09<41:58,  1.29s/it]

https://hiring.cafe/job/65nfghb4fdlgi07m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\65nfghb4fdlgi07m.json.gz

 19%|█▊        | 449/2404 [09:10<43:12,  1.33s/it]

https://hiring.cafe/job/9ptrvnhqg9smjtwx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9ptrvnhqg9smjtwx.json.gz

 19%|█▊        | 450/2404 [09:12<43:33,  1.34s/it]

https://hiring.cafe/job/b8709cnz7oaiypsj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b8709cnz7oaiypsj.json.gz

 19%|█▉        | 451/2404 [09:13<43:18,  1.33s/it]

https://hiring.cafe/job/juu0ont9nt87vj1g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\juu0ont9nt87vj1g.json.gz

 19%|█▉        | 452/2404 [09:14<44:17,  1.36s/it]

https://hiring.cafe/job/0a0jmwuk2hlm9amt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0a0jmwuk2hlm9amt.json.gz

 19%|█▉        | 453/2404 [09:16<43:10,  1.33s/it]

https://hiring.cafe/job/m69vexpzx8m3lqj9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m69vexpzx8m3lqj9.json.gz

 19%|█▉        | 454/2404 [09:17<41:25,  1.27s/it]

https://hiring.cafe/job/hgyepbgpld2scomh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hgyepbgpld2scomh.json.gz

 19%|█▉        | 455/2404 [09:18<41:00,  1.26s/it]

https://hiring.cafe/job/5bky3vzy2hhm1e31
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5bky3vzy2hhm1e31.json.gz

 19%|█▉        | 456/2404 [09:19<40:02,  1.23s/it]

https://hiring.cafe/job/j8ts1efzkl1unbup
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j8ts1efzkl1unbup.json.gz

 19%|█▉        | 457/2404 [09:20<39:48,  1.23s/it]

https://hiring.cafe/job/zbl30uu7u6snnot2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zbl30uu7u6snnot2.json.gz

 19%|█▉        | 458/2404 [09:22<40:23,  1.25s/it]

https://hiring.cafe/job/mq2lfhu20rf3rfwu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mq2lfhu20rf3rfwu.json.gz

 19%|█▉        | 459/2404 [09:23<39:07,  1.21s/it]

https://hiring.cafe/job/p9hdw8wty7dyx779
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p9hdw8wty7dyx779.json.gz

 19%|█▉        | 460/2404 [09:24<39:38,  1.22s/it]

https://hiring.cafe/job/xqddvaed6ku95cfq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xqddvaed6ku95cfq.json.gz

 19%|█▉        | 461/2404 [09:25<41:11,  1.27s/it]

https://hiring.cafe/job/j25xbxzwbqr07h0j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j25xbxzwbqr07h0j.json.gz

 19%|█▉        | 462/2404 [09:27<41:24,  1.28s/it]

https://hiring.cafe/job/j35gasr27ub7cv6l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j35gasr27ub7cv6l.json.gz

 19%|█▉        | 463/2404 [09:28<41:04,  1.27s/it]

https://hiring.cafe/job/0nyi1kn304idszyq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0nyi1kn304idszyq.json.gz

 19%|█▉        | 464/2404 [09:29<40:45,  1.26s/it]

https://hiring.cafe/job/a0noafmhbcjyrwha
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a0noafmhbcjyrwha.json.gz

 19%|█▉        | 465/2404 [09:30<41:06,  1.27s/it]

https://hiring.cafe/job/cows5mcfys6pb7eq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cows5mcfys6pb7eq.json.gz

 19%|█▉        | 466/2404 [09:32<41:39,  1.29s/it]

https://hiring.cafe/job/n0rktg5wumg3vpmp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n0rktg5wumg3vpmp.json.gz

 19%|█▉        | 467/2404 [09:33<43:38,  1.35s/it]

https://hiring.cafe/job/mlivysu2xvaxod3l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mlivysu2xvaxod3l.json.gz

 19%|█▉        | 468/2404 [09:34<40:17,  1.25s/it]

https://hiring.cafe/job/miibaaeza5s4jwq0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\miibaaeza5s4jwq0.json.gz

 20%|█▉        | 469/2404 [09:36<40:30,  1.26s/it]

https://hiring.cafe/job/7oo5zymnsv08833k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7oo5zymnsv08833k.json.gz

 20%|█▉        | 470/2404 [09:37<41:33,  1.29s/it]

https://hiring.cafe/job/0jv1mjwctm7wrsme
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0jv1mjwctm7wrsme.json.gz

 20%|█▉        | 471/2404 [09:38<38:57,  1.21s/it]

https://hiring.cafe/job/0ee10xql6uujzr6j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ee10xql6uujzr6j.json.gz

 20%|█▉        | 472/2404 [09:39<40:15,  1.25s/it]

https://hiring.cafe/job/pwkgynyrmo4oer5f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pwkgynyrmo4oer5f.json.gz

 20%|█▉        | 473/2404 [09:40<38:59,  1.21s/it]

https://hiring.cafe/job/2fee86cu3iu3v7nh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2fee86cu3iu3v7nh.json.gz

 20%|█▉        | 474/2404 [09:41<35:29,  1.10s/it]

https://hiring.cafe/job/te101nk9ghbjibuv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\te101nk9ghbjibuv.json.gz

 20%|█▉        | 475/2404 [09:42<36:13,  1.13s/it]

https://hiring.cafe/job/1paex4z6p4tqcpf9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1paex4z6p4tqcpf9.json.gz

 20%|█▉        | 476/2404 [09:43<34:51,  1.08s/it]

https://hiring.cafe/job/mexblccsjzut82jl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mexblccsjzut82jl.json.gz

 20%|█▉        | 477/2404 [09:45<36:23,  1.13s/it]

https://hiring.cafe/job/qr7vngw6l4vrfras
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qr7vngw6l4vrfras.json.gz

 20%|█▉        | 478/2404 [09:46<35:47,  1.12s/it]

https://hiring.cafe/job/21p8fnquaw9hg02c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\21p8fnquaw9hg02c.json.gz

 20%|█▉        | 479/2404 [09:47<37:06,  1.16s/it]

https://hiring.cafe/job/wuwuyro9y8evaaax
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wuwuyro9y8evaaax.json.gz

 20%|█▉        | 480/2404 [09:48<38:05,  1.19s/it]

https://hiring.cafe/job/ta0nju6fcc0j648c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ta0nju6fcc0j648c.json.gz

 20%|██        | 481/2404 [09:49<37:42,  1.18s/it]

https://hiring.cafe/job/p7henfy9gtqjc1tt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p7henfy9gtqjc1tt.json.gz

 20%|██        | 482/2404 [09:51<36:30,  1.14s/it]

https://hiring.cafe/job/yslpffsaqeqgkjz3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yslpffsaqeqgkjz3.json.gz

 20%|██        | 483/2404 [09:52<38:51,  1.21s/it]

https://hiring.cafe/job/ifi884ka3awtzwso
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ifi884ka3awtzwso.json.gz

 20%|██        | 484/2404 [09:53<36:11,  1.13s/it]

https://hiring.cafe/job/bnb36cmhasowqzu2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bnb36cmhasowqzu2.json.gz

 20%|██        | 485/2404 [09:54<36:49,  1.15s/it]

https://hiring.cafe/job/pu782zk941t56mv1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pu782zk941t56mv1.json.gz

 20%|██        | 486/2404 [09:55<38:52,  1.22s/it]

https://hiring.cafe/job/j4kgjg8utjmf1igf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j4kgjg8utjmf1igf.json.gz

 20%|██        | 487/2404 [09:57<38:09,  1.19s/it]

https://hiring.cafe/job/lzkpg0dt895pi81h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lzkpg0dt895pi81h.json.gz

 20%|██        | 488/2404 [09:58<38:04,  1.19s/it]

https://hiring.cafe/job/g75p7n4693nzsybr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g75p7n4693nzsybr.json.gz

 20%|██        | 489/2404 [09:59<37:25,  1.17s/it]

https://hiring.cafe/job/zybntaprijotn5g7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zybntaprijotn5g7.json.gz

 20%|██        | 490/2404 [10:00<37:56,  1.19s/it]

https://hiring.cafe/job/pfijmdn2wp6q1g2d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pfijmdn2wp6q1g2d.json.gz

 20%|██        | 491/2404 [10:01<38:17,  1.20s/it]

https://hiring.cafe/job/3fd23xnzju9r007i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3fd23xnzju9r007i.json.gz

 20%|██        | 492/2404 [10:03<39:36,  1.24s/it]

https://hiring.cafe/job/ffrzrfvx3eqaotpq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ffrzrfvx3eqaotpq.json.gz

 21%|██        | 493/2404 [10:04<38:54,  1.22s/it]

https://hiring.cafe/job/3ii4f3fsu9blwvft
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3ii4f3fsu9blwvft.json.gz

 21%|██        | 494/2404 [10:05<41:48,  1.31s/it]

https://hiring.cafe/job/8zwac193y0k535p5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8zwac193y0k535p5.json.gz

 21%|██        | 495/2404 [10:07<40:41,  1.28s/it]

https://hiring.cafe/job/lzc5a6glx358hycz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lzc5a6glx358hycz.json.gz

 21%|██        | 496/2404 [10:08<39:41,  1.25s/it]

https://hiring.cafe/job/hmymn8ui8gw5s4mc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hmymn8ui8gw5s4mc.json.gz

 21%|██        | 497/2404 [10:09<37:43,  1.19s/it]

https://hiring.cafe/job/47tijycymkqm0urg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\47tijycymkqm0urg.json.gz

 21%|██        | 498/2404 [10:10<39:47,  1.25s/it]

https://hiring.cafe/job/3tssu3ccsnvwgxgz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3tssu3ccsnvwgxgz.json.gz

 21%|██        | 499/2404 [10:12<40:46,  1.28s/it]

https://hiring.cafe/job/3tm7vlvxghafy27l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3tm7vlvxghafy27l.json.gz

 21%|██        | 500/2404 [10:13<40:39,  1.28s/it]

https://hiring.cafe/job/k3f24rb6yp4to5s3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k3f24rb6yp4to5s3.json.gz

 21%|██        | 501/2404 [10:14<38:58,  1.23s/it]

https://hiring.cafe/job/2n5dpkcaoanctd67
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2n5dpkcaoanctd67.json.gz

 21%|██        | 502/2404 [10:15<41:32,  1.31s/it]

https://hiring.cafe/job/t7w6dta38uw9g6d2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t7w6dta38uw9g6d2.json.gz

 21%|██        | 503/2404 [10:17<40:29,  1.28s/it]

https://hiring.cafe/job/mc54psd5262dcrfl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mc54psd5262dcrfl.json.gz

 21%|██        | 504/2404 [10:18<46:01,  1.45s/it]

https://hiring.cafe/job/9h5t45ok9m04n5m3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9h5t45ok9m04n5m3.json.gz

 21%|██        | 505/2404 [10:20<50:54,  1.61s/it]

https://hiring.cafe/job/b1ra30am66sr9s26
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b1ra30am66sr9s26.json.gz

 21%|██        | 506/2404 [10:22<47:52,  1.51s/it]

https://hiring.cafe/job/jkbf6pbkgpynwj51
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jkbf6pbkgpynwj51.json.gz

 21%|██        | 507/2404 [10:23<45:13,  1.43s/it]

https://hiring.cafe/job/n2mt3kke3vgn3d0q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n2mt3kke3vgn3d0q.json.gz

 21%|██        | 508/2404 [10:24<43:56,  1.39s/it]

https://hiring.cafe/job/5q2780knmbd9ip1m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5q2780knmbd9ip1m.json.gz

 21%|██        | 509/2404 [10:26<42:16,  1.34s/it]

https://hiring.cafe/job/zm33a6cch18dxucq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zm33a6cch18dxucq.json.gz

 21%|██        | 510/2404 [10:27<39:50,  1.26s/it]

https://hiring.cafe/job/fuhv79z3leevzrxw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fuhv79z3leevzrxw.json.gz

 21%|██▏       | 511/2404 [10:28<40:11,  1.27s/it]

https://hiring.cafe/job/scrberqs4rsgs6f9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\scrberqs4rsgs6f9.json.gz

 21%|██▏       | 512/2404 [10:29<41:03,  1.30s/it]

https://hiring.cafe/job/ukqboyar5h6f44oq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ukqboyar5h6f44oq.json.gz

 21%|██▏       | 513/2404 [10:30<40:13,  1.28s/it]

https://hiring.cafe/job/y9srsaish02ve6zo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y9srsaish02ve6zo.json.gz

 21%|██▏       | 514/2404 [10:32<41:06,  1.31s/it]

https://hiring.cafe/job/pkyity9rmhkvk8k2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pkyity9rmhkvk8k2.json.gz

 21%|██▏       | 515/2404 [10:33<39:21,  1.25s/it]

https://hiring.cafe/job/pjz04uma399xsaqk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pjz04uma399xsaqk.json.gz

 21%|██▏       | 516/2404 [10:34<40:00,  1.27s/it]

https://hiring.cafe/job/tv3xvllinrum9ohz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tv3xvllinrum9ohz.json.gz

 22%|██▏       | 517/2404 [10:36<39:34,  1.26s/it]

https://hiring.cafe/job/0qu8s8hereqb93fc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0qu8s8hereqb93fc.json.gz

 22%|██▏       | 518/2404 [10:37<38:20,  1.22s/it]

https://hiring.cafe/job/vvwsn09nqyikxlyl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vvwsn09nqyikxlyl.json.gz

 22%|██▏       | 519/2404 [10:38<38:47,  1.23s/it]

https://hiring.cafe/job/lk6pxfdxpuxdcae9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lk6pxfdxpuxdcae9.json.gz

 22%|██▏       | 520/2404 [10:39<35:31,  1.13s/it]

https://hiring.cafe/job/bcsi89mph8kyd9zz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bcsi89mph8kyd9zz.json.gz

 22%|██▏       | 521/2404 [10:40<37:18,  1.19s/it]

https://hiring.cafe/job/r2457q1ds6jmvak0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r2457q1ds6jmvak0.json.gz

 22%|██▏       | 522/2404 [10:41<36:12,  1.15s/it]

https://hiring.cafe/job/cnv16yl3f1h6i519
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cnv16yl3f1h6i519.json.gz

 22%|██▏       | 523/2404 [10:42<36:51,  1.18s/it]

https://hiring.cafe/job/9jr5hhh35df88pgd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9jr5hhh35df88pgd.json.gz

 22%|██▏       | 524/2404 [10:43<35:00,  1.12s/it]

https://hiring.cafe/job/3av1rzzeoocrrv8j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3av1rzzeoocrrv8j.json.gz

 22%|██▏       | 525/2404 [10:45<36:06,  1.15s/it]

https://hiring.cafe/job/wdnlh7e8ummw00g2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wdnlh7e8ummw00g2.json.gz

 22%|██▏       | 526/2404 [10:46<35:26,  1.13s/it]

https://hiring.cafe/job/tzfzf362s0xp6kjd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tzfzf362s0xp6kjd.json.gz

 22%|██▏       | 527/2404 [10:47<36:36,  1.17s/it]

https://hiring.cafe/job/w8stai2uotbz1mhn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w8stai2uotbz1mhn.json.gz

 22%|██▏       | 528/2404 [10:48<37:22,  1.20s/it]

https://hiring.cafe/job/0q0j21es81pieu5o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0q0j21es81pieu5o.json.gz

 22%|██▏       | 529/2404 [10:49<37:05,  1.19s/it]

https://hiring.cafe/job/k8rham28oa8jukbo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k8rham28oa8jukbo.json.gz

 22%|██▏       | 530/2404 [10:51<36:50,  1.18s/it]

https://hiring.cafe/job/oz08mpg94v4t0bb4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oz08mpg94v4t0bb4.json.gz

 22%|██▏       | 531/2404 [10:52<36:07,  1.16s/it]

https://hiring.cafe/job/cxpufeb37prkub3y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cxpufeb37prkub3y.json.gz

 22%|██▏       | 532/2404 [10:53<37:00,  1.19s/it]

https://hiring.cafe/job/6vbrew6h0c23jnkm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6vbrew6h0c23jnkm.json.gz

 22%|██▏       | 533/2404 [10:55<40:38,  1.30s/it]

https://hiring.cafe/job/w4qybi4586s41jp7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w4qybi4586s41jp7.json.gz

 22%|██▏       | 534/2404 [10:56<40:13,  1.29s/it]

https://hiring.cafe/job/56agb333n3tgstfg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\56agb333n3tgstfg.json.gz

 22%|██▏       | 535/2404 [10:57<42:36,  1.37s/it]

https://hiring.cafe/job/0whptu5vtzp15a7g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0whptu5vtzp15a7g.json.gz

 22%|██▏       | 536/2404 [10:59<41:10,  1.32s/it]

https://hiring.cafe/job/ylzgsxrpoubgf4pw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ylzgsxrpoubgf4pw.json.gz

 22%|██▏       | 537/2404 [10:59<36:54,  1.19s/it]

https://hiring.cafe/job/ychvszdgaugvicoj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ychvszdgaugvicoj.json.gz

 22%|██▏       | 538/2404 [11:01<36:33,  1.18s/it]

https://hiring.cafe/job/dpihjik0ziz47bh8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dpihjik0ziz47bh8.json.gz

 22%|██▏       | 539/2404 [11:02<39:00,  1.26s/it]

https://hiring.cafe/job/pqhvhwxjjjj5focy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pqhvhwxjjjj5focy.json.gz

 22%|██▏       | 540/2404 [11:03<38:34,  1.24s/it]

https://hiring.cafe/job/var6jlkgmpqqgfqk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\var6jlkgmpqqgfqk.json.gz

 23%|██▎       | 541/2404 [11:04<36:01,  1.16s/it]

https://hiring.cafe/job/hnbg8cvq6is6ac2o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hnbg8cvq6is6ac2o.json.gz

 23%|██▎       | 542/2404 [11:05<36:54,  1.19s/it]

https://hiring.cafe/job/v9xzx25fge1q8dyg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v9xzx25fge1q8dyg.json.gz

 23%|██▎       | 543/2404 [11:07<39:23,  1.27s/it]

https://hiring.cafe/job/qy2o1blnrdeg1lb1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qy2o1blnrdeg1lb1.json.gz

 23%|██▎       | 544/2404 [11:08<35:38,  1.15s/it]

https://hiring.cafe/job/fs0hpc5h8kth2ej1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fs0hpc5h8kth2ej1.json.gz

 23%|██▎       | 545/2404 [11:09<36:37,  1.18s/it]

https://hiring.cafe/job/gi2m2kpxxx89n9q3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gi2m2kpxxx89n9q3.json.gz

 23%|██▎       | 546/2404 [11:10<36:55,  1.19s/it]

https://hiring.cafe/job/cysbfklnsassqt38
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cysbfklnsassqt38.json.gz

 23%|██▎       | 547/2404 [11:11<36:54,  1.19s/it]

https://hiring.cafe/job/8tw6vl64vllq5wts
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8tw6vl64vllq5wts.json.gz

 23%|██▎       | 548/2404 [11:13<38:48,  1.25s/it]

https://hiring.cafe/job/nxn68dvz1beb9nvt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nxn68dvz1beb9nvt.json.gz

 23%|██▎       | 549/2404 [11:14<38:16,  1.24s/it]

https://hiring.cafe/job/7sko9vl3164ronms
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7sko9vl3164ronms.json.gz

 23%|██▎       | 550/2404 [11:15<38:45,  1.25s/it]

https://hiring.cafe/job/a7w025s2osl4vd1p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a7w025s2osl4vd1p.json.gz

 23%|██▎       | 551/2404 [11:17<38:28,  1.25s/it]

https://hiring.cafe/job/df7exae36xe46ffv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\df7exae36xe46ffv.json.gz

 23%|██▎       | 552/2404 [11:17<35:35,  1.15s/it]

https://hiring.cafe/job/bpeu9pcd7puda28g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bpeu9pcd7puda28g.json.gz

 23%|██▎       | 553/2404 [11:19<36:46,  1.19s/it]

https://hiring.cafe/job/l2a99d5i26avkvox
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l2a99d5i26avkvox.json.gz

 23%|██▎       | 554/2404 [11:21<42:26,  1.38s/it]

https://hiring.cafe/job/8no77z1q6iwg4rj5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8no77z1q6iwg4rj5.json.gz

 23%|██▎       | 555/2404 [11:22<40:55,  1.33s/it]

https://hiring.cafe/job/xdty6pbrme3o2ydf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xdty6pbrme3o2ydf.json.gz

 23%|██▎       | 556/2404 [11:23<39:08,  1.27s/it]

https://hiring.cafe/job/y3avej2er6go0kny
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y3avej2er6go0kny.json.gz

 23%|██▎       | 557/2404 [11:24<38:41,  1.26s/it]

https://hiring.cafe/job/8y9799r1sxw10o2j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8y9799r1sxw10o2j.json.gz

 23%|██▎       | 558/2404 [11:25<39:09,  1.27s/it]

https://hiring.cafe/job/p1bbd4j124pr0i72
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p1bbd4j124pr0i72.json.gz

 23%|██▎       | 559/2404 [11:26<36:39,  1.19s/it]

https://hiring.cafe/job/r4schvbmqwcd2xvz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r4schvbmqwcd2xvz.json.gz

 23%|██▎       | 560/2404 [11:28<35:29,  1.16s/it]

https://hiring.cafe/job/hn3oxqqiejl7uuml
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hn3oxqqiejl7uuml.json.gz

 23%|██▎       | 561/2404 [11:29<35:37,  1.16s/it]

https://hiring.cafe/job/aplucmkrw1tjl5i6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\aplucmkrw1tjl5i6.json.gz

 23%|██▎       | 562/2404 [11:30<37:11,  1.21s/it]

https://hiring.cafe/job/8v89l0cdnukgl2y5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8v89l0cdnukgl2y5.json.gz

 23%|██▎       | 563/2404 [11:32<40:19,  1.31s/it]

https://hiring.cafe/job/mbonq45nf043hsh2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mbonq45nf043hsh2.json.gz

 23%|██▎       | 564/2404 [11:33<38:11,  1.25s/it]

https://hiring.cafe/job/zh6jnxbkg911keuy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zh6jnxbkg911keuy.json.gz

 24%|██▎       | 565/2404 [11:34<36:50,  1.20s/it]

https://hiring.cafe/job/saddu14tefu0ye0w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\saddu14tefu0ye0w.json.gz

 24%|██▎       | 566/2404 [11:35<34:29,  1.13s/it]

https://hiring.cafe/job/1rdwkdtr863tg1h7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1rdwkdtr863tg1h7.json.gz

 24%|██▎       | 567/2404 [11:36<34:53,  1.14s/it]

https://hiring.cafe/job/vforagzsob908q3t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vforagzsob908q3t.json.gz

 24%|██▎       | 568/2404 [11:37<34:34,  1.13s/it]

https://hiring.cafe/job/ekgr9vfbd8p7ghug
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ekgr9vfbd8p7ghug.json.gz

 24%|██▎       | 569/2404 [11:38<33:01,  1.08s/it]

https://hiring.cafe/job/nqzfufu7mhgfol45
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nqzfufu7mhgfol45.json.gz

 24%|██▎       | 570/2404 [11:39<34:37,  1.13s/it]

https://hiring.cafe/job/xtsqhskmkvfl5hr0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xtsqhskmkvfl5hr0.json.gz

 24%|██▍       | 571/2404 [11:40<34:04,  1.12s/it]

https://hiring.cafe/job/uxgv5bol86gxlvq9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uxgv5bol86gxlvq9.json.gz

 24%|██▍       | 572/2404 [11:42<35:20,  1.16s/it]

https://hiring.cafe/job/ndklxzwk03nb4sbm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ndklxzwk03nb4sbm.json.gz

 24%|██▍       | 573/2404 [11:42<32:53,  1.08s/it]

https://hiring.cafe/job/09lbxtp8rotmi03j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\09lbxtp8rotmi03j.json.gz

 24%|██▍       | 574/2404 [11:44<32:54,  1.08s/it]

https://hiring.cafe/job/s167bhqfxczjcx22
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s167bhqfxczjcx22.json.gz

 24%|██▍       | 575/2404 [11:45<35:10,  1.15s/it]

https://hiring.cafe/job/mknpl19hpczkvrzv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mknpl19hpczkvrzv.json.gz

 24%|██▍       | 576/2404 [11:46<37:04,  1.22s/it]

https://hiring.cafe/job/7723un58bqxwtljx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7723un58bqxwtljx.json.gz

 24%|██▍       | 577/2404 [11:47<36:35,  1.20s/it]

https://hiring.cafe/job/71qn4yqpv5tfo14t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\71qn4yqpv5tfo14t.json.gz

 24%|██▍       | 578/2404 [11:49<36:22,  1.20s/it]

https://hiring.cafe/job/3e1j46lw7tmjxbdz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3e1j46lw7tmjxbdz.json.gz

 24%|██▍       | 579/2404 [11:50<38:37,  1.27s/it]

https://hiring.cafe/job/nxj3uu6qut0cgqbz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nxj3uu6qut0cgqbz.json.gz

 24%|██▍       | 580/2404 [11:51<36:59,  1.22s/it]

https://hiring.cafe/job/fqwna7zkbljrooe7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fqwna7zkbljrooe7.json.gz

 24%|██▍       | 581/2404 [11:52<35:55,  1.18s/it]

https://hiring.cafe/job/9v2313xm2unayhrc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9v2313xm2unayhrc.json.gz

 24%|██▍       | 582/2404 [11:53<36:32,  1.20s/it]

https://hiring.cafe/job/i8i5kzrhih3x9ksa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i8i5kzrhih3x9ksa.json.gz

 24%|██▍       | 583/2404 [11:55<38:16,  1.26s/it]

https://hiring.cafe/job/u88bkpt1kldsupfe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u88bkpt1kldsupfe.json.gz

 24%|██▍       | 584/2404 [11:56<36:32,  1.20s/it]

https://hiring.cafe/job/w0ohelji0duskiam
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w0ohelji0duskiam.json.gz

 24%|██▍       | 585/2404 [11:57<36:30,  1.20s/it]

https://hiring.cafe/job/nesoc1pwx8qh077t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nesoc1pwx8qh077t.json.gz

 24%|██▍       | 586/2404 [11:58<34:25,  1.14s/it]

https://hiring.cafe/job/3j1h1rquxboy20ub
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3j1h1rquxboy20ub.json.gz

 24%|██▍       | 587/2404 [11:59<33:52,  1.12s/it]

https://hiring.cafe/job/hnb9fl4kzfbbcgz9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hnb9fl4kzfbbcgz9.json.gz

 24%|██▍       | 588/2404 [12:00<35:03,  1.16s/it]

https://hiring.cafe/job/oohgvvepy4des0ym
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oohgvvepy4des0ym.json.gz

 25%|██▍       | 589/2404 [12:02<34:46,  1.15s/it]

https://hiring.cafe/job/1y0zmgsirhzs4oji
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1y0zmgsirhzs4oji.json.gz

 25%|██▍       | 590/2404 [12:03<38:58,  1.29s/it]

https://hiring.cafe/job/ksay02i6eys59pek
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ksay02i6eys59pek.json.gz

 25%|██▍       | 591/2404 [12:04<35:53,  1.19s/it]

https://hiring.cafe/job/7nwylo9zsy9puc5h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7nwylo9zsy9puc5h.json.gz

 25%|██▍       | 592/2404 [12:05<35:36,  1.18s/it]

https://hiring.cafe/job/3yg6epl4gbpef5so
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3yg6epl4gbpef5so.json.gz

 25%|██▍       | 593/2404 [12:06<35:18,  1.17s/it]

https://hiring.cafe/job/9k6xiabdeud99lwz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9k6xiabdeud99lwz.json.gz

 25%|██▍       | 594/2404 [12:08<36:40,  1.22s/it]

https://hiring.cafe/job/i6btogyw0f6eq6i3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i6btogyw0f6eq6i3.json.gz

 25%|██▍       | 595/2404 [12:09<35:09,  1.17s/it]

https://hiring.cafe/job/pa260f24usx5ynnj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pa260f24usx5ynnj.json.gz

 25%|██▍       | 596/2404 [12:10<34:43,  1.15s/it]

https://hiring.cafe/job/6tou9m5l5r76ha5r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6tou9m5l5r76ha5r.json.gz

 25%|██▍       | 597/2404 [12:11<34:23,  1.14s/it]

https://hiring.cafe/job/v36ybpk2f5n0frgd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v36ybpk2f5n0frgd.json.gz

 25%|██▍       | 598/2404 [12:12<32:15,  1.07s/it]

https://hiring.cafe/job/xzad4w01jwybxyj2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xzad4w01jwybxyj2.json.gz

 25%|██▍       | 599/2404 [12:13<31:13,  1.04s/it]

https://hiring.cafe/job/5xal3u9vjnnetn7z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5xal3u9vjnnetn7z.json.gz

 25%|██▍       | 600/2404 [12:14<31:47,  1.06s/it]

https://hiring.cafe/job/o0ewicoeswzi265s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o0ewicoeswzi265s.json.gz

 25%|██▌       | 601/2404 [12:15<32:13,  1.07s/it]

https://hiring.cafe/job/i10yuo5inl6n22hz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i10yuo5inl6n22hz.json.gz

 25%|██▌       | 602/2404 [12:16<33:06,  1.10s/it]

https://hiring.cafe/job/9sd0ayi5ih9yk7eg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9sd0ayi5ih9yk7eg.json.gz

 25%|██▌       | 603/2404 [12:18<34:42,  1.16s/it]

https://hiring.cafe/job/vymho2qu18yme05x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vymho2qu18yme05x.json.gz

 25%|██▌       | 604/2404 [12:19<35:54,  1.20s/it]

https://hiring.cafe/job/nqjj9xwrwm2rw7ux
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nqjj9xwrwm2rw7ux.json.gz

 25%|██▌       | 605/2404 [12:20<33:42,  1.12s/it]

https://hiring.cafe/job/48zc3lg52dj3f1br
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\48zc3lg52dj3f1br.json.gz

 25%|██▌       | 606/2404 [12:21<32:44,  1.09s/it]

https://hiring.cafe/job/dzpqntqeqf6byjyf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dzpqntqeqf6byjyf.json.gz

 25%|██▌       | 607/2404 [12:22<32:04,  1.07s/it]

https://hiring.cafe/job/hupie7mxuwksotgz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hupie7mxuwksotgz.json.gz

 25%|██▌       | 608/2404 [12:23<31:44,  1.06s/it]

https://hiring.cafe/job/dyib9n4dd8h8ne59
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dyib9n4dd8h8ne59.json.gz

 25%|██▌       | 609/2404 [12:24<31:59,  1.07s/it]

https://hiring.cafe/job/5325llnb7ktt6jtl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5325llnb7ktt6jtl.json.gz

 25%|██▌       | 610/2404 [12:25<32:56,  1.10s/it]

https://hiring.cafe/job/89hdjj1c9ud6ub6c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\89hdjj1c9ud6ub6c.json.gz

 25%|██▌       | 611/2404 [12:26<32:58,  1.10s/it]

https://hiring.cafe/job/fl1v0x2693a6zw8c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fl1v0x2693a6zw8c.json.gz

 25%|██▌       | 612/2404 [12:28<35:18,  1.18s/it]

https://hiring.cafe/job/5fwuye8co54fze12
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5fwuye8co54fze12.json.gz

 25%|██▌       | 613/2404 [12:29<34:09,  1.14s/it]

https://hiring.cafe/job/wxcntea3ntjsoujb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wxcntea3ntjsoujb.json.gz

 26%|██▌       | 614/2404 [12:30<35:22,  1.19s/it]

https://hiring.cafe/job/v39u2na8848tkcmn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v39u2na8848tkcmn.json.gz

 26%|██▌       | 615/2404 [12:31<37:12,  1.25s/it]

https://hiring.cafe/job/xnew5t1zzaz7idfr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xnew5t1zzaz7idfr.json.gz

 26%|██▌       | 616/2404 [12:33<38:04,  1.28s/it]

https://hiring.cafe/job/jvvn5b1iebyiem4v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jvvn5b1iebyiem4v.json.gz

 26%|██▌       | 617/2404 [12:34<37:24,  1.26s/it]

https://hiring.cafe/job/d1hgsm9xjjpxg906
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d1hgsm9xjjpxg906.json.gz

 26%|██▌       | 618/2404 [12:35<37:31,  1.26s/it]

https://hiring.cafe/job/0ljk3wqkl4xmt5ck
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ljk3wqkl4xmt5ck.json.gz

 26%|██▌       | 619/2404 [12:37<37:56,  1.28s/it]

https://hiring.cafe/job/1n88adbxm3xepoye
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1n88adbxm3xepoye.json.gz

 26%|██▌       | 620/2404 [12:38<36:49,  1.24s/it]

https://hiring.cafe/job/orovv65sitlk9iap
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\orovv65sitlk9iap.json.gz

 26%|██▌       | 621/2404 [12:39<37:24,  1.26s/it]

https://hiring.cafe/job/itq7e0swi1he9guc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\itq7e0swi1he9guc.json.gz

 26%|██▌       | 622/2404 [12:40<39:32,  1.33s/it]

https://hiring.cafe/job/h96wrq42tf5tlswx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h96wrq42tf5tlswx.json.gz

 26%|██▌       | 623/2404 [12:42<38:36,  1.30s/it]

https://hiring.cafe/job/gezmoa7mxw35khya
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gezmoa7mxw35khya.json.gz

 26%|██▌       | 624/2404 [12:43<39:20,  1.33s/it]

https://hiring.cafe/job/sgvt6nj3u7u6m08c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sgvt6nj3u7u6m08c.json.gz

 26%|██▌       | 625/2404 [12:44<38:50,  1.31s/it]

https://hiring.cafe/job/1r6i1lubbdb4klz2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1r6i1lubbdb4klz2.json.gz

 26%|██▌       | 626/2404 [12:45<35:56,  1.21s/it]

https://hiring.cafe/job/xwda9ci8v1v0i11t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xwda9ci8v1v0i11t.json.gz

 26%|██▌       | 627/2404 [12:46<34:36,  1.17s/it]

https://hiring.cafe/job/kh80nnw5ulurbpv7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kh80nnw5ulurbpv7.json.gz

 26%|██▌       | 628/2404 [12:48<35:34,  1.20s/it]

https://hiring.cafe/job/7dmc3d7gnqskd5wu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7dmc3d7gnqskd5wu.json.gz

 26%|██▌       | 629/2404 [12:49<36:50,  1.25s/it]

https://hiring.cafe/job/cadnmmxacpy4vtxw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cadnmmxacpy4vtxw.json.gz

 26%|██▌       | 630/2404 [12:50<37:03,  1.25s/it]

https://hiring.cafe/job/rcf6oghvx6ef8np9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rcf6oghvx6ef8np9.json.gz

 26%|██▌       | 631/2404 [12:51<35:05,  1.19s/it]

https://hiring.cafe/job/dm7a5v3lkykw8u6k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dm7a5v3lkykw8u6k.json.gz

 26%|██▋       | 632/2404 [12:52<34:19,  1.16s/it]

https://hiring.cafe/job/fk7l7v4qvx1t2bsq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fk7l7v4qvx1t2bsq.json.gz

 26%|██▋       | 633/2404 [12:54<34:40,  1.17s/it]

https://hiring.cafe/job/o0yrnho43udj047h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o0yrnho43udj047h.json.gz

 26%|██▋       | 634/2404 [12:55<34:11,  1.16s/it]

https://hiring.cafe/job/9pimf6kpmlze0lje
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9pimf6kpmlze0lje.json.gz

 26%|██▋       | 635/2404 [12:56<35:01,  1.19s/it]

https://hiring.cafe/job/teozugkumc515yks
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\teozugkumc515yks.json.gz

 26%|██▋       | 636/2404 [12:57<33:08,  1.12s/it]

https://hiring.cafe/job/qcoisb0q8wxh6idu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qcoisb0q8wxh6idu.json.gz

 26%|██▋       | 637/2404 [12:58<33:02,  1.12s/it]

https://hiring.cafe/job/ov5ls82dodfdwazf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ov5ls82dodfdwazf.json.gz

 27%|██▋       | 638/2404 [12:59<33:26,  1.14s/it]

https://hiring.cafe/job/qt4xhww4dl5rxr1y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qt4xhww4dl5rxr1y.json.gz

 27%|██▋       | 639/2404 [13:00<33:09,  1.13s/it]

https://hiring.cafe/job/734uw9kwmr55vjk8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\734uw9kwmr55vjk8.json.gz

 27%|██▋       | 640/2404 [13:01<32:13,  1.10s/it]

https://hiring.cafe/job/grb6je4aosabff8q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\grb6je4aosabff8q.json.gz

 27%|██▋       | 641/2404 [13:02<30:57,  1.05s/it]

https://hiring.cafe/job/ov3hvtdmu15z7gtl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ov3hvtdmu15z7gtl.json.gz

 27%|██▋       | 642/2404 [13:04<33:15,  1.13s/it]

https://hiring.cafe/job/nhh35f1gvjw095p7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nhh35f1gvjw095p7.json.gz

 27%|██▋       | 643/2404 [13:05<34:24,  1.17s/it]

https://hiring.cafe/job/ng4qjvemvp2wl27o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ng4qjvemvp2wl27o.json.gz

 27%|██▋       | 644/2404 [13:06<34:22,  1.17s/it]

https://hiring.cafe/job/ka8y6euc8xx6a18t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ka8y6euc8xx6a18t.json.gz

 27%|██▋       | 645/2404 [13:07<35:09,  1.20s/it]

https://hiring.cafe/job/52wf76rljbbbbnzw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\52wf76rljbbbbnzw.json.gz

 27%|██▋       | 646/2404 [13:09<36:14,  1.24s/it]

https://hiring.cafe/job/nqspo793pjyz0jcz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nqspo793pjyz0jcz.json.gz

 27%|██▋       | 647/2404 [13:10<33:54,  1.16s/it]

https://hiring.cafe/job/pctezrrpyobi8nj1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pctezrrpyobi8nj1.json.gz

 27%|██▋       | 648/2404 [13:11<33:45,  1.15s/it]

https://hiring.cafe/job/3faurmhz3w5uetu5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3faurmhz3w5uetu5.json.gz

 27%|██▋       | 649/2404 [13:12<34:36,  1.18s/it]

https://hiring.cafe/job/9pfa8wfu0qr8swdl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9pfa8wfu0qr8swdl.json.gz

 27%|██▋       | 650/2404 [13:13<33:47,  1.16s/it]

https://hiring.cafe/job/c9x7ialg4qvheimd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c9x7ialg4qvheimd.json.gz

 27%|██▋       | 651/2404 [13:14<35:09,  1.20s/it]

https://hiring.cafe/job/t28wf9d048afqvl2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t28wf9d048afqvl2.json.gz

 27%|██▋       | 652/2404 [13:16<34:46,  1.19s/it]

https://hiring.cafe/job/tpe9xakru5asma0o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tpe9xakru5asma0o.json.gz

 27%|██▋       | 653/2404 [13:17<34:37,  1.19s/it]

https://hiring.cafe/job/31ycw62rygl8ie9w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\31ycw62rygl8ie9w.json.gz

 27%|██▋       | 654/2404 [13:18<33:58,  1.16s/it]

https://hiring.cafe/job/sn7lulqot8rvfp11
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sn7lulqot8rvfp11.json.gz

 27%|██▋       | 655/2404 [13:19<34:18,  1.18s/it]

https://hiring.cafe/job/a75epzjxzke8g2mm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a75epzjxzke8g2mm.json.gz

 27%|██▋       | 656/2404 [13:20<34:13,  1.17s/it]

https://hiring.cafe/job/bf71gck4wgt0m2y8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bf71gck4wgt0m2y8.json.gz

 27%|██▋       | 657/2404 [13:22<35:02,  1.20s/it]

https://hiring.cafe/job/dhhhy70rmeo938e9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dhhhy70rmeo938e9.json.gz

 27%|██▋       | 658/2404 [13:23<36:14,  1.25s/it]

https://hiring.cafe/job/wbb6hog5fm0dozja
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wbb6hog5fm0dozja.json.gz

 27%|██▋       | 659/2404 [13:24<39:00,  1.34s/it]

https://hiring.cafe/job/3ggjhwh98jgz5tmq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3ggjhwh98jgz5tmq.json.gz

 27%|██▋       | 660/2404 [13:26<36:21,  1.25s/it]

https://hiring.cafe/job/odnq44bsvqs36u8f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\odnq44bsvqs36u8f.json.gz

 27%|██▋       | 661/2404 [13:27<35:26,  1.22s/it]

https://hiring.cafe/job/u4g1ld4jopb3v9n0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u4g1ld4jopb3v9n0.json.gz

 28%|██▊       | 662/2404 [13:28<35:08,  1.21s/it]

https://hiring.cafe/job/1iikoq0hqjebp5bm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1iikoq0hqjebp5bm.json.gz

 28%|██▊       | 663/2404 [13:29<33:49,  1.17s/it]

https://hiring.cafe/job/mbxf6yzj95hvrp5d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mbxf6yzj95hvrp5d.json.gz

 28%|██▊       | 664/2404 [13:30<36:51,  1.27s/it]

https://hiring.cafe/job/su2p7doh35u1eiwc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\su2p7doh35u1eiwc.json.gz

 28%|██▊       | 665/2404 [13:31<33:20,  1.15s/it]

https://hiring.cafe/job/a7hj9kergsw0ah8k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a7hj9kergsw0ah8k.json.gz

 28%|██▊       | 666/2404 [13:33<36:02,  1.24s/it]

https://hiring.cafe/job/uh0fk62ky3qpiwdy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uh0fk62ky3qpiwdy.json.gz

 28%|██▊       | 667/2404 [13:34<34:45,  1.20s/it]

https://hiring.cafe/job/yyz9q3oy90n67izk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yyz9q3oy90n67izk.json.gz

 28%|██▊       | 668/2404 [13:35<33:10,  1.15s/it]

https://hiring.cafe/job/7tulqbbi3keu03ur
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7tulqbbi3keu03ur.json.gz

 28%|██▊       | 669/2404 [13:36<33:00,  1.14s/it]

https://hiring.cafe/job/fa2ew86ke4nv343a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fa2ew86ke4nv343a.json.gz

 28%|██▊       | 670/2404 [13:37<32:32,  1.13s/it]

https://hiring.cafe/job/l77307fdqeqy3bwm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l77307fdqeqy3bwm.json.gz

 28%|██▊       | 671/2404 [13:39<35:10,  1.22s/it]

https://hiring.cafe/job/ujw5bsr5w8c205w5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ujw5bsr5w8c205w5.json.gz

 28%|██▊       | 672/2404 [13:40<35:01,  1.21s/it]

https://hiring.cafe/job/vb2ndo7hblu7xn1m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vb2ndo7hblu7xn1m.json.gz

 28%|██▊       | 673/2404 [13:41<34:51,  1.21s/it]

https://hiring.cafe/job/pkuhqli63vh3q0w4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pkuhqli63vh3q0w4.json.gz

 28%|██▊       | 674/2404 [13:42<33:48,  1.17s/it]

https://hiring.cafe/job/73uv34lklnenrc2i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\73uv34lklnenrc2i.json.gz

 28%|██▊       | 675/2404 [13:43<33:10,  1.15s/it]

https://hiring.cafe/job/5npmuozg2i1ec12o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5npmuozg2i1ec12o.json.gz

 28%|██▊       | 676/2404 [13:44<33:24,  1.16s/it]

https://hiring.cafe/job/n1ec4he81x8rr9l0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n1ec4he81x8rr9l0.json.gz

 28%|██▊       | 677/2404 [13:45<31:43,  1.10s/it]

https://hiring.cafe/job/efykzhmzqfer0h3t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\efykzhmzqfer0h3t.json.gz

 28%|██▊       | 678/2404 [13:47<35:50,  1.25s/it]

https://hiring.cafe/job/ortqfsp77tgmb044
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ortqfsp77tgmb044.json.gz

 28%|██▊       | 679/2404 [13:48<37:34,  1.31s/it]

https://hiring.cafe/job/upu6k3jhfzuwqdiy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\upu6k3jhfzuwqdiy.json.gz

 28%|██▊       | 680/2404 [13:50<37:29,  1.30s/it]

https://hiring.cafe/job/l8v3aseykvg7chbq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l8v3aseykvg7chbq.json.gz

 28%|██▊       | 681/2404 [13:51<39:42,  1.38s/it]

https://hiring.cafe/job/vpr7s2ezb954a2x9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vpr7s2ezb954a2x9.json.gz

 28%|██▊       | 682/2404 [13:52<36:14,  1.26s/it]

https://hiring.cafe/job/kydwjal66mw9b79q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kydwjal66mw9b79q.json.gz

 28%|██▊       | 683/2404 [13:53<35:23,  1.23s/it]

https://hiring.cafe/job/3bzg7kbz018mrg2b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3bzg7kbz018mrg2b.json.gz

 28%|██▊       | 684/2404 [13:55<38:27,  1.34s/it]

https://hiring.cafe/job/v0ton6ol064c6aw3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v0ton6ol064c6aw3.json.gz

 28%|██▊       | 685/2404 [13:56<38:50,  1.36s/it]

https://hiring.cafe/job/o0gw3no1vkq7hw7s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o0gw3no1vkq7hw7s.json.gz

 29%|██▊       | 686/2404 [13:58<37:54,  1.32s/it]

https://hiring.cafe/job/zv68ue0dzy47lqpy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zv68ue0dzy47lqpy.json.gz

 29%|██▊       | 687/2404 [13:59<37:27,  1.31s/it]

https://hiring.cafe/job/24gcs0ymtc5qttj2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\24gcs0ymtc5qttj2.json.gz

 29%|██▊       | 688/2404 [14:00<38:30,  1.35s/it]

https://hiring.cafe/job/yx0bdztifqu9n3os
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yx0bdztifqu9n3os.json.gz

 29%|██▊       | 689/2404 [14:02<38:14,  1.34s/it]

https://hiring.cafe/job/0zo18m19vueb0kgo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0zo18m19vueb0kgo.json.gz

 29%|██▊       | 690/2404 [14:03<36:09,  1.27s/it]

https://hiring.cafe/job/mlfpjuhhtsku731a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mlfpjuhhtsku731a.json.gz

 29%|██▊       | 691/2404 [14:04<37:18,  1.31s/it]

https://hiring.cafe/job/xiobpuv403u4tago
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xiobpuv403u4tago.json.gz

 29%|██▉       | 692/2404 [14:05<36:21,  1.27s/it]

https://hiring.cafe/job/8jg1gq6czw05dzt9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8jg1gq6czw05dzt9.json.gz

 29%|██▉       | 693/2404 [14:07<37:53,  1.33s/it]

https://hiring.cafe/job/uux36c2yjxspduk1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uux36c2yjxspduk1.json.gz

 29%|██▉       | 694/2404 [14:08<34:47,  1.22s/it]

https://hiring.cafe/job/acfvdjhpfzdu1qi6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\acfvdjhpfzdu1qi6.json.gz

 29%|██▉       | 695/2404 [14:09<35:28,  1.25s/it]

https://hiring.cafe/job/87wp9exszgfgemnz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\87wp9exszgfgemnz.json.gz

 29%|██▉       | 696/2404 [14:11<38:22,  1.35s/it]

https://hiring.cafe/job/o0vvi84p3rmdravg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o0vvi84p3rmdravg.json.gz

 29%|██▉       | 697/2404 [14:12<35:59,  1.27s/it]

https://hiring.cafe/job/y4qx6rjgnihtrxuu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y4qx6rjgnihtrxuu.json.gz

 29%|██▉       | 698/2404 [14:13<34:54,  1.23s/it]

https://hiring.cafe/job/kusci3vxggymg81n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kusci3vxggymg81n.json.gz

 29%|██▉       | 699/2404 [14:14<34:51,  1.23s/it]

https://hiring.cafe/job/bkobzlqkuc4krfzj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bkobzlqkuc4krfzj.json.gz

 29%|██▉       | 700/2404 [14:15<34:52,  1.23s/it]

https://hiring.cafe/job/qglhexsth3b1jht6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qglhexsth3b1jht6.json.gz

 29%|██▉       | 701/2404 [14:17<34:59,  1.23s/it]

https://hiring.cafe/job/e0mzqx99p23dd0ev
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e0mzqx99p23dd0ev.json.gz

 29%|██▉       | 702/2404 [14:18<36:13,  1.28s/it]

https://hiring.cafe/job/fqd91ffswl5xttw0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fqd91ffswl5xttw0.json.gz

 29%|██▉       | 703/2404 [14:19<33:27,  1.18s/it]

https://hiring.cafe/job/xzwhhu2h04fwpgpc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xzwhhu2h04fwpgpc.json.gz

 29%|██▉       | 704/2404 [14:20<33:43,  1.19s/it]

https://hiring.cafe/job/e7dzk9xdegfr2ixr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e7dzk9xdegfr2ixr.json.gz

 29%|██▉       | 705/2404 [14:21<34:38,  1.22s/it]

https://hiring.cafe/job/v049pygo3p7xvthu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v049pygo3p7xvthu.json.gz

 29%|██▉       | 706/2404 [14:23<34:43,  1.23s/it]

https://hiring.cafe/job/p260baflyyw5qcea
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p260baflyyw5qcea.json.gz

 29%|██▉       | 707/2404 [14:24<38:37,  1.37s/it]

https://hiring.cafe/job/m17krexg79snt9o6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m17krexg79snt9o6.json.gz

 29%|██▉       | 708/2404 [14:25<37:08,  1.31s/it]

https://hiring.cafe/job/6un6yu7rkoud0fkm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6un6yu7rkoud0fkm.json.gz

 29%|██▉       | 709/2404 [14:27<36:08,  1.28s/it]

https://hiring.cafe/job/96hega35602lvs6z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\96hega35602lvs6z.json.gz

 30%|██▉       | 710/2404 [14:28<33:28,  1.19s/it]

https://hiring.cafe/job/dfp4d1vud8ec48ax
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dfp4d1vud8ec48ax.json.gz

 30%|██▉       | 711/2404 [14:29<34:46,  1.23s/it]

https://hiring.cafe/job/q4jvjpja89ol7yha
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q4jvjpja89ol7yha.json.gz

 30%|██▉       | 712/2404 [14:30<34:56,  1.24s/it]

https://hiring.cafe/job/pxzgktvkbwm80ub8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pxzgktvkbwm80ub8.json.gz

 30%|██▉       | 713/2404 [14:32<36:52,  1.31s/it]

https://hiring.cafe/job/1a2yiq896r8ja47p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1a2yiq896r8ja47p.json.gz

 30%|██▉       | 714/2404 [14:33<37:24,  1.33s/it]

https://hiring.cafe/job/3o5wsmxyzwwoxh30
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3o5wsmxyzwwoxh30.json.gz

 30%|██▉       | 715/2404 [14:35<38:16,  1.36s/it]

https://hiring.cafe/job/lfst4ld44l7630ja
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lfst4ld44l7630ja.json.gz

 30%|██▉       | 716/2404 [14:36<37:48,  1.34s/it]

https://hiring.cafe/job/apm178pull44egdl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\apm178pull44egdl.json.gz

 30%|██▉       | 717/2404 [14:37<37:56,  1.35s/it]

https://hiring.cafe/job/7d2noo03gza1biyb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7d2noo03gza1biyb.json.gz

 30%|██▉       | 718/2404 [14:39<37:41,  1.34s/it]

https://hiring.cafe/job/hxy0r4skufd39c3j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hxy0r4skufd39c3j.json.gz

 30%|██▉       | 719/2404 [14:40<36:06,  1.29s/it]

https://hiring.cafe/job/0lzx7w50tuumqzjb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0lzx7w50tuumqzjb.json.gz

 30%|██▉       | 720/2404 [14:41<32:44,  1.17s/it]

https://hiring.cafe/job/aiws25yydlo88x44
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\aiws25yydlo88x44.json.gz

 30%|██▉       | 721/2404 [14:42<30:59,  1.10s/it]

https://hiring.cafe/job/mv98t14hhum743hy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mv98t14hhum743hy.json.gz

 30%|███       | 722/2404 [14:43<33:29,  1.19s/it]

https://hiring.cafe/job/20ac117rpe3c3vmk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\20ac117rpe3c3vmk.json.gz

 30%|███       | 723/2404 [14:44<33:44,  1.20s/it]

https://hiring.cafe/job/hj5hmwadusf72xz9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hj5hmwadusf72xz9.json.gz

 30%|███       | 724/2404 [14:45<34:07,  1.22s/it]

https://hiring.cafe/job/cdbtpsm0ryh1nsza
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cdbtpsm0ryh1nsza.json.gz

 30%|███       | 725/2404 [14:47<35:36,  1.27s/it]

https://hiring.cafe/job/tr73amkkjura6d7l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tr73amkkjura6d7l.json.gz

 30%|███       | 726/2404 [14:48<36:10,  1.29s/it]

https://hiring.cafe/job/z894nnu0w00vywt6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z894nnu0w00vywt6.json.gz

 30%|███       | 727/2404 [14:49<36:40,  1.31s/it]

https://hiring.cafe/job/ji3h31plyknx4vy8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ji3h31plyknx4vy8.json.gz

 30%|███       | 728/2404 [14:51<35:23,  1.27s/it]

https://hiring.cafe/job/388qvyzxc50712rw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\388qvyzxc50712rw.json.gz

 30%|███       | 729/2404 [14:52<34:26,  1.23s/it]

https://hiring.cafe/job/s0fgzbkotzzvezke
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s0fgzbkotzzvezke.json.gz

 30%|███       | 730/2404 [14:53<36:00,  1.29s/it]

https://hiring.cafe/job/sivnmpdfdqg7nazp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sivnmpdfdqg7nazp.json.gz

 30%|███       | 731/2404 [14:55<36:11,  1.30s/it]

https://hiring.cafe/job/jcny1bdvqjksc9si
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jcny1bdvqjksc9si.json.gz

 30%|███       | 732/2404 [14:56<35:03,  1.26s/it]

https://hiring.cafe/job/g69actoejlxrghwb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g69actoejlxrghwb.json.gz

 30%|███       | 733/2404 [14:57<34:51,  1.25s/it]

https://hiring.cafe/job/fn3pmsnwfnjcur2z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fn3pmsnwfnjcur2z.json.gz

 31%|███       | 734/2404 [14:58<35:43,  1.28s/it]

https://hiring.cafe/job/7a5d5cwyhbib0ipv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7a5d5cwyhbib0ipv.json.gz

 31%|███       | 735/2404 [14:59<34:06,  1.23s/it]

https://hiring.cafe/job/047dcir1uxb7kvo9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\047dcir1uxb7kvo9.json.gz

 31%|███       | 736/2404 [15:01<33:04,  1.19s/it]

https://hiring.cafe/job/y0fpzvj80sgmbrhb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y0fpzvj80sgmbrhb.json.gz

 31%|███       | 737/2404 [15:02<33:01,  1.19s/it]

https://hiring.cafe/job/qyxh5rifhj63sbmm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qyxh5rifhj63sbmm.json.gz

 31%|███       | 738/2404 [15:03<32:56,  1.19s/it]

https://hiring.cafe/job/13vvndvtu9yt0gui
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\13vvndvtu9yt0gui.json.gz

 31%|███       | 739/2404 [15:04<31:01,  1.12s/it]

https://hiring.cafe/job/fvmo0f5ykkxp9myx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fvmo0f5ykkxp9myx.json.gz

 31%|███       | 740/2404 [15:05<30:01,  1.08s/it]

https://hiring.cafe/job/qt0elc63rmdhdl49
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qt0elc63rmdhdl49.json.gz

 31%|███       | 741/2404 [15:06<33:03,  1.19s/it]

https://hiring.cafe/job/1w8wzkt0ocknib5s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1w8wzkt0ocknib5s.json.gz

 31%|███       | 742/2404 [15:08<35:03,  1.27s/it]

https://hiring.cafe/job/acy02x04nbovbbtt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\acy02x04nbovbbtt.json.gz

 31%|███       | 743/2404 [15:09<32:16,  1.17s/it]

https://hiring.cafe/job/6qfhu55wjzcp0h23
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6qfhu55wjzcp0h23.json.gz

 31%|███       | 744/2404 [15:10<30:26,  1.10s/it]

https://hiring.cafe/job/mdpcmukgs7tzu5ym
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mdpcmukgs7tzu5ym.json.gz

 31%|███       | 745/2404 [15:11<33:03,  1.20s/it]

https://hiring.cafe/job/xxyaw58o9zggyuqu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xxyaw58o9zggyuqu.json.gz

 31%|███       | 746/2404 [15:13<35:58,  1.30s/it]

https://hiring.cafe/job/08qtkptdqkw3rgmd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\08qtkptdqkw3rgmd.json.gz

 31%|███       | 747/2404 [15:14<34:51,  1.26s/it]

https://hiring.cafe/job/215ud1bxenf8qy60
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\215ud1bxenf8qy60.json.gz

 31%|███       | 748/2404 [15:15<31:47,  1.15s/it]

https://hiring.cafe/job/2ettrjy1zir1es3r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2ettrjy1zir1es3r.json.gz

 31%|███       | 749/2404 [15:16<31:54,  1.16s/it]

https://hiring.cafe/job/evqssob6337j3qos
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\evqssob6337j3qos.json.gz

 31%|███       | 750/2404 [15:17<31:20,  1.14s/it]

https://hiring.cafe/job/gcocuueieu79yw8v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gcocuueieu79yw8v.json.gz

 31%|███       | 751/2404 [15:18<32:39,  1.19s/it]

https://hiring.cafe/job/lt9r5c3n8rk7q2zx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lt9r5c3n8rk7q2zx.json.gz

 31%|███▏      | 752/2404 [15:19<33:15,  1.21s/it]

https://hiring.cafe/job/hhatlsmrf2re8wqp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hhatlsmrf2re8wqp.json.gz

 31%|███▏      | 753/2404 [15:20<31:20,  1.14s/it]

https://hiring.cafe/job/7a4tvalgl83dx0un
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7a4tvalgl83dx0un.json.gz

 31%|███▏      | 754/2404 [15:22<31:50,  1.16s/it]

https://hiring.cafe/job/nasc7h6cf1629w73
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nasc7h6cf1629w73.json.gz

 31%|███▏      | 755/2404 [15:23<30:57,  1.13s/it]

https://hiring.cafe/job/tev6i6cpm1mi58bj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tev6i6cpm1mi58bj.json.gz

 31%|███▏      | 756/2404 [15:24<32:32,  1.18s/it]

https://hiring.cafe/job/mep4g7s35ge4ax04
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mep4g7s35ge4ax04.json.gz

 31%|███▏      | 757/2404 [15:25<34:56,  1.27s/it]

https://hiring.cafe/job/brattvozute34t30
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\brattvozute34t30.json.gz

 32%|███▏      | 758/2404 [15:27<34:15,  1.25s/it]

https://hiring.cafe/job/yilsezezl2z8e2lc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yilsezezl2z8e2lc.json.gz

 32%|███▏      | 759/2404 [15:28<35:21,  1.29s/it]

https://hiring.cafe/job/bhk83amnymf37h6y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bhk83amnymf37h6y.json.gz

 32%|███▏      | 760/2404 [15:29<34:51,  1.27s/it]

https://hiring.cafe/job/8sws8n9mw8fsnfzs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8sws8n9mw8fsnfzs.json.gz

 32%|███▏      | 761/2404 [15:31<36:08,  1.32s/it]

https://hiring.cafe/job/n46sj7okj646olge
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n46sj7okj646olge.json.gz

 32%|███▏      | 762/2404 [15:32<34:41,  1.27s/it]

https://hiring.cafe/job/ggdq5sfquaashzqk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ggdq5sfquaashzqk.json.gz

 32%|███▏      | 763/2404 [15:33<33:11,  1.21s/it]

https://hiring.cafe/job/bwfnmuteyrm8stbn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bwfnmuteyrm8stbn.json.gz

 32%|███▏      | 764/2404 [15:34<32:30,  1.19s/it]

https://hiring.cafe/job/vztjxrcn33i46a2p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vztjxrcn33i46a2p.json.gz

 32%|███▏      | 765/2404 [15:35<32:05,  1.17s/it]

https://hiring.cafe/job/c4wethryt6qzt1j7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c4wethryt6qzt1j7.json.gz

 32%|███▏      | 766/2404 [15:36<32:27,  1.19s/it]

https://hiring.cafe/job/v0rho1qxbm2kj9v6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v0rho1qxbm2kj9v6.json.gz

 32%|███▏      | 767/2404 [15:38<33:16,  1.22s/it]

https://hiring.cafe/job/q5gxaajt7bwq66bs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q5gxaajt7bwq66bs.json.gz

 32%|███▏      | 768/2404 [15:39<35:36,  1.31s/it]

https://hiring.cafe/job/lwix0alvu3rv94uz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lwix0alvu3rv94uz.json.gz

 32%|███▏      | 769/2404 [15:41<35:32,  1.30s/it]

https://hiring.cafe/job/g63xijj6l716xdpp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g63xijj6l716xdpp.json.gz

 32%|███▏      | 770/2404 [15:42<35:02,  1.29s/it]

https://hiring.cafe/job/liaiqk9azswt576h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\liaiqk9azswt576h.json.gz

 32%|███▏      | 771/2404 [15:43<34:51,  1.28s/it]

https://hiring.cafe/job/vxj18e7ygmefh1mr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vxj18e7ygmefh1mr.json.gz

 32%|███▏      | 772/2404 [15:44<33:41,  1.24s/it]

https://hiring.cafe/job/6b5rybjikm30xf9m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6b5rybjikm30xf9m.json.gz

 32%|███▏      | 773/2404 [15:46<35:15,  1.30s/it]

https://hiring.cafe/job/582s233dh1eyvkc3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\582s233dh1eyvkc3.json.gz

 32%|███▏      | 774/2404 [15:47<34:34,  1.27s/it]

https://hiring.cafe/job/fe9hgu5c8uczmjt5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fe9hgu5c8uczmjt5.json.gz

 32%|███▏      | 775/2404 [15:48<35:17,  1.30s/it]

https://hiring.cafe/job/s47qms85whybensk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s47qms85whybensk.json.gz

 32%|███▏      | 776/2404 [15:50<36:04,  1.33s/it]

https://hiring.cafe/job/ucx7b4qk6chaogg9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ucx7b4qk6chaogg9.json.gz

 32%|███▏      | 777/2404 [15:51<34:24,  1.27s/it]

https://hiring.cafe/job/gbdvdea1p2zghk5b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gbdvdea1p2zghk5b.json.gz

 32%|███▏      | 778/2404 [15:52<34:26,  1.27s/it]

https://hiring.cafe/job/lg7tl84n0v4c8p9k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lg7tl84n0v4c8p9k.json.gz

 32%|███▏      | 779/2404 [15:53<33:28,  1.24s/it]

https://hiring.cafe/job/q008wtm3bmq4a7xq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q008wtm3bmq4a7xq.json.gz

 32%|███▏      | 780/2404 [15:54<33:59,  1.26s/it]

https://hiring.cafe/job/1cnvhulmpyuamp8k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1cnvhulmpyuamp8k.json.gz

 32%|███▏      | 781/2404 [15:55<30:59,  1.15s/it]

https://hiring.cafe/job/e832a4xifwlmr04d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e832a4xifwlmr04d.json.gz

 33%|███▎      | 782/2404 [15:56<30:49,  1.14s/it]

https://hiring.cafe/job/as5fft4yr95uqynb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\as5fft4yr95uqynb.json.gz

 33%|███▎      | 783/2404 [15:57<29:05,  1.08s/it]

https://hiring.cafe/job/mofgfd7sxtmdeiqc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mofgfd7sxtmdeiqc.json.gz

 33%|███▎      | 784/2404 [15:59<30:12,  1.12s/it]

https://hiring.cafe/job/i1hlsz3ir5rhtfm7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i1hlsz3ir5rhtfm7.json.gz

 33%|███▎      | 785/2404 [16:00<30:15,  1.12s/it]

https://hiring.cafe/job/x5j13hmpw3wdffn6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x5j13hmpw3wdffn6.json.gz

 33%|███▎      | 786/2404 [16:01<31:00,  1.15s/it]

https://hiring.cafe/job/phg9f5aq5fhs1dsz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\phg9f5aq5fhs1dsz.json.gz

 33%|███▎      | 787/2404 [16:02<31:27,  1.17s/it]

https://hiring.cafe/job/fl876dqg55pmhs6p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fl876dqg55pmhs6p.json.gz

 33%|███▎      | 788/2404 [16:03<31:40,  1.18s/it]

https://hiring.cafe/job/0tsi9iy2f4pln37k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0tsi9iy2f4pln37k.json.gz

 33%|███▎      | 789/2404 [16:05<31:33,  1.17s/it]

https://hiring.cafe/job/gh91h2c4lfqd3b7d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gh91h2c4lfqd3b7d.json.gz

 33%|███▎      | 790/2404 [16:06<31:00,  1.15s/it]

https://hiring.cafe/job/a819jvlm0ford12h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a819jvlm0ford12h.json.gz

 33%|███▎      | 791/2404 [16:07<31:22,  1.17s/it]

https://hiring.cafe/job/fziq0cez2cxc6i7h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fziq0cez2cxc6i7h.json.gz

 33%|███▎      | 792/2404 [16:08<30:13,  1.12s/it]

https://hiring.cafe/job/7xrxqfj4ngrcu7m0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7xrxqfj4ngrcu7m0.json.gz

 33%|███▎      | 793/2404 [16:09<29:10,  1.09s/it]

https://hiring.cafe/job/qnsihenulu9jhrwi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qnsihenulu9jhrwi.json.gz

 33%|███▎      | 794/2404 [16:10<29:02,  1.08s/it]

https://hiring.cafe/job/8wfoz750hx7u9ocg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8wfoz750hx7u9ocg.json.gz

 33%|███▎      | 795/2404 [16:11<29:21,  1.09s/it]

https://hiring.cafe/job/ujsxercexp5393hk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ujsxercexp5393hk.json.gz

 33%|███▎      | 796/2404 [16:12<31:27,  1.17s/it]

https://hiring.cafe/job/cdso65fc82abcs2k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cdso65fc82abcs2k.json.gz

 33%|███▎      | 797/2404 [16:14<32:25,  1.21s/it]

https://hiring.cafe/job/px8jjd491jbm49r4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\px8jjd491jbm49r4.json.gz

 33%|███▎      | 798/2404 [16:15<31:07,  1.16s/it]

https://hiring.cafe/job/g65cobizq6nvcg69
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g65cobizq6nvcg69.json.gz

 33%|███▎      | 799/2404 [16:16<32:15,  1.21s/it]

https://hiring.cafe/job/or1qigywn2bh6kge
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\or1qigywn2bh6kge.json.gz

 33%|███▎      | 800/2404 [16:17<33:48,  1.26s/it]

https://hiring.cafe/job/udoim5ev1ohrt8qf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\udoim5ev1ohrt8qf.json.gz

 33%|███▎      | 801/2404 [16:19<33:43,  1.26s/it]

https://hiring.cafe/job/onpk7jgjvfumz7nr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\onpk7jgjvfumz7nr.json.gz

 33%|███▎      | 802/2404 [16:20<30:52,  1.16s/it]

https://hiring.cafe/job/c28axdnouxpzfw0f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c28axdnouxpzfw0f.json.gz

 33%|███▎      | 803/2404 [16:21<32:22,  1.21s/it]

https://hiring.cafe/job/n99wee2azdbtxafv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n99wee2azdbtxafv.json.gz

 33%|███▎      | 804/2404 [16:23<34:58,  1.31s/it]

https://hiring.cafe/job/3zpw1aqbmb82tfxz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3zpw1aqbmb82tfxz.json.gz

 33%|███▎      | 805/2404 [16:24<35:24,  1.33s/it]

https://hiring.cafe/job/2xztjhutpo56dvg9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2xztjhutpo56dvg9.json.gz

 34%|███▎      | 806/2404 [16:25<33:43,  1.27s/it]

https://hiring.cafe/job/q525b4c1yqb37ofm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q525b4c1yqb37ofm.json.gz

 34%|███▎      | 807/2404 [16:26<32:05,  1.21s/it]

https://hiring.cafe/job/ex1js1ummi1fg154
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ex1js1ummi1fg154.json.gz

 34%|███▎      | 808/2404 [16:27<31:52,  1.20s/it]

https://hiring.cafe/job/ln9dcblqjxza1q7e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ln9dcblqjxza1q7e.json.gz

 34%|███▎      | 809/2404 [16:29<34:55,  1.31s/it]

https://hiring.cafe/job/gtsklp344zv1tg1x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gtsklp344zv1tg1x.json.gz

 34%|███▎      | 810/2404 [16:30<33:46,  1.27s/it]

https://hiring.cafe/job/e47r5746b9lqbnxh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e47r5746b9lqbnxh.json.gz

 34%|███▎      | 811/2404 [16:31<33:06,  1.25s/it]

https://hiring.cafe/job/urs85xyhvpu9hpek
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\urs85xyhvpu9hpek.json.gz

 34%|███▍      | 812/2404 [16:32<33:15,  1.25s/it]

https://hiring.cafe/job/qb2jfhiacdz769eg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qb2jfhiacdz769eg.json.gz

 34%|███▍      | 813/2404 [16:34<32:53,  1.24s/it]

https://hiring.cafe/job/imscf8havv7wd4ez
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\imscf8havv7wd4ez.json.gz

 34%|███▍      | 814/2404 [16:35<32:39,  1.23s/it]

https://hiring.cafe/job/9b7gy6vfnj1ycan0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9b7gy6vfnj1ycan0.json.gz

 34%|███▍      | 815/2404 [16:36<31:10,  1.18s/it]

https://hiring.cafe/job/fwqyzuntgzxwoh4c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fwqyzuntgzxwoh4c.json.gz

 34%|███▍      | 816/2404 [16:37<30:53,  1.17s/it]

https://hiring.cafe/job/7brae1z50yfgvx13
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7brae1z50yfgvx13.json.gz

 34%|███▍      | 817/2404 [16:38<31:20,  1.18s/it]

https://hiring.cafe/job/j13zwexc74pxorf6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j13zwexc74pxorf6.json.gz

 34%|███▍      | 818/2404 [16:39<30:18,  1.15s/it]

https://hiring.cafe/job/uh4rzflvm6ttul1z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uh4rzflvm6ttul1z.json.gz

 34%|███▍      | 819/2404 [16:41<31:55,  1.21s/it]

https://hiring.cafe/job/vh26mi1l0p17eqml
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vh26mi1l0p17eqml.json.gz

 34%|███▍      | 820/2404 [16:42<32:07,  1.22s/it]

https://hiring.cafe/job/yhaf1wydqz6byazg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yhaf1wydqz6byazg.json.gz

 34%|███▍      | 821/2404 [16:43<33:17,  1.26s/it]

https://hiring.cafe/job/f9ul9cfl9r7utmhs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f9ul9cfl9r7utmhs.json.gz

 34%|███▍      | 822/2404 [16:44<31:09,  1.18s/it]

https://hiring.cafe/job/zv4bcf1jv8lopq5b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zv4bcf1jv8lopq5b.json.gz

 34%|███▍      | 823/2404 [16:45<30:22,  1.15s/it]

https://hiring.cafe/job/liwqtrg2dp0ed3ia
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\liwqtrg2dp0ed3ia.json.gz

 34%|███▍      | 824/2404 [16:47<30:42,  1.17s/it]

https://hiring.cafe/job/wayuofry2b1a5amu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wayuofry2b1a5amu.json.gz

 34%|███▍      | 825/2404 [16:48<33:30,  1.27s/it]

https://hiring.cafe/job/2hooxqaz5b40cx84
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2hooxqaz5b40cx84.json.gz

 34%|███▍      | 826/2404 [16:50<34:15,  1.30s/it]

https://hiring.cafe/job/y9mddtnszigz4z29
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y9mddtnszigz4z29.json.gz

 34%|███▍      | 827/2404 [16:51<33:30,  1.28s/it]

https://hiring.cafe/job/dyowq66pi3rdq7xr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dyowq66pi3rdq7xr.json.gz

 34%|███▍      | 828/2404 [16:52<32:35,  1.24s/it]

https://hiring.cafe/job/jssfqmofi6il850x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jssfqmofi6il850x.json.gz

 34%|███▍      | 829/2404 [16:53<33:20,  1.27s/it]

https://hiring.cafe/job/zq5b06ps8envl2j9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zq5b06ps8envl2j9.json.gz

 35%|███▍      | 830/2404 [16:54<32:50,  1.25s/it]

https://hiring.cafe/job/00rhygxxf0j6cf0x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\00rhygxxf0j6cf0x.json.gz

 35%|███▍      | 831/2404 [16:56<33:29,  1.28s/it]

https://hiring.cafe/job/426g0rkrdubkf5tu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\426g0rkrdubkf5tu.json.gz

 35%|███▍      | 832/2404 [16:57<34:04,  1.30s/it]

https://hiring.cafe/job/ftj866fv794t8p5x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ftj866fv794t8p5x.json.gz

 35%|███▍      | 833/2404 [16:58<33:21,  1.27s/it]

https://hiring.cafe/job/ryldo15jys5fjfox
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ryldo15jys5fjfox.json.gz

 35%|███▍      | 834/2404 [17:00<33:57,  1.30s/it]

https://hiring.cafe/job/6oq95bffvqfjts76
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6oq95bffvqfjts76.json.gz

 35%|███▍      | 835/2404 [17:01<33:41,  1.29s/it]

https://hiring.cafe/job/4bl4x1ge7s21tows
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4bl4x1ge7s21tows.json.gz

 35%|███▍      | 836/2404 [17:02<35:25,  1.36s/it]

https://hiring.cafe/job/ciseadh06nt3vw7e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ciseadh06nt3vw7e.json.gz

 35%|███▍      | 837/2404 [17:04<33:38,  1.29s/it]

https://hiring.cafe/job/eg4d0of8uo2cd63b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eg4d0of8uo2cd63b.json.gz

 35%|███▍      | 838/2404 [17:05<33:45,  1.29s/it]

https://hiring.cafe/job/k4gst0pqa9inuy9e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k4gst0pqa9inuy9e.json.gz

 35%|███▍      | 839/2404 [17:06<33:02,  1.27s/it]

https://hiring.cafe/job/i32398v4hjz1xqsk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i32398v4hjz1xqsk.json.gz

 35%|███▍      | 840/2404 [17:07<33:29,  1.28s/it]

https://hiring.cafe/job/gxqgyzcwz158v47s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gxqgyzcwz158v47s.json.gz

 35%|███▍      | 841/2404 [17:09<33:18,  1.28s/it]

https://hiring.cafe/job/ydwhawxfazncd57o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ydwhawxfazncd57o.json.gz

 35%|███▌      | 842/2404 [17:10<32:14,  1.24s/it]

https://hiring.cafe/job/64eupplu8z6ui7uj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\64eupplu8z6ui7uj.json.gz

 35%|███▌      | 843/2404 [17:11<30:17,  1.16s/it]

https://hiring.cafe/job/fo68b0aybiftct5n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fo68b0aybiftct5n.json.gz

 35%|███▌      | 844/2404 [17:12<32:23,  1.25s/it]

https://hiring.cafe/job/8jspeqgovjp7pvrk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8jspeqgovjp7pvrk.json.gz

 35%|███▌      | 845/2404 [17:14<33:36,  1.29s/it]

https://hiring.cafe/job/syqevzujo69pce3u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\syqevzujo69pce3u.json.gz

 35%|███▌      | 846/2404 [17:15<32:13,  1.24s/it]

https://hiring.cafe/job/unq5vx2fl49kuohy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\unq5vx2fl49kuohy.json.gz

 35%|███▌      | 847/2404 [17:16<33:16,  1.28s/it]

https://hiring.cafe/job/on7ne5kotf27rbis
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\on7ne5kotf27rbis.json.gz

 35%|███▌      | 848/2404 [17:17<31:38,  1.22s/it]

https://hiring.cafe/job/kobiqyfl4qkvts9l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kobiqyfl4qkvts9l.json.gz

 35%|███▌      | 849/2404 [17:19<35:28,  1.37s/it]

https://hiring.cafe/job/qdwvsmfuwazla9zf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qdwvsmfuwazla9zf.json.gz

 35%|███▌      | 850/2404 [17:20<33:42,  1.30s/it]

https://hiring.cafe/job/9ufqw08y8avuw3tp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9ufqw08y8avuw3tp.json.gz

 35%|███▌      | 851/2404 [17:21<33:00,  1.28s/it]

https://hiring.cafe/job/odm5aygs8ryjy5nw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\odm5aygs8ryjy5nw.json.gz

 35%|███▌      | 852/2404 [17:23<34:39,  1.34s/it]

https://hiring.cafe/job/1mhid5u8z7wvs8bk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1mhid5u8z7wvs8bk.json.gz

 35%|███▌      | 853/2404 [17:24<32:23,  1.25s/it]

https://hiring.cafe/job/ifmrs5bxmf3l1y7k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ifmrs5bxmf3l1y7k.json.gz

 36%|███▌      | 854/2404 [17:25<31:38,  1.23s/it]

https://hiring.cafe/job/z58gseeq4g2x6j0l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z58gseeq4g2x6j0l.json.gz

 36%|███▌      | 855/2404 [17:27<33:40,  1.30s/it]

https://hiring.cafe/job/tasl83c68t1xyzi9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tasl83c68t1xyzi9.json.gz

 36%|███▌      | 856/2404 [17:28<32:22,  1.25s/it]

https://hiring.cafe/job/2ny2trcf346tblg6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2ny2trcf346tblg6.json.gz

 36%|███▌      | 857/2404 [17:29<30:21,  1.18s/it]

https://hiring.cafe/job/hm8oq40a5yajni1f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hm8oq40a5yajni1f.json.gz

 36%|███▌      | 858/2404 [17:30<31:34,  1.23s/it]

https://hiring.cafe/job/fguznb0jn13isx1q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fguznb0jn13isx1q.json.gz

 36%|███▌      | 859/2404 [17:31<31:04,  1.21s/it]

https://hiring.cafe/job/04dg2rfiou2kv0xm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\04dg2rfiou2kv0xm.json.gz

 36%|███▌      | 860/2404 [17:32<28:40,  1.11s/it]

https://hiring.cafe/job/9eb2f5rgsk8fpkyr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9eb2f5rgsk8fpkyr.json.gz

 36%|███▌      | 861/2404 [17:33<29:27,  1.15s/it]

https://hiring.cafe/job/cgws2104d882d29s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cgws2104d882d29s.json.gz

 36%|███▌      | 862/2404 [17:34<29:31,  1.15s/it]

https://hiring.cafe/job/6r0i6lgdbsj5fwvj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6r0i6lgdbsj5fwvj.json.gz

 36%|███▌      | 863/2404 [17:36<30:40,  1.19s/it]

https://hiring.cafe/job/suj889dfoqwv59wz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\suj889dfoqwv59wz.json.gz

 36%|███▌      | 864/2404 [17:37<30:57,  1.21s/it]

https://hiring.cafe/job/iui6xdxmc8he8s30
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iui6xdxmc8he8s30.json.gz

 36%|███▌      | 865/2404 [17:38<30:19,  1.18s/it]

https://hiring.cafe/job/jssy0inkiow1rhxk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jssy0inkiow1rhxk.json.gz

 36%|███▌      | 866/2404 [17:39<29:01,  1.13s/it]

https://hiring.cafe/job/ivr4x61fpd7a2zvu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ivr4x61fpd7a2zvu.json.gz

 36%|███▌      | 867/2404 [17:40<29:05,  1.14s/it]

https://hiring.cafe/job/uoopbulh5esosviz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uoopbulh5esosviz.json.gz

 36%|███▌      | 868/2404 [17:41<29:03,  1.14s/it]

https://hiring.cafe/job/sgbv81yyo22efdsz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sgbv81yyo22efdsz.json.gz

 36%|███▌      | 869/2404 [17:43<29:31,  1.15s/it]

https://hiring.cafe/job/9h3y9ha3pans3vcx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9h3y9ha3pans3vcx.json.gz

 36%|███▌      | 870/2404 [17:44<28:49,  1.13s/it]

https://hiring.cafe/job/w4sn6b5cz1tyqdtx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w4sn6b5cz1tyqdtx.json.gz

 36%|███▌      | 871/2404 [17:45<30:23,  1.19s/it]

https://hiring.cafe/job/hgfh4m67vfi1wzf9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hgfh4m67vfi1wzf9.json.gz

 36%|███▋      | 872/2404 [17:46<31:24,  1.23s/it]

https://hiring.cafe/job/9kvyod2bjdpiqi8i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9kvyod2bjdpiqi8i.json.gz

 36%|███▋      | 873/2404 [17:48<31:55,  1.25s/it]

https://hiring.cafe/job/btvqxa799uv5fied
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\btvqxa799uv5fied.json.gz

 36%|███▋      | 874/2404 [17:49<32:24,  1.27s/it]

https://hiring.cafe/job/hizoadszpyjucq1m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hizoadszpyjucq1m.json.gz

 36%|███▋      | 875/2404 [17:50<34:11,  1.34s/it]

https://hiring.cafe/job/pqy91rwzc3tvjm91
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pqy91rwzc3tvjm91.json.gz

 36%|███▋      | 876/2404 [17:52<34:58,  1.37s/it]

https://hiring.cafe/job/vssngtcug5e4sr1k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vssngtcug5e4sr1k.json.gz

 36%|███▋      | 877/2404 [17:53<31:23,  1.23s/it]

https://hiring.cafe/job/41vy5lb49y2a2eh0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\41vy5lb49y2a2eh0.json.gz

 37%|███▋      | 878/2404 [17:54<33:24,  1.31s/it]

https://hiring.cafe/job/pmsj2t4e038t5vly
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pmsj2t4e038t5vly.json.gz

 37%|███▋      | 879/2404 [17:56<32:45,  1.29s/it]

https://hiring.cafe/job/n4m9caqn4wh6mvga
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n4m9caqn4wh6mvga.json.gz

 37%|███▋      | 880/2404 [17:57<32:11,  1.27s/it]

https://hiring.cafe/job/ukyouxz82oey7hqv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ukyouxz82oey7hqv.json.gz

 37%|███▋      | 881/2404 [17:58<33:14,  1.31s/it]

https://hiring.cafe/job/u16i19sbwyypubxe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u16i19sbwyypubxe.json.gz

 37%|███▋      | 882/2404 [17:59<29:35,  1.17s/it]

https://hiring.cafe/job/8nyma8ap7iczfjot
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8nyma8ap7iczfjot.json.gz

 37%|███▋      | 883/2404 [18:00<29:51,  1.18s/it]

https://hiring.cafe/job/en3cr09frbpkym0s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\en3cr09frbpkym0s.json.gz

 37%|███▋      | 884/2404 [18:01<29:39,  1.17s/it]

https://hiring.cafe/job/y8e5e7y8r6569ol3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y8e5e7y8r6569ol3.json.gz

 37%|███▋      | 885/2404 [18:02<28:38,  1.13s/it]

https://hiring.cafe/job/oz5n5t9x8x87uwn7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oz5n5t9x8x87uwn7.json.gz

 37%|███▋      | 886/2404 [18:04<28:46,  1.14s/it]

https://hiring.cafe/job/haicuzbkw2z1rhle
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\haicuzbkw2z1rhle.json.gz

 37%|███▋      | 887/2404 [18:05<29:15,  1.16s/it]

https://hiring.cafe/job/5vaz19qsl2mnvnc8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5vaz19qsl2mnvnc8.json.gz

 37%|███▋      | 888/2404 [18:06<29:46,  1.18s/it]

https://hiring.cafe/job/9k6drexjuigm0dy2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9k6drexjuigm0dy2.json.gz

 37%|███▋      | 889/2404 [18:07<29:50,  1.18s/it]

https://hiring.cafe/job/conoqtiz7353z9y2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\conoqtiz7353z9y2.json.gz

 37%|███▋      | 890/2404 [18:08<28:16,  1.12s/it]

https://hiring.cafe/job/y08hlet5g6rva996
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y08hlet5g6rva996.json.gz

 37%|███▋      | 891/2404 [18:09<28:55,  1.15s/it]

https://hiring.cafe/job/xx8mn40tp6lf8ppf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xx8mn40tp6lf8ppf.json.gz

 37%|███▋      | 892/2404 [18:11<29:08,  1.16s/it]

https://hiring.cafe/job/lg7au26w5aqzdk72
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lg7au26w5aqzdk72.json.gz

 37%|███▋      | 893/2404 [18:12<29:42,  1.18s/it]

https://hiring.cafe/job/ar41jxddjedsud1f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ar41jxddjedsud1f.json.gz

 37%|███▋      | 894/2404 [18:13<29:45,  1.18s/it]

https://hiring.cafe/job/z6nf3a19p8yskgeg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z6nf3a19p8yskgeg.json.gz

 37%|███▋      | 895/2404 [18:14<30:08,  1.20s/it]

https://hiring.cafe/job/wm3eg02vbb237uqo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wm3eg02vbb237uqo.json.gz

 37%|███▋      | 896/2404 [18:15<29:12,  1.16s/it]

https://hiring.cafe/job/82b0eoljd9dku1h3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\82b0eoljd9dku1h3.json.gz

 37%|███▋      | 897/2404 [18:17<30:16,  1.21s/it]

https://hiring.cafe/job/fexf5kq0g3u8ve3v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fexf5kq0g3u8ve3v.json.gz

 37%|███▋      | 898/2404 [18:18<30:15,  1.21s/it]

https://hiring.cafe/job/wb2ibzvxg2ar7ng4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wb2ibzvxg2ar7ng4.json.gz

 37%|███▋      | 899/2404 [18:19<31:22,  1.25s/it]

https://hiring.cafe/job/ihkce4hnnxd06kl7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ihkce4hnnxd06kl7.json.gz

 37%|███▋      | 900/2404 [18:20<30:36,  1.22s/it]

https://hiring.cafe/job/n88g2txhgzikt7ez
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n88g2txhgzikt7ez.json.gz

 37%|███▋      | 901/2404 [18:22<30:39,  1.22s/it]

https://hiring.cafe/job/snl7kggdeujb3nra
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\snl7kggdeujb3nra.json.gz

 38%|███▊      | 902/2404 [18:23<30:19,  1.21s/it]

https://hiring.cafe/job/ipeyz602n192j4r3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ipeyz602n192j4r3.json.gz

 38%|███▊      | 903/2404 [18:24<28:42,  1.15s/it]

https://hiring.cafe/job/erg72zromo6hbd22
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\erg72zromo6hbd22.json.gz

 38%|███▊      | 904/2404 [18:25<28:23,  1.14s/it]

https://hiring.cafe/job/409qjqv5oaamiiyw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\409qjqv5oaamiiyw.json.gz

 38%|███▊      | 905/2404 [18:26<28:13,  1.13s/it]

https://hiring.cafe/job/9f9stei01bo4byld
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9f9stei01bo4byld.json.gz

 38%|███▊      | 906/2404 [18:27<28:30,  1.14s/it]

https://hiring.cafe/job/r8lc5lb15n9npapq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r8lc5lb15n9npapq.json.gz

 38%|███▊      | 907/2404 [18:28<29:07,  1.17s/it]

https://hiring.cafe/job/xenyjetfmme84x1c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xenyjetfmme84x1c.json.gz

 38%|███▊      | 908/2404 [18:30<30:57,  1.24s/it]

https://hiring.cafe/job/hi42h4brm41noeoa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hi42h4brm41noeoa.json.gz

 38%|███▊      | 909/2404 [18:31<28:47,  1.16s/it]

https://hiring.cafe/job/bj3ox994w9lrmca4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bj3ox994w9lrmca4.json.gz

 38%|███▊      | 910/2404 [18:32<28:51,  1.16s/it]

https://hiring.cafe/job/2q3c3yucf3jlrlbk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2q3c3yucf3jlrlbk.json.gz

 38%|███▊      | 911/2404 [18:33<29:26,  1.18s/it]

https://hiring.cafe/job/jji2h4k07i20xs3t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jji2h4k07i20xs3t.json.gz

 38%|███▊      | 912/2404 [18:34<27:55,  1.12s/it]

https://hiring.cafe/job/gzxbwa82z23kyzqp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gzxbwa82z23kyzqp.json.gz

 38%|███▊      | 913/2404 [18:35<29:31,  1.19s/it]

https://hiring.cafe/job/y145186xhwyze1ej
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y145186xhwyze1ej.json.gz

 38%|███▊      | 914/2404 [18:36<28:48,  1.16s/it]

https://hiring.cafe/job/4ocafma80aqv49bk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4ocafma80aqv49bk.json.gz

 38%|███▊      | 915/2404 [18:38<30:47,  1.24s/it]

https://hiring.cafe/job/8p76u0rh6zy1sfa7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8p76u0rh6zy1sfa7.json.gz

 38%|███▊      | 916/2404 [18:39<29:21,  1.18s/it]

https://hiring.cafe/job/obn6p356vswk80o5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\obn6p356vswk80o5.json.gz

 38%|███▊      | 917/2404 [18:40<30:18,  1.22s/it]

https://hiring.cafe/job/8njr39j7fjwdd75o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8njr39j7fjwdd75o.json.gz

 38%|███▊      | 918/2404 [18:42<30:34,  1.23s/it]

https://hiring.cafe/job/hcj4s6761hrwuooq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hcj4s6761hrwuooq.json.gz

 38%|███▊      | 919/2404 [18:43<29:54,  1.21s/it]

https://hiring.cafe/job/ae93ph7snktx1soi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ae93ph7snktx1soi.json.gz

 38%|███▊      | 920/2404 [18:44<29:20,  1.19s/it]

https://hiring.cafe/job/79nu8ixpg8awrivv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\79nu8ixpg8awrivv.json.gz

 38%|███▊      | 921/2404 [18:45<27:35,  1.12s/it]

https://hiring.cafe/job/ldaci5d6i892oymg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ldaci5d6i892oymg.json.gz

 38%|███▊      | 922/2404 [18:46<28:27,  1.15s/it]

https://hiring.cafe/job/ehu1ms9valo36qk0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ehu1ms9valo36qk0.json.gz

 38%|███▊      | 923/2404 [18:48<30:53,  1.25s/it]

https://hiring.cafe/job/btt9831zthxsvcam
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\btt9831zthxsvcam.json.gz

 38%|███▊      | 924/2404 [18:49<29:32,  1.20s/it]

https://hiring.cafe/job/45drxjj3tnzj34ys
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\45drxjj3tnzj34ys.json.gz

 38%|███▊      | 925/2404 [18:50<30:10,  1.22s/it]

https://hiring.cafe/job/mhghqtygyoxx3j6o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mhghqtygyoxx3j6o.json.gz

 39%|███▊      | 926/2404 [18:51<29:31,  1.20s/it]

https://hiring.cafe/job/t0731ow3f1mwgyhp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t0731ow3f1mwgyhp.json.gz

 39%|███▊      | 927/2404 [18:52<29:01,  1.18s/it]

https://hiring.cafe/job/bkjiqw75pphq38xg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bkjiqw75pphq38xg.json.gz

 39%|███▊      | 928/2404 [18:53<29:56,  1.22s/it]

https://hiring.cafe/job/7caukl9oc68vu1gl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7caukl9oc68vu1gl.json.gz

 39%|███▊      | 929/2404 [18:55<30:07,  1.23s/it]

https://hiring.cafe/job/fv8pngyv3rq5tytu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fv8pngyv3rq5tytu.json.gz

 39%|███▊      | 930/2404 [18:56<31:11,  1.27s/it]

https://hiring.cafe/job/nl9jbehn5c6g3aer
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nl9jbehn5c6g3aer.json.gz

 39%|███▊      | 931/2404 [18:57<30:42,  1.25s/it]

https://hiring.cafe/job/z78s021kuqx7gq4h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z78s021kuqx7gq4h.json.gz

 39%|███▉      | 932/2404 [18:58<30:14,  1.23s/it]

https://hiring.cafe/job/d7xb3eafo8bvez9w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d7xb3eafo8bvez9w.json.gz

 39%|███▉      | 933/2404 [18:59<28:09,  1.15s/it]

https://hiring.cafe/job/ze5qqhg3azc3vk8z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ze5qqhg3azc3vk8z.json.gz

 39%|███▉      | 934/2404 [19:01<28:26,  1.16s/it]

https://hiring.cafe/job/l4ljbdxml52qfz38
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l4ljbdxml52qfz38.json.gz

 39%|███▉      | 935/2404 [19:02<29:13,  1.19s/it]

https://hiring.cafe/job/isb7xg6p5hm6qsv3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\isb7xg6p5hm6qsv3.json.gz

 39%|███▉      | 936/2404 [19:03<26:47,  1.09s/it]

https://hiring.cafe/job/n2u54vtbgtrriwrx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n2u54vtbgtrriwrx.json.gz

 39%|███▉      | 937/2404 [19:04<25:34,  1.05s/it]

https://hiring.cafe/job/qd5b86c6ywm9fkhg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qd5b86c6ywm9fkhg.json.gz

 39%|███▉      | 938/2404 [19:05<25:34,  1.05s/it]

https://hiring.cafe/job/wbfyfyr7lnn6a4ac
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wbfyfyr7lnn6a4ac.json.gz

 39%|███▉      | 939/2404 [19:06<26:10,  1.07s/it]

https://hiring.cafe/job/kae7pvoksc93d9o8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kae7pvoksc93d9o8.json.gz

 39%|███▉      | 940/2404 [19:07<25:49,  1.06s/it]

https://hiring.cafe/job/nenw0c9ij907zkzo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nenw0c9ij907zkzo.json.gz

 39%|███▉      | 941/2404 [19:08<27:20,  1.12s/it]

https://hiring.cafe/job/j7tzlgnjguuefosp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j7tzlgnjguuefosp.json.gz

 39%|███▉      | 942/2404 [19:09<28:55,  1.19s/it]

https://hiring.cafe/job/kwny8v4w8q5rikg0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kwny8v4w8q5rikg0.json.gz

 39%|███▉      | 943/2404 [19:11<29:49,  1.22s/it]

https://hiring.cafe/job/5n1wcq0r1iq9xwk2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5n1wcq0r1iq9xwk2.json.gz

 39%|███▉      | 944/2404 [19:12<28:32,  1.17s/it]

https://hiring.cafe/job/lnlvlow9b8t65scn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lnlvlow9b8t65scn.json.gz

 39%|███▉      | 945/2404 [19:13<28:28,  1.17s/it]

https://hiring.cafe/job/6actmf6nup09uysi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6actmf6nup09uysi.json.gz

 39%|███▉      | 946/2404 [19:14<26:58,  1.11s/it]

https://hiring.cafe/job/83bec63aoz7u6vim
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\83bec63aoz7u6vim.json.gz

 39%|███▉      | 947/2404 [19:15<27:42,  1.14s/it]

https://hiring.cafe/job/0qibv79v5br9oxgl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0qibv79v5br9oxgl.json.gz

 39%|███▉      | 948/2404 [19:16<27:45,  1.14s/it]

https://hiring.cafe/job/irz1jme6wfnskj7u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\irz1jme6wfnskj7u.json.gz

 39%|███▉      | 949/2404 [19:18<29:03,  1.20s/it]

https://hiring.cafe/job/lpm7oc5wekt4hfsx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lpm7oc5wekt4hfsx.json.gz

 40%|███▉      | 950/2404 [19:19<29:05,  1.20s/it]

https://hiring.cafe/job/ei4uf3w8bwkxfhcc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ei4uf3w8bwkxfhcc.json.gz

 40%|███▉      | 951/2404 [19:20<27:46,  1.15s/it]

https://hiring.cafe/job/wooq1r3cix3277uf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wooq1r3cix3277uf.json.gz

 40%|███▉      | 952/2404 [19:21<29:27,  1.22s/it]

https://hiring.cafe/job/s4dzosxrpi3a245e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s4dzosxrpi3a245e.json.gz

 40%|███▉      | 953/2404 [19:23<31:16,  1.29s/it]

https://hiring.cafe/job/llzkis0s609bxwjc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\llzkis0s609bxwjc.json.gz

 40%|███▉      | 954/2404 [19:24<30:21,  1.26s/it]

https://hiring.cafe/job/k3lpf80mewvw6xo2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k3lpf80mewvw6xo2.json.gz

 40%|███▉      | 955/2404 [19:25<29:19,  1.21s/it]

https://hiring.cafe/job/euqr4oyxm17og1pd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\euqr4oyxm17og1pd.json.gz

 40%|███▉      | 956/2404 [19:26<30:18,  1.26s/it]

https://hiring.cafe/job/k2bco350y6uec3vn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k2bco350y6uec3vn.json.gz

 40%|███▉      | 957/2404 [19:28<30:36,  1.27s/it]

https://hiring.cafe/job/844q2w4no9igfkoa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\844q2w4no9igfkoa.json.gz

 40%|███▉      | 958/2404 [19:29<29:15,  1.21s/it]

https://hiring.cafe/job/ug446do5j5gozgj2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ug446do5j5gozgj2.json.gz

 40%|███▉      | 959/2404 [19:30<27:54,  1.16s/it]

https://hiring.cafe/job/cf0x0zam304pjnvu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cf0x0zam304pjnvu.json.gz

 40%|███▉      | 960/2404 [19:31<28:39,  1.19s/it]

https://hiring.cafe/job/c5ksdyvjhc1fhmeb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c5ksdyvjhc1fhmeb.json.gz

 40%|███▉      | 961/2404 [19:32<28:49,  1.20s/it]

https://hiring.cafe/job/5zuxwsfblz9r1ohh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5zuxwsfblz9r1ohh.json.gz

 40%|████      | 962/2404 [19:33<27:37,  1.15s/it]

https://hiring.cafe/job/0wxvak2l62irevoo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0wxvak2l62irevoo.json.gz

 40%|████      | 963/2404 [19:34<27:43,  1.15s/it]

https://hiring.cafe/job/q02m54bgensiwidi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q02m54bgensiwidi.json.gz

 40%|████      | 964/2404 [19:36<26:44,  1.11s/it]

https://hiring.cafe/job/4zj7icr9bschgwbu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4zj7icr9bschgwbu.json.gz

 40%|████      | 965/2404 [19:37<26:41,  1.11s/it]

https://hiring.cafe/job/484st4683o1oznsb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\484st4683o1oznsb.json.gz

 40%|████      | 966/2404 [19:38<26:05,  1.09s/it]

https://hiring.cafe/job/9kvt6km5uaatfew7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9kvt6km5uaatfew7.json.gz

 40%|████      | 967/2404 [19:39<26:15,  1.10s/it]

https://hiring.cafe/job/oq66o9qwehozv8xz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oq66o9qwehozv8xz.json.gz

 40%|████      | 968/2404 [19:40<25:46,  1.08s/it]

https://hiring.cafe/job/w8jqbfhk5e7gc28s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w8jqbfhk5e7gc28s.json.gz

 40%|████      | 969/2404 [19:41<26:55,  1.13s/it]

https://hiring.cafe/job/y0xb9gvzabs21blh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y0xb9gvzabs21blh.json.gz

 40%|████      | 970/2404 [19:42<28:56,  1.21s/it]

https://hiring.cafe/job/k0vobrux819gokjs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k0vobrux819gokjs.json.gz

 40%|████      | 971/2404 [19:44<30:34,  1.28s/it]

https://hiring.cafe/job/nfo3lbkmlx2hk5r5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nfo3lbkmlx2hk5r5.json.gz

 40%|████      | 972/2404 [19:45<31:06,  1.30s/it]

https://hiring.cafe/job/uidaitv3v6e9cdfi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uidaitv3v6e9cdfi.json.gz

 40%|████      | 973/2404 [19:47<32:23,  1.36s/it]

https://hiring.cafe/job/przzfmhbff4bdptw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\przzfmhbff4bdptw.json.gz

 41%|████      | 974/2404 [19:48<31:46,  1.33s/it]

https://hiring.cafe/job/tzlnxwkk1driqgs8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tzlnxwkk1driqgs8.json.gz

 41%|████      | 975/2404 [19:49<30:22,  1.28s/it]

https://hiring.cafe/job/1vmg8dnc1t5jgq8a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1vmg8dnc1t5jgq8a.json.gz

 41%|████      | 976/2404 [19:51<31:38,  1.33s/it]

https://hiring.cafe/job/qcexbzep2iaj2q9r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qcexbzep2iaj2q9r.json.gz

 41%|████      | 977/2404 [19:52<28:57,  1.22s/it]

https://hiring.cafe/job/isvqyn26aelcw9nk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\isvqyn26aelcw9nk.json.gz

 41%|████      | 978/2404 [19:53<31:23,  1.32s/it]

https://hiring.cafe/job/5rda98e9tlww3951
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5rda98e9tlww3951.json.gz

 41%|████      | 979/2404 [19:54<30:06,  1.27s/it]

https://hiring.cafe/job/zzdqcjpqwuzigsbb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zzdqcjpqwuzigsbb.json.gz

 41%|████      | 980/2404 [19:55<28:20,  1.19s/it]

https://hiring.cafe/job/8wg3yqd0bczvlf6m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8wg3yqd0bczvlf6m.json.gz

 41%|████      | 981/2404 [19:57<29:15,  1.23s/it]

https://hiring.cafe/job/z4ur3o9uy3d3ard0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z4ur3o9uy3d3ard0.json.gz

 41%|████      | 982/2404 [19:58<28:56,  1.22s/it]

https://hiring.cafe/job/2r07q55nqmww6opj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2r07q55nqmww6opj.json.gz

 41%|████      | 983/2404 [19:59<29:12,  1.23s/it]

https://hiring.cafe/job/n85fblznnndj4kp1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n85fblznnndj4kp1.json.gz

 41%|████      | 984/2404 [20:01<30:47,  1.30s/it]

https://hiring.cafe/job/xyqpz67xo7hnw3ac
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xyqpz67xo7hnw3ac.json.gz

 41%|████      | 985/2404 [20:02<31:32,  1.33s/it]

https://hiring.cafe/job/rd118e6ps772r5sa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rd118e6ps772r5sa.json.gz

 41%|████      | 986/2404 [20:03<31:20,  1.33s/it]

https://hiring.cafe/job/dop3umlkggbetyam
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dop3umlkggbetyam.json.gz

 41%|████      | 987/2404 [20:04<29:28,  1.25s/it]

https://hiring.cafe/job/8lfhycdna3xxf4jj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8lfhycdna3xxf4jj.json.gz

 41%|████      | 988/2404 [20:06<30:50,  1.31s/it]

https://hiring.cafe/job/b6gu8bqwpogkoyl2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b6gu8bqwpogkoyl2.json.gz

 41%|████      | 989/2404 [20:07<31:38,  1.34s/it]

https://hiring.cafe/job/n82g2opitpbn5xbv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n82g2opitpbn5xbv.json.gz

 41%|████      | 990/2404 [20:08<31:08,  1.32s/it]

https://hiring.cafe/job/p9aqoxahsoz785b9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p9aqoxahsoz785b9.json.gz

 41%|████      | 991/2404 [20:10<31:24,  1.33s/it]

https://hiring.cafe/job/tgaipuvfis9qz9r9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tgaipuvfis9qz9r9.json.gz

 41%|████▏     | 992/2404 [20:11<30:22,  1.29s/it]

https://hiring.cafe/job/9i7tbpexivsieane
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9i7tbpexivsieane.json.gz

 41%|████▏     | 993/2404 [20:12<29:37,  1.26s/it]

https://hiring.cafe/job/vn5kxykvqg8ckmm2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vn5kxykvqg8ckmm2.json.gz

 41%|████▏     | 994/2404 [20:14<30:50,  1.31s/it]

https://hiring.cafe/job/ti7adw7x4um0o7e2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ti7adw7x4um0o7e2.json.gz

 41%|████▏     | 995/2404 [20:15<33:46,  1.44s/it]

https://hiring.cafe/job/26dfy44dqsoee3ti
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\26dfy44dqsoee3ti.json.gz

 41%|████▏     | 996/2404 [20:17<33:18,  1.42s/it]

https://hiring.cafe/job/fljq7yjqp4g7uxyh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fljq7yjqp4g7uxyh.json.gz

 41%|████▏     | 997/2404 [20:18<32:09,  1.37s/it]

https://hiring.cafe/job/ktumn26s9ihd8yaj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ktumn26s9ihd8yaj.json.gz

 42%|████▏     | 998/2404 [20:19<31:11,  1.33s/it]

https://hiring.cafe/job/g42o2bbetf8v389r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g42o2bbetf8v389r.json.gz

 42%|████▏     | 999/2404 [20:21<30:57,  1.32s/it]

https://hiring.cafe/job/diqf6qsygg0viphe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\diqf6qsygg0viphe.json.gz

 42%|████▏     | 1000/2404 [20:22<32:21,  1.38s/it]

https://hiring.cafe/job/mt9tjdv29rfe6kt6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mt9tjdv29rfe6kt6.json.gz

 42%|████▏     | 1001/2404 [20:24<33:01,  1.41s/it]

https://hiring.cafe/job/n4jo5o2z1qbe4sxu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n4jo5o2z1qbe4sxu.json.gz

 42%|████▏     | 1002/2404 [20:25<32:53,  1.41s/it]

https://hiring.cafe/job/rk076l2oghn6cwgu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rk076l2oghn6cwgu.json.gz

 42%|████▏     | 1003/2404 [20:26<31:23,  1.34s/it]

https://hiring.cafe/job/zlm96faf1bosx2y6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zlm96faf1bosx2y6.json.gz

 42%|████▏     | 1004/2404 [20:27<29:18,  1.26s/it]

https://hiring.cafe/job/xw1um56dytjvt20z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xw1um56dytjvt20z.json.gz

 42%|████▏     | 1005/2404 [20:28<29:02,  1.25s/it]

https://hiring.cafe/job/l3tu8b8kij0h35sl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l3tu8b8kij0h35sl.json.gz

 42%|████▏     | 1006/2404 [20:30<32:49,  1.41s/it]

https://hiring.cafe/job/wk5lhlzwol3sv72c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wk5lhlzwol3sv72c.json.gz

 42%|████▏     | 1007/2404 [20:32<33:43,  1.45s/it]

https://hiring.cafe/job/s6jrqa356ex4188e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s6jrqa356ex4188e.json.gz

 42%|████▏     | 1008/2404 [20:33<32:32,  1.40s/it]

https://hiring.cafe/job/a2b6oqzaoj2droes
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a2b6oqzaoj2droes.json.gz

 42%|████▏     | 1009/2404 [20:34<31:55,  1.37s/it]

https://hiring.cafe/job/segmb2jh3ie5wdhq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\segmb2jh3ie5wdhq.json.gz

 42%|████▏     | 1010/2404 [20:36<32:46,  1.41s/it]

https://hiring.cafe/job/t0il34l8w2s9y5m3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t0il34l8w2s9y5m3.json.gz

 42%|████▏     | 1011/2404 [20:37<32:08,  1.38s/it]

https://hiring.cafe/job/tcvxxd7cbw5ljt8o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tcvxxd7cbw5ljt8o.json.gz

 42%|████▏     | 1012/2404 [20:38<31:14,  1.35s/it]

https://hiring.cafe/job/gj106twpeu5p3hvx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gj106twpeu5p3hvx.json.gz

 42%|████▏     | 1013/2404 [20:40<29:54,  1.29s/it]

https://hiring.cafe/job/6iru8ura0hgukhew
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6iru8ura0hgukhew.json.gz

 42%|████▏     | 1014/2404 [20:41<29:40,  1.28s/it]

https://hiring.cafe/job/vkvie9dy6wyan6u5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vkvie9dy6wyan6u5.json.gz

 42%|████▏     | 1015/2404 [20:42<30:27,  1.32s/it]

https://hiring.cafe/job/ik1qcu7ou7haubk6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ik1qcu7ou7haubk6.json.gz

 42%|████▏     | 1016/2404 [20:44<30:51,  1.33s/it]

https://hiring.cafe/job/car64zchs28e0pdg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\car64zchs28e0pdg.json.gz

 42%|████▏     | 1017/2404 [20:45<29:20,  1.27s/it]

https://hiring.cafe/job/bk4aywiizijs1bqv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bk4aywiizijs1bqv.json.gz

 42%|████▏     | 1018/2404 [20:46<28:43,  1.24s/it]

https://hiring.cafe/job/5kigegbaz52oejxc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5kigegbaz52oejxc.json.gz

 42%|████▏     | 1019/2404 [20:47<29:52,  1.29s/it]

https://hiring.cafe/job/dw67b87kbltkh7se
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dw67b87kbltkh7se.json.gz

 42%|████▏     | 1020/2404 [20:49<30:13,  1.31s/it]

https://hiring.cafe/job/f4me995wq1kyqt5e
https://hiring.cafe/job/f4me995wq1kyqt5e

 42%|████▏     | 1021/2404 [20:50<27:28,  1.19s/it]

https://hiring.cafe/job/f7d9cvm1ncgl4e3u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f7d9cvm1ncgl4e3u.json.gz

 43%|████▎     | 1022/2404 [20:51<31:07,  1.35s/it]

https://hiring.cafe/job/x7u97y92y5og1ubg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x7u97y92y5og1ubg.json.gz

 43%|████▎     | 1023/2404 [20:53<30:46,  1.34s/it]

https://hiring.cafe/job/8gm785pfcuv9btyc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8gm785pfcuv9btyc.json.gz

 43%|████▎     | 1024/2404 [20:54<30:07,  1.31s/it]

https://hiring.cafe/job/chwxhkzmhl73v79l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\chwxhkzmhl73v79l.json.gz

 43%|████▎     | 1025/2404 [20:55<28:51,  1.26s/it]

https://hiring.cafe/job/joq8f4fqrw9hosqs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\joq8f4fqrw9hosqs.json.gz

 43%|████▎     | 1026/2404 [20:57<30:49,  1.34s/it]

https://hiring.cafe/job/yz4lgcdr75y5klo0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yz4lgcdr75y5klo0.json.gz

 43%|████▎     | 1027/2404 [20:58<30:04,  1.31s/it]

https://hiring.cafe/job/acklh9jrjc6jdabj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\acklh9jrjc6jdabj.json.gz

 43%|████▎     | 1028/2404 [20:59<31:00,  1.35s/it]

https://hiring.cafe/job/77z82hw7jz775z88
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\77z82hw7jz775z88.json.gz

 43%|████▎     | 1029/2404 [21:01<30:52,  1.35s/it]

https://hiring.cafe/job/g55ec8bhbw53ahzu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g55ec8bhbw53ahzu.json.gz

 43%|████▎     | 1030/2404 [21:02<30:21,  1.33s/it]

https://hiring.cafe/job/65jl75hpskh4f7ji
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\65jl75hpskh4f7ji.json.gz

 43%|████▎     | 1031/2404 [21:03<29:03,  1.27s/it]

https://hiring.cafe/job/k6ls2w741h5ae7ir
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k6ls2w741h5ae7ir.json.gz

 43%|████▎     | 1032/2404 [21:04<27:00,  1.18s/it]

https://hiring.cafe/job/5toqsvap8b5wq8dw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5toqsvap8b5wq8dw.json.gz

 43%|████▎     | 1033/2404 [21:05<28:30,  1.25s/it]

https://hiring.cafe/job/tyar2rk90aufqqmw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tyar2rk90aufqqmw.json.gz

 43%|████▎     | 1034/2404 [21:06<26:56,  1.18s/it]

https://hiring.cafe/job/aqmjyxvac4797n2r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\aqmjyxvac4797n2r.json.gz

 43%|████▎     | 1035/2404 [21:07<26:30,  1.16s/it]

https://hiring.cafe/job/m6a3xqj28s5te9ai
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m6a3xqj28s5te9ai.json.gz

 43%|████▎     | 1036/2404 [21:09<26:23,  1.16s/it]

https://hiring.cafe/job/9wcuilko7k9qv69w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9wcuilko7k9qv69w.json.gz

 43%|████▎     | 1037/2404 [21:10<24:54,  1.09s/it]

https://hiring.cafe/job/2md1hbei73etcvea
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2md1hbei73etcvea.json.gz

 43%|████▎     | 1038/2404 [21:11<23:52,  1.05s/it]

https://hiring.cafe/job/yzz5kl1yciis0v4g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yzz5kl1yciis0v4g.json.gz

 43%|████▎     | 1039/2404 [21:12<26:43,  1.17s/it]

https://hiring.cafe/job/veywi8vqbs6pp78g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\veywi8vqbs6pp78g.json.gz

 43%|████▎     | 1040/2404 [21:13<27:48,  1.22s/it]

https://hiring.cafe/job/5r8lsndho1lshm0l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5r8lsndho1lshm0l.json.gz

 43%|████▎     | 1041/2404 [21:15<27:41,  1.22s/it]

https://hiring.cafe/job/bpbxqvxcnwp5t3co
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bpbxqvxcnwp5t3co.json.gz

 43%|████▎     | 1042/2404 [21:16<30:16,  1.33s/it]

https://hiring.cafe/job/tjups8dudrgti9pw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tjups8dudrgti9pw.json.gz

 43%|████▎     | 1043/2404 [21:17<30:02,  1.32s/it]

https://hiring.cafe/job/b2dzapihdzjxetd5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b2dzapihdzjxetd5.json.gz

 43%|████▎     | 1044/2404 [21:19<30:57,  1.37s/it]

https://hiring.cafe/job/vtnv7crviqvi5m1f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vtnv7crviqvi5m1f.json.gz

 43%|████▎     | 1045/2404 [21:20<31:12,  1.38s/it]

https://hiring.cafe/job/cvrigtzh9xw3x9uy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cvrigtzh9xw3x9uy.json.gz

 44%|████▎     | 1046/2404 [21:22<32:22,  1.43s/it]

https://hiring.cafe/job/uargyj2kx2ufohoz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uargyj2kx2ufohoz.json.gz

 44%|████▎     | 1047/2404 [21:23<30:05,  1.33s/it]

https://hiring.cafe/job/asuzdpm5otz5vnpl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\asuzdpm5otz5vnpl.json.gz

 44%|████▎     | 1048/2404 [21:24<28:55,  1.28s/it]

https://hiring.cafe/job/up5irz3ag64cd2qh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\up5irz3ag64cd2qh.json.gz

 44%|████▎     | 1049/2404 [21:25<28:26,  1.26s/it]

https://hiring.cafe/job/5jz6hrk0xwk9eveq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5jz6hrk0xwk9eveq.json.gz

 44%|████▎     | 1050/2404 [21:27<27:54,  1.24s/it]

https://hiring.cafe/job/ffcc6oxhuchj94py
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ffcc6oxhuchj94py.json.gz

 44%|████▎     | 1051/2404 [21:28<28:59,  1.29s/it]

https://hiring.cafe/job/6b3rc64mw89mkpe5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6b3rc64mw89mkpe5.json.gz

 44%|████▍     | 1052/2404 [21:29<27:35,  1.22s/it]

https://hiring.cafe/job/zv8x8swqy65a4bn6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zv8x8swqy65a4bn6.json.gz

 44%|████▍     | 1053/2404 [21:31<29:54,  1.33s/it]

https://hiring.cafe/job/sh5hanx30o1mggk6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sh5hanx30o1mggk6.json.gz

 44%|████▍     | 1054/2404 [21:32<29:19,  1.30s/it]

https://hiring.cafe/job/df338b8mgx9asyox
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\df338b8mgx9asyox.json.gz

 44%|████▍     | 1055/2404 [21:33<29:01,  1.29s/it]

https://hiring.cafe/job/srqpso9p2n971ax4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\srqpso9p2n971ax4.json.gz

 44%|████▍     | 1056/2404 [21:34<28:54,  1.29s/it]

https://hiring.cafe/job/p9nzy410xe845d59
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p9nzy410xe845d59.json.gz

 44%|████▍     | 1057/2404 [21:36<28:57,  1.29s/it]

https://hiring.cafe/job/1ewemivt0b32of93
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1ewemivt0b32of93.json.gz

 44%|████▍     | 1058/2404 [21:37<28:17,  1.26s/it]

https://hiring.cafe/job/dehxsgl5qkr27ho3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dehxsgl5qkr27ho3.json.gz

 44%|████▍     | 1059/2404 [21:38<27:46,  1.24s/it]

https://hiring.cafe/job/qvt1qrb050of4ce0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qvt1qrb050of4ce0.json.gz

 44%|████▍     | 1060/2404 [21:39<27:29,  1.23s/it]

https://hiring.cafe/job/ia1y6b0vvq45gw90
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ia1y6b0vvq45gw90.json.gz

 44%|████▍     | 1061/2404 [21:41<28:04,  1.25s/it]

https://hiring.cafe/job/mq5u9mebs4r8cuv3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mq5u9mebs4r8cuv3.json.gz

 44%|████▍     | 1062/2404 [21:42<26:50,  1.20s/it]

https://hiring.cafe/job/r4ur92h5yaj0hw6h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r4ur92h5yaj0hw6h.json.gz

 44%|████▍     | 1063/2404 [21:43<25:58,  1.16s/it]

https://hiring.cafe/job/zza2ge5kfk489ypj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zza2ge5kfk489ypj.json.gz

 44%|████▍     | 1064/2404 [21:44<27:13,  1.22s/it]

https://hiring.cafe/job/3hulva6tqesplkdt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3hulva6tqesplkdt.json.gz

 44%|████▍     | 1065/2404 [21:45<28:27,  1.28s/it]

https://hiring.cafe/job/z1xnyk9nzkur8scb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z1xnyk9nzkur8scb.json.gz

 44%|████▍     | 1066/2404 [21:47<28:17,  1.27s/it]

https://hiring.cafe/job/eqs4ux4radwq6kb7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eqs4ux4radwq6kb7.json.gz

 44%|████▍     | 1067/2404 [21:48<29:21,  1.32s/it]

https://hiring.cafe/job/f88pc7pkxyx556v1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f88pc7pkxyx556v1.json.gz

 44%|████▍     | 1068/2404 [21:50<30:24,  1.37s/it]

https://hiring.cafe/job/ygbe897ew8w0ynwb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ygbe897ew8w0ynwb.json.gz

 44%|████▍     | 1069/2404 [21:51<31:06,  1.40s/it]

https://hiring.cafe/job/3tkj5h3i1quftqn8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3tkj5h3i1quftqn8.json.gz

 45%|████▍     | 1070/2404 [21:52<29:50,  1.34s/it]

https://hiring.cafe/job/r5zloqjgyrvo7qxw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r5zloqjgyrvo7qxw.json.gz

 45%|████▍     | 1071/2404 [21:54<29:11,  1.31s/it]

https://hiring.cafe/job/0ycrkrgq1y65d4ku
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ycrkrgq1y65d4ku.json.gz

 45%|████▍     | 1072/2404 [21:55<28:44,  1.29s/it]

https://hiring.cafe/job/txvukwt692gnpiju
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\txvukwt692gnpiju.json.gz

 45%|████▍     | 1073/2404 [21:56<28:10,  1.27s/it]

https://hiring.cafe/job/ftko7m3ht395aud6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ftko7m3ht395aud6.json.gz

 45%|████▍     | 1074/2404 [21:57<28:20,  1.28s/it]

https://hiring.cafe/job/it6e4qsa5q8khbvl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\it6e4qsa5q8khbvl.json.gz

 45%|████▍     | 1075/2404 [21:58<26:28,  1.20s/it]

https://hiring.cafe/job/atxt7e6klf2n2ac8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\atxt7e6klf2n2ac8.json.gz

 45%|████▍     | 1076/2404 [22:00<27:42,  1.25s/it]

https://hiring.cafe/job/1i0irt318am804kg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1i0irt318am804kg.json.gz

 45%|████▍     | 1077/2404 [22:01<29:23,  1.33s/it]

https://hiring.cafe/job/x720clcxikdufi1x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x720clcxikdufi1x.json.gz

 45%|████▍     | 1078/2404 [22:03<29:36,  1.34s/it]

https://hiring.cafe/job/71t57dt5gx6856yy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\71t57dt5gx6856yy.json.gz

 45%|████▍     | 1079/2404 [22:04<30:06,  1.36s/it]

https://hiring.cafe/job/b7voi0qyn123q3a3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b7voi0qyn123q3a3.json.gz

 45%|████▍     | 1080/2404 [22:05<29:09,  1.32s/it]

https://hiring.cafe/job/tz2aqbcn7l0zapfe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tz2aqbcn7l0zapfe.json.gz

 45%|████▍     | 1081/2404 [22:06<28:10,  1.28s/it]

https://hiring.cafe/job/184qp67j3y8jer8v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\184qp67j3y8jer8v.json.gz

 45%|████▌     | 1082/2404 [22:08<28:06,  1.28s/it]

https://hiring.cafe/job/9k0yjn0nrg7rbm9k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9k0yjn0nrg7rbm9k.json.gz

 45%|████▌     | 1083/2404 [22:09<27:55,  1.27s/it]

https://hiring.cafe/job/t96dsr9c73sibgf4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t96dsr9c73sibgf4.json.gz

 45%|████▌     | 1084/2404 [22:10<26:30,  1.20s/it]

https://hiring.cafe/job/vjz3tgem3xo9ghik
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vjz3tgem3xo9ghik.json.gz

 45%|████▌     | 1085/2404 [22:11<26:52,  1.22s/it]

https://hiring.cafe/job/cmuatde9ylyae6zk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cmuatde9ylyae6zk.json.gz

 45%|████▌     | 1086/2404 [22:12<26:03,  1.19s/it]

https://hiring.cafe/job/qazwm55v7e8yuat8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qazwm55v7e8yuat8.json.gz

 45%|████▌     | 1087/2404 [22:14<26:39,  1.21s/it]

https://hiring.cafe/job/7lldhil05q8z4ssp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7lldhil05q8z4ssp.json.gz

 45%|████▌     | 1088/2404 [22:15<25:23,  1.16s/it]

https://hiring.cafe/job/rrwiatct99glrs64
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rrwiatct99glrs64.json.gz

 45%|████▌     | 1089/2404 [22:16<25:00,  1.14s/it]

https://hiring.cafe/job/gsagku2g6jblbvsg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gsagku2g6jblbvsg.json.gz

 45%|████▌     | 1090/2404 [22:17<25:43,  1.18s/it]

https://hiring.cafe/job/dlze3ikhj6rr0r1a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dlze3ikhj6rr0r1a.json.gz

 45%|████▌     | 1091/2404 [22:18<25:07,  1.15s/it]

https://hiring.cafe/job/de05cn3ig4tqfndy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\de05cn3ig4tqfndy.json.gz

 45%|████▌     | 1092/2404 [22:19<25:03,  1.15s/it]

https://hiring.cafe/job/bbcx695fagk5fupi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bbcx695fagk5fupi.json.gz

 45%|████▌     | 1093/2404 [22:20<25:35,  1.17s/it]

https://hiring.cafe/job/410nd1k5g47e51mi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\410nd1k5g47e51mi.json.gz

 46%|████▌     | 1094/2404 [22:22<27:21,  1.25s/it]

https://hiring.cafe/job/8b0d4650y2b8lzm0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8b0d4650y2b8lzm0.json.gz

 46%|████▌     | 1095/2404 [22:23<26:40,  1.22s/it]

https://hiring.cafe/job/71svm7fcrnflwcmq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\71svm7fcrnflwcmq.json.gz

 46%|████▌     | 1096/2404 [22:24<26:52,  1.23s/it]

https://hiring.cafe/job/jmmqysk0nowvlktu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jmmqysk0nowvlktu.json.gz

 46%|████▌     | 1097/2404 [22:25<25:52,  1.19s/it]

https://hiring.cafe/job/dt8kjndqfynk7h6a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dt8kjndqfynk7h6a.json.gz

 46%|████▌     | 1098/2404 [22:27<25:35,  1.18s/it]

https://hiring.cafe/job/36e6e48ripr191xc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\36e6e48ripr191xc.json.gz

 46%|████▌     | 1099/2404 [22:28<27:18,  1.26s/it]

https://hiring.cafe/job/dqfe0s3dva1ak83g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dqfe0s3dva1ak83g.json.gz

 46%|████▌     | 1100/2404 [22:30<29:11,  1.34s/it]

https://hiring.cafe/job/wxhf579lhzw7kgu4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wxhf579lhzw7kgu4.json.gz

 46%|████▌     | 1101/2404 [22:31<27:33,  1.27s/it]

https://hiring.cafe/job/mbioxsna7wpa082j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mbioxsna7wpa082j.json.gz

 46%|████▌     | 1102/2404 [22:32<28:50,  1.33s/it]

https://hiring.cafe/job/xhdqz3td21nuast5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xhdqz3td21nuast5.json.gz

 46%|████▌     | 1103/2404 [22:34<30:09,  1.39s/it]

https://hiring.cafe/job/76yupt2qys0ufffs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\76yupt2qys0ufffs.json.gz

 46%|████▌     | 1104/2404 [22:35<30:45,  1.42s/it]

https://hiring.cafe/job/82sdsp815mjfzpda
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\82sdsp815mjfzpda.json.gz

 46%|████▌     | 1105/2404 [22:37<32:14,  1.49s/it]

https://hiring.cafe/job/wwtwo1uwib58cegg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wwtwo1uwib58cegg.json.gz

 46%|████▌     | 1106/2404 [22:38<29:13,  1.35s/it]

https://hiring.cafe/job/dvpnvuy1fro5nv66
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dvpnvuy1fro5nv66.json.gz

 46%|████▌     | 1107/2404 [22:39<29:20,  1.36s/it]

https://hiring.cafe/job/d410e57fdb9feha9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d410e57fdb9feha9.json.gz

 46%|████▌     | 1108/2404 [22:40<28:09,  1.30s/it]

https://hiring.cafe/job/55722o2tm5iy2n1l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\55722o2tm5iy2n1l.json.gz

 46%|████▌     | 1109/2404 [22:42<27:52,  1.29s/it]

https://hiring.cafe/job/mwu2om6qt0nsmrwf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mwu2om6qt0nsmrwf.json.gz

 46%|████▌     | 1110/2404 [22:43<27:07,  1.26s/it]

https://hiring.cafe/job/4xm2e1i7gmhmumwk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4xm2e1i7gmhmumwk.json.gz

 46%|████▌     | 1111/2404 [22:44<27:19,  1.27s/it]

https://hiring.cafe/job/cni7zbixbdm9djy7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cni7zbixbdm9djy7.json.gz

 46%|████▋     | 1112/2404 [22:46<28:32,  1.33s/it]

https://hiring.cafe/job/v3nrmaze2mnq7k7d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v3nrmaze2mnq7k7d.json.gz

 46%|████▋     | 1113/2404 [22:47<26:30,  1.23s/it]

https://hiring.cafe/job/o7cl06696qmkzyyi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o7cl06696qmkzyyi.json.gz

 46%|████▋     | 1114/2404 [22:48<27:27,  1.28s/it]

https://hiring.cafe/job/9ne9gw12cnquxbx5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9ne9gw12cnquxbx5.json.gz

 46%|████▋     | 1115/2404 [22:49<29:00,  1.35s/it]

https://hiring.cafe/job/myz8ppo708oxiuth
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\myz8ppo708oxiuth.json.gz

 46%|████▋     | 1116/2404 [22:51<29:30,  1.37s/it]

https://hiring.cafe/job/5lcraw2qkyguk9x2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5lcraw2qkyguk9x2.json.gz

 46%|████▋     | 1117/2404 [22:52<28:13,  1.32s/it]

https://hiring.cafe/job/ej49ymds3tqwf0tv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ej49ymds3tqwf0tv.json.gz

 47%|████▋     | 1118/2404 [22:53<28:22,  1.32s/it]

https://hiring.cafe/job/ef20v9a76b35ds4u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ef20v9a76b35ds4u.json.gz

 47%|████▋     | 1119/2404 [22:55<28:46,  1.34s/it]

https://hiring.cafe/job/cl83hn73ms5j9nlw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cl83hn73ms5j9nlw.json.gz

 47%|████▋     | 1120/2404 [22:56<30:55,  1.45s/it]

https://hiring.cafe/job/6f5kfvz2dcm8ozku
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6f5kfvz2dcm8ozku.json.gz

 47%|████▋     | 1121/2404 [22:58<29:12,  1.37s/it]

https://hiring.cafe/job/ceuf9s2bpnu5fioi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ceuf9s2bpnu5fioi.json.gz

 47%|████▋     | 1122/2404 [22:59<27:06,  1.27s/it]

https://hiring.cafe/job/lq0x641jo96q3g7n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lq0x641jo96q3g7n.json.gz

 47%|████▋     | 1123/2404 [23:00<27:53,  1.31s/it]

https://hiring.cafe/job/5ovcyixb5ho3vb2j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ovcyixb5ho3vb2j.json.gz

 47%|████▋     | 1124/2404 [23:01<27:14,  1.28s/it]

https://hiring.cafe/job/w097bddymdw6dsx5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w097bddymdw6dsx5.json.gz

 47%|████▋     | 1125/2404 [23:03<27:11,  1.28s/it]

https://hiring.cafe/job/qoub8l6ucyc3ylyc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qoub8l6ucyc3ylyc.json.gz

 47%|████▋     | 1126/2404 [23:04<25:33,  1.20s/it]

https://hiring.cafe/job/mh3zej1ufwl6rm1i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mh3zej1ufwl6rm1i.json.gz

 47%|████▋     | 1127/2404 [23:05<26:37,  1.25s/it]

https://hiring.cafe/job/wrmndfm16qj0ltfo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wrmndfm16qj0ltfo.json.gz

 47%|████▋     | 1128/2404 [23:06<25:44,  1.21s/it]

https://hiring.cafe/job/3ahhwq9ipnan3mlv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3ahhwq9ipnan3mlv.json.gz

 47%|████▋     | 1129/2404 [23:07<25:30,  1.20s/it]

https://hiring.cafe/job/fut1ylamzgsiln5v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fut1ylamzgsiln5v.json.gz

 47%|████▋     | 1130/2404 [23:09<25:55,  1.22s/it]

https://hiring.cafe/job/w6qozkjbgo5hmo1n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w6qozkjbgo5hmo1n.json.gz

 47%|████▋     | 1131/2404 [23:10<25:50,  1.22s/it]

https://hiring.cafe/job/yk42pqopxzf6wk3z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yk42pqopxzf6wk3z.json.gz

 47%|████▋     | 1132/2404 [23:11<26:47,  1.26s/it]

https://hiring.cafe/job/gw97ck02uc5mvvcf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gw97ck02uc5mvvcf.json.gz

 47%|████▋     | 1133/2404 [23:12<26:18,  1.24s/it]

https://hiring.cafe/job/5whumcvo1ne6fyos
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5whumcvo1ne6fyos.json.gz

 47%|████▋     | 1134/2404 [23:14<26:28,  1.25s/it]

https://hiring.cafe/job/m63vptfhw1bi0pf5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m63vptfhw1bi0pf5.json.gz

 47%|████▋     | 1135/2404 [23:15<25:26,  1.20s/it]

https://hiring.cafe/job/2o04uh51o1fgm8ti
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2o04uh51o1fgm8ti.json.gz

 47%|████▋     | 1136/2404 [23:16<24:14,  1.15s/it]

https://hiring.cafe/job/wuh1w362k9sf30uz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wuh1w362k9sf30uz.json.gz

 47%|████▋     | 1137/2404 [23:17<25:41,  1.22s/it]

https://hiring.cafe/job/sqm7nniulrzcohx4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sqm7nniulrzcohx4.json.gz

 47%|████▋     | 1138/2404 [23:18<25:22,  1.20s/it]

https://hiring.cafe/job/phr423xg24lpf890
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\phr423xg24lpf890.json.gz

 47%|████▋     | 1139/2404 [23:20<26:07,  1.24s/it]

https://hiring.cafe/job/r3gund84wt9a4x8e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r3gund84wt9a4x8e.json.gz

 47%|████▋     | 1140/2404 [23:21<25:52,  1.23s/it]

https://hiring.cafe/job/2ywrcnsenbebngmt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2ywrcnsenbebngmt.json.gz

 47%|████▋     | 1141/2404 [23:22<25:59,  1.23s/it]

https://hiring.cafe/job/vdx4j5q19k2tfg58
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vdx4j5q19k2tfg58.json.gz

 48%|████▊     | 1142/2404 [23:23<27:04,  1.29s/it]

https://hiring.cafe/job/u7v30drr0w7yus6b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u7v30drr0w7yus6b.json.gz

 48%|████▊     | 1143/2404 [23:25<25:54,  1.23s/it]

https://hiring.cafe/job/j8xbonykp2rnqhsd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j8xbonykp2rnqhsd.json.gz

 48%|████▊     | 1144/2404 [23:26<25:42,  1.22s/it]

https://hiring.cafe/job/hfgpdxm974bdu57b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hfgpdxm974bdu57b.json.gz

 48%|████▊     | 1145/2404 [23:27<26:21,  1.26s/it]

https://hiring.cafe/job/uqeeluup134hsnzf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uqeeluup134hsnzf.json.gz

 48%|████▊     | 1146/2404 [23:28<27:20,  1.30s/it]

https://hiring.cafe/job/dd6u2w4j5w4j4wsq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dd6u2w4j5w4j4wsq.json.gz

 48%|████▊     | 1147/2404 [23:30<25:59,  1.24s/it]

https://hiring.cafe/job/e8z368m6ro2b8nku
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e8z368m6ro2b8nku.json.gz

 48%|████▊     | 1148/2404 [23:31<25:46,  1.23s/it]

https://hiring.cafe/job/xj6v4qtetwonzfur
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xj6v4qtetwonzfur.json.gz

 48%|████▊     | 1149/2404 [23:32<26:24,  1.26s/it]

https://hiring.cafe/job/x3q33cxt4hh5snrd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x3q33cxt4hh5snrd.json.gz

 48%|████▊     | 1150/2404 [23:33<26:59,  1.29s/it]

https://hiring.cafe/job/zetviiz4jntqq37k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zetviiz4jntqq37k.json.gz

 48%|████▊     | 1151/2404 [23:35<27:41,  1.33s/it]

https://hiring.cafe/job/t4am1nu1928j3dzo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t4am1nu1928j3dzo.json.gz

 48%|████▊     | 1152/2404 [23:36<25:31,  1.22s/it]

https://hiring.cafe/job/mgtd8gbg40nlc5mu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mgtd8gbg40nlc5mu.json.gz

 48%|████▊     | 1153/2404 [23:37<25:06,  1.20s/it]

https://hiring.cafe/job/aisqsa9zu09c3h5r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\aisqsa9zu09c3h5r.json.gz

 48%|████▊     | 1154/2404 [23:38<25:43,  1.24s/it]

https://hiring.cafe/job/yuoxuydajvroplys
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yuoxuydajvroplys.json.gz

 48%|████▊     | 1155/2404 [23:40<26:48,  1.29s/it]

https://hiring.cafe/job/lftjypk263wd1hxs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lftjypk263wd1hxs.json.gz

 48%|████▊     | 1156/2404 [23:41<24:10,  1.16s/it]

https://hiring.cafe/job/l7lyty578kn1d7ox
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l7lyty578kn1d7ox.json.gz

 48%|████▊     | 1157/2404 [23:42<24:00,  1.16s/it]

https://hiring.cafe/job/b4702i9mfs1rxsor
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b4702i9mfs1rxsor.json.gz

 48%|████▊     | 1158/2404 [23:43<23:55,  1.15s/it]

https://hiring.cafe/job/xrj3p56ef845r2rl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xrj3p56ef845r2rl.json.gz

 48%|████▊     | 1159/2404 [23:44<26:01,  1.25s/it]

https://hiring.cafe/job/1l1vfia198l19e4z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1l1vfia198l19e4z.json.gz

 48%|████▊     | 1160/2404 [23:46<26:38,  1.29s/it]

https://hiring.cafe/job/ohv16c9nnfd9a7b2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ohv16c9nnfd9a7b2.json.gz

 48%|████▊     | 1161/2404 [23:47<27:10,  1.31s/it]

https://hiring.cafe/job/w5aoh6tw75qk29hh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w5aoh6tw75qk29hh.json.gz

 48%|████▊     | 1162/2404 [23:48<24:50,  1.20s/it]

https://hiring.cafe/job/s2fepyf20u8uiijn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s2fepyf20u8uiijn.json.gz

 48%|████▊     | 1163/2404 [23:49<25:47,  1.25s/it]

https://hiring.cafe/job/ulvl4l9fn7eu66yu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ulvl4l9fn7eu66yu.json.gz

 48%|████▊     | 1164/2404 [23:51<28:15,  1.37s/it]

https://hiring.cafe/job/00hk9dsqz2y8iay3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\00hk9dsqz2y8iay3.json.gz

 48%|████▊     | 1165/2404 [23:52<28:03,  1.36s/it]

https://hiring.cafe/job/ixa9ve2t3oliw4yu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ixa9ve2t3oliw4yu.json.gz

 49%|████▊     | 1166/2404 [23:54<28:17,  1.37s/it]

https://hiring.cafe/job/v62cyct6aez2ojz8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v62cyct6aez2ojz8.json.gz

 49%|████▊     | 1167/2404 [23:55<28:06,  1.36s/it]

https://hiring.cafe/job/xu5xikmsnatw8nsm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xu5xikmsnatw8nsm.json.gz

 49%|████▊     | 1168/2404 [23:56<26:13,  1.27s/it]

https://hiring.cafe/job/b6459la4kby51w4i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b6459la4kby51w4i.json.gz

 49%|████▊     | 1169/2404 [23:57<25:51,  1.26s/it]

https://hiring.cafe/job/fsg0jahfvb8sgo9z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fsg0jahfvb8sgo9z.json.gz

 49%|████▊     | 1170/2404 [23:59<25:22,  1.23s/it]

https://hiring.cafe/job/gqwohkdznb3q9xkv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gqwohkdznb3q9xkv.json.gz

 49%|████▊     | 1171/2404 [24:00<26:25,  1.29s/it]

https://hiring.cafe/job/5hcwb0jx5igtgcgg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5hcwb0jx5igtgcgg.json.gz

 49%|████▉     | 1172/2404 [24:01<25:57,  1.26s/it]

https://hiring.cafe/job/ird8sj8sheobxh3m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ird8sj8sheobxh3m.json.gz

 49%|████▉     | 1173/2404 [24:02<24:55,  1.21s/it]

https://hiring.cafe/job/m0fs9bz3pmec1yib
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m0fs9bz3pmec1yib.json.gz

 49%|████▉     | 1174/2404 [24:03<23:32,  1.15s/it]

https://hiring.cafe/job/75ylo2vde44hskmq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\75ylo2vde44hskmq.json.gz

 49%|████▉     | 1175/2404 [24:04<23:25,  1.14s/it]

https://hiring.cafe/job/5lbxt3xoepr8lvsz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5lbxt3xoepr8lvsz.json.gz

 49%|████▉     | 1176/2404 [24:06<24:09,  1.18s/it]

https://hiring.cafe/job/l73hxy5ecig4hydj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l73hxy5ecig4hydj.json.gz

 49%|████▉     | 1177/2404 [24:07<24:41,  1.21s/it]

https://hiring.cafe/job/uezf5bpvru86m26h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uezf5bpvru86m26h.json.gz

 49%|████▉     | 1178/2404 [24:08<24:35,  1.20s/it]

https://hiring.cafe/job/8qq1xbba7q8m33cd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8qq1xbba7q8m33cd.json.gz

 49%|████▉     | 1179/2404 [24:09<25:17,  1.24s/it]

https://hiring.cafe/job/p5ipnuxau568y2w1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p5ipnuxau568y2w1.json.gz

 49%|████▉     | 1180/2404 [24:11<26:26,  1.30s/it]

https://hiring.cafe/job/b76x1gginuvaqlcg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b76x1gginuvaqlcg.json.gz

 49%|████▉     | 1181/2404 [24:12<25:20,  1.24s/it]

https://hiring.cafe/job/txtfu9s6qy0iyjhk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\txtfu9s6qy0iyjhk.json.gz

 49%|████▉     | 1182/2404 [24:14<26:45,  1.31s/it]

https://hiring.cafe/job/jc2qe4ssk31b70sr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jc2qe4ssk31b70sr.json.gz

 49%|████▉     | 1183/2404 [24:15<27:50,  1.37s/it]

https://hiring.cafe/job/bni97dz5kud7u1xa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bni97dz5kud7u1xa.json.gz

 49%|████▉     | 1184/2404 [24:16<28:21,  1.39s/it]

https://hiring.cafe/job/nnlnmlgxi6drsoqz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nnlnmlgxi6drsoqz.json.gz

 49%|████▉     | 1185/2404 [24:18<27:43,  1.36s/it]

https://hiring.cafe/job/mcuymfognol4bp9x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mcuymfognol4bp9x.json.gz

 49%|████▉     | 1186/2404 [24:19<27:27,  1.35s/it]

https://hiring.cafe/job/wsoq1tfpc6lodqaa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wsoq1tfpc6lodqaa.json.gz

 49%|████▉     | 1187/2404 [24:20<25:23,  1.25s/it]

https://hiring.cafe/job/6p6e44k925sp7n31
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6p6e44k925sp7n31.json.gz

 49%|████▉     | 1188/2404 [24:21<26:10,  1.29s/it]

https://hiring.cafe/job/p7w0tqovumaxucfr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p7w0tqovumaxucfr.json.gz

 49%|████▉     | 1189/2404 [24:23<25:23,  1.25s/it]

https://hiring.cafe/job/4rkjuxsrf0kyzm4m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4rkjuxsrf0kyzm4m.json.gz

 50%|████▉     | 1190/2404 [24:24<24:45,  1.22s/it]

https://hiring.cafe/job/9qfj92eci9hmlvyx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9qfj92eci9hmlvyx.json.gz

 50%|████▉     | 1191/2404 [24:25<25:47,  1.28s/it]

https://hiring.cafe/job/ym684gj9n0bapoal
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ym684gj9n0bapoal.json.gz

 50%|████▉     | 1192/2404 [24:26<25:14,  1.25s/it]

https://hiring.cafe/job/8tl5ev9wan27fw8u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8tl5ev9wan27fw8u.json.gz

 50%|████▉     | 1193/2404 [24:27<23:07,  1.15s/it]

https://hiring.cafe/job/natoa2yj44yczy0s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\natoa2yj44yczy0s.json.gz

 50%|████▉     | 1194/2404 [24:28<22:32,  1.12s/it]

https://hiring.cafe/job/wdb6flqbi0nmxk6l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wdb6flqbi0nmxk6l.json.gz

 50%|████▉     | 1195/2404 [24:29<21:24,  1.06s/it]

https://hiring.cafe/job/evlmo0l82tz9b0q2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\evlmo0l82tz9b0q2.json.gz

 50%|████▉     | 1196/2404 [24:30<21:44,  1.08s/it]

https://hiring.cafe/job/gc595cf3i03ddz2d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gc595cf3i03ddz2d.json.gz

 50%|████▉     | 1197/2404 [24:32<22:42,  1.13s/it]

https://hiring.cafe/job/pn2cqyn7ehge296y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pn2cqyn7ehge296y.json.gz

 50%|████▉     | 1198/2404 [24:33<22:44,  1.13s/it]

https://hiring.cafe/job/7e2pita60wjz28ix
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7e2pita60wjz28ix.json.gz

 50%|████▉     | 1199/2404 [24:34<22:16,  1.11s/it]

https://hiring.cafe/job/kwibuxjp8w4omuub
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kwibuxjp8w4omuub.json.gz

 50%|████▉     | 1200/2404 [24:35<23:57,  1.19s/it]

https://hiring.cafe/job/w8vbm8ez1uh6ninm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w8vbm8ez1uh6ninm.json.gz

 50%|████▉     | 1201/2404 [24:36<23:53,  1.19s/it]

https://hiring.cafe/job/k6px4rpa6l7ioxq6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k6px4rpa6l7ioxq6.json.gz

 50%|█████     | 1202/2404 [24:38<23:51,  1.19s/it]

https://hiring.cafe/job/vzzz3cbl4lrgwamr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vzzz3cbl4lrgwamr.json.gz

 50%|█████     | 1203/2404 [24:39<25:24,  1.27s/it]

https://hiring.cafe/job/h8yu3aw1clba8yt8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h8yu3aw1clba8yt8.json.gz

 50%|█████     | 1204/2404 [24:40<24:41,  1.23s/it]

https://hiring.cafe/job/gs21hsohyum3souu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gs21hsohyum3souu.json.gz

 50%|█████     | 1205/2404 [24:42<25:12,  1.26s/it]

https://hiring.cafe/job/d4owrvclyj2awlj0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d4owrvclyj2awlj0.json.gz

 50%|█████     | 1206/2404 [24:43<23:24,  1.17s/it]

https://hiring.cafe/job/t52v2mwbsgexnjxc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t52v2mwbsgexnjxc.json.gz

 50%|█████     | 1207/2404 [24:44<24:46,  1.24s/it]

https://hiring.cafe/job/n22lxhe0ixvg0ho5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n22lxhe0ixvg0ho5.json.gz

 50%|█████     | 1208/2404 [24:45<23:26,  1.18s/it]

https://hiring.cafe/job/agjnwihn20zyn1zt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\agjnwihn20zyn1zt.json.gz

 50%|█████     | 1209/2404 [24:46<22:56,  1.15s/it]

https://hiring.cafe/job/u4dcn5rytwjvu8gl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u4dcn5rytwjvu8gl.json.gz

 50%|█████     | 1210/2404 [24:47<23:34,  1.18s/it]

https://hiring.cafe/job/dep9i6fu78ewoqyj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dep9i6fu78ewoqyj.json.gz

 50%|█████     | 1211/2404 [24:48<22:48,  1.15s/it]

https://hiring.cafe/job/jjbiisf3wa32o38u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jjbiisf3wa32o38u.json.gz

 50%|█████     | 1212/2404 [24:49<22:43,  1.14s/it]

https://hiring.cafe/job/gr7g60ertiz6gu15
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gr7g60ertiz6gu15.json.gz

 50%|█████     | 1213/2404 [24:51<23:01,  1.16s/it]

https://hiring.cafe/job/fvwyci8qcywvo7sq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fvwyci8qcywvo7sq.json.gz

 50%|█████     | 1214/2404 [24:52<24:02,  1.21s/it]

https://hiring.cafe/job/wgv9n4184jutkwr8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wgv9n4184jutkwr8.json.gz

 51%|█████     | 1215/2404 [24:53<22:48,  1.15s/it]

https://hiring.cafe/job/l0b8d6z6zgs7o2f6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l0b8d6z6zgs7o2f6.json.gz

 51%|█████     | 1216/2404 [24:54<24:35,  1.24s/it]

https://hiring.cafe/job/x6u2siypc61agwx9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x6u2siypc61agwx9.json.gz

 51%|█████     | 1217/2404 [24:56<24:53,  1.26s/it]

https://hiring.cafe/job/x23ls6d89l1qc58y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x23ls6d89l1qc58y.json.gz

 51%|█████     | 1218/2404 [24:57<24:44,  1.25s/it]

https://hiring.cafe/job/rbhbr29yulez4r9f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rbhbr29yulez4r9f.json.gz

 51%|█████     | 1219/2404 [24:58<25:02,  1.27s/it]

https://hiring.cafe/job/mxbvkj4k8x8tuqj2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mxbvkj4k8x8tuqj2.json.gz

 51%|█████     | 1220/2404 [25:00<25:04,  1.27s/it]

https://hiring.cafe/job/skzcg3epxjrdlxe6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\skzcg3epxjrdlxe6.json.gz

 51%|█████     | 1221/2404 [25:01<26:42,  1.35s/it]

https://hiring.cafe/job/oyznwvr06x42wab7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oyznwvr06x42wab7.json.gz

 51%|█████     | 1222/2404 [25:02<25:48,  1.31s/it]

https://hiring.cafe/job/2g751cee3jkp4d83
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2g751cee3jkp4d83.json.gz

 51%|█████     | 1223/2404 [25:04<26:01,  1.32s/it]

https://hiring.cafe/job/1tln88ipcic7craj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1tln88ipcic7craj.json.gz

 51%|█████     | 1224/2404 [25:05<25:37,  1.30s/it]

https://hiring.cafe/job/fzwjfm8kk526fb5b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fzwjfm8kk526fb5b.json.gz

 51%|█████     | 1225/2404 [25:06<23:49,  1.21s/it]

https://hiring.cafe/job/s70xpl6v7tqsvjdo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s70xpl6v7tqsvjdo.json.gz

 51%|█████     | 1226/2404 [25:07<23:03,  1.17s/it]

https://hiring.cafe/job/dq4eu51uwupfgqgl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dq4eu51uwupfgqgl.json.gz

 51%|█████     | 1227/2404 [25:08<23:20,  1.19s/it]

https://hiring.cafe/job/e9yfe91760c52bel
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e9yfe91760c52bel.json.gz

 51%|█████     | 1228/2404 [25:09<22:33,  1.15s/it]

https://hiring.cafe/job/j0d81sofkn1ufdb7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j0d81sofkn1ufdb7.json.gz

 51%|█████     | 1229/2404 [25:11<23:17,  1.19s/it]

https://hiring.cafe/job/zp6lads3es89rud8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zp6lads3es89rud8.json.gz

 51%|█████     | 1230/2404 [25:12<21:50,  1.12s/it]

https://hiring.cafe/job/fhgwe32swrcyqod6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fhgwe32swrcyqod6.json.gz

 51%|█████     | 1231/2404 [25:13<22:41,  1.16s/it]

https://hiring.cafe/job/0ad52uca91nop9kt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ad52uca91nop9kt.json.gz

 51%|█████     | 1232/2404 [25:14<23:13,  1.19s/it]

https://hiring.cafe/job/lbha0njqt1t8dlik
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lbha0njqt1t8dlik.json.gz

 51%|█████▏    | 1233/2404 [25:15<23:06,  1.18s/it]

https://hiring.cafe/job/o9c1doagw80habti
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o9c1doagw80habti.json.gz

 51%|█████▏    | 1234/2404 [25:17<24:22,  1.25s/it]

https://hiring.cafe/job/2n7jhd6vuxcjqcbx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2n7jhd6vuxcjqcbx.json.gz

 51%|█████▏    | 1235/2404 [25:18<25:00,  1.28s/it]

https://hiring.cafe/job/tx0wzoyy3uldirdu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tx0wzoyy3uldirdu.json.gz

 51%|█████▏    | 1236/2404 [25:19<25:20,  1.30s/it]

https://hiring.cafe/job/rt3em1fmicel66us
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rt3em1fmicel66us.json.gz

 51%|█████▏    | 1237/2404 [25:20<24:04,  1.24s/it]

https://hiring.cafe/job/i6brzcnrm1bbckaa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i6brzcnrm1bbckaa.json.gz

 51%|█████▏    | 1238/2404 [25:21<22:16,  1.15s/it]

https://hiring.cafe/job/cpwcf9izeu82kcii
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cpwcf9izeu82kcii.json.gz

 52%|█████▏    | 1239/2404 [25:23<22:19,  1.15s/it]

https://hiring.cafe/job/mvv622urjvkfwajw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mvv622urjvkfwajw.json.gz

 52%|█████▏    | 1240/2404 [25:24<24:14,  1.25s/it]

https://hiring.cafe/job/e5s5uytm8ck6zuax
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e5s5uytm8ck6zuax.json.gz

 52%|█████▏    | 1241/2404 [25:25<24:36,  1.27s/it]

https://hiring.cafe/job/nuv1kerlg7xmty0c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nuv1kerlg7xmty0c.json.gz

 52%|█████▏    | 1242/2404 [25:27<24:39,  1.27s/it]

https://hiring.cafe/job/9o2a2afxg7qup343
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9o2a2afxg7qup343.json.gz

 52%|█████▏    | 1243/2404 [25:28<24:18,  1.26s/it]

https://hiring.cafe/job/np6cos6v9rp5pl9d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\np6cos6v9rp5pl9d.json.gz

 52%|█████▏    | 1244/2404 [25:29<23:48,  1.23s/it]

https://hiring.cafe/job/5aqs8dbsm2tk25ox
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5aqs8dbsm2tk25ox.json.gz

 52%|█████▏    | 1245/2404 [25:30<23:58,  1.24s/it]

https://hiring.cafe/job/1kx18j5k1z1wr0eg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1kx18j5k1z1wr0eg.json.gz

 52%|█████▏    | 1246/2404 [25:31<22:49,  1.18s/it]

https://hiring.cafe/job/7hawu6jz3axw2yse
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7hawu6jz3axw2yse.json.gz

 52%|█████▏    | 1247/2404 [25:32<20:56,  1.09s/it]

https://hiring.cafe/job/on9mc5wvlvv0m6np
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\on9mc5wvlvv0m6np.json.gz

 52%|█████▏    | 1248/2404 [25:33<22:11,  1.15s/it]

https://hiring.cafe/job/b970s3c05hysslif
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b970s3c05hysslif.json.gz

 52%|█████▏    | 1249/2404 [25:35<22:33,  1.17s/it]

https://hiring.cafe/job/hv13bu73u6zg0q7e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hv13bu73u6zg0q7e.json.gz

 52%|█████▏    | 1250/2404 [25:36<23:28,  1.22s/it]

https://hiring.cafe/job/nx6e5zg1tnmiztvs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nx6e5zg1tnmiztvs.json.gz

 52%|█████▏    | 1251/2404 [25:37<23:06,  1.20s/it]

https://hiring.cafe/job/8mkdzazd9y81cl3q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8mkdzazd9y81cl3q.json.gz

 52%|█████▏    | 1252/2404 [25:38<22:43,  1.18s/it]

https://hiring.cafe/job/u06nok6tj7xej3vo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u06nok6tj7xej3vo.json.gz

 52%|█████▏    | 1253/2404 [25:40<23:28,  1.22s/it]

https://hiring.cafe/job/cxdgtec4mp3n4g5g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cxdgtec4mp3n4g5g.json.gz

 52%|█████▏    | 1254/2404 [25:41<23:55,  1.25s/it]

https://hiring.cafe/job/xi7c1yp5ofbgf4yg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xi7c1yp5ofbgf4yg.json.gz

 52%|█████▏    | 1255/2404 [25:42<23:33,  1.23s/it]

https://hiring.cafe/job/tfvpepk3mh9pr0lc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tfvpepk3mh9pr0lc.json.gz

 52%|█████▏    | 1256/2404 [25:43<22:45,  1.19s/it]

https://hiring.cafe/job/907asmpce9wfvk6v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\907asmpce9wfvk6v.json.gz

 52%|█████▏    | 1257/2404 [25:45<23:19,  1.22s/it]

https://hiring.cafe/job/crinmrrinaowb8gr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\crinmrrinaowb8gr.json.gz

 52%|█████▏    | 1258/2404 [25:46<22:49,  1.20s/it]

https://hiring.cafe/job/oigy6kdx3xhu4hpe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oigy6kdx3xhu4hpe.json.gz

 52%|█████▏    | 1259/2404 [25:47<23:00,  1.21s/it]

https://hiring.cafe/job/xq8revrxf2trf7ta
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xq8revrxf2trf7ta.json.gz

 52%|█████▏    | 1260/2404 [25:48<23:59,  1.26s/it]

https://hiring.cafe/job/3zcsw6ufvjn0aonj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3zcsw6ufvjn0aonj.json.gz

 52%|█████▏    | 1261/2404 [25:49<23:01,  1.21s/it]

https://hiring.cafe/job/ht5as0jfckxf6og1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ht5as0jfckxf6og1.json.gz

 52%|█████▏    | 1262/2404 [25:51<23:05,  1.21s/it]

https://hiring.cafe/job/451n6b0nmumjovw5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\451n6b0nmumjovw5.json.gz

 53%|█████▎    | 1263/2404 [25:52<22:48,  1.20s/it]

https://hiring.cafe/job/jbz69q531kinfgbl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jbz69q531kinfgbl.json.gz

 53%|█████▎    | 1264/2404 [25:53<24:37,  1.30s/it]

https://hiring.cafe/job/h0bbw15ajpnn85f5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h0bbw15ajpnn85f5.json.gz

 53%|█████▎    | 1265/2404 [25:54<22:53,  1.21s/it]

https://hiring.cafe/job/wved0e8kkog2ub7r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wved0e8kkog2ub7r.json.gz

 53%|█████▎    | 1266/2404 [25:55<21:31,  1.13s/it]

https://hiring.cafe/job/rhtio3eg8dz66i7m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rhtio3eg8dz66i7m.json.gz

 53%|█████▎    | 1267/2404 [25:56<22:06,  1.17s/it]

https://hiring.cafe/job/pv83210mbqa4ra5x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pv83210mbqa4ra5x.json.gz

 53%|█████▎    | 1268/2404 [25:58<24:15,  1.28s/it]

https://hiring.cafe/job/5ivt7t4kbjhyw0uw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ivt7t4kbjhyw0uw.json.gz

 53%|█████▎    | 1269/2404 [25:59<23:13,  1.23s/it]

https://hiring.cafe/job/mdoyavyzyupaoqub
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mdoyavyzyupaoqub.json.gz

 53%|█████▎    | 1270/2404 [26:00<23:19,  1.23s/it]

https://hiring.cafe/job/0pwqw7hdla6f9r1z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0pwqw7hdla6f9r1z.json.gz

 53%|█████▎    | 1271/2404 [26:01<22:35,  1.20s/it]

https://hiring.cafe/job/gtgk8bt2auvkjom6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gtgk8bt2auvkjom6.json.gz

 53%|█████▎    | 1272/2404 [26:02<21:20,  1.13s/it]

https://hiring.cafe/job/fgw3eu6ifpcwy1wm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fgw3eu6ifpcwy1wm.json.gz

 53%|█████▎    | 1273/2404 [26:04<22:19,  1.18s/it]

https://hiring.cafe/job/g9gjuwdea95unrg4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g9gjuwdea95unrg4.json.gz

 53%|█████▎    | 1274/2404 [26:05<22:15,  1.18s/it]

https://hiring.cafe/job/g7vrw1xcxwwfmo5i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g7vrw1xcxwwfmo5i.json.gz

 53%|█████▎    | 1275/2404 [26:06<22:00,  1.17s/it]

https://hiring.cafe/job/wnl1fldedcz1plm9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wnl1fldedcz1plm9.json.gz

 53%|█████▎    | 1276/2404 [26:07<23:01,  1.22s/it]

https://hiring.cafe/job/psibkbwn9yi6ncn2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\psibkbwn9yi6ncn2.json.gz

 53%|█████▎    | 1277/2404 [26:09<24:26,  1.30s/it]

https://hiring.cafe/job/zo8lts4pb4ttuqkz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zo8lts4pb4ttuqkz.json.gz

 53%|█████▎    | 1278/2404 [26:10<23:52,  1.27s/it]

https://hiring.cafe/job/i7wdvhel3ia86619
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i7wdvhel3ia86619.json.gz

 53%|█████▎    | 1279/2404 [26:12<24:28,  1.31s/it]

https://hiring.cafe/job/nk55n403p243lxrq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nk55n403p243lxrq.json.gz

 53%|█████▎    | 1280/2404 [26:13<22:55,  1.22s/it]

https://hiring.cafe/job/p9hdix7pztez9jfy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p9hdix7pztez9jfy.json.gz

 53%|█████▎    | 1281/2404 [26:14<22:14,  1.19s/it]

https://hiring.cafe/job/fyiyxux87ul2hv9j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fyiyxux87ul2hv9j.json.gz

 53%|█████▎    | 1282/2404 [26:15<24:41,  1.32s/it]

https://hiring.cafe/job/tzetin22bfcvla9x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tzetin22bfcvla9x.json.gz

 53%|█████▎    | 1283/2404 [26:17<24:16,  1.30s/it]

https://hiring.cafe/job/8w72vis5kkggkfzt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8w72vis5kkggkfzt.json.gz

 53%|█████▎    | 1284/2404 [26:18<22:53,  1.23s/it]

https://hiring.cafe/job/rtr2jwbnrmuzkxoo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rtr2jwbnrmuzkxoo.json.gz

 53%|█████▎    | 1285/2404 [26:19<24:03,  1.29s/it]

https://hiring.cafe/job/vbpe6jd5379cli9f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vbpe6jd5379cli9f.json.gz

 53%|█████▎    | 1286/2404 [26:20<23:28,  1.26s/it]

https://hiring.cafe/job/bpg04z0k5vtz3mwd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bpg04z0k5vtz3mwd.json.gz

 54%|█████▎    | 1287/2404 [26:22<23:45,  1.28s/it]

https://hiring.cafe/job/bzlb4dfm04oe4ajz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bzlb4dfm04oe4ajz.json.gz

 54%|█████▎    | 1288/2404 [26:23<22:46,  1.22s/it]

https://hiring.cafe/job/1g7fbqk21mzizl3n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1g7fbqk21mzizl3n.json.gz

 54%|█████▎    | 1289/2404 [26:24<21:52,  1.18s/it]

https://hiring.cafe/job/e3hogtwkf7bf6w55
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e3hogtwkf7bf6w55.json.gz

 54%|█████▎    | 1290/2404 [26:25<21:12,  1.14s/it]

https://hiring.cafe/job/ah64yc3s6oma8vwe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ah64yc3s6oma8vwe.json.gz

 54%|█████▎    | 1291/2404 [26:26<21:49,  1.18s/it]

https://hiring.cafe/job/p7mabvamg4uej7hz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p7mabvamg4uej7hz.json.gz

 54%|█████▎    | 1292/2404 [26:27<22:53,  1.24s/it]

https://hiring.cafe/job/q7gddrgvn1zbm2ao
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q7gddrgvn1zbm2ao.json.gz

 54%|█████▍    | 1293/2404 [26:29<22:51,  1.23s/it]

https://hiring.cafe/job/oqlj6k5qpfx7ltc5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oqlj6k5qpfx7ltc5.json.gz

 54%|█████▍    | 1294/2404 [26:30<22:21,  1.21s/it]

https://hiring.cafe/job/dou8p0y6t4bbn70q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dou8p0y6t4bbn70q.json.gz

 54%|█████▍    | 1295/2404 [26:31<22:01,  1.19s/it]

https://hiring.cafe/job/9c4lb2jqaf0l50tj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9c4lb2jqaf0l50tj.json.gz

 54%|█████▍    | 1296/2404 [26:32<21:43,  1.18s/it]

https://hiring.cafe/job/uamz0riap45h1akp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uamz0riap45h1akp.json.gz

 54%|█████▍    | 1297/2404 [26:33<22:35,  1.22s/it]

https://hiring.cafe/job/z4k0zfjq2wr3bv7j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z4k0zfjq2wr3bv7j.json.gz

 54%|█████▍    | 1298/2404 [26:35<22:28,  1.22s/it]

https://hiring.cafe/job/555ov5z8snj2ev5z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\555ov5z8snj2ev5z.json.gz

 54%|█████▍    | 1299/2404 [26:36<22:55,  1.25s/it]

https://hiring.cafe/job/nda5pvkfj4d1etqt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nda5pvkfj4d1etqt.json.gz

 54%|█████▍    | 1300/2404 [26:37<23:13,  1.26s/it]

https://hiring.cafe/job/w3tn8txadd2hla4x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w3tn8txadd2hla4x.json.gz

 54%|█████▍    | 1301/2404 [26:38<21:51,  1.19s/it]

https://hiring.cafe/job/19w2lveu32gopfyt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\19w2lveu32gopfyt.json.gz

 54%|█████▍    | 1302/2404 [26:40<22:41,  1.24s/it]

https://hiring.cafe/job/e5ij2s9a9lzrl5m0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e5ij2s9a9lzrl5m0.json.gz

 54%|█████▍    | 1303/2404 [26:41<23:37,  1.29s/it]

https://hiring.cafe/job/jetmz9d5soljcyrc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jetmz9d5soljcyrc.json.gz

 54%|█████▍    | 1304/2404 [26:42<22:49,  1.25s/it]

https://hiring.cafe/job/32l8pwkpmdqzc8mh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\32l8pwkpmdqzc8mh.json.gz

 54%|█████▍    | 1305/2404 [26:43<22:50,  1.25s/it]

https://hiring.cafe/job/e12lzm1hujztedn2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e12lzm1hujztedn2.json.gz

 54%|█████▍    | 1306/2404 [26:45<22:51,  1.25s/it]

https://hiring.cafe/job/yhn3e4c7amyzicj2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yhn3e4c7amyzicj2.json.gz

 54%|█████▍    | 1307/2404 [26:46<22:49,  1.25s/it]

https://hiring.cafe/job/qyvou0riyqj422yz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qyvou0riyqj422yz.json.gz

 54%|█████▍    | 1308/2404 [26:47<22:46,  1.25s/it]

https://hiring.cafe/job/fqjuii7izzds2qyr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fqjuii7izzds2qyr.json.gz

 54%|█████▍    | 1309/2404 [26:48<21:35,  1.18s/it]

https://hiring.cafe/job/eo2b8tzgnpt0o16j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eo2b8tzgnpt0o16j.json.gz

 54%|█████▍    | 1310/2404 [26:50<22:51,  1.25s/it]

https://hiring.cafe/job/81o5wzvmt7thi3fy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\81o5wzvmt7thi3fy.json.gz

 55%|█████▍    | 1311/2404 [26:51<23:02,  1.26s/it]

https://hiring.cafe/job/1cm7sow95w1y1upy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1cm7sow95w1y1upy.json.gz

 55%|█████▍    | 1312/2404 [26:52<22:38,  1.24s/it]

https://hiring.cafe/job/03y2ckk1emk32yhp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\03y2ckk1emk32yhp.json.gz

 55%|█████▍    | 1313/2404 [26:53<23:12,  1.28s/it]

https://hiring.cafe/job/4ivulg2fgkd3ws3y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4ivulg2fgkd3ws3y.json.gz

 55%|█████▍    | 1314/2404 [26:55<23:02,  1.27s/it]

https://hiring.cafe/job/6qyvut7s2dtfyxee
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6qyvut7s2dtfyxee.json.gz

 55%|█████▍    | 1315/2404 [26:56<23:04,  1.27s/it]

https://hiring.cafe/job/kw04uncqr0038mmz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kw04uncqr0038mmz.json.gz

 55%|█████▍    | 1316/2404 [26:57<22:44,  1.25s/it]

https://hiring.cafe/job/pnv61oesjc6bisci
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pnv61oesjc6bisci.json.gz

 55%|█████▍    | 1317/2404 [26:58<23:01,  1.27s/it]

https://hiring.cafe/job/drz1fyowgvemvouj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\drz1fyowgvemvouj.json.gz

 55%|█████▍    | 1318/2404 [27:00<21:58,  1.21s/it]

https://hiring.cafe/job/a91yw7owh4727dte
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a91yw7owh4727dte.json.gz

 55%|█████▍    | 1319/2404 [27:01<21:47,  1.21s/it]

https://hiring.cafe/job/ifiqzdvb1b5xnuwz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ifiqzdvb1b5xnuwz.json.gz

 55%|█████▍    | 1320/2404 [27:02<20:58,  1.16s/it]

https://hiring.cafe/job/qv0tju4lslzxkn0v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qv0tju4lslzxkn0v.json.gz

 55%|█████▍    | 1321/2404 [27:03<20:32,  1.14s/it]

https://hiring.cafe/job/3vg53qdmicxdl87f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3vg53qdmicxdl87f.json.gz

 55%|█████▍    | 1322/2404 [27:04<20:50,  1.16s/it]

https://hiring.cafe/job/yki9hw1540f4yq62
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yki9hw1540f4yq62.json.gz

 55%|█████▌    | 1323/2404 [27:05<20:19,  1.13s/it]

https://hiring.cafe/job/wcmad69aaz0j5pb5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wcmad69aaz0j5pb5.json.gz

 55%|█████▌    | 1324/2404 [27:06<19:49,  1.10s/it]

https://hiring.cafe/job/8rjll6xpc9by1h2p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8rjll6xpc9by1h2p.json.gz

 55%|█████▌    | 1325/2404 [27:08<20:58,  1.17s/it]

https://hiring.cafe/job/739240je9f693p55
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\739240je9f693p55.json.gz

 55%|█████▌    | 1326/2404 [27:09<21:13,  1.18s/it]

https://hiring.cafe/job/37wxcwgxoosq5gja
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\37wxcwgxoosq5gja.json.gz

 55%|█████▌    | 1327/2404 [27:10<21:19,  1.19s/it]

https://hiring.cafe/job/lu89uce0qtfpoyse
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lu89uce0qtfpoyse.json.gz

 55%|█████▌    | 1328/2404 [27:11<20:06,  1.12s/it]

https://hiring.cafe/job/cug4voqn8wzwrok5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cug4voqn8wzwrok5.json.gz

 55%|█████▌    | 1329/2404 [27:12<19:29,  1.09s/it]

https://hiring.cafe/job/qaw3ymmvll4cw0sz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qaw3ymmvll4cw0sz.json.gz

 55%|█████▌    | 1330/2404 [27:13<20:04,  1.12s/it]

https://hiring.cafe/job/vmj7wywtdnrnihk2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vmj7wywtdnrnihk2.json.gz

 55%|█████▌    | 1331/2404 [27:14<19:01,  1.06s/it]

https://hiring.cafe/job/16r0qj0b5yeiqfco
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\16r0qj0b5yeiqfco.json.gz

 55%|█████▌    | 1332/2404 [27:15<20:23,  1.14s/it]

https://hiring.cafe/job/q3njr0rko23nnuna
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q3njr0rko23nnuna.json.gz

 55%|█████▌    | 1333/2404 [27:16<19:15,  1.08s/it]

https://hiring.cafe/job/ho4iccpu06qdovjj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ho4iccpu06qdovjj.json.gz

 55%|█████▌    | 1334/2404 [27:18<20:17,  1.14s/it]

https://hiring.cafe/job/g3j97u0vwnde9ed7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g3j97u0vwnde9ed7.json.gz

 56%|█████▌    | 1335/2404 [27:19<20:57,  1.18s/it]

https://hiring.cafe/job/ikjwpio511awsjnf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ikjwpio511awsjnf.json.gz

 56%|█████▌    | 1336/2404 [27:20<20:38,  1.16s/it]

https://hiring.cafe/job/8wo6gzf3ov6m99uy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8wo6gzf3ov6m99uy.json.gz

 56%|█████▌    | 1337/2404 [27:21<20:39,  1.16s/it]

https://hiring.cafe/job/tcd8c41kkswm9olq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tcd8c41kkswm9olq.json.gz

 56%|█████▌    | 1338/2404 [27:22<21:38,  1.22s/it]

https://hiring.cafe/job/56xvwjwzs789jc0m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\56xvwjwzs789jc0m.json.gz

 56%|█████▌    | 1339/2404 [27:24<21:54,  1.23s/it]

https://hiring.cafe/job/yh3yywimwbwlw70h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yh3yywimwbwlw70h.json.gz

 56%|█████▌    | 1340/2404 [27:25<21:17,  1.20s/it]

https://hiring.cafe/job/kozobyceq5hfepy3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kozobyceq5hfepy3.json.gz

 56%|█████▌    | 1341/2404 [27:26<21:15,  1.20s/it]

https://hiring.cafe/job/62v6atsbjpwtvjtw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\62v6atsbjpwtvjtw.json.gz

 56%|█████▌    | 1342/2404 [27:27<22:21,  1.26s/it]

https://hiring.cafe/job/vgy9vcy95s2n8mqs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vgy9vcy95s2n8mqs.json.gz

 56%|█████▌    | 1343/2404 [27:29<21:48,  1.23s/it]

https://hiring.cafe/job/9hkk23cob6altl5i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9hkk23cob6altl5i.json.gz

 56%|█████▌    | 1344/2404 [27:30<22:14,  1.26s/it]

https://hiring.cafe/job/mtisp3wumik2x1pe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mtisp3wumik2x1pe.json.gz

 56%|█████▌    | 1345/2404 [27:31<22:03,  1.25s/it]

https://hiring.cafe/job/v55o72z5jiertop9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v55o72z5jiertop9.json.gz

 56%|█████▌    | 1346/2404 [27:32<20:35,  1.17s/it]

https://hiring.cafe/job/b2mdkn52e2h41pcg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b2mdkn52e2h41pcg.json.gz

 56%|█████▌    | 1347/2404 [27:33<21:28,  1.22s/it]

https://hiring.cafe/job/ef4h3piukifeiibm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ef4h3piukifeiibm.json.gz

 56%|█████▌    | 1348/2404 [27:34<20:09,  1.15s/it]

https://hiring.cafe/job/wsw1rv8vhjvdwl7d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wsw1rv8vhjvdwl7d.json.gz

 56%|█████▌    | 1349/2404 [27:36<21:06,  1.20s/it]

https://hiring.cafe/job/hd0l4iqvbygyrbbz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hd0l4iqvbygyrbbz.json.gz

 56%|█████▌    | 1350/2404 [27:37<21:45,  1.24s/it]

https://hiring.cafe/job/s1jss4jwpj5gli51
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s1jss4jwpj5gli51.json.gz

 56%|█████▌    | 1351/2404 [27:38<20:46,  1.18s/it]

https://hiring.cafe/job/5zkw3rllf0jp24j9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5zkw3rllf0jp24j9.json.gz

 56%|█████▌    | 1352/2404 [27:40<22:22,  1.28s/it]

https://hiring.cafe/job/heobh8pazyg5slqz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\heobh8pazyg5slqz.json.gz

 56%|█████▋    | 1353/2404 [27:41<22:58,  1.31s/it]

https://hiring.cafe/job/tkghmq9vra7gbab5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tkghmq9vra7gbab5.json.gz

 56%|█████▋    | 1354/2404 [27:43<25:20,  1.45s/it]

https://hiring.cafe/job/8ihunmn1bammpvpx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8ihunmn1bammpvpx.json.gz

 56%|█████▋    | 1355/2404 [27:44<23:59,  1.37s/it]

https://hiring.cafe/job/qa16a496rlj7e3ds
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qa16a496rlj7e3ds.json.gz

 56%|█████▋    | 1356/2404 [27:45<22:49,  1.31s/it]

https://hiring.cafe/job/suznz6438vvomsn2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\suznz6438vvomsn2.json.gz

 56%|█████▋    | 1357/2404 [27:46<22:42,  1.30s/it]

https://hiring.cafe/job/s6lwvb86r41kw3ai
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s6lwvb86r41kw3ai.json.gz

 56%|█████▋    | 1358/2404 [27:48<22:52,  1.31s/it]

https://hiring.cafe/job/vltovjth7r7ha03n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vltovjth7r7ha03n.json.gz

 57%|█████▋    | 1359/2404 [27:49<23:27,  1.35s/it]

https://hiring.cafe/job/ihsmmwospiorsa53
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ihsmmwospiorsa53.json.gz

 57%|█████▋    | 1360/2404 [27:50<22:25,  1.29s/it]

https://hiring.cafe/job/azgdh43eiofs7ze3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\azgdh43eiofs7ze3.json.gz

 57%|█████▋    | 1361/2404 [27:51<21:27,  1.23s/it]

https://hiring.cafe/job/e84buafc62ecf6dx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e84buafc62ecf6dx.json.gz

 57%|█████▋    | 1362/2404 [27:53<20:37,  1.19s/it]

https://hiring.cafe/job/k03zbxkywco85odu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k03zbxkywco85odu.json.gz

 57%|█████▋    | 1363/2404 [27:54<21:27,  1.24s/it]

https://hiring.cafe/job/ff035ak5v0nzi14c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ff035ak5v0nzi14c.json.gz

 57%|█████▋    | 1364/2404 [27:55<21:06,  1.22s/it]

https://hiring.cafe/job/q11vxt05n8z9s0tv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q11vxt05n8z9s0tv.json.gz

 57%|█████▋    | 1365/2404 [27:56<21:52,  1.26s/it]

https://hiring.cafe/job/grg7h4uww8ybupxh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\grg7h4uww8ybupxh.json.gz

 57%|█████▋    | 1366/2404 [27:58<21:57,  1.27s/it]

https://hiring.cafe/job/jngpq1ifwujcf1hz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jngpq1ifwujcf1hz.json.gz

 57%|█████▋    | 1367/2404 [27:59<21:26,  1.24s/it]

https://hiring.cafe/job/5b3yewpg66ntqmo0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5b3yewpg66ntqmo0.json.gz

 57%|█████▋    | 1368/2404 [28:00<21:37,  1.25s/it]

https://hiring.cafe/job/z8wo0hbicmjnc9ix
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z8wo0hbicmjnc9ix.json.gz

 57%|█████▋    | 1369/2404 [28:02<21:58,  1.27s/it]

https://hiring.cafe/job/8c6a16odyi5zrc5o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8c6a16odyi5zrc5o.json.gz

 57%|█████▋    | 1370/2404 [28:03<22:13,  1.29s/it]

https://hiring.cafe/job/1xbxa4getf4lz901
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1xbxa4getf4lz901.json.gz

 57%|█████▋    | 1371/2404 [28:04<22:27,  1.30s/it]

https://hiring.cafe/job/i31t1d0qm5bpbjyc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i31t1d0qm5bpbjyc.json.gz

 57%|█████▋    | 1372/2404 [28:05<21:46,  1.27s/it]

https://hiring.cafe/job/cnay2uah1xvn2nrs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cnay2uah1xvn2nrs.json.gz

 57%|█████▋    | 1373/2404 [28:07<21:52,  1.27s/it]

https://hiring.cafe/job/yo7vtkj1sudf6esy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yo7vtkj1sudf6esy.json.gz

 57%|█████▋    | 1374/2404 [28:08<21:51,  1.27s/it]

https://hiring.cafe/job/bsr66radr1w6za30
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bsr66radr1w6za30.json.gz

 57%|█████▋    | 1375/2404 [28:09<21:17,  1.24s/it]

https://hiring.cafe/job/bq7i1d2uyc7xddl0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bq7i1d2uyc7xddl0.json.gz

 57%|█████▋    | 1376/2404 [28:10<21:34,  1.26s/it]

https://hiring.cafe/job/rv74tvc9nuruha19
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rv74tvc9nuruha19.json.gz

 57%|█████▋    | 1377/2404 [28:12<21:40,  1.27s/it]

https://hiring.cafe/job/olgp675a4awt6jg5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\olgp675a4awt6jg5.json.gz

 57%|█████▋    | 1378/2404 [28:13<21:28,  1.26s/it]

https://hiring.cafe/job/z077gfzlvavuqds0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z077gfzlvavuqds0.json.gz

 57%|█████▋    | 1379/2404 [28:14<20:40,  1.21s/it]

https://hiring.cafe/job/mnt3zpvy8sj5bml5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mnt3zpvy8sj5bml5.json.gz

 57%|█████▋    | 1380/2404 [28:16<22:19,  1.31s/it]

https://hiring.cafe/job/krtroh24qbpj2zll
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\krtroh24qbpj2zll.json.gz

 57%|█████▋    | 1381/2404 [28:17<22:01,  1.29s/it]

https://hiring.cafe/job/ss6qnzro4g2wiugk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ss6qnzro4g2wiugk.json.gz

 57%|█████▋    | 1382/2404 [28:18<20:57,  1.23s/it]

https://hiring.cafe/job/e46c0bhjdtrgmvdk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e46c0bhjdtrgmvdk.json.gz

 58%|█████▊    | 1383/2404 [28:19<22:05,  1.30s/it]

https://hiring.cafe/job/rijbgjmtt4yw9v0f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rijbgjmtt4yw9v0f.json.gz

 58%|█████▊    | 1384/2404 [28:21<21:55,  1.29s/it]

https://hiring.cafe/job/9chevfkn0425gr0r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9chevfkn0425gr0r.json.gz

 58%|█████▊    | 1385/2404 [28:22<21:31,  1.27s/it]

https://hiring.cafe/job/bqo5j4ealm3blw88
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bqo5j4ealm3blw88.json.gz

 58%|█████▊    | 1386/2404 [28:23<21:11,  1.25s/it]

https://hiring.cafe/job/hycptcz7x85kyhaz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hycptcz7x85kyhaz.json.gz

 58%|█████▊    | 1387/2404 [28:24<21:04,  1.24s/it]

https://hiring.cafe/job/wc2v5fse7zcmra5i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wc2v5fse7zcmra5i.json.gz

 58%|█████▊    | 1388/2404 [28:26<21:35,  1.27s/it]

https://hiring.cafe/job/d86xrs1jet3kxscb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d86xrs1jet3kxscb.json.gz

 58%|█████▊    | 1389/2404 [28:27<21:07,  1.25s/it]

https://hiring.cafe/job/fbtzzl1fa3pjkqfq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fbtzzl1fa3pjkqfq.json.gz

 58%|█████▊    | 1390/2404 [28:28<19:56,  1.18s/it]

https://hiring.cafe/job/qkjsdl7dnlprimu4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qkjsdl7dnlprimu4.json.gz

 58%|█████▊    | 1391/2404 [28:29<18:56,  1.12s/it]

https://hiring.cafe/job/09arujbnqtqimyn4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\09arujbnqtqimyn4.json.gz

 58%|█████▊    | 1392/2404 [28:30<19:33,  1.16s/it]

https://hiring.cafe/job/nluit938ijzyov4j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nluit938ijzyov4j.json.gz

 58%|█████▊    | 1393/2404 [28:31<18:22,  1.09s/it]

https://hiring.cafe/job/9puli6h65s5ursyu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9puli6h65s5ursyu.json.gz

 58%|█████▊    | 1394/2404 [28:33<20:28,  1.22s/it]

https://hiring.cafe/job/dz1956owjrkbxojf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dz1956owjrkbxojf.json.gz

 58%|█████▊    | 1395/2404 [28:34<22:32,  1.34s/it]

https://hiring.cafe/job/olh5rytatosi1kq9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\olh5rytatosi1kq9.json.gz

 58%|█████▊    | 1396/2404 [28:35<22:18,  1.33s/it]

https://hiring.cafe/job/7lb078i5rqi9jn20
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7lb078i5rqi9jn20.json.gz

 58%|█████▊    | 1397/2404 [28:37<23:12,  1.38s/it]

https://hiring.cafe/job/i0syjmag4c67iu4f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i0syjmag4c67iu4f.json.gz

 58%|█████▊    | 1398/2404 [28:38<22:50,  1.36s/it]

https://hiring.cafe/job/l74nxqvqu6m16uh6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l74nxqvqu6m16uh6.json.gz

 58%|█████▊    | 1399/2404 [28:40<23:45,  1.42s/it]

https://hiring.cafe/job/xb15uumc85kz82ss
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xb15uumc85kz82ss.json.gz

 58%|█████▊    | 1400/2404 [28:41<23:07,  1.38s/it]

https://hiring.cafe/job/uslwaqxfx32xug6l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uslwaqxfx32xug6l.json.gz

 58%|█████▊    | 1401/2404 [28:42<21:40,  1.30s/it]

https://hiring.cafe/job/hba3jgi5pkyjo5br
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hba3jgi5pkyjo5br.json.gz

 58%|█████▊    | 1402/2404 [28:43<21:25,  1.28s/it]

https://hiring.cafe/job/t40883gha10dtl71
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t40883gha10dtl71.json.gz

 58%|█████▊    | 1403/2404 [28:45<21:16,  1.27s/it]

https://hiring.cafe/job/2p0jbvngjy4n6ama
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2p0jbvngjy4n6ama.json.gz

 58%|█████▊    | 1404/2404 [28:46<20:38,  1.24s/it]

https://hiring.cafe/job/a9gl9nwfxrvkoixf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a9gl9nwfxrvkoixf.json.gz

 58%|█████▊    | 1405/2404 [28:47<20:58,  1.26s/it]

https://hiring.cafe/job/6ygmvz620kts60mj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6ygmvz620kts60mj.json.gz

 58%|█████▊    | 1406/2404 [28:48<20:38,  1.24s/it]

https://hiring.cafe/job/jtv92sjljoamdsp2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jtv92sjljoamdsp2.json.gz

 59%|█████▊    | 1407/2404 [28:50<20:58,  1.26s/it]

https://hiring.cafe/job/c0iq1n55zllyp1kk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c0iq1n55zllyp1kk.json.gz

 59%|█████▊    | 1408/2404 [28:51<21:34,  1.30s/it]

https://hiring.cafe/job/5lv5c9hn4715cupf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5lv5c9hn4715cupf.json.gz

 59%|█████▊    | 1409/2404 [28:52<20:41,  1.25s/it]

https://hiring.cafe/job/tsan5uezw49vwf9t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tsan5uezw49vwf9t.json.gz

 59%|█████▊    | 1410/2404 [28:53<20:13,  1.22s/it]

https://hiring.cafe/job/tpkh54xmln6i3542
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tpkh54xmln6i3542.json.gz

 59%|█████▊    | 1411/2404 [28:55<21:15,  1.28s/it]

https://hiring.cafe/job/a87hdl4j74jng6v4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a87hdl4j74jng6v4.json.gz

 59%|█████▊    | 1412/2404 [28:56<20:25,  1.24s/it]

https://hiring.cafe/job/xj28hl7bk8hlj6rp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xj28hl7bk8hlj6rp.json.gz

 59%|█████▉    | 1413/2404 [28:57<20:46,  1.26s/it]

https://hiring.cafe/job/4zcizzri7apqgyt5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4zcizzri7apqgyt5.json.gz

 59%|█████▉    | 1414/2404 [28:59<21:01,  1.27s/it]

https://hiring.cafe/job/3q2wisu2nq3uvot8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3q2wisu2nq3uvot8.json.gz

 59%|█████▉    | 1415/2404 [29:00<19:33,  1.19s/it]

https://hiring.cafe/job/r220x5bll453flot
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r220x5bll453flot.json.gz

 59%|█████▉    | 1416/2404 [29:01<19:35,  1.19s/it]

https://hiring.cafe/job/yiwn82qrmwytikzz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yiwn82qrmwytikzz.json.gz

 59%|█████▉    | 1417/2404 [29:02<21:22,  1.30s/it]

https://hiring.cafe/job/rlatvoz8ajttgji4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rlatvoz8ajttgji4.json.gz

 59%|█████▉    | 1418/2404 [29:03<19:56,  1.21s/it]

https://hiring.cafe/job/ojffj6ffxhq9jkhu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ojffj6ffxhq9jkhu.json.gz

 59%|█████▉    | 1419/2404 [29:04<19:19,  1.18s/it]

https://hiring.cafe/job/j4fdh6nfr67cpeqm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j4fdh6nfr67cpeqm.json.gz

 59%|█████▉    | 1420/2404 [29:06<19:37,  1.20s/it]

https://hiring.cafe/job/fyqq7qupfbcrkpsn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fyqq7qupfbcrkpsn.json.gz

 59%|█████▉    | 1421/2404 [29:07<19:25,  1.19s/it]

https://hiring.cafe/job/6746ljnsvfo53iqi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6746ljnsvfo53iqi.json.gz

 59%|█████▉    | 1422/2404 [29:08<20:05,  1.23s/it]

https://hiring.cafe/job/w0qn43hnp6cdkmeu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w0qn43hnp6cdkmeu.json.gz

 59%|█████▉    | 1423/2404 [29:09<19:50,  1.21s/it]

https://hiring.cafe/job/2fb8azcyz3p1htgp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2fb8azcyz3p1htgp.json.gz

 59%|█████▉    | 1424/2404 [29:10<19:45,  1.21s/it]

https://hiring.cafe/job/4p1en4r8gwpkk9m1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4p1en4r8gwpkk9m1.json.gz

 59%|█████▉    | 1425/2404 [29:12<19:49,  1.22s/it]

https://hiring.cafe/job/uqesmf4b74a02kcr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uqesmf4b74a02kcr.json.gz

 59%|█████▉    | 1426/2404 [29:13<19:42,  1.21s/it]

https://hiring.cafe/job/3570ohws6044dxr1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3570ohws6044dxr1.json.gz

 59%|█████▉    | 1427/2404 [29:14<18:31,  1.14s/it]

https://hiring.cafe/job/tpzv45vuorcs9naj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tpzv45vuorcs9naj.json.gz

 59%|█████▉    | 1428/2404 [29:15<20:33,  1.26s/it]

https://hiring.cafe/job/xtbxvghmyz5lrcr1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xtbxvghmyz5lrcr1.json.gz

 59%|█████▉    | 1429/2404 [29:17<20:06,  1.24s/it]

https://hiring.cafe/job/si9ycz7zrkab1hbx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\si9ycz7zrkab1hbx.json.gz

 59%|█████▉    | 1430/2404 [29:18<19:18,  1.19s/it]

https://hiring.cafe/job/c3xmkd6osnzg50ey
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c3xmkd6osnzg50ey.json.gz

 60%|█████▉    | 1431/2404 [29:19<18:27,  1.14s/it]

https://hiring.cafe/job/g564sywkkids0hpn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g564sywkkids0hpn.json.gz

 60%|█████▉    | 1432/2404 [29:20<19:11,  1.18s/it]

https://hiring.cafe/job/6kp00yxjzkqg753r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6kp00yxjzkqg753r.json.gz

 60%|█████▉    | 1433/2404 [29:21<19:52,  1.23s/it]

https://hiring.cafe/job/xcslq433pqif0ho0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xcslq433pqif0ho0.json.gz

 60%|█████▉    | 1434/2404 [29:23<19:40,  1.22s/it]

https://hiring.cafe/job/fcwgz1k2w0xsbnyv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fcwgz1k2w0xsbnyv.json.gz

 60%|█████▉    | 1435/2404 [29:24<19:25,  1.20s/it]

https://hiring.cafe/job/hfnuc164f1qfw613
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hfnuc164f1qfw613.json.gz

 60%|█████▉    | 1436/2404 [29:25<20:11,  1.25s/it]

https://hiring.cafe/job/s6hkrczabd2tljcm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s6hkrczabd2tljcm.json.gz

 60%|█████▉    | 1437/2404 [29:26<19:18,  1.20s/it]

https://hiring.cafe/job/f3gbxx9t6s2hqruu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f3gbxx9t6s2hqruu.json.gz

 60%|█████▉    | 1438/2404 [29:27<19:51,  1.23s/it]

https://hiring.cafe/job/s0io1rj6d009kgw3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s0io1rj6d009kgw3.json.gz

 60%|█████▉    | 1439/2404 [29:29<20:24,  1.27s/it]

https://hiring.cafe/job/lty5bmnfnvwwej3y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lty5bmnfnvwwej3y.json.gz

 60%|█████▉    | 1440/2404 [29:30<20:41,  1.29s/it]

https://hiring.cafe/job/824kkt0ubpouukjk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\824kkt0ubpouukjk.json.gz

 60%|█████▉    | 1441/2404 [29:31<19:12,  1.20s/it]

https://hiring.cafe/job/zu5hi34qmqj8i11n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zu5hi34qmqj8i11n.json.gz

 60%|█████▉    | 1442/2404 [29:32<19:01,  1.19s/it]

https://hiring.cafe/job/29qs1qny62r3snwx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\29qs1qny62r3snwx.json.gz

 60%|██████    | 1443/2404 [29:34<19:12,  1.20s/it]

https://hiring.cafe/job/f47js8hj9tomvltm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f47js8hj9tomvltm.json.gz

 60%|██████    | 1444/2404 [29:35<19:40,  1.23s/it]

https://hiring.cafe/job/6o817e426iw2jvyf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6o817e426iw2jvyf.json.gz

 60%|██████    | 1445/2404 [29:36<19:08,  1.20s/it]

https://hiring.cafe/job/f5be0auvuraaxvye
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f5be0auvuraaxvye.json.gz

 60%|██████    | 1446/2404 [29:37<18:33,  1.16s/it]

https://hiring.cafe/job/vucnkkvm1v1hxzs5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vucnkkvm1v1hxzs5.json.gz

 60%|██████    | 1447/2404 [29:38<18:54,  1.19s/it]

https://hiring.cafe/job/ybuozxawmdb06v9m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ybuozxawmdb06v9m.json.gz

 60%|██████    | 1448/2404 [29:39<18:53,  1.19s/it]

https://hiring.cafe/job/p4zrryvrj14xu8ln
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p4zrryvrj14xu8ln.json.gz

 60%|██████    | 1449/2404 [29:41<19:04,  1.20s/it]

https://hiring.cafe/job/1pyo33buhbx4k04e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1pyo33buhbx4k04e.json.gz

 60%|██████    | 1450/2404 [29:42<19:05,  1.20s/it]

https://hiring.cafe/job/1sbned9hl5jkpgvc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1sbned9hl5jkpgvc.json.gz

 60%|██████    | 1451/2404 [29:43<18:13,  1.15s/it]

https://hiring.cafe/job/9oimxs01om5egwne
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9oimxs01om5egwne.json.gz

 60%|██████    | 1452/2404 [29:44<18:07,  1.14s/it]

https://hiring.cafe/job/uenq4u9uyn934yep
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uenq4u9uyn934yep.json.gz

 60%|██████    | 1453/2404 [29:45<18:47,  1.19s/it]

https://hiring.cafe/job/hh5ju1h7foy5f9tf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hh5ju1h7foy5f9tf.json.gz

 60%|██████    | 1454/2404 [29:46<17:44,  1.12s/it]

https://hiring.cafe/job/9n3e48lmjpsfiusb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9n3e48lmjpsfiusb.json.gz

 61%|██████    | 1455/2404 [29:47<17:14,  1.09s/it]

https://hiring.cafe/job/xpmyw02pykcft8a5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xpmyw02pykcft8a5.json.gz

 61%|██████    | 1456/2404 [29:49<18:10,  1.15s/it]

https://hiring.cafe/job/nsdyfz98rydhyp44
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nsdyfz98rydhyp44.json.gz

 61%|██████    | 1457/2404 [29:49<17:02,  1.08s/it]

https://hiring.cafe/job/lqjk85lz0libmbwm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lqjk85lz0libmbwm.json.gz

 61%|██████    | 1458/2404 [29:51<17:55,  1.14s/it]

https://hiring.cafe/job/v7tlleci6jkvp1ga
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v7tlleci6jkvp1ga.json.gz

 61%|██████    | 1459/2404 [29:52<19:05,  1.21s/it]

https://hiring.cafe/job/ef2py36cd9jftrlz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ef2py36cd9jftrlz.json.gz

 61%|██████    | 1460/2404 [29:53<19:12,  1.22s/it]

https://hiring.cafe/job/3j0i5y0lifnwd0if
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3j0i5y0lifnwd0if.json.gz

 61%|██████    | 1461/2404 [29:54<18:09,  1.16s/it]

https://hiring.cafe/job/udwmni1x41w75039
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\udwmni1x41w75039.json.gz

 61%|██████    | 1462/2404 [29:56<18:50,  1.20s/it]

https://hiring.cafe/job/60nsk3utwfbd8w1v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\60nsk3utwfbd8w1v.json.gz

 61%|██████    | 1463/2404 [29:57<17:59,  1.15s/it]

https://hiring.cafe/job/mzqpsngilcvt6ywz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mzqpsngilcvt6ywz.json.gz

 61%|██████    | 1464/2404 [29:58<18:27,  1.18s/it]

https://hiring.cafe/job/b4asczl93l3oxmz3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b4asczl93l3oxmz3.json.gz

 61%|██████    | 1465/2404 [29:59<18:10,  1.16s/it]

https://hiring.cafe/job/nu1vrsv83yij465r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nu1vrsv83yij465r.json.gz

 61%|██████    | 1466/2404 [30:00<18:19,  1.17s/it]

https://hiring.cafe/job/lt6e7wsxttn0wybu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lt6e7wsxttn0wybu.json.gz

 61%|██████    | 1467/2404 [30:02<19:24,  1.24s/it]

https://hiring.cafe/job/ckx7a8v88f3g6pxk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ckx7a8v88f3g6pxk.json.gz

 61%|██████    | 1468/2404 [30:03<17:59,  1.15s/it]

https://hiring.cafe/job/8byncyvjn903lo5g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8byncyvjn903lo5g.json.gz

 61%|██████    | 1469/2404 [30:04<19:29,  1.25s/it]

https://hiring.cafe/job/qyy70zqxnfi43vi4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qyy70zqxnfi43vi4.json.gz

 61%|██████    | 1470/2404 [30:05<19:12,  1.23s/it]

https://hiring.cafe/job/wfiskzaecbfqv76t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wfiskzaecbfqv76t.json.gz

 61%|██████    | 1471/2404 [30:06<17:35,  1.13s/it]

https://hiring.cafe/job/6s92p19q1h27w9m4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6s92p19q1h27w9m4.json.gz

 61%|██████    | 1472/2404 [30:07<17:05,  1.10s/it]

https://hiring.cafe/job/pr1fcvx5hdtymfbh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pr1fcvx5hdtymfbh.json.gz

 61%|██████▏   | 1473/2404 [30:08<16:47,  1.08s/it]

https://hiring.cafe/job/dznfa5vi16305oxv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dznfa5vi16305oxv.json.gz

 61%|██████▏   | 1474/2404 [30:10<17:43,  1.14s/it]

https://hiring.cafe/job/37diwrqqxx9y67uh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\37diwrqqxx9y67uh.json.gz

 61%|██████▏   | 1475/2404 [30:11<18:40,  1.21s/it]

https://hiring.cafe/job/e4s7xeiz5p5ifykd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e4s7xeiz5p5ifykd.json.gz

 61%|██████▏   | 1476/2404 [30:12<18:12,  1.18s/it]

https://hiring.cafe/job/1xsty2j11lsdtfb6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1xsty2j11lsdtfb6.json.gz

 61%|██████▏   | 1477/2404 [30:13<18:37,  1.21s/it]

https://hiring.cafe/job/arl1h0qcly5y6e7s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\arl1h0qcly5y6e7s.json.gz

 61%|██████▏   | 1478/2404 [30:15<19:04,  1.24s/it]

https://hiring.cafe/job/mi6fyke71f9qwyd7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mi6fyke71f9qwyd7.json.gz

 62%|██████▏   | 1479/2404 [30:16<19:23,  1.26s/it]

https://hiring.cafe/job/41pr8hi49540fxc6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\41pr8hi49540fxc6.json.gz

 62%|██████▏   | 1480/2404 [30:17<17:50,  1.16s/it]

https://hiring.cafe/job/jehrcn4i6jcti3eg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jehrcn4i6jcti3eg.json.gz

 62%|██████▏   | 1481/2404 [30:18<18:30,  1.20s/it]

https://hiring.cafe/job/7xjnf0zd5bvx8ykx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7xjnf0zd5bvx8ykx.json.gz

 62%|██████▏   | 1482/2404 [30:19<17:17,  1.13s/it]

https://hiring.cafe/job/dr2bw6sbbnv58ajc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dr2bw6sbbnv58ajc.json.gz

 62%|██████▏   | 1483/2404 [30:20<17:50,  1.16s/it]

https://hiring.cafe/job/dredaw7o13pflu0f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dredaw7o13pflu0f.json.gz

 62%|██████▏   | 1484/2404 [30:22<18:04,  1.18s/it]

https://hiring.cafe/job/4ceozrrhkrj4sig5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4ceozrrhkrj4sig5.json.gz

 62%|██████▏   | 1485/2404 [30:23<17:31,  1.14s/it]

https://hiring.cafe/job/lfboqr0ih14j1w8q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lfboqr0ih14j1w8q.json.gz

 62%|██████▏   | 1486/2404 [30:24<18:12,  1.19s/it]

https://hiring.cafe/job/mpfftzlmubovwo36
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mpfftzlmubovwo36.json.gz

 62%|██████▏   | 1487/2404 [30:25<18:57,  1.24s/it]

https://hiring.cafe/job/5t7ycg6iqh0k9c2x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5t7ycg6iqh0k9c2x.json.gz

 62%|██████▏   | 1488/2404 [30:27<19:25,  1.27s/it]

https://hiring.cafe/job/qdpimnbdjb0uaph5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qdpimnbdjb0uaph5.json.gz

 62%|██████▏   | 1489/2404 [30:28<19:04,  1.25s/it]

https://hiring.cafe/job/1yv5a032vuiux7ua
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1yv5a032vuiux7ua.json.gz

 62%|██████▏   | 1490/2404 [30:29<19:36,  1.29s/it]

https://hiring.cafe/job/i1yntdyox5jmfziy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i1yntdyox5jmfziy.json.gz

 62%|██████▏   | 1491/2404 [30:31<20:03,  1.32s/it]

https://hiring.cafe/job/7ne35psx0z0xip9d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7ne35psx0z0xip9d.json.gz

 62%|██████▏   | 1492/2404 [30:32<20:46,  1.37s/it]

https://hiring.cafe/job/a23ta1vyas2xatmq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a23ta1vyas2xatmq.json.gz

 62%|██████▏   | 1493/2404 [30:33<19:40,  1.30s/it]

https://hiring.cafe/job/9eq3yva9ygmwan91
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9eq3yva9ygmwan91.json.gz

 62%|██████▏   | 1494/2404 [30:34<19:02,  1.25s/it]

https://hiring.cafe/job/5qtiav3udkukxj5k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5qtiav3udkukxj5k.json.gz

 62%|██████▏   | 1495/2404 [30:36<18:44,  1.24s/it]

https://hiring.cafe/job/fu92tgfw2opf6dw7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fu92tgfw2opf6dw7.json.gz

 62%|██████▏   | 1496/2404 [30:37<18:19,  1.21s/it]

https://hiring.cafe/job/1ug6bd91hmd9gzhz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1ug6bd91hmd9gzhz.json.gz

 62%|██████▏   | 1497/2404 [30:38<17:17,  1.14s/it]

https://hiring.cafe/job/ijk36tnxeol0v4q8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ijk36tnxeol0v4q8.json.gz

 62%|██████▏   | 1498/2404 [30:39<17:17,  1.14s/it]

https://hiring.cafe/job/ekpwah4vu2u2tq9k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ekpwah4vu2u2tq9k.json.gz

 62%|██████▏   | 1499/2404 [30:40<17:58,  1.19s/it]

https://hiring.cafe/job/do0z0zsc2djuu5c0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\do0z0zsc2djuu5c0.json.gz

 62%|██████▏   | 1500/2404 [30:41<17:43,  1.18s/it]

https://hiring.cafe/job/ghnvc2vvbs9bb8b8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ghnvc2vvbs9bb8b8.json.gz

 62%|██████▏   | 1501/2404 [30:42<17:22,  1.15s/it]

https://hiring.cafe/job/jvhzsfpvkih8ujzx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jvhzsfpvkih8ujzx.json.gz

 62%|██████▏   | 1502/2404 [30:44<18:08,  1.21s/it]

https://hiring.cafe/job/9t113995763yo5hg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9t113995763yo5hg.json.gz

 63%|██████▎   | 1503/2404 [30:45<18:55,  1.26s/it]

https://hiring.cafe/job/r9jpu7qnr9b4z3fz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r9jpu7qnr9b4z3fz.json.gz

 63%|██████▎   | 1504/2404 [30:46<19:05,  1.27s/it]

https://hiring.cafe/job/eho70hizumrg2sux
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eho70hizumrg2sux.json.gz

 63%|██████▎   | 1505/2404 [30:48<19:42,  1.32s/it]

https://hiring.cafe/job/vdj52i00w2rxsfpb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vdj52i00w2rxsfpb.json.gz

 63%|██████▎   | 1506/2404 [30:49<19:14,  1.29s/it]

https://hiring.cafe/job/n8drcc43bvotmxdf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n8drcc43bvotmxdf.json.gz

 63%|██████▎   | 1507/2404 [30:50<19:49,  1.33s/it]

https://hiring.cafe/job/3qzukjhls3gnfc4o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3qzukjhls3gnfc4o.json.gz

 63%|██████▎   | 1508/2404 [30:52<19:59,  1.34s/it]

https://hiring.cafe/job/8zn9mt4i93yx2vap
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8zn9mt4i93yx2vap.json.gz

 63%|██████▎   | 1509/2404 [30:53<19:13,  1.29s/it]

https://hiring.cafe/job/skf7k4jp1pmfkawc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\skf7k4jp1pmfkawc.json.gz

 63%|██████▎   | 1510/2404 [30:54<18:57,  1.27s/it]

https://hiring.cafe/job/uu11thsdw7404k1c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uu11thsdw7404k1c.json.gz

 63%|██████▎   | 1511/2404 [30:56<19:55,  1.34s/it]

https://hiring.cafe/job/l74108artg32vip4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l74108artg32vip4.json.gz

 63%|██████▎   | 1512/2404 [30:57<20:24,  1.37s/it]

https://hiring.cafe/job/ew0mfwdiqfeg44n6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ew0mfwdiqfeg44n6.json.gz

 63%|██████▎   | 1513/2404 [30:58<19:19,  1.30s/it]

https://hiring.cafe/job/a6grq2kmmiiv06lh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a6grq2kmmiiv06lh.json.gz

 63%|██████▎   | 1514/2404 [30:59<18:32,  1.25s/it]

https://hiring.cafe/job/1eryob6zwc6p5syp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1eryob6zwc6p5syp.json.gz

 63%|██████▎   | 1515/2404 [31:01<19:41,  1.33s/it]

https://hiring.cafe/job/gogyffrk6u4hmsdh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gogyffrk6u4hmsdh.json.gz

 63%|██████▎   | 1516/2404 [31:02<19:15,  1.30s/it]

https://hiring.cafe/job/tp9w3x90g9z5h54a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tp9w3x90g9z5h54a.json.gz

 63%|██████▎   | 1517/2404 [31:03<18:44,  1.27s/it]

https://hiring.cafe/job/7ze5m18rogcy99d9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7ze5m18rogcy99d9.json.gz

 63%|██████▎   | 1518/2404 [31:05<18:50,  1.28s/it]

https://hiring.cafe/job/goykmn4rjh6dln1q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\goykmn4rjh6dln1q.json.gz

 63%|██████▎   | 1519/2404 [31:06<18:37,  1.26s/it]

https://hiring.cafe/job/bglde980jipd8jl7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bglde980jipd8jl7.json.gz

 63%|██████▎   | 1520/2404 [31:07<19:03,  1.29s/it]

https://hiring.cafe/job/rgptjur9rmjkyuux
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rgptjur9rmjkyuux.json.gz

 63%|██████▎   | 1521/2404 [31:08<18:38,  1.27s/it]

https://hiring.cafe/job/tp6j6ifpgh7so3ab
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tp6j6ifpgh7so3ab.json.gz

 63%|██████▎   | 1522/2404 [31:10<19:04,  1.30s/it]

https://hiring.cafe/job/70zs2bv2uigk8s4h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\70zs2bv2uigk8s4h.json.gz

 63%|██████▎   | 1523/2404 [31:11<20:11,  1.38s/it]

https://hiring.cafe/job/wggm6v0a2hto1flc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wggm6v0a2hto1flc.json.gz

 63%|██████▎   | 1524/2404 [31:13<20:50,  1.42s/it]

https://hiring.cafe/job/1apyi3jtoq166s0k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1apyi3jtoq166s0k.json.gz

 63%|██████▎   | 1525/2404 [31:14<19:45,  1.35s/it]

https://hiring.cafe/job/bey1gm1v49l2host
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bey1gm1v49l2host.json.gz

 63%|██████▎   | 1526/2404 [31:15<19:07,  1.31s/it]

https://hiring.cafe/job/wal9c4nryu7yug0q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wal9c4nryu7yug0q.json.gz

 64%|██████▎   | 1527/2404 [31:16<18:17,  1.25s/it]

https://hiring.cafe/job/546gqleqi8okmq0t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\546gqleqi8okmq0t.json.gz

 64%|██████▎   | 1528/2404 [31:18<18:11,  1.25s/it]

https://hiring.cafe/job/y5y22lxu90ocdut1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y5y22lxu90ocdut1.json.gz

 64%|██████▎   | 1529/2404 [31:19<18:16,  1.25s/it]

https://hiring.cafe/job/bwh839e9hrbnb4im
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bwh839e9hrbnb4im.json.gz

 64%|██████▎   | 1530/2404 [31:20<18:35,  1.28s/it]

https://hiring.cafe/job/p1jq71gfahn07w4t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p1jq71gfahn07w4t.json.gz

 64%|██████▎   | 1531/2404 [31:21<17:27,  1.20s/it]

https://hiring.cafe/job/mmac2dslyvarhkum
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mmac2dslyvarhkum.json.gz

 64%|██████▎   | 1532/2404 [31:23<17:43,  1.22s/it]

https://hiring.cafe/job/glwf4h5gikb3nnp4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\glwf4h5gikb3nnp4.json.gz

 64%|██████▍   | 1533/2404 [31:24<17:42,  1.22s/it]

https://hiring.cafe/job/su7ro3nlpu8qq0hq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\su7ro3nlpu8qq0hq.json.gz

 64%|██████▍   | 1534/2404 [31:25<17:38,  1.22s/it]

https://hiring.cafe/job/r4qq2gi0sifj8snw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r4qq2gi0sifj8snw.json.gz

 64%|██████▍   | 1535/2404 [31:26<18:33,  1.28s/it]

https://hiring.cafe/job/v2laawv70z2fhgkm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v2laawv70z2fhgkm.json.gz

 64%|██████▍   | 1536/2404 [31:28<18:53,  1.31s/it]

https://hiring.cafe/job/4tces8izelaycqax
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4tces8izelaycqax.json.gz

 64%|██████▍   | 1537/2404 [31:29<18:41,  1.29s/it]

https://hiring.cafe/job/f5nefh80di44s602
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f5nefh80di44s602.json.gz

 64%|██████▍   | 1538/2404 [31:30<19:07,  1.33s/it]

https://hiring.cafe/job/7mndox0wkmgwmtey
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7mndox0wkmgwmtey.json.gz

 64%|██████▍   | 1539/2404 [31:32<18:38,  1.29s/it]

https://hiring.cafe/job/wr8bdzgq1o02szf2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wr8bdzgq1o02szf2.json.gz

 64%|██████▍   | 1540/2404 [31:33<18:14,  1.27s/it]

https://hiring.cafe/job/5vtdjudi3h6epk70
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5vtdjudi3h6epk70.json.gz

 64%|██████▍   | 1541/2404 [31:34<17:47,  1.24s/it]

https://hiring.cafe/job/bcwe4kuchhbu9pso
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bcwe4kuchhbu9pso.json.gz

 64%|██████▍   | 1542/2404 [31:35<17:56,  1.25s/it]

https://hiring.cafe/job/tns872p0w4qskl0o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tns872p0w4qskl0o.json.gz

 64%|██████▍   | 1543/2404 [31:36<16:30,  1.15s/it]

https://hiring.cafe/job/0qzmsrnn2r1b6nt9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0qzmsrnn2r1b6nt9.json.gz

 64%|██████▍   | 1544/2404 [31:37<16:13,  1.13s/it]

https://hiring.cafe/job/o0h6b4n4hcyxtwny
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o0h6b4n4hcyxtwny.json.gz

 64%|██████▍   | 1545/2404 [31:39<18:02,  1.26s/it]

https://hiring.cafe/job/0q5tcn06v9u5gp97
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0q5tcn06v9u5gp97.json.gz

 64%|██████▍   | 1546/2404 [31:40<18:12,  1.27s/it]

https://hiring.cafe/job/9o48gobbve1jcbf2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9o48gobbve1jcbf2.json.gz

 64%|██████▍   | 1547/2404 [31:41<17:39,  1.24s/it]

https://hiring.cafe/job/e8cw4lwpzz517v3v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e8cw4lwpzz517v3v.json.gz

 64%|██████▍   | 1548/2404 [31:42<16:57,  1.19s/it]

https://hiring.cafe/job/6nhl6wksuyugph2j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6nhl6wksuyugph2j.json.gz

 64%|██████▍   | 1549/2404 [31:44<16:37,  1.17s/it]

https://hiring.cafe/job/kwzsv6c3ldfsph8b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kwzsv6c3ldfsph8b.json.gz

 64%|██████▍   | 1550/2404 [31:45<15:57,  1.12s/it]

https://hiring.cafe/job/5hei1v2h4j46um40
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5hei1v2h4j46um40.json.gz

 65%|██████▍   | 1551/2404 [31:46<15:49,  1.11s/it]

https://hiring.cafe/job/pilwqbeidlcg0bq3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pilwqbeidlcg0bq3.json.gz

 65%|██████▍   | 1552/2404 [31:47<16:23,  1.15s/it]

https://hiring.cafe/job/iu1z5z8tf5spzw1u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iu1z5z8tf5spzw1u.json.gz

 65%|██████▍   | 1553/2404 [31:48<16:58,  1.20s/it]

https://hiring.cafe/job/zm1s7pacdgqgf3rg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zm1s7pacdgqgf3rg.json.gz

 65%|██████▍   | 1554/2404 [31:49<16:39,  1.18s/it]

https://hiring.cafe/job/1kc5imr2bp1b2mod
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1kc5imr2bp1b2mod.json.gz

 65%|██████▍   | 1555/2404 [31:50<15:59,  1.13s/it]

https://hiring.cafe/job/ra9n2gpasdsr2l14
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ra9n2gpasdsr2l14.json.gz

 65%|██████▍   | 1556/2404 [31:51<14:54,  1.05s/it]

https://hiring.cafe/job/oe2rjwu1zs8sjpip
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oe2rjwu1zs8sjpip.json.gz

 65%|██████▍   | 1557/2404 [31:52<15:18,  1.08s/it]

https://hiring.cafe/job/ex379zwrzu7xak6v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ex379zwrzu7xak6v.json.gz

 65%|██████▍   | 1558/2404 [31:54<16:23,  1.16s/it]

https://hiring.cafe/job/eg20scyxik12dodf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eg20scyxik12dodf.json.gz

 65%|██████▍   | 1559/2404 [31:55<16:10,  1.15s/it]

https://hiring.cafe/job/ijj3m5lzi0uksplf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ijj3m5lzi0uksplf.json.gz

 65%|██████▍   | 1560/2404 [31:56<16:15,  1.16s/it]

https://hiring.cafe/job/f4eatl65ba9vxtv5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f4eatl65ba9vxtv5.json.gz

 65%|██████▍   | 1561/2404 [31:57<16:38,  1.18s/it]

https://hiring.cafe/job/u7keddc205kzret5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u7keddc205kzret5.json.gz

 65%|██████▍   | 1562/2404 [31:59<17:16,  1.23s/it]

https://hiring.cafe/job/tvnq7m7bv0zi1agw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tvnq7m7bv0zi1agw.json.gz

 65%|██████▌   | 1563/2404 [32:00<17:14,  1.23s/it]

https://hiring.cafe/job/wwnoq6v46z9dfk44
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wwnoq6v46z9dfk44.json.gz

 65%|██████▌   | 1564/2404 [32:01<16:49,  1.20s/it]

https://hiring.cafe/job/373s2ajy0glpu61b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\373s2ajy0glpu61b.json.gz

 65%|██████▌   | 1565/2404 [32:02<16:28,  1.18s/it]

https://hiring.cafe/job/y3ft8w25wwchixkz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y3ft8w25wwchixkz.json.gz

 65%|██████▌   | 1566/2404 [32:04<17:31,  1.26s/it]

https://hiring.cafe/job/jjsq16fm6k6ia55h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jjsq16fm6k6ia55h.json.gz

 65%|██████▌   | 1567/2404 [32:05<17:12,  1.23s/it]

https://hiring.cafe/job/vh0azggp8u2mfgkd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vh0azggp8u2mfgkd.json.gz

 65%|██████▌   | 1568/2404 [32:06<17:06,  1.23s/it]

https://hiring.cafe/job/swcobrsttyrhhn80
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\swcobrsttyrhhn80.json.gz

 65%|██████▌   | 1569/2404 [32:07<16:12,  1.17s/it]

https://hiring.cafe/job/r0wsreueaj0bn4ed
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r0wsreueaj0bn4ed.json.gz

 65%|██████▌   | 1570/2404 [32:08<15:40,  1.13s/it]

https://hiring.cafe/job/s4zip9qf5gbquay8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s4zip9qf5gbquay8.json.gz

 65%|██████▌   | 1571/2404 [32:09<16:23,  1.18s/it]

https://hiring.cafe/job/dh9v9l1shmpd4g92
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dh9v9l1shmpd4g92.json.gz

 65%|██████▌   | 1572/2404 [32:10<16:16,  1.17s/it]

https://hiring.cafe/job/1dm0ly4o9y4x9pzt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1dm0ly4o9y4x9pzt.json.gz

 65%|██████▌   | 1573/2404 [32:12<16:49,  1.21s/it]

https://hiring.cafe/job/c856m8z7ctrg3lbm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c856m8z7ctrg3lbm.json.gz

 65%|██████▌   | 1574/2404 [32:13<16:22,  1.18s/it]

https://hiring.cafe/job/gfjb9i4lb6pg5lud
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gfjb9i4lb6pg5lud.json.gz

 66%|██████▌   | 1575/2404 [32:14<16:03,  1.16s/it]

https://hiring.cafe/job/mcalok1m7cupw41o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mcalok1m7cupw41o.json.gz

 66%|██████▌   | 1576/2404 [32:15<16:21,  1.19s/it]

https://hiring.cafe/job/8uhvsi76sbtjuh8i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8uhvsi76sbtjuh8i.json.gz

 66%|██████▌   | 1577/2404 [32:16<15:48,  1.15s/it]

https://hiring.cafe/job/hlzypj85huah69my
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hlzypj85huah69my.json.gz

 66%|██████▌   | 1578/2404 [32:17<15:14,  1.11s/it]

https://hiring.cafe/job/663w8pxpgre7z0yg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\663w8pxpgre7z0yg.json.gz

 66%|██████▌   | 1579/2404 [32:19<16:34,  1.21s/it]

https://hiring.cafe/job/pu8jgglpoqdn2cgq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pu8jgglpoqdn2cgq.json.gz

 66%|██████▌   | 1580/2404 [32:20<16:35,  1.21s/it]

https://hiring.cafe/job/f4rdut8kl3voz3fj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f4rdut8kl3voz3fj.json.gz

 66%|██████▌   | 1581/2404 [32:22<18:03,  1.32s/it]

https://hiring.cafe/job/pz4997sk6thdg6ry
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pz4997sk6thdg6ry.json.gz

 66%|██████▌   | 1582/2404 [32:23<17:50,  1.30s/it]

https://hiring.cafe/job/kn75oj3htxdjyclw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kn75oj3htxdjyclw.json.gz

 66%|██████▌   | 1583/2404 [32:24<17:29,  1.28s/it]

https://hiring.cafe/job/6wuh4fhgalu2tlnb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6wuh4fhgalu2tlnb.json.gz

 66%|██████▌   | 1584/2404 [32:25<16:30,  1.21s/it]

https://hiring.cafe/job/z40db0rp5wzwbjtf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z40db0rp5wzwbjtf.json.gz

 66%|██████▌   | 1585/2404 [32:26<17:10,  1.26s/it]

https://hiring.cafe/job/o2x7s2hcc0mp7nyy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o2x7s2hcc0mp7nyy.json.gz

 66%|██████▌   | 1586/2404 [32:28<16:28,  1.21s/it]

https://hiring.cafe/job/sjloxnsf7ajlvb46
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sjloxnsf7ajlvb46.json.gz

 66%|██████▌   | 1587/2404 [32:29<16:06,  1.18s/it]

https://hiring.cafe/job/w1j27d0n5xn2vzpz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w1j27d0n5xn2vzpz.json.gz

 66%|██████▌   | 1588/2404 [32:30<17:23,  1.28s/it]

https://hiring.cafe/job/fh96rpw3gjjgicha
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fh96rpw3gjjgicha.json.gz

 66%|██████▌   | 1589/2404 [32:31<16:34,  1.22s/it]

https://hiring.cafe/job/z9pef2o332xmli1h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z9pef2o332xmli1h.json.gz

 66%|██████▌   | 1590/2404 [32:32<16:09,  1.19s/it]

https://hiring.cafe/job/wu3a1zrnlzq7dead
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wu3a1zrnlzq7dead.json.gz

 66%|██████▌   | 1591/2404 [32:34<16:13,  1.20s/it]

https://hiring.cafe/job/adoyna5rua70v632
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\adoyna5rua70v632.json.gz

 66%|██████▌   | 1592/2404 [32:35<15:26,  1.14s/it]

https://hiring.cafe/job/03rdwn044swr5uy5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\03rdwn044swr5uy5.json.gz

 66%|██████▋   | 1593/2404 [32:36<17:08,  1.27s/it]

https://hiring.cafe/job/0wgntb1qstdh1uus
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0wgntb1qstdh1uus.json.gz

 66%|██████▋   | 1594/2404 [32:37<17:21,  1.29s/it]

https://hiring.cafe/job/f7qdfgd8tqpsv3hx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f7qdfgd8tqpsv3hx.json.gz

 66%|██████▋   | 1595/2404 [32:39<16:35,  1.23s/it]

https://hiring.cafe/job/n0vssi46z42doff6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n0vssi46z42doff6.json.gz

 66%|██████▋   | 1596/2404 [32:40<17:19,  1.29s/it]

https://hiring.cafe/job/p2beekqtbuc0223q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p2beekqtbuc0223q.json.gz

 66%|██████▋   | 1597/2404 [32:41<16:30,  1.23s/it]

https://hiring.cafe/job/zqvajbu21kyhibm7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zqvajbu21kyhibm7.json.gz

 66%|██████▋   | 1598/2404 [32:42<16:20,  1.22s/it]

https://hiring.cafe/job/5d50bmd2mvd63nyt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5d50bmd2mvd63nyt.json.gz

 67%|██████▋   | 1599/2404 [32:43<15:20,  1.14s/it]

https://hiring.cafe/job/ahxokeko2nm78spt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ahxokeko2nm78spt.json.gz

 67%|██████▋   | 1600/2404 [32:45<16:08,  1.21s/it]

https://hiring.cafe/job/dorzatcrn4mamt09
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dorzatcrn4mamt09.json.gz

 67%|██████▋   | 1601/2404 [32:46<15:47,  1.18s/it]

https://hiring.cafe/job/vwpdek3p5ld0wfa8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vwpdek3p5ld0wfa8.json.gz

 67%|██████▋   | 1602/2404 [32:47<15:17,  1.14s/it]

https://hiring.cafe/job/4s330oeejpms2q9d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4s330oeejpms2q9d.json.gz

 67%|██████▋   | 1603/2404 [32:48<16:20,  1.22s/it]

https://hiring.cafe/job/qxhacdqbgfudvvpg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qxhacdqbgfudvvpg.json.gz

 67%|██████▋   | 1604/2404 [32:50<17:51,  1.34s/it]

https://hiring.cafe/job/o5cj850i77np49kz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o5cj850i77np49kz.json.gz

 67%|██████▋   | 1605/2404 [32:51<18:18,  1.37s/it]

https://hiring.cafe/job/15omtpduboti0j3r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\15omtpduboti0j3r.json.gz

 67%|██████▋   | 1606/2404 [32:53<18:43,  1.41s/it]

https://hiring.cafe/job/pebugi5j2vcog0qr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pebugi5j2vcog0qr.json.gz

 67%|██████▋   | 1607/2404 [32:54<17:41,  1.33s/it]

https://hiring.cafe/job/qghdkmkgwbkz7xsf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qghdkmkgwbkz7xsf.json.gz

 67%|██████▋   | 1608/2404 [32:55<18:03,  1.36s/it]

https://hiring.cafe/job/kn3jpe755gewmuv8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kn3jpe755gewmuv8.json.gz

 67%|██████▋   | 1609/2404 [32:57<18:29,  1.40s/it]

https://hiring.cafe/job/0czn1l6kugpgehje
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0czn1l6kugpgehje.json.gz

 67%|██████▋   | 1610/2404 [32:58<19:00,  1.44s/it]

https://hiring.cafe/job/mr8uxa7mi4c14q6g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mr8uxa7mi4c14q6g.json.gz

 67%|██████▋   | 1611/2404 [32:59<16:55,  1.28s/it]

https://hiring.cafe/job/llxgmc0wvpimk9jc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\llxgmc0wvpimk9jc.json.gz

 67%|██████▋   | 1612/2404 [33:00<16:16,  1.23s/it]

https://hiring.cafe/job/kuobjbq329vkbn1d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kuobjbq329vkbn1d.json.gz

 67%|██████▋   | 1613/2404 [33:01<15:33,  1.18s/it]

https://hiring.cafe/job/tsg3o984sums41va
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tsg3o984sums41va.json.gz

 67%|██████▋   | 1614/2404 [33:03<15:26,  1.17s/it]

https://hiring.cafe/job/ay50id466u3hle0s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ay50id466u3hle0s.json.gz

 67%|██████▋   | 1615/2404 [33:04<15:00,  1.14s/it]

https://hiring.cafe/job/bze41807eq33j8hs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bze41807eq33j8hs.json.gz

 67%|██████▋   | 1616/2404 [33:05<16:03,  1.22s/it]

https://hiring.cafe/job/zjyon146voiq99qx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zjyon146voiq99qx.json.gz

 67%|██████▋   | 1617/2404 [33:06<15:22,  1.17s/it]

https://hiring.cafe/job/etjhv5terb44p6pt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\etjhv5terb44p6pt.json.gz

 67%|██████▋   | 1618/2404 [33:07<14:48,  1.13s/it]

https://hiring.cafe/job/knotn23lckolxofz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\knotn23lckolxofz.json.gz

 67%|██████▋   | 1619/2404 [33:08<14:36,  1.12s/it]

https://hiring.cafe/job/ngnxuu88lyoec5rl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ngnxuu88lyoec5rl.json.gz

 67%|██████▋   | 1620/2404 [33:10<16:16,  1.25s/it]

https://hiring.cafe/job/kv5nc1vw2an34ine
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kv5nc1vw2an34ine.json.gz

 67%|██████▋   | 1621/2404 [33:11<16:20,  1.25s/it]

https://hiring.cafe/job/s9uu2gg6j7ex2vgq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s9uu2gg6j7ex2vgq.json.gz

 67%|██████▋   | 1622/2404 [33:12<16:37,  1.28s/it]

https://hiring.cafe/job/v4uas0it1eljfr7j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v4uas0it1eljfr7j.json.gz

 68%|██████▊   | 1623/2404 [33:14<16:27,  1.26s/it]

https://hiring.cafe/job/yb2rj4cpx3bp912n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yb2rj4cpx3bp912n.json.gz

 68%|██████▊   | 1624/2404 [33:15<15:45,  1.21s/it]

https://hiring.cafe/job/jf09y09s0dl601p5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jf09y09s0dl601p5.json.gz

 68%|██████▊   | 1625/2404 [33:16<16:18,  1.26s/it]

https://hiring.cafe/job/glkarwahz898grvp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\glkarwahz898grvp.json.gz

 68%|██████▊   | 1626/2404 [33:17<15:49,  1.22s/it]

https://hiring.cafe/job/oen8ky9t7l412zi7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oen8ky9t7l412zi7.json.gz

 68%|██████▊   | 1627/2404 [33:18<15:27,  1.19s/it]

https://hiring.cafe/job/f1im41xuoxy1ofo5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f1im41xuoxy1ofo5.json.gz

 68%|██████▊   | 1628/2404 [33:19<15:11,  1.17s/it]

https://hiring.cafe/job/qafiy2yxxhniz8gt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qafiy2yxxhniz8gt.json.gz

 68%|██████▊   | 1629/2404 [33:21<16:01,  1.24s/it]

https://hiring.cafe/job/uf1xx2l0epl7wkb5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uf1xx2l0epl7wkb5.json.gz

 68%|██████▊   | 1630/2404 [33:22<14:36,  1.13s/it]

https://hiring.cafe/job/opyybpfuqitrq29r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\opyybpfuqitrq29r.json.gz

 68%|██████▊   | 1631/2404 [33:23<14:56,  1.16s/it]

https://hiring.cafe/job/g3m2a071y9ylvxre
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g3m2a071y9ylvxre.json.gz

 68%|██████▊   | 1632/2404 [33:24<15:04,  1.17s/it]

https://hiring.cafe/job/4l65hkapac4rw7y3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4l65hkapac4rw7y3.json.gz

 68%|██████▊   | 1633/2404 [33:25<15:30,  1.21s/it]

https://hiring.cafe/job/bz4pwo8m3s8vpqh6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bz4pwo8m3s8vpqh6.json.gz

 68%|██████▊   | 1634/2404 [33:27<17:00,  1.33s/it]

https://hiring.cafe/job/gi0gnhygvl6dvwzs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gi0gnhygvl6dvwzs.json.gz

 68%|██████▊   | 1635/2404 [33:28<16:33,  1.29s/it]

https://hiring.cafe/job/chziok2swvx1w3xp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\chziok2swvx1w3xp.json.gz

 68%|██████▊   | 1636/2404 [33:29<15:42,  1.23s/it]

https://hiring.cafe/job/54peby2t5cxblz53
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\54peby2t5cxblz53.json.gz

 68%|██████▊   | 1637/2404 [33:30<15:06,  1.18s/it]

https://hiring.cafe/job/veijqanryqbqqw42
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\veijqanryqbqqw42.json.gz

 68%|██████▊   | 1638/2404 [33:32<15:05,  1.18s/it]

https://hiring.cafe/job/i0drzdivz0xmayfc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i0drzdivz0xmayfc.json.gz

 68%|██████▊   | 1639/2404 [33:33<15:15,  1.20s/it]

https://hiring.cafe/job/gy2pnklpx0d4bchb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gy2pnklpx0d4bchb.json.gz

 68%|██████▊   | 1640/2404 [33:34<14:44,  1.16s/it]

https://hiring.cafe/job/xzmy7vwk2gxtakc9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xzmy7vwk2gxtakc9.json.gz

 68%|██████▊   | 1641/2404 [33:35<14:58,  1.18s/it]

https://hiring.cafe/job/x9i051ih0fpauco9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x9i051ih0fpauco9.json.gz

 68%|██████▊   | 1642/2404 [33:36<14:21,  1.13s/it]

https://hiring.cafe/job/pixvutma01wygkf4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pixvutma01wygkf4.json.gz

 68%|██████▊   | 1643/2404 [33:37<14:44,  1.16s/it]

https://hiring.cafe/job/5vq0j5femv9fircv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5vq0j5femv9fircv.json.gz

 68%|██████▊   | 1644/2404 [33:39<14:45,  1.17s/it]

https://hiring.cafe/job/vndhqz8mbx4f7eel
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vndhqz8mbx4f7eel.json.gz

 68%|██████▊   | 1645/2404 [33:40<15:25,  1.22s/it]

https://hiring.cafe/job/5o3xz0sp6bgfutl6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5o3xz0sp6bgfutl6.json.gz

 68%|██████▊   | 1646/2404 [33:41<15:37,  1.24s/it]

https://hiring.cafe/job/sp39eee9gxf6c7qi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sp39eee9gxf6c7qi.json.gz

 69%|██████▊   | 1647/2404 [33:42<14:39,  1.16s/it]

https://hiring.cafe/job/liqnc4td5qphtfq5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\liqnc4td5qphtfq5.json.gz

 69%|██████▊   | 1648/2404 [33:43<14:20,  1.14s/it]

https://hiring.cafe/job/7x3vpf8zmo2nkj2j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7x3vpf8zmo2nkj2j.json.gz

 69%|██████▊   | 1649/2404 [33:44<14:30,  1.15s/it]

https://hiring.cafe/job/65karj5ww9vtpeja
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\65karj5ww9vtpeja.json.gz

 69%|██████▊   | 1650/2404 [33:46<15:15,  1.21s/it]

https://hiring.cafe/job/rn56eud0zclyw6sb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rn56eud0zclyw6sb.json.gz

 69%|██████▊   | 1651/2404 [33:47<15:06,  1.20s/it]

https://hiring.cafe/job/ewkfxr575kty7rs2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ewkfxr575kty7rs2.json.gz

 69%|██████▊   | 1652/2404 [33:48<14:14,  1.14s/it]

https://hiring.cafe/job/uzr5b535zl26pvp8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uzr5b535zl26pvp8.json.gz

 69%|██████▉   | 1653/2404 [33:49<13:57,  1.11s/it]

https://hiring.cafe/job/a5tx6cs7mqycf5pp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a5tx6cs7mqycf5pp.json.gz

 69%|██████▉   | 1654/2404 [33:50<14:28,  1.16s/it]

https://hiring.cafe/job/l8ke1rgb3mshvas3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l8ke1rgb3mshvas3.json.gz

 69%|██████▉   | 1655/2404 [33:52<15:17,  1.23s/it]

https://hiring.cafe/job/5y3aayeo2rvtg9hm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5y3aayeo2rvtg9hm.json.gz

 69%|██████▉   | 1656/2404 [33:53<14:55,  1.20s/it]

https://hiring.cafe/job/kct21rpul862vno1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kct21rpul862vno1.json.gz

 69%|██████▉   | 1657/2404 [33:54<15:28,  1.24s/it]

https://hiring.cafe/job/gdigsc1liv3xuxvy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gdigsc1liv3xuxvy.json.gz

 69%|██████▉   | 1658/2404 [33:55<15:25,  1.24s/it]

https://hiring.cafe/job/75c2824i6kcy57ml
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\75c2824i6kcy57ml.json.gz

 69%|██████▉   | 1659/2404 [33:57<15:10,  1.22s/it]

https://hiring.cafe/job/mhmoghcor4adki17
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mhmoghcor4adki17.json.gz

 69%|██████▉   | 1660/2404 [33:58<15:39,  1.26s/it]

https://hiring.cafe/job/d35h6sn69qvbfgkg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d35h6sn69qvbfgkg.json.gz

 69%|██████▉   | 1661/2404 [33:59<15:38,  1.26s/it]

https://hiring.cafe/job/ukbrrr4oky9r8g39
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ukbrrr4oky9r8g39.json.gz

 69%|██████▉   | 1662/2404 [34:00<15:09,  1.23s/it]

https://hiring.cafe/job/di3jeg8s6c7vrcun
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\di3jeg8s6c7vrcun.json.gz

 69%|██████▉   | 1663/2404 [34:01<14:27,  1.17s/it]

https://hiring.cafe/job/qi32z5hxgboa23c5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qi32z5hxgboa23c5.json.gz

 69%|██████▉   | 1664/2404 [34:03<15:08,  1.23s/it]

https://hiring.cafe/job/49djnkvculi99hxk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\49djnkvculi99hxk.json.gz

 69%|██████▉   | 1665/2404 [34:04<15:17,  1.24s/it]

https://hiring.cafe/job/7xk5reg85lk880ot
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7xk5reg85lk880ot.json.gz

 69%|██████▉   | 1666/2404 [34:05<15:22,  1.25s/it]

https://hiring.cafe/job/6gqz1mdw7e4wm2er
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6gqz1mdw7e4wm2er.json.gz

 69%|██████▉   | 1667/2404 [34:07<16:12,  1.32s/it]

https://hiring.cafe/job/ze89zj0t6jxdl18z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ze89zj0t6jxdl18z.json.gz

 69%|██████▉   | 1668/2404 [34:08<16:18,  1.33s/it]

https://hiring.cafe/job/40ngvshmzwspnrx1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\40ngvshmzwspnrx1.json.gz

 69%|██████▉   | 1669/2404 [34:09<15:44,  1.28s/it]

https://hiring.cafe/job/towtdmqtgdlx5g2r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\towtdmqtgdlx5g2r.json.gz

 69%|██████▉   | 1670/2404 [34:10<15:30,  1.27s/it]

https://hiring.cafe/job/ud4ye0084lhoz5a4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ud4ye0084lhoz5a4.json.gz

 70%|██████▉   | 1671/2404 [34:12<14:57,  1.22s/it]

https://hiring.cafe/job/rbjkgkeizxhmyy9e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rbjkgkeizxhmyy9e.json.gz

 70%|██████▉   | 1672/2404 [34:13<15:53,  1.30s/it]

https://hiring.cafe/job/vlekk2151y9pjux3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vlekk2151y9pjux3.json.gz

 70%|██████▉   | 1673/2404 [34:14<15:34,  1.28s/it]

https://hiring.cafe/job/3y67sxm3mld81k25
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3y67sxm3mld81k25.json.gz

 70%|██████▉   | 1674/2404 [34:16<15:21,  1.26s/it]

https://hiring.cafe/job/5bl1qgi2vxasukva
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5bl1qgi2vxasukva.json.gz

 70%|██████▉   | 1675/2404 [34:17<15:18,  1.26s/it]

https://hiring.cafe/job/et5o1bkflefjn04m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\et5o1bkflefjn04m.json.gz

 70%|██████▉   | 1676/2404 [34:18<15:33,  1.28s/it]

https://hiring.cafe/job/x1axrkrcqmqmjg17
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x1axrkrcqmqmjg17.json.gz

 70%|██████▉   | 1677/2404 [34:19<15:33,  1.28s/it]

https://hiring.cafe/job/v3tr11lpezndjno4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v3tr11lpezndjno4.json.gz

 70%|██████▉   | 1678/2404 [34:21<14:54,  1.23s/it]

https://hiring.cafe/job/5of5d8ni54r2ftu6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5of5d8ni54r2ftu6.json.gz

 70%|██████▉   | 1679/2404 [34:22<15:17,  1.27s/it]

https://hiring.cafe/job/3q6bysiasfcmdntm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3q6bysiasfcmdntm.json.gz

 70%|██████▉   | 1680/2404 [34:23<14:05,  1.17s/it]

https://hiring.cafe/job/a15qxl4bzu9exbh0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a15qxl4bzu9exbh0.json.gz

 70%|██████▉   | 1681/2404 [34:24<15:22,  1.28s/it]

https://hiring.cafe/job/0ooavib18aqfq2hn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ooavib18aqfq2hn.json.gz

 70%|██████▉   | 1682/2404 [34:26<15:03,  1.25s/it]

https://hiring.cafe/job/gu0skxs5mo9k9mbn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gu0skxs5mo9k9mbn.json.gz

 70%|███████   | 1683/2404 [34:27<14:46,  1.23s/it]

https://hiring.cafe/job/7y7bko9rd9mynazf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7y7bko9rd9mynazf.json.gz

 70%|███████   | 1684/2404 [34:28<13:41,  1.14s/it]

https://hiring.cafe/job/koj5pmrb4n4adxwh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\koj5pmrb4n4adxwh.json.gz

 70%|███████   | 1685/2404 [34:29<13:27,  1.12s/it]

https://hiring.cafe/job/5ld1gara57q1le1c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ld1gara57q1le1c.json.gz

 70%|███████   | 1686/2404 [34:30<13:24,  1.12s/it]

https://hiring.cafe/job/niwokrt4pbdfogfu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\niwokrt4pbdfogfu.json.gz

 70%|███████   | 1687/2404 [34:31<14:17,  1.20s/it]

https://hiring.cafe/job/otxt2rjdqcv214ow
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\otxt2rjdqcv214ow.json.gz

 70%|███████   | 1688/2404 [34:32<14:32,  1.22s/it]

https://hiring.cafe/job/kp4tgi0xdsgtbxmu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kp4tgi0xdsgtbxmu.json.gz

 70%|███████   | 1689/2404 [34:34<14:17,  1.20s/it]

https://hiring.cafe/job/oxfsfasazoc4aw17
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oxfsfasazoc4aw17.json.gz

 70%|███████   | 1690/2404 [34:35<13:56,  1.17s/it]

https://hiring.cafe/job/xg9dkdy96d2gmvd9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xg9dkdy96d2gmvd9.json.gz

 70%|███████   | 1691/2404 [34:36<14:00,  1.18s/it]

https://hiring.cafe/job/kjwu50wdy4qurb0m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kjwu50wdy4qurb0m.json.gz

 70%|███████   | 1692/2404 [34:37<14:07,  1.19s/it]

https://hiring.cafe/job/lbqc7hgfnai3w771
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lbqc7hgfnai3w771.json.gz

 70%|███████   | 1693/2404 [34:38<14:15,  1.20s/it]

https://hiring.cafe/job/pyibgi7xdqnf10d6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pyibgi7xdqnf10d6.json.gz

 70%|███████   | 1694/2404 [34:40<14:34,  1.23s/it]

https://hiring.cafe/job/sb39u512mb07hk9j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sb39u512mb07hk9j.json.gz

 71%|███████   | 1695/2404 [34:41<14:00,  1.19s/it]

https://hiring.cafe/job/dgst6wf4146t35l0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dgst6wf4146t35l0.json.gz

 71%|███████   | 1696/2404 [34:42<13:56,  1.18s/it]

https://hiring.cafe/job/egzi4c99pumbjcdi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\egzi4c99pumbjcdi.json.gz

 71%|███████   | 1697/2404 [34:43<14:03,  1.19s/it]

https://hiring.cafe/job/qsgfowmsau84rsry
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qsgfowmsau84rsry.json.gz

 71%|███████   | 1698/2404 [34:44<13:04,  1.11s/it]

https://hiring.cafe/job/gcm0r7p1pbblvsx6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gcm0r7p1pbblvsx6.json.gz

 71%|███████   | 1699/2404 [34:46<14:52,  1.27s/it]

https://hiring.cafe/job/gow8ysc2oae7l745
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gow8ysc2oae7l745.json.gz

 71%|███████   | 1700/2404 [34:47<14:26,  1.23s/it]

https://hiring.cafe/job/u1qe8iz54xck4b5y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u1qe8iz54xck4b5y.json.gz

 71%|███████   | 1701/2404 [34:48<15:07,  1.29s/it]

https://hiring.cafe/job/zl3htlflelzqqsot
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zl3htlflelzqqsot.json.gz

 71%|███████   | 1702/2404 [34:50<15:05,  1.29s/it]

https://hiring.cafe/job/0e7baligk6hdxb0p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0e7baligk6hdxb0p.json.gz

 71%|███████   | 1703/2404 [34:51<14:37,  1.25s/it]

https://hiring.cafe/job/uxqe26qa89436iaj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uxqe26qa89436iaj.json.gz

 71%|███████   | 1704/2404 [34:52<13:47,  1.18s/it]

https://hiring.cafe/job/rfzcd69jj1qpdwkz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rfzcd69jj1qpdwkz.json.gz

 71%|███████   | 1705/2404 [34:53<13:52,  1.19s/it]

https://hiring.cafe/job/25ppr00ayot57kam
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\25ppr00ayot57kam.json.gz

 71%|███████   | 1706/2404 [34:54<13:45,  1.18s/it]

https://hiring.cafe/job/hssafxx692ayhtsn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hssafxx692ayhtsn.json.gz

 71%|███████   | 1707/2404 [34:55<14:01,  1.21s/it]

https://hiring.cafe/job/m3x1bcxmeljfcck9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m3x1bcxmeljfcck9.json.gz

 71%|███████   | 1708/2404 [34:57<13:53,  1.20s/it]

https://hiring.cafe/job/ch9vi3it5jgmuyv4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ch9vi3it5jgmuyv4.json.gz

 71%|███████   | 1709/2404 [34:58<15:04,  1.30s/it]

https://hiring.cafe/job/mzu5bekwj4paid2x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mzu5bekwj4paid2x.json.gz

 71%|███████   | 1710/2404 [34:59<14:24,  1.25s/it]

https://hiring.cafe/job/v376k2czkbea747t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v376k2czkbea747t.json.gz

 71%|███████   | 1711/2404 [35:01<15:12,  1.32s/it]

https://hiring.cafe/job/sg84nwo0r9dij6w0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sg84nwo0r9dij6w0.json.gz

 71%|███████   | 1712/2404 [35:02<15:04,  1.31s/it]

https://hiring.cafe/job/3qzsrq6o3a6fei77
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3qzsrq6o3a6fei77.json.gz

 71%|███████▏  | 1713/2404 [35:03<13:50,  1.20s/it]

https://hiring.cafe/job/vvyxd6530j8jrjmc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vvyxd6530j8jrjmc.json.gz

 71%|███████▏  | 1714/2404 [35:04<13:49,  1.20s/it]

https://hiring.cafe/job/7lcrdq2yzn3e7m4k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7lcrdq2yzn3e7m4k.json.gz

 71%|███████▏  | 1715/2404 [35:05<12:59,  1.13s/it]

https://hiring.cafe/job/3fe2jjip0s9fo7e0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3fe2jjip0s9fo7e0.json.gz

 71%|███████▏  | 1716/2404 [35:07<14:40,  1.28s/it]

https://hiring.cafe/job/xh3y4u2nwdy7hc4k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xh3y4u2nwdy7hc4k.json.gz

 71%|███████▏  | 1717/2404 [35:08<14:34,  1.27s/it]

https://hiring.cafe/job/wrpwt3yzi9lgh2mf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wrpwt3yzi9lgh2mf.json.gz

 71%|███████▏  | 1718/2404 [35:09<14:13,  1.24s/it]

https://hiring.cafe/job/wa41qash9xwarhq4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wa41qash9xwarhq4.json.gz

 72%|███████▏  | 1719/2404 [35:10<13:50,  1.21s/it]

https://hiring.cafe/job/9qcrkg9mbmlbfhas
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9qcrkg9mbmlbfhas.json.gz

 72%|███████▏  | 1720/2404 [35:12<14:14,  1.25s/it]

https://hiring.cafe/job/3nf7wo8hdzptnovl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3nf7wo8hdzptnovl.json.gz

 72%|███████▏  | 1721/2404 [35:13<13:15,  1.17s/it]

https://hiring.cafe/job/gks3d40czzrexk2b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gks3d40czzrexk2b.json.gz

 72%|███████▏  | 1722/2404 [35:14<12:54,  1.14s/it]

https://hiring.cafe/job/0gpgtl9domuw2i0x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0gpgtl9domuw2i0x.json.gz

 72%|███████▏  | 1723/2404 [35:15<12:44,  1.12s/it]

https://hiring.cafe/job/h9zewfylgfzxa733
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h9zewfylgfzxa733.json.gz

 72%|███████▏  | 1724/2404 [35:16<12:16,  1.08s/it]

https://hiring.cafe/job/k4bdxoecd52qr6xt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k4bdxoecd52qr6xt.json.gz

 72%|███████▏  | 1725/2404 [35:17<13:14,  1.17s/it]

https://hiring.cafe/job/ztw1ok9rxu4l6n22
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ztw1ok9rxu4l6n22.json.gz

 72%|███████▏  | 1726/2404 [35:18<13:40,  1.21s/it]

https://hiring.cafe/job/ip131ytrczih1477
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ip131ytrczih1477.json.gz

 72%|███████▏  | 1727/2404 [35:20<13:37,  1.21s/it]

https://hiring.cafe/job/poj4spcrfhg2a0nv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\poj4spcrfhg2a0nv.json.gz

 72%|███████▏  | 1728/2404 [35:21<13:35,  1.21s/it]

https://hiring.cafe/job/xuqcwnr7omgoiy4t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xuqcwnr7omgoiy4t.json.gz

 72%|███████▏  | 1729/2404 [35:22<13:49,  1.23s/it]

https://hiring.cafe/job/jca0eukyln2qkhtg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jca0eukyln2qkhtg.json.gz

 72%|███████▏  | 1730/2404 [35:23<13:20,  1.19s/it]

https://hiring.cafe/job/kocza1ppu0xtvemd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kocza1ppu0xtvemd.json.gz

 72%|███████▏  | 1731/2404 [35:25<13:56,  1.24s/it]

https://hiring.cafe/job/1j89adw5uhd7j65l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1j89adw5uhd7j65l.json.gz

 72%|███████▏  | 1732/2404 [35:26<13:45,  1.23s/it]

https://hiring.cafe/job/w7czbremzgcz5lbp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w7czbremzgcz5lbp.json.gz

 72%|███████▏  | 1733/2404 [35:27<14:28,  1.29s/it]

https://hiring.cafe/job/q3ep6ac5bhsl6us3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q3ep6ac5bhsl6us3.json.gz

 72%|███████▏  | 1734/2404 [35:28<14:14,  1.28s/it]

https://hiring.cafe/job/di4o25a9yz5yw22v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\di4o25a9yz5yw22v.json.gz

 72%|███████▏  | 1735/2404 [35:30<14:07,  1.27s/it]

https://hiring.cafe/job/fthdyzqnkpp05h33
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fthdyzqnkpp05h33.json.gz

 72%|███████▏  | 1736/2404 [35:31<14:11,  1.27s/it]

https://hiring.cafe/job/ubu1gwkkojm9xoos
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ubu1gwkkojm9xoos.json.gz

 72%|███████▏  | 1737/2404 [35:32<13:54,  1.25s/it]

https://hiring.cafe/job/8w43ggy3u6lnr7i7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8w43ggy3u6lnr7i7.json.gz

 72%|███████▏  | 1738/2404 [35:34<14:01,  1.26s/it]

https://hiring.cafe/job/dborcr3a7h28i0tn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dborcr3a7h28i0tn.json.gz

 72%|███████▏  | 1739/2404 [35:35<14:19,  1.29s/it]

https://hiring.cafe/job/rqwd26i1qhn4b9jz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rqwd26i1qhn4b9jz.json.gz

 72%|███████▏  | 1740/2404 [35:36<14:07,  1.28s/it]

https://hiring.cafe/job/hyg49m51n8iywh0f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hyg49m51n8iywh0f.json.gz

 72%|███████▏  | 1741/2404 [35:37<13:44,  1.24s/it]

https://hiring.cafe/job/bqmhzgp9s98211hs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bqmhzgp9s98211hs.json.gz

 72%|███████▏  | 1742/2404 [35:39<14:07,  1.28s/it]

https://hiring.cafe/job/kgi003k6gbbzspl4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kgi003k6gbbzspl4.json.gz

 73%|███████▎  | 1743/2404 [35:40<13:57,  1.27s/it]

https://hiring.cafe/job/o263u3sqvt7fc6lo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o263u3sqvt7fc6lo.json.gz

 73%|███████▎  | 1744/2404 [35:41<14:06,  1.28s/it]

https://hiring.cafe/job/oy6k5l4czwolfkqw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oy6k5l4czwolfkqw.json.gz

 73%|███████▎  | 1745/2404 [35:42<13:47,  1.26s/it]

https://hiring.cafe/job/1lmdm9vawaol2yl7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1lmdm9vawaol2yl7.json.gz

 73%|███████▎  | 1746/2404 [35:44<13:28,  1.23s/it]

https://hiring.cafe/job/mtlx75arddedwsqp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mtlx75arddedwsqp.json.gz

 73%|███████▎  | 1747/2404 [35:45<13:04,  1.19s/it]

https://hiring.cafe/job/95f81xypehed6hgy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\95f81xypehed6hgy.json.gz

 73%|███████▎  | 1748/2404 [35:46<14:08,  1.29s/it]

https://hiring.cafe/job/luhs25qzf2sdgkb4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\luhs25qzf2sdgkb4.json.gz

 73%|███████▎  | 1749/2404 [35:47<13:03,  1.20s/it]

https://hiring.cafe/job/4qnuv4s1hz16888b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4qnuv4s1hz16888b.json.gz

 73%|███████▎  | 1750/2404 [35:49<13:51,  1.27s/it]

https://hiring.cafe/job/27z187gn9r2v8oel
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\27z187gn9r2v8oel.json.gz

 73%|███████▎  | 1751/2404 [35:50<14:17,  1.31s/it]

https://hiring.cafe/job/rrvp99uulus44dj8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rrvp99uulus44dj8.json.gz

 73%|███████▎  | 1752/2404 [35:51<13:57,  1.28s/it]

https://hiring.cafe/job/3oie5d7xskffylj2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3oie5d7xskffylj2.json.gz

 73%|███████▎  | 1753/2404 [35:52<13:49,  1.27s/it]

https://hiring.cafe/job/svnfk9ix9gh8pl21
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\svnfk9ix9gh8pl21.json.gz

 73%|███████▎  | 1754/2404 [35:54<14:25,  1.33s/it]

https://hiring.cafe/job/l5h0nqcqlgrdf093
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l5h0nqcqlgrdf093.json.gz

 73%|███████▎  | 1755/2404 [35:55<14:13,  1.31s/it]

https://hiring.cafe/job/vw63mdyjghx6iw9x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vw63mdyjghx6iw9x.json.gz

 73%|███████▎  | 1756/2404 [35:56<13:33,  1.26s/it]

https://hiring.cafe/job/f77hhu2r6nn0u5u9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f77hhu2r6nn0u5u9.json.gz

 73%|███████▎  | 1757/2404 [35:58<13:15,  1.23s/it]

https://hiring.cafe/job/xl6srmn4nphjwy7f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xl6srmn4nphjwy7f.json.gz

 73%|███████▎  | 1758/2404 [35:59<13:20,  1.24s/it]

https://hiring.cafe/job/yg5hs5mcnjsiihnf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yg5hs5mcnjsiihnf.json.gz

 73%|███████▎  | 1759/2404 [36:00<13:11,  1.23s/it]

https://hiring.cafe/job/o6aa9lhzlmdsj8em
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o6aa9lhzlmdsj8em.json.gz

 73%|███████▎  | 1760/2404 [36:01<13:40,  1.27s/it]

https://hiring.cafe/job/sgb926hdju16dkmn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sgb926hdju16dkmn.json.gz

 73%|███████▎  | 1761/2404 [36:02<12:43,  1.19s/it]

https://hiring.cafe/job/u8q71alzytkp8i5v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u8q71alzytkp8i5v.json.gz

 73%|███████▎  | 1762/2404 [36:04<13:26,  1.26s/it]

https://hiring.cafe/job/xd50j9yblutroa6u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xd50j9yblutroa6u.json.gz

 73%|███████▎  | 1763/2404 [36:05<12:57,  1.21s/it]

https://hiring.cafe/job/bs1ttos8zk2mtfnk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bs1ttos8zk2mtfnk.json.gz

 73%|███████▎  | 1764/2404 [36:06<12:26,  1.17s/it]

https://hiring.cafe/job/nvutotylvzicfvma
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nvutotylvzicfvma.json.gz

 73%|███████▎  | 1765/2404 [36:07<12:38,  1.19s/it]

https://hiring.cafe/job/xdfy8rqirwruerqe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xdfy8rqirwruerqe.json.gz

 73%|███████▎  | 1766/2404 [36:08<12:35,  1.18s/it]

https://hiring.cafe/job/paqhf0tqd26828zb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\paqhf0tqd26828zb.json.gz

 74%|███████▎  | 1767/2404 [36:09<11:47,  1.11s/it]

https://hiring.cafe/job/69tci1k37r49y0jb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\69tci1k37r49y0jb.json.gz

 74%|███████▎  | 1768/2404 [36:11<12:46,  1.21s/it]

https://hiring.cafe/job/y39gr4zbbh0h88kj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y39gr4zbbh0h88kj.json.gz

 74%|███████▎  | 1769/2404 [36:12<12:34,  1.19s/it]

https://hiring.cafe/job/gm1kyuao1eu452ki
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gm1kyuao1eu452ki.json.gz

 74%|███████▎  | 1770/2404 [36:13<12:09,  1.15s/it]

https://hiring.cafe/job/iqn9qncz2z7c65dz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iqn9qncz2z7c65dz.json.gz

 74%|███████▎  | 1771/2404 [36:14<12:57,  1.23s/it]

https://hiring.cafe/job/oc18a9r3zmu47axp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oc18a9r3zmu47axp.json.gz

 74%|███████▎  | 1772/2404 [36:15<12:11,  1.16s/it]

https://hiring.cafe/job/0jl5coqhcktjj7jk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0jl5coqhcktjj7jk.json.gz

 74%|███████▍  | 1773/2404 [36:17<12:23,  1.18s/it]

https://hiring.cafe/job/gjw6dxjt89fekzja
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gjw6dxjt89fekzja.json.gz

 74%|███████▍  | 1774/2404 [36:18<12:40,  1.21s/it]

https://hiring.cafe/job/huds7bkh4fkmw3l9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\huds7bkh4fkmw3l9.json.gz

 74%|███████▍  | 1775/2404 [36:19<12:34,  1.20s/it]

https://hiring.cafe/job/tt0vxlf45ilwkqhn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tt0vxlf45ilwkqhn.json.gz

 74%|███████▍  | 1776/2404 [36:20<11:56,  1.14s/it]

https://hiring.cafe/job/x5svx7ks6iq7lp6z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x5svx7ks6iq7lp6z.json.gz

 74%|███████▍  | 1777/2404 [36:21<11:54,  1.14s/it]

https://hiring.cafe/job/c9pbu726x7fqhnf5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c9pbu726x7fqhnf5.json.gz

 74%|███████▍  | 1778/2404 [36:22<11:25,  1.10s/it]

https://hiring.cafe/job/vdfifkle0n92osua
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vdfifkle0n92osua.json.gz

 74%|███████▍  | 1779/2404 [36:24<12:38,  1.21s/it]

https://hiring.cafe/job/gn7xyeorhoe9d4ai
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gn7xyeorhoe9d4ai.json.gz

 74%|███████▍  | 1780/2404 [36:25<13:32,  1.30s/it]

https://hiring.cafe/job/6dl8xfhr9ebyyrh7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6dl8xfhr9ebyyrh7.json.gz

 74%|███████▍  | 1781/2404 [36:26<13:29,  1.30s/it]

https://hiring.cafe/job/pv3gohuj0ztshrlb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pv3gohuj0ztshrlb.json.gz

 74%|███████▍  | 1782/2404 [36:28<13:03,  1.26s/it]

https://hiring.cafe/job/8fm9qtztp1atocmq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8fm9qtztp1atocmq.json.gz

 74%|███████▍  | 1783/2404 [36:29<12:48,  1.24s/it]

https://hiring.cafe/job/t69d0cuvo2w96sx4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t69d0cuvo2w96sx4.json.gz

 74%|███████▍  | 1784/2404 [36:30<13:29,  1.31s/it]

https://hiring.cafe/job/42kgzuli3mri60j4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\42kgzuli3mri60j4.json.gz

 74%|███████▍  | 1785/2404 [36:32<13:36,  1.32s/it]

https://hiring.cafe/job/msflb6v2k4bm9b14
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\msflb6v2k4bm9b14.json.gz

 74%|███████▍  | 1786/2404 [36:33<13:13,  1.28s/it]

https://hiring.cafe/job/xarj9bdp53gunhut
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xarj9bdp53gunhut.json.gz

 74%|███████▍  | 1787/2404 [36:34<13:44,  1.34s/it]

https://hiring.cafe/job/lhv9zcj3vftvywgt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lhv9zcj3vftvywgt.json.gz

 74%|███████▍  | 1788/2404 [36:36<13:54,  1.35s/it]

https://hiring.cafe/job/26o0b2ccal52trvw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\26o0b2ccal52trvw.json.gz

 74%|███████▍  | 1789/2404 [36:37<14:25,  1.41s/it]

https://hiring.cafe/job/gmf8akinu4tk4hwa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gmf8akinu4tk4hwa.json.gz

 74%|███████▍  | 1790/2404 [36:38<13:56,  1.36s/it]

https://hiring.cafe/job/7kd2x5hl7u5d322k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7kd2x5hl7u5d322k.json.gz

 75%|███████▍  | 1791/2404 [36:40<13:01,  1.28s/it]

https://hiring.cafe/job/nf6y0ameb035k0fk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nf6y0ameb035k0fk.json.gz

 75%|███████▍  | 1792/2404 [36:41<13:14,  1.30s/it]

https://hiring.cafe/job/vif7j2033wel2n58
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vif7j2033wel2n58.json.gz

 75%|███████▍  | 1793/2404 [36:42<12:48,  1.26s/it]

https://hiring.cafe/job/o2vh167bs3g93mmu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o2vh167bs3g93mmu.json.gz

 75%|███████▍  | 1794/2404 [36:43<12:26,  1.22s/it]

https://hiring.cafe/job/kg5azq58wvb0fh74
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kg5azq58wvb0fh74.json.gz

 75%|███████▍  | 1795/2404 [36:44<11:58,  1.18s/it]

https://hiring.cafe/job/k0cxcmhfwqw54rky
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k0cxcmhfwqw54rky.json.gz

 75%|███████▍  | 1796/2404 [36:46<12:27,  1.23s/it]

https://hiring.cafe/job/p8dfkyh1fd0hdw3q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p8dfkyh1fd0hdw3q.json.gz

 75%|███████▍  | 1797/2404 [36:47<12:31,  1.24s/it]

https://hiring.cafe/job/g67v3uob6330zu0u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g67v3uob6330zu0u.json.gz

 75%|███████▍  | 1798/2404 [36:48<12:34,  1.25s/it]

https://hiring.cafe/job/rnk3nzbi72nbsyma
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rnk3nzbi72nbsyma.json.gz

 75%|███████▍  | 1799/2404 [36:50<13:27,  1.34s/it]

https://hiring.cafe/job/2evddb47juzmrull
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2evddb47juzmrull.json.gz

 75%|███████▍  | 1800/2404 [36:51<12:46,  1.27s/it]

https://hiring.cafe/job/6us0hmdwv64rz18b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6us0hmdwv64rz18b.json.gz

 75%|███████▍  | 1801/2404 [36:52<13:00,  1.29s/it]

https://hiring.cafe/job/1xy8cbwdwfbg71np
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1xy8cbwdwfbg71np.json.gz

 75%|███████▍  | 1802/2404 [36:53<12:18,  1.23s/it]

https://hiring.cafe/job/d1uk9lb1ma9pbvc8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d1uk9lb1ma9pbvc8.json.gz

 75%|███████▌  | 1803/2404 [36:55<12:46,  1.28s/it]

https://hiring.cafe/job/g90jtz0eux9bi42k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g90jtz0eux9bi42k.json.gz

 75%|███████▌  | 1804/2404 [36:56<13:02,  1.30s/it]

https://hiring.cafe/job/a7ptd0yyrstgsmg7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a7ptd0yyrstgsmg7.json.gz

 75%|███████▌  | 1805/2404 [36:57<12:52,  1.29s/it]

https://hiring.cafe/job/ct4maap6588vs6hf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ct4maap6588vs6hf.json.gz

 75%|███████▌  | 1806/2404 [36:58<12:34,  1.26s/it]

https://hiring.cafe/job/wtkdg5tiy9kxhmh6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wtkdg5tiy9kxhmh6.json.gz

 75%|███████▌  | 1807/2404 [37:00<12:50,  1.29s/it]

https://hiring.cafe/job/x1j36lo7rjg4m3v1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x1j36lo7rjg4m3v1.json.gz

 75%|███████▌  | 1808/2404 [37:01<12:21,  1.24s/it]

https://hiring.cafe/job/30gtxkt9b9jkx5ui
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\30gtxkt9b9jkx5ui.json.gz

 75%|███████▌  | 1809/2404 [37:02<12:20,  1.25s/it]

https://hiring.cafe/job/isvk3nll90llbsuk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\isvk3nll90llbsuk.json.gz

 75%|███████▌  | 1810/2404 [37:03<11:42,  1.18s/it]

https://hiring.cafe/job/58bl7tkni377ktr6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\58bl7tkni377ktr6.json.gz

 75%|███████▌  | 1811/2404 [37:05<12:32,  1.27s/it]

https://hiring.cafe/job/dr5gc4jpc1qnmfl3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dr5gc4jpc1qnmfl3.json.gz

 75%|███████▌  | 1812/2404 [37:06<11:59,  1.22s/it]

https://hiring.cafe/job/3652upe6vwnc9m4l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3652upe6vwnc9m4l.json.gz

 75%|███████▌  | 1813/2404 [37:07<12:23,  1.26s/it]

https://hiring.cafe/job/mo39kx6m6fxg4tnd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mo39kx6m6fxg4tnd.json.gz

 75%|███████▌  | 1814/2404 [37:08<11:54,  1.21s/it]

https://hiring.cafe/job/s5056wx2gb38fcd4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s5056wx2gb38fcd4.json.gz

 75%|███████▌  | 1815/2404 [37:09<11:20,  1.16s/it]

https://hiring.cafe/job/503ekvet4d2go0xs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\503ekvet4d2go0xs.json.gz

 76%|███████▌  | 1816/2404 [37:10<11:15,  1.15s/it]

https://hiring.cafe/job/n8w2i5ko7zr4ghat
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n8w2i5ko7zr4ghat.json.gz

 76%|███████▌  | 1817/2404 [37:11<10:40,  1.09s/it]

https://hiring.cafe/job/tsb3j1rik2l4rcbo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tsb3j1rik2l4rcbo.json.gz

 76%|███████▌  | 1818/2404 [37:13<11:26,  1.17s/it]

https://hiring.cafe/job/qrzsnf9tjybp79vt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qrzsnf9tjybp79vt.json.gz

 76%|███████▌  | 1819/2404 [37:14<11:32,  1.18s/it]

https://hiring.cafe/job/ztx7qs89jxocaqwf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ztx7qs89jxocaqwf.json.gz

 76%|███████▌  | 1820/2404 [37:16<12:57,  1.33s/it]

https://hiring.cafe/job/61gnug8090ss4vg5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\61gnug8090ss4vg5.json.gz

 76%|███████▌  | 1821/2404 [37:17<12:36,  1.30s/it]

https://hiring.cafe/job/uoaol65ppuj2x664
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uoaol65ppuj2x664.json.gz

 76%|███████▌  | 1822/2404 [37:18<12:58,  1.34s/it]

https://hiring.cafe/job/b55eus6wx6lb33bl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b55eus6wx6lb33bl.json.gz

 76%|███████▌  | 1823/2404 [37:19<12:37,  1.30s/it]

https://hiring.cafe/job/221bf7j9zcbj7cld
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\221bf7j9zcbj7cld.json.gz

 76%|███████▌  | 1824/2404 [37:21<12:55,  1.34s/it]

https://hiring.cafe/job/ykjc8vrt7h05t7mt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ykjc8vrt7h05t7mt.json.gz

 76%|███████▌  | 1825/2404 [37:22<12:30,  1.30s/it]

https://hiring.cafe/job/mrl7kyg2s8p0hm5o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mrl7kyg2s8p0hm5o.json.gz

 76%|███████▌  | 1826/2404 [37:23<12:23,  1.29s/it]

https://hiring.cafe/job/aijs5ad78jj14l36
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\aijs5ad78jj14l36.json.gz

 76%|███████▌  | 1827/2404 [37:24<11:57,  1.24s/it]

https://hiring.cafe/job/pvch8nfyzn4l500y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pvch8nfyzn4l500y.json.gz

 76%|███████▌  | 1828/2404 [37:26<11:39,  1.22s/it]

https://hiring.cafe/job/veboqxekxg5iaewr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\veboqxekxg5iaewr.json.gz

 76%|███████▌  | 1829/2404 [37:27<11:55,  1.24s/it]

https://hiring.cafe/job/rcc1459actfk81eg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rcc1459actfk81eg.json.gz

 76%|███████▌  | 1830/2404 [37:28<11:55,  1.25s/it]

https://hiring.cafe/job/ax4p85po3qqi7i4f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ax4p85po3qqi7i4f.json.gz

 76%|███████▌  | 1831/2404 [37:29<11:40,  1.22s/it]

https://hiring.cafe/job/vq9abcuhawe8dqhl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vq9abcuhawe8dqhl.json.gz

 76%|███████▌  | 1832/2404 [37:31<11:27,  1.20s/it]

https://hiring.cafe/job/dxdkhslgy5rasbef
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dxdkhslgy5rasbef.json.gz

 76%|███████▌  | 1833/2404 [37:32<11:33,  1.21s/it]

https://hiring.cafe/job/ge7wrkov3nqiq955
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ge7wrkov3nqiq955.json.gz

 76%|███████▋  | 1834/2404 [37:33<11:24,  1.20s/it]

https://hiring.cafe/job/c0umx9r3v9zse6om
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c0umx9r3v9zse6om.json.gz

 76%|███████▋  | 1835/2404 [37:34<10:45,  1.13s/it]

https://hiring.cafe/job/gih4nsiiohvdvblc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gih4nsiiohvdvblc.json.gz

 76%|███████▋  | 1836/2404 [37:35<10:23,  1.10s/it]

https://hiring.cafe/job/z57rx07ruzs5llos
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z57rx07ruzs5llos.json.gz

 76%|███████▋  | 1837/2404 [37:36<10:10,  1.08s/it]

https://hiring.cafe/job/q00lkmdqw9ou7mug
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q00lkmdqw9ou7mug.json.gz

 76%|███████▋  | 1838/2404 [37:37<10:26,  1.11s/it]

https://hiring.cafe/job/avfi3c2bi2hnbu0a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\avfi3c2bi2hnbu0a.json.gz

 76%|███████▋  | 1839/2404 [37:39<11:58,  1.27s/it]

https://hiring.cafe/job/08tewchrkxe0mqf9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\08tewchrkxe0mqf9.json.gz

 77%|███████▋  | 1840/2404 [37:40<12:28,  1.33s/it]

https://hiring.cafe/job/r57fcutyaoesnopj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r57fcutyaoesnopj.json.gz

 77%|███████▋  | 1841/2404 [37:42<12:19,  1.31s/it]

https://hiring.cafe/job/nbk5igqx8hgfldxq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nbk5igqx8hgfldxq.json.gz

 77%|███████▋  | 1842/2404 [37:43<12:13,  1.31s/it]

https://hiring.cafe/job/n7tktgltxx102xid
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n7tktgltxx102xid.json.gz

 77%|███████▋  | 1843/2404 [37:44<12:05,  1.29s/it]

https://hiring.cafe/job/22t8kw34ewhu4dpi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\22t8kw34ewhu4dpi.json.gz

 77%|███████▋  | 1844/2404 [37:45<12:18,  1.32s/it]

https://hiring.cafe/job/p8jcov3rqplqpjpi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p8jcov3rqplqpjpi.json.gz

 77%|███████▋  | 1845/2404 [37:46<11:30,  1.23s/it]

https://hiring.cafe/job/43isq129i9bv9ef0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\43isq129i9bv9ef0.json.gz

 77%|███████▋  | 1846/2404 [37:48<12:08,  1.31s/it]

https://hiring.cafe/job/lwudn0d0horij4a1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lwudn0d0horij4a1.json.gz

 77%|███████▋  | 1847/2404 [37:49<11:45,  1.27s/it]

https://hiring.cafe/job/zlqia10q50r9hi7q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zlqia10q50r9hi7q.json.gz

 77%|███████▋  | 1848/2404 [37:51<12:25,  1.34s/it]

https://hiring.cafe/job/vpq4anl3f3voy0k8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vpq4anl3f3voy0k8.json.gz

 77%|███████▋  | 1849/2404 [37:52<11:43,  1.27s/it]

https://hiring.cafe/job/jvo5vpkp222ohtea
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jvo5vpkp222ohtea.json.gz

 77%|███████▋  | 1850/2404 [37:53<11:17,  1.22s/it]

https://hiring.cafe/job/k8vc4aa3d9841z6w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k8vc4aa3d9841z6w.json.gz

 77%|███████▋  | 1851/2404 [37:54<11:12,  1.22s/it]

https://hiring.cafe/job/p4s7r3cm6hcx8qzw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p4s7r3cm6hcx8qzw.json.gz

 77%|███████▋  | 1852/2404 [37:55<11:36,  1.26s/it]

https://hiring.cafe/job/2ocbjza3fvzu4tai
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2ocbjza3fvzu4tai.json.gz

 77%|███████▋  | 1853/2404 [37:57<11:40,  1.27s/it]

https://hiring.cafe/job/49wu97b4j6g9q9rt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\49wu97b4j6g9q9rt.json.gz

 77%|███████▋  | 1854/2404 [37:58<12:14,  1.33s/it]

https://hiring.cafe/job/31yomqciupvdyzso
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\31yomqciupvdyzso.json.gz

 77%|███████▋  | 1855/2404 [38:00<12:18,  1.35s/it]

https://hiring.cafe/job/g1hhef5np2k7e1yp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g1hhef5np2k7e1yp.json.gz

 77%|███████▋  | 1856/2404 [38:01<11:09,  1.22s/it]

https://hiring.cafe/job/r3x82f34zpjlj6si
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r3x82f34zpjlj6si.json.gz

 77%|███████▋  | 1857/2404 [38:01<10:24,  1.14s/it]

https://hiring.cafe/job/zdoc45jhgyu28bsu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zdoc45jhgyu28bsu.json.gz

 77%|███████▋  | 1858/2404 [38:03<10:38,  1.17s/it]

https://hiring.cafe/job/jiw0n3nfz5x4ctti
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jiw0n3nfz5x4ctti.json.gz

 77%|███████▋  | 1859/2404 [38:04<11:15,  1.24s/it]

https://hiring.cafe/job/eevdkm892dk5bl7x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eevdkm892dk5bl7x.json.gz

 77%|███████▋  | 1860/2404 [38:05<11:21,  1.25s/it]

https://hiring.cafe/job/tx5xzekixz441ts7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tx5xzekixz441ts7.json.gz

 77%|███████▋  | 1861/2404 [38:07<11:34,  1.28s/it]

https://hiring.cafe/job/hth040twd0hj7xz1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hth040twd0hj7xz1.json.gz

 77%|███████▋  | 1862/2404 [38:08<10:58,  1.21s/it]

https://hiring.cafe/job/tgprx8krcyaqbvt8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tgprx8krcyaqbvt8.json.gz

 77%|███████▋  | 1863/2404 [38:09<10:56,  1.21s/it]

https://hiring.cafe/job/iitblk4t816xreaz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iitblk4t816xreaz.json.gz

 78%|███████▊  | 1864/2404 [38:10<10:47,  1.20s/it]

https://hiring.cafe/job/jyddve6rqhra683l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jyddve6rqhra683l.json.gz

 78%|███████▊  | 1865/2404 [38:11<10:58,  1.22s/it]

https://hiring.cafe/job/snw4a5gx9sqiu7f2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\snw4a5gx9sqiu7f2.json.gz

 78%|███████▊  | 1866/2404 [38:13<10:52,  1.21s/it]

https://hiring.cafe/job/rctixksj594v2k2h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rctixksj594v2k2h.json.gz

 78%|███████▊  | 1867/2404 [38:14<11:13,  1.25s/it]

https://hiring.cafe/job/1laxv5sobbpxura0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1laxv5sobbpxura0.json.gz

 78%|███████▊  | 1868/2404 [38:15<11:54,  1.33s/it]

https://hiring.cafe/job/pibxdq7isehnekf2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pibxdq7isehnekf2.json.gz

 78%|███████▊  | 1869/2404 [38:17<11:05,  1.24s/it]

https://hiring.cafe/job/qv1q82u0jvihvdaq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qv1q82u0jvihvdaq.json.gz

 78%|███████▊  | 1870/2404 [38:18<11:01,  1.24s/it]

https://hiring.cafe/job/3rk1rhald8b2eysz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3rk1rhald8b2eysz.json.gz

 78%|███████▊  | 1871/2404 [38:19<10:45,  1.21s/it]

https://hiring.cafe/job/xvpkqw1qh27cp5dk
https://hiring.cafe/job/xvpkqw1qh27cp5dk

 78%|███████▊  | 1872/2404 [38:20<09:59,  1.13s/it]

https://hiring.cafe/job/w7dnanuosp3xjl7h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w7dnanuosp3xjl7h.json.gz

 78%|███████▊  | 1873/2404 [38:21<10:02,  1.13s/it]

https://hiring.cafe/job/g0jqbb0pb4jywehy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g0jqbb0pb4jywehy.json.gz

 78%|███████▊  | 1874/2404 [38:22<10:08,  1.15s/it]

https://hiring.cafe/job/bas3hur9c74u69jv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bas3hur9c74u69jv.json.gz

 78%|███████▊  | 1875/2404 [38:24<10:41,  1.21s/it]

https://hiring.cafe/job/81a4raskhvsuk9uq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\81a4raskhvsuk9uq.json.gz

 78%|███████▊  | 1876/2404 [38:25<10:44,  1.22s/it]

https://hiring.cafe/job/rcehb58xcvnwe7di
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rcehb58xcvnwe7di.json.gz

 78%|███████▊  | 1877/2404 [38:26<11:18,  1.29s/it]

https://hiring.cafe/job/rmlol0qv0rka1ndv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rmlol0qv0rka1ndv.json.gz

 78%|███████▊  | 1878/2404 [38:27<11:11,  1.28s/it]

https://hiring.cafe/job/zx01zja02asy3wdw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zx01zja02asy3wdw.json.gz

 78%|███████▊  | 1879/2404 [38:29<11:06,  1.27s/it]

https://hiring.cafe/job/9peay0s08iswgr26
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9peay0s08iswgr26.json.gz

 78%|███████▊  | 1880/2404 [38:30<11:23,  1.30s/it]

https://hiring.cafe/job/iktt4j9tqaukdtkv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iktt4j9tqaukdtkv.json.gz

 78%|███████▊  | 1881/2404 [38:31<11:13,  1.29s/it]

https://hiring.cafe/job/ul6d2jakj9w9hxkj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ul6d2jakj9w9hxkj.json.gz

 78%|███████▊  | 1882/2404 [38:33<10:59,  1.26s/it]

https://hiring.cafe/job/o1z3gk4i6go4k602
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o1z3gk4i6go4k602.json.gz

 78%|███████▊  | 1883/2404 [38:34<11:08,  1.28s/it]

https://hiring.cafe/job/cluplthqprds48sa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cluplthqprds48sa.json.gz

 78%|███████▊  | 1884/2404 [38:35<10:47,  1.24s/it]

https://hiring.cafe/job/l1e5dor1m6bwk4nv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l1e5dor1m6bwk4nv.json.gz

 78%|███████▊  | 1885/2404 [38:36<11:10,  1.29s/it]

https://hiring.cafe/job/miom3uodi4a51bvn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\miom3uodi4a51bvn.json.gz

 78%|███████▊  | 1886/2404 [38:38<10:36,  1.23s/it]

https://hiring.cafe/job/c3cba1aav6t52lzf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c3cba1aav6t52lzf.json.gz

 78%|███████▊  | 1887/2404 [38:39<10:43,  1.24s/it]

https://hiring.cafe/job/2263m65l03owpn16
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2263m65l03owpn16.json.gz

 79%|███████▊  | 1888/2404 [38:40<10:24,  1.21s/it]

https://hiring.cafe/job/f3e7oqllwdhbdsth
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f3e7oqllwdhbdsth.json.gz

 79%|███████▊  | 1889/2404 [38:41<10:35,  1.23s/it]

https://hiring.cafe/job/3i7ga8icmbfgq7va
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3i7ga8icmbfgq7va.json.gz

 79%|███████▊  | 1890/2404 [38:43<10:55,  1.28s/it]

https://hiring.cafe/job/o0rqgwk2s8wt8q3v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o0rqgwk2s8wt8q3v.json.gz

 79%|███████▊  | 1891/2404 [38:44<10:48,  1.26s/it]

https://hiring.cafe/job/zcy0p2roa42fo4jp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zcy0p2roa42fo4jp.json.gz

 79%|███████▊  | 1892/2404 [38:45<10:55,  1.28s/it]

https://hiring.cafe/job/zca8v6rbhtj8dkcl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zca8v6rbhtj8dkcl.json.gz

 79%|███████▊  | 1893/2404 [38:46<10:49,  1.27s/it]

https://hiring.cafe/job/qt27hcmrsznfh5ql
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qt27hcmrsznfh5ql.json.gz

 79%|███████▉  | 1894/2404 [38:48<10:30,  1.24s/it]

https://hiring.cafe/job/4gw7lxkpmr6b8cyc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4gw7lxkpmr6b8cyc.json.gz

 79%|███████▉  | 1895/2404 [38:49<10:53,  1.28s/it]

https://hiring.cafe/job/05ov57y52yv9y47p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\05ov57y52yv9y47p.json.gz

 79%|███████▉  | 1896/2404 [38:50<10:37,  1.25s/it]

https://hiring.cafe/job/3sg0uybjj2vzdabo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3sg0uybjj2vzdabo.json.gz

 79%|███████▉  | 1897/2404 [38:52<10:55,  1.29s/it]

https://hiring.cafe/job/9od8hiz6w86utrs7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9od8hiz6w86utrs7.json.gz

 79%|███████▉  | 1898/2404 [38:53<11:02,  1.31s/it]

https://hiring.cafe/job/jeydpwqfw71mma96
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jeydpwqfw71mma96.json.gz

 79%|███████▉  | 1899/2404 [38:54<11:08,  1.32s/it]

https://hiring.cafe/job/sg7wr914vbyy01mx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sg7wr914vbyy01mx.json.gz

 79%|███████▉  | 1900/2404 [38:56<11:24,  1.36s/it]

https://hiring.cafe/job/sk876vb0ldfcnyt0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sk876vb0ldfcnyt0.json.gz

 79%|███████▉  | 1901/2404 [38:57<11:38,  1.39s/it]

https://hiring.cafe/job/phu30rg6dd27n0ar
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\phu30rg6dd27n0ar.json.gz

 79%|███████▉  | 1902/2404 [38:58<10:59,  1.31s/it]

https://hiring.cafe/job/mq5v4iqtwu29orri
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mq5v4iqtwu29orri.json.gz

 79%|███████▉  | 1903/2404 [39:00<11:04,  1.33s/it]

https://hiring.cafe/job/deqx0pfknptwf887
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\deqx0pfknptwf887.json.gz

 79%|███████▉  | 1904/2404 [39:01<11:09,  1.34s/it]

https://hiring.cafe/job/7du8n0g4xpu1vg61
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7du8n0g4xpu1vg61.json.gz

 79%|███████▉  | 1905/2404 [39:02<11:02,  1.33s/it]

https://hiring.cafe/job/vbt9opljxdtp3kvt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vbt9opljxdtp3kvt.json.gz

 79%|███████▉  | 1906/2404 [39:04<11:34,  1.40s/it]

https://hiring.cafe/job/fhs86kuhvd32k03n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fhs86kuhvd32k03n.json.gz

 79%|███████▉  | 1907/2404 [39:05<11:08,  1.35s/it]

https://hiring.cafe/job/to6nyqszbub1t1nc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\to6nyqszbub1t1nc.json.gz

 79%|███████▉  | 1908/2404 [39:07<11:49,  1.43s/it]

https://hiring.cafe/job/7q0qez61o7dzu0kk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7q0qez61o7dzu0kk.json.gz

 79%|███████▉  | 1909/2404 [39:08<11:42,  1.42s/it]

https://hiring.cafe/job/bq4u4faur6s5gm6b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bq4u4faur6s5gm6b.json.gz

 79%|███████▉  | 1910/2404 [39:10<11:56,  1.45s/it]

https://hiring.cafe/job/1u93zt9etuz0htj6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1u93zt9etuz0htj6.json.gz

 79%|███████▉  | 1911/2404 [39:11<11:38,  1.42s/it]

https://hiring.cafe/job/fn5igm9ru3nspor9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fn5igm9ru3nspor9.json.gz

 80%|███████▉  | 1912/2404 [39:12<11:52,  1.45s/it]

https://hiring.cafe/job/spxn3gwwqykdw6dx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\spxn3gwwqykdw6dx.json.gz

 80%|███████▉  | 1913/2404 [39:14<11:31,  1.41s/it]

https://hiring.cafe/job/9q34lllypwf40rgx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9q34lllypwf40rgx.json.gz

 80%|███████▉  | 1914/2404 [39:15<11:25,  1.40s/it]

https://hiring.cafe/job/g99bqdl0c7h2size
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g99bqdl0c7h2size.json.gz

 80%|███████▉  | 1915/2404 [39:17<11:16,  1.38s/it]

https://hiring.cafe/job/7ki2pxhxnhf57yu9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7ki2pxhxnhf57yu9.json.gz

 80%|███████▉  | 1916/2404 [39:18<11:24,  1.40s/it]

https://hiring.cafe/job/q5363t5xysy3ly1g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q5363t5xysy3ly1g.json.gz

 80%|███████▉  | 1917/2404 [39:19<11:09,  1.38s/it]

https://hiring.cafe/job/kg29o6sypktr31kv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kg29o6sypktr31kv.json.gz

 80%|███████▉  | 1918/2404 [39:21<10:57,  1.35s/it]

https://hiring.cafe/job/dcgx6paj6oo9r7sf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dcgx6paj6oo9r7sf.json.gz

 80%|███████▉  | 1919/2404 [39:22<11:05,  1.37s/it]

https://hiring.cafe/job/d57cy6y2ocntpgku
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d57cy6y2ocntpgku.json.gz

 80%|███████▉  | 1920/2404 [39:23<11:20,  1.41s/it]

https://hiring.cafe/job/mgd5hsj4c1xj8nre
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mgd5hsj4c1xj8nre.json.gz

 80%|███████▉  | 1921/2404 [39:25<11:21,  1.41s/it]

https://hiring.cafe/job/t56zk95qz5vydva3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t56zk95qz5vydva3.json.gz

 80%|███████▉  | 1922/2404 [39:27<11:47,  1.47s/it]

https://hiring.cafe/job/9kzaiwj26tpazeej
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9kzaiwj26tpazeej.json.gz

 80%|███████▉  | 1923/2404 [39:28<10:53,  1.36s/it]

https://hiring.cafe/job/1906nutr2tzdkewu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1906nutr2tzdkewu.json.gz

 80%|████████  | 1924/2404 [39:29<11:21,  1.42s/it]

https://hiring.cafe/job/lz8srzwrbmn8wjg5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lz8srzwrbmn8wjg5.json.gz

 80%|████████  | 1925/2404 [39:30<11:00,  1.38s/it]

https://hiring.cafe/job/0crurynghgcriwhl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0crurynghgcriwhl.json.gz

 80%|████████  | 1926/2404 [39:32<11:29,  1.44s/it]

https://hiring.cafe/job/gjlnsqgyrh28kgfj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gjlnsqgyrh28kgfj.json.gz

 80%|████████  | 1927/2404 [39:33<10:58,  1.38s/it]

https://hiring.cafe/job/6f9djtv6d1bcl85e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6f9djtv6d1bcl85e.json.gz

 80%|████████  | 1928/2404 [39:35<10:44,  1.35s/it]

https://hiring.cafe/job/9aojhkh57aco9m6o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9aojhkh57aco9m6o.json.gz

 80%|████████  | 1929/2404 [39:36<10:16,  1.30s/it]

https://hiring.cafe/job/683estzhe5dfhuzg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\683estzhe5dfhuzg.json.gz

 80%|████████  | 1930/2404 [39:37<10:08,  1.28s/it]

https://hiring.cafe/job/vf5ntkc8w3tcdkrc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vf5ntkc8w3tcdkrc.json.gz

 80%|████████  | 1931/2404 [39:38<10:11,  1.29s/it]

https://hiring.cafe/job/z8fqkqb0l8cog5i0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z8fqkqb0l8cog5i0.json.gz

 80%|████████  | 1932/2404 [39:40<10:25,  1.32s/it]

https://hiring.cafe/job/zrmacmkh7xmxjdj9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zrmacmkh7xmxjdj9.json.gz

 80%|████████  | 1933/2404 [39:41<10:07,  1.29s/it]

https://hiring.cafe/job/cycufhk2uqg2fprd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cycufhk2uqg2fprd.json.gz

 80%|████████  | 1934/2404 [39:42<09:55,  1.27s/it]

https://hiring.cafe/job/3mkc7jyu15hi67ci
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3mkc7jyu15hi67ci.json.gz

 80%|████████  | 1935/2404 [39:44<10:14,  1.31s/it]

https://hiring.cafe/job/qwo1gqc045zygolm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qwo1gqc045zygolm.json.gz

 81%|████████  | 1936/2404 [39:45<10:37,  1.36s/it]

https://hiring.cafe/job/ce8u3bb4e2e7z4f7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ce8u3bb4e2e7z4f7.json.gz

 81%|████████  | 1937/2404 [39:46<10:33,  1.36s/it]

https://hiring.cafe/job/etwyxqn8l5kpp154
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\etwyxqn8l5kpp154.json.gz

 81%|████████  | 1938/2404 [39:48<10:31,  1.35s/it]

https://hiring.cafe/job/hocdaz3l12crrcet
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hocdaz3l12crrcet.json.gz

 81%|████████  | 1939/2404 [39:49<10:32,  1.36s/it]

https://hiring.cafe/job/9i66hr9bc9vt3v5e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9i66hr9bc9vt3v5e.json.gz

 81%|████████  | 1940/2404 [39:51<11:51,  1.53s/it]

https://hiring.cafe/job/063omwj0vpx7h0u0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\063omwj0vpx7h0u0.json.gz

 81%|████████  | 1941/2404 [39:52<11:07,  1.44s/it]

https://hiring.cafe/job/xgng8qhxcn886l7g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xgng8qhxcn886l7g.json.gz

 81%|████████  | 1942/2404 [39:54<11:28,  1.49s/it]

https://hiring.cafe/job/18fpxsiks7tv2meo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\18fpxsiks7tv2meo.json.gz

 81%|████████  | 1943/2404 [39:55<10:54,  1.42s/it]

https://hiring.cafe/job/msw2outlzfyut8fa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\msw2outlzfyut8fa.json.gz

 81%|████████  | 1944/2404 [39:56<10:18,  1.34s/it]

https://hiring.cafe/job/c6gaofp9g4ebtc6h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c6gaofp9g4ebtc6h.json.gz

 81%|████████  | 1945/2404 [39:58<10:07,  1.32s/it]

https://hiring.cafe/job/s82ycqgw76hjcg3g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s82ycqgw76hjcg3g.json.gz

 81%|████████  | 1946/2404 [39:59<09:39,  1.27s/it]

https://hiring.cafe/job/r90wlyunkak3pd8w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r90wlyunkak3pd8w.json.gz

 81%|████████  | 1947/2404 [40:00<09:51,  1.29s/it]

https://hiring.cafe/job/5l0m7os71q27kidz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5l0m7os71q27kidz.json.gz

 81%|████████  | 1948/2404 [40:02<10:17,  1.35s/it]

https://hiring.cafe/job/q9o0j6m09bvh46fc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q9o0j6m09bvh46fc.json.gz

 81%|████████  | 1949/2404 [40:03<10:00,  1.32s/it]

https://hiring.cafe/job/bgnmbk35yyy6asd2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bgnmbk35yyy6asd2.json.gz

 81%|████████  | 1950/2404 [40:04<09:39,  1.28s/it]

https://hiring.cafe/job/u5hj2dgtvvv95ypm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u5hj2dgtvvv95ypm.json.gz

 81%|████████  | 1951/2404 [40:05<09:27,  1.25s/it]

https://hiring.cafe/job/5e37e7nx3f6s09vi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5e37e7nx3f6s09vi.json.gz

 81%|████████  | 1952/2404 [40:06<09:08,  1.21s/it]

https://hiring.cafe/job/isqyrd7tv1cyn345
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\isqyrd7tv1cyn345.json.gz

 81%|████████  | 1953/2404 [40:08<10:11,  1.36s/it]

https://hiring.cafe/job/i1zmvz3is2ct1jad
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i1zmvz3is2ct1jad.json.gz

 81%|████████▏ | 1954/2404 [40:09<09:59,  1.33s/it]

https://hiring.cafe/job/ke8rfnb6jmtiy0mr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ke8rfnb6jmtiy0mr.json.gz

 81%|████████▏ | 1955/2404 [40:11<09:49,  1.31s/it]

https://hiring.cafe/job/4uh9ihnxw7yyy83j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4uh9ihnxw7yyy83j.json.gz

 81%|████████▏ | 1956/2404 [40:11<08:55,  1.19s/it]

https://hiring.cafe/job/6ae93kubc1t2mnj6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6ae93kubc1t2mnj6.json.gz

 81%|████████▏ | 1957/2404 [40:13<09:07,  1.22s/it]

https://hiring.cafe/job/6z17wsirgwdyxu3p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6z17wsirgwdyxu3p.json.gz

 81%|████████▏ | 1958/2404 [40:14<09:34,  1.29s/it]

https://hiring.cafe/job/e544tdbkbrktry36
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e544tdbkbrktry36.json.gz

 81%|████████▏ | 1959/2404 [40:15<09:33,  1.29s/it]

https://hiring.cafe/job/lkmpyb0wd76yg0xu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lkmpyb0wd76yg0xu.json.gz

 82%|████████▏ | 1960/2404 [40:17<10:02,  1.36s/it]

https://hiring.cafe/job/utm7cg3d975kc2lb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\utm7cg3d975kc2lb.json.gz

 82%|████████▏ | 1961/2404 [40:18<09:14,  1.25s/it]

https://hiring.cafe/job/hh69yknw6rey2xsq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hh69yknw6rey2xsq.json.gz

 82%|████████▏ | 1962/2404 [40:19<09:38,  1.31s/it]

https://hiring.cafe/job/azp0rptlie8zwqkq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\azp0rptlie8zwqkq.json.gz

 82%|████████▏ | 1963/2404 [40:21<09:24,  1.28s/it]

https://hiring.cafe/job/uchydmvnad66wkp7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uchydmvnad66wkp7.json.gz

 82%|████████▏ | 1964/2404 [40:22<09:23,  1.28s/it]

https://hiring.cafe/job/ljmishwmtgg7jc9n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ljmishwmtgg7jc9n.json.gz

 82%|████████▏ | 1965/2404 [40:23<09:30,  1.30s/it]

https://hiring.cafe/job/nh0kw9pkwfzfqmpe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nh0kw9pkwfzfqmpe.json.gz

 82%|████████▏ | 1966/2404 [40:25<09:48,  1.34s/it]

https://hiring.cafe/job/g1t7pkzkz9hk85kh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g1t7pkzkz9hk85kh.json.gz

 82%|████████▏ | 1967/2404 [40:26<09:22,  1.29s/it]

https://hiring.cafe/job/85ixyjezk2ln29cn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\85ixyjezk2ln29cn.json.gz

 82%|████████▏ | 1968/2404 [40:27<09:39,  1.33s/it]

https://hiring.cafe/job/vlha7gkgkzvvgdxr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vlha7gkgkzvvgdxr.json.gz

 82%|████████▏ | 1969/2404 [40:29<09:32,  1.32s/it]

https://hiring.cafe/job/6ccp16t4w1g9416o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6ccp16t4w1g9416o.json.gz

 82%|████████▏ | 1970/2404 [40:30<09:15,  1.28s/it]

https://hiring.cafe/job/drqz1ipd3qdbc5e1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\drqz1ipd3qdbc5e1.json.gz

 82%|████████▏ | 1971/2404 [40:31<09:29,  1.31s/it]

https://hiring.cafe/job/cvj5wgab8fer4avv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cvj5wgab8fer4avv.json.gz

 82%|████████▏ | 1972/2404 [40:32<09:08,  1.27s/it]

https://hiring.cafe/job/xbslnecazxerhb8g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xbslnecazxerhb8g.json.gz

 82%|████████▏ | 1973/2404 [40:34<09:28,  1.32s/it]

https://hiring.cafe/job/3mozuvyteqpbdx81
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3mozuvyteqpbdx81.json.gz

 82%|████████▏ | 1974/2404 [40:35<09:14,  1.29s/it]

https://hiring.cafe/job/nkzwbvg5uggyvc7v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nkzwbvg5uggyvc7v.json.gz

 82%|████████▏ | 1975/2404 [40:36<09:30,  1.33s/it]

https://hiring.cafe/job/tls3m49rib5x2r99
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tls3m49rib5x2r99.json.gz

 82%|████████▏ | 1976/2404 [40:38<09:52,  1.38s/it]

https://hiring.cafe/job/4pa12c3ar2nvv5jo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4pa12c3ar2nvv5jo.json.gz

 82%|████████▏ | 1977/2404 [40:39<09:29,  1.33s/it]

https://hiring.cafe/job/j0kt52wx8kc70w4z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j0kt52wx8kc70w4z.json.gz

 82%|████████▏ | 1978/2404 [40:41<09:59,  1.41s/it]

https://hiring.cafe/job/lr7yv2yipjudmhy1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lr7yv2yipjudmhy1.json.gz

 82%|████████▏ | 1979/2404 [40:42<09:09,  1.29s/it]

https://hiring.cafe/job/5h70a3ddl1k0aeeb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5h70a3ddl1k0aeeb.json.gz

 82%|████████▏ | 1980/2404 [40:43<09:08,  1.29s/it]

https://hiring.cafe/job/ttg9fsf8r12yl7l9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ttg9fsf8r12yl7l9.json.gz

 82%|████████▏ | 1981/2404 [40:44<08:52,  1.26s/it]

https://hiring.cafe/job/mw1gge04aigg0yw6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mw1gge04aigg0yw6.json.gz

 82%|████████▏ | 1982/2404 [40:45<08:45,  1.25s/it]

https://hiring.cafe/job/pi9pe0cel7v36irz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pi9pe0cel7v36irz.json.gz

 82%|████████▏ | 1983/2404 [40:47<09:18,  1.33s/it]

https://hiring.cafe/job/z4r3rnrv7r0nw2tc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z4r3rnrv7r0nw2tc.json.gz

 83%|████████▎ | 1984/2404 [40:48<08:35,  1.23s/it]

https://hiring.cafe/job/j0fcabecy3q5wwug
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j0fcabecy3q5wwug.json.gz

 83%|████████▎ | 1985/2404 [40:49<08:18,  1.19s/it]

https://hiring.cafe/job/tio81l6nt64dhpo8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tio81l6nt64dhpo8.json.gz

 83%|████████▎ | 1986/2404 [40:50<08:46,  1.26s/it]

https://hiring.cafe/job/cw5esei86a56mmm3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cw5esei86a56mmm3.json.gz

 83%|████████▎ | 1987/2404 [40:52<08:38,  1.24s/it]

https://hiring.cafe/job/2xznfw8xzfo3o0qz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2xznfw8xzfo3o0qz.json.gz

 83%|████████▎ | 1988/2404 [40:53<08:50,  1.28s/it]

https://hiring.cafe/job/oc9va608ixr9vhvr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oc9va608ixr9vhvr.json.gz

 83%|████████▎ | 1989/2404 [40:54<09:14,  1.34s/it]

https://hiring.cafe/job/netu7znsplvkkn76
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\netu7znsplvkkn76.json.gz

 83%|████████▎ | 1990/2404 [40:56<09:15,  1.34s/it]

https://hiring.cafe/job/knmyt2st3lnkfqv9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\knmyt2st3lnkfqv9.json.gz

 83%|████████▎ | 1991/2404 [40:57<08:54,  1.29s/it]

https://hiring.cafe/job/0jjadqhepme130sg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0jjadqhepme130sg.json.gz

 83%|████████▎ | 1992/2404 [40:59<09:21,  1.36s/it]

https://hiring.cafe/job/aeuxmyciddf1lhyl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\aeuxmyciddf1lhyl.json.gz

 83%|████████▎ | 1993/2404 [41:00<09:04,  1.32s/it]

https://hiring.cafe/job/kdcxo9j65dcf12lv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kdcxo9j65dcf12lv.json.gz

 83%|████████▎ | 1994/2404 [41:01<08:55,  1.31s/it]

https://hiring.cafe/job/dmkgxkreysy2fsaf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dmkgxkreysy2fsaf.json.gz

 83%|████████▎ | 1995/2404 [41:02<08:46,  1.29s/it]

https://hiring.cafe/job/5yx45svekqweiaga
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5yx45svekqweiaga.json.gz

 83%|████████▎ | 1996/2404 [41:04<09:25,  1.38s/it]

https://hiring.cafe/job/f9572jwx072p6ii7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f9572jwx072p6ii7.json.gz

 83%|████████▎ | 1997/2404 [41:05<08:46,  1.29s/it]

https://hiring.cafe/job/7xiar5rghdfkl3p7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7xiar5rghdfkl3p7.json.gz

 83%|████████▎ | 1998/2404 [41:06<09:08,  1.35s/it]

https://hiring.cafe/job/holglwva2easv68i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\holglwva2easv68i.json.gz

 83%|████████▎ | 1999/2404 [41:08<08:38,  1.28s/it]

https://hiring.cafe/job/4rhti9cnbm8q6sp2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4rhti9cnbm8q6sp2.json.gz

 83%|████████▎ | 2000/2404 [41:09<08:31,  1.27s/it]

https://hiring.cafe/job/m2veurhmqbvnxorx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m2veurhmqbvnxorx.json.gz

 83%|████████▎ | 2001/2404 [41:10<08:16,  1.23s/it]

https://hiring.cafe/job/k7scjwz9a7r2bttq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k7scjwz9a7r2bttq.json.gz

 83%|████████▎ | 2002/2404 [41:11<08:48,  1.31s/it]

https://hiring.cafe/job/zvvu6qj4i8h9g2kq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zvvu6qj4i8h9g2kq.json.gz

 83%|████████▎ | 2003/2404 [41:13<08:13,  1.23s/it]

https://hiring.cafe/job/fdo5f8zt2o86sxfx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fdo5f8zt2o86sxfx.json.gz

 83%|████████▎ | 2004/2404 [41:14<08:27,  1.27s/it]

https://hiring.cafe/job/w9m6ot1dwep7keys
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w9m6ot1dwep7keys.json.gz

 83%|████████▎ | 2005/2404 [41:15<08:01,  1.21s/it]

https://hiring.cafe/job/fpguf9v3gdm6opfp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fpguf9v3gdm6opfp.json.gz

 83%|████████▎ | 2006/2404 [41:16<07:46,  1.17s/it]

https://hiring.cafe/job/cuvqc0kigxtdkl2q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cuvqc0kigxtdkl2q.json.gz

 83%|████████▎ | 2007/2404 [41:17<07:51,  1.19s/it]

https://hiring.cafe/job/lc42bcoxzbyahqmh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lc42bcoxzbyahqmh.json.gz

 84%|████████▎ | 2008/2404 [41:19<08:34,  1.30s/it]

https://hiring.cafe/job/19q62so5poqplpwo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\19q62so5poqplpwo.json.gz

 84%|████████▎ | 2009/2404 [41:20<08:27,  1.28s/it]

https://hiring.cafe/job/cq4vir2izlaz25ae
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cq4vir2izlaz25ae.json.gz

 84%|████████▎ | 2010/2404 [41:21<07:38,  1.16s/it]

https://hiring.cafe/job/yw8arpdubqy5o5p8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yw8arpdubqy5o5p8.json.gz

 84%|████████▎ | 2011/2404 [41:22<07:44,  1.18s/it]

https://hiring.cafe/job/b8zlgftgq6cewxwh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b8zlgftgq6cewxwh.json.gz

 84%|████████▎ | 2012/2404 [41:23<07:24,  1.13s/it]

https://hiring.cafe/job/raabqnm5tshhtvn2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\raabqnm5tshhtvn2.json.gz

 84%|████████▎ | 2013/2404 [41:25<07:48,  1.20s/it]

https://hiring.cafe/job/ijqu6bhdo4834c80
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ijqu6bhdo4834c80.json.gz

 84%|████████▍ | 2014/2404 [41:26<08:47,  1.35s/it]

https://hiring.cafe/job/ppl6yrrsraps1sz9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ppl6yrrsraps1sz9.json.gz

 84%|████████▍ | 2015/2404 [41:27<07:43,  1.19s/it]

https://hiring.cafe/job/wzb5kdg477l8j4rw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wzb5kdg477l8j4rw.json.gz

 84%|████████▍ | 2016/2404 [41:28<07:49,  1.21s/it]

https://hiring.cafe/job/dpqmgjpme66hmbbx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dpqmgjpme66hmbbx.json.gz

 84%|████████▍ | 2017/2404 [41:29<07:42,  1.20s/it]

https://hiring.cafe/job/o5gxinw12uows7w8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o5gxinw12uows7w8.json.gz

 84%|████████▍ | 2018/2404 [41:31<07:26,  1.16s/it]

https://hiring.cafe/job/grui080h191jqfhe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\grui080h191jqfhe.json.gz

 84%|████████▍ | 2019/2404 [41:32<07:15,  1.13s/it]

https://hiring.cafe/job/gumstd07160bxty0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gumstd07160bxty0.json.gz

 84%|████████▍ | 2020/2404 [41:33<07:36,  1.19s/it]

https://hiring.cafe/job/rlprsoj30vjbz6s5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rlprsoj30vjbz6s5.json.gz

 84%|████████▍ | 2021/2404 [41:34<07:38,  1.20s/it]

https://hiring.cafe/job/r6w7lk9q4dhw3ck8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r6w7lk9q4dhw3ck8.json.gz

 84%|████████▍ | 2022/2404 [41:36<08:01,  1.26s/it]

https://hiring.cafe/job/kov1iqp2kwytltrr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kov1iqp2kwytltrr.json.gz

 84%|████████▍ | 2023/2404 [41:37<08:11,  1.29s/it]

https://hiring.cafe/job/qmjm8xopa5mikzem
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qmjm8xopa5mikzem.json.gz

 84%|████████▍ | 2024/2404 [41:38<07:55,  1.25s/it]

https://hiring.cafe/job/n9dj2g38cvntf87u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n9dj2g38cvntf87u.json.gz

 84%|████████▍ | 2025/2404 [41:39<08:11,  1.30s/it]

https://hiring.cafe/job/eu2u4izr7ln1o260
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eu2u4izr7ln1o260.json.gz

 84%|████████▍ | 2026/2404 [41:41<07:49,  1.24s/it]

https://hiring.cafe/job/5tx29ryyo44fjq0x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5tx29ryyo44fjq0x.json.gz

 84%|████████▍ | 2027/2404 [41:42<07:50,  1.25s/it]

https://hiring.cafe/job/ejjgqnn11gyfb1f5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ejjgqnn11gyfb1f5.json.gz

 84%|████████▍ | 2028/2404 [41:43<08:09,  1.30s/it]

https://hiring.cafe/job/vezalj5kzx0isywk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vezalj5kzx0isywk.json.gz

 84%|████████▍ | 2029/2404 [41:45<07:58,  1.28s/it]

https://hiring.cafe/job/4gkqp9cevkydx2st
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4gkqp9cevkydx2st.json.gz

 84%|████████▍ | 2030/2404 [41:46<07:44,  1.24s/it]

https://hiring.cafe/job/3q4zj2l2asr042ul
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3q4zj2l2asr042ul.json.gz

 84%|████████▍ | 2031/2404 [41:47<08:01,  1.29s/it]

https://hiring.cafe/job/l3qd0e7eia8ads4b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l3qd0e7eia8ads4b.json.gz

 85%|████████▍ | 2032/2404 [41:48<08:13,  1.33s/it]

https://hiring.cafe/job/chtjww429kryvk8m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\chtjww429kryvk8m.json.gz

 85%|████████▍ | 2033/2404 [41:50<08:04,  1.31s/it]

https://hiring.cafe/job/5ca8d8hysbf2b7o7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ca8d8hysbf2b7o7.json.gz

 85%|████████▍ | 2034/2404 [41:51<07:48,  1.27s/it]

https://hiring.cafe/job/c1u2vi40lu0josas
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c1u2vi40lu0josas.json.gz

 85%|████████▍ | 2035/2404 [41:52<07:52,  1.28s/it]

https://hiring.cafe/job/txdjlxg0j55ecdqv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\txdjlxg0j55ecdqv.json.gz

 85%|████████▍ | 2036/2404 [41:54<07:54,  1.29s/it]

https://hiring.cafe/job/n1x1qrvx86n7hbdb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\n1x1qrvx86n7hbdb.json.gz

 85%|████████▍ | 2037/2404 [41:55<08:03,  1.32s/it]

https://hiring.cafe/job/o5rwg54gwm5cplim
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o5rwg54gwm5cplim.json.gz

 85%|████████▍ | 2038/2404 [41:56<08:13,  1.35s/it]

https://hiring.cafe/job/ci42mjrpmj796te2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ci42mjrpmj796te2.json.gz

 85%|████████▍ | 2039/2404 [41:57<07:37,  1.25s/it]

https://hiring.cafe/job/3bmvv4r3o21fv0im
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3bmvv4r3o21fv0im.json.gz

 85%|████████▍ | 2040/2404 [41:59<07:45,  1.28s/it]

https://hiring.cafe/job/74m7yuyr62zxofgh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\74m7yuyr62zxofgh.json.gz

 85%|████████▍ | 2041/2404 [42:00<07:34,  1.25s/it]

https://hiring.cafe/job/ot85bncns2p6uwwg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ot85bncns2p6uwwg.json.gz

 85%|████████▍ | 2042/2404 [42:01<08:02,  1.33s/it]

https://hiring.cafe/job/qel6q933ai8djwup
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qel6q933ai8djwup.json.gz

 85%|████████▍ | 2043/2404 [42:03<07:54,  1.32s/it]

https://hiring.cafe/job/mnwojevr396j4be5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mnwojevr396j4be5.json.gz

 85%|████████▌ | 2044/2404 [42:04<08:26,  1.41s/it]

https://hiring.cafe/job/qt9qw26vqd2p2q3y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qt9qw26vqd2p2q3y.json.gz

 85%|████████▌ | 2045/2404 [42:05<07:37,  1.27s/it]

https://hiring.cafe/job/ko37ksr7mvgf8kmq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ko37ksr7mvgf8kmq.json.gz

 85%|████████▌ | 2046/2404 [42:07<08:32,  1.43s/it]

https://hiring.cafe/job/110dh25dnqump79t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\110dh25dnqump79t.json.gz

 85%|████████▌ | 2047/2404 [42:08<08:04,  1.36s/it]

https://hiring.cafe/job/zppvnn0mx6j42681
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zppvnn0mx6j42681.json.gz

 85%|████████▌ | 2048/2404 [42:09<07:39,  1.29s/it]

https://hiring.cafe/job/nyaukg48ir92vwhj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nyaukg48ir92vwhj.json.gz

 85%|████████▌ | 2049/2404 [42:11<07:57,  1.34s/it]

https://hiring.cafe/job/ys3oavxzb1zl1mnj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ys3oavxzb1zl1mnj.json.gz

 85%|████████▌ | 2050/2404 [42:12<08:14,  1.40s/it]

https://hiring.cafe/job/pm75k2zwnkqfaohq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pm75k2zwnkqfaohq.json.gz

 85%|████████▌ | 2051/2404 [42:14<07:49,  1.33s/it]

https://hiring.cafe/job/ifszhb77kpvleaik
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ifszhb77kpvleaik.json.gz

 85%|████████▌ | 2052/2404 [42:15<08:12,  1.40s/it]

https://hiring.cafe/job/re4xb5qykpv42xvv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\re4xb5qykpv42xvv.json.gz

 85%|████████▌ | 2053/2404 [42:16<07:55,  1.35s/it]

https://hiring.cafe/job/dvdja1kv8fhc306f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dvdja1kv8fhc306f.json.gz

 85%|████████▌ | 2054/2404 [42:18<08:03,  1.38s/it]

https://hiring.cafe/job/xpq53ixdegz8bl4t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xpq53ixdegz8bl4t.json.gz

 85%|████████▌ | 2055/2404 [42:19<08:06,  1.39s/it]

https://hiring.cafe/job/lq9fpe887azk4dql
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lq9fpe887azk4dql.json.gz

 86%|████████▌ | 2056/2404 [42:21<08:29,  1.46s/it]

https://hiring.cafe/job/33tn3lirwsx7yl25
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\33tn3lirwsx7yl25.json.gz

 86%|████████▌ | 2057/2404 [42:22<08:08,  1.41s/it]

https://hiring.cafe/job/uu6eprbuw96cmooy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uu6eprbuw96cmooy.json.gz

 86%|████████▌ | 2058/2404 [42:24<08:03,  1.40s/it]

https://hiring.cafe/job/uahevjjv4yemh63b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uahevjjv4yemh63b.json.gz

 86%|████████▌ | 2059/2404 [42:25<07:46,  1.35s/it]

https://hiring.cafe/job/hv374llnxskhg2t1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hv374llnxskhg2t1.json.gz

 86%|████████▌ | 2060/2404 [42:26<07:27,  1.30s/it]

https://hiring.cafe/job/of54jx8g996oti9u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\of54jx8g996oti9u.json.gz

 86%|████████▌ | 2061/2404 [42:27<07:31,  1.32s/it]

https://hiring.cafe/job/vsv9rgihatrobxcr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vsv9rgihatrobxcr.json.gz

 86%|████████▌ | 2062/2404 [42:29<07:25,  1.30s/it]

https://hiring.cafe/job/kpc45swjt935g589
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kpc45swjt935g589.json.gz

 86%|████████▌ | 2063/2404 [42:30<07:07,  1.25s/it]

https://hiring.cafe/job/7vc88viwqcpraonw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7vc88viwqcpraonw.json.gz

 86%|████████▌ | 2064/2404 [42:31<07:03,  1.25s/it]

https://hiring.cafe/job/dr6qwsml9k6nbshr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dr6qwsml9k6nbshr.json.gz

 86%|████████▌ | 2065/2404 [42:32<06:51,  1.21s/it]

https://hiring.cafe/job/niupg43c8pzxgu5u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\niupg43c8pzxgu5u.json.gz

 86%|████████▌ | 2066/2404 [42:33<06:29,  1.15s/it]

https://hiring.cafe/job/iw8dvu4kelpwcukd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iw8dvu4kelpwcukd.json.gz

 86%|████████▌ | 2067/2404 [42:34<06:46,  1.21s/it]

https://hiring.cafe/job/5wasiiwowndsrf2j
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5wasiiwowndsrf2j.json.gz

 86%|████████▌ | 2068/2404 [42:36<06:34,  1.17s/it]

https://hiring.cafe/job/5bdmqz8llusw02n1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5bdmqz8llusw02n1.json.gz

 86%|████████▌ | 2069/2404 [42:37<06:51,  1.23s/it]

https://hiring.cafe/job/j92l3twfw3rjbo2h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\j92l3twfw3rjbo2h.json.gz

 86%|████████▌ | 2070/2404 [42:38<06:54,  1.24s/it]

https://hiring.cafe/job/cmqnqlkgguisshyh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cmqnqlkgguisshyh.json.gz

 86%|████████▌ | 2071/2404 [42:39<06:41,  1.20s/it]

https://hiring.cafe/job/z71u4tqompc8qqsl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z71u4tqompc8qqsl.json.gz

 86%|████████▌ | 2072/2404 [42:40<06:39,  1.20s/it]

https://hiring.cafe/job/ob53leni4nn57hd6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ob53leni4nn57hd6.json.gz

 86%|████████▌ | 2073/2404 [42:42<06:59,  1.27s/it]

https://hiring.cafe/job/swm60r9ima4dh8cv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\swm60r9ima4dh8cv.json.gz

 86%|████████▋ | 2074/2404 [42:43<07:24,  1.35s/it]

https://hiring.cafe/job/6c0488du84y28dtq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6c0488du84y28dtq.json.gz

 86%|████████▋ | 2075/2404 [42:45<07:09,  1.31s/it]

https://hiring.cafe/job/bmssa0b66pzz7osj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bmssa0b66pzz7osj.json.gz

 86%|████████▋ | 2076/2404 [42:46<07:02,  1.29s/it]

https://hiring.cafe/job/o37b6qx46v66nvfd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o37b6qx46v66nvfd.json.gz

 86%|████████▋ | 2077/2404 [42:47<06:42,  1.23s/it]

https://hiring.cafe/job/oy0nksu0jmxjtkvb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oy0nksu0jmxjtkvb.json.gz

 86%|████████▋ | 2078/2404 [42:48<06:20,  1.17s/it]

https://hiring.cafe/job/bt4ozh8bzjnw43wd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bt4ozh8bzjnw43wd.json.gz

 86%|████████▋ | 2079/2404 [42:49<06:33,  1.21s/it]

https://hiring.cafe/job/p5m9rza3j4kmsnrr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\p5m9rza3j4kmsnrr.json.gz

 87%|████████▋ | 2080/2404 [42:51<07:30,  1.39s/it]

https://hiring.cafe/job/ofibiciufhp04qvw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ofibiciufhp04qvw.json.gz

 87%|████████▋ | 2081/2404 [42:52<06:58,  1.30s/it]

https://hiring.cafe/job/8eirm7914ycqjtkp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8eirm7914ycqjtkp.json.gz

 87%|████████▋ | 2082/2404 [42:53<06:52,  1.28s/it]

https://hiring.cafe/job/dzqzhhn0arm6jsbz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dzqzhhn0arm6jsbz.json.gz

 87%|████████▋ | 2083/2404 [42:55<06:57,  1.30s/it]

https://hiring.cafe/job/ql5rh8elwiqzjd0i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ql5rh8elwiqzjd0i.json.gz

 87%|████████▋ | 2084/2404 [42:56<07:13,  1.35s/it]

https://hiring.cafe/job/sixoep6heoyztq52
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\sixoep6heoyztq52.json.gz

 87%|████████▋ | 2085/2404 [42:57<06:50,  1.29s/it]

https://hiring.cafe/job/hr7ymbdrrb7s1vc5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hr7ymbdrrb7s1vc5.json.gz

 87%|████████▋ | 2086/2404 [42:59<06:33,  1.24s/it]

https://hiring.cafe/job/yq88b5oe1krbtqsa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yq88b5oe1krbtqsa.json.gz

 87%|████████▋ | 2087/2404 [42:59<06:04,  1.15s/it]

https://hiring.cafe/job/xx3e5lxymxfa9dxa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xx3e5lxymxfa9dxa.json.gz

 87%|████████▋ | 2088/2404 [43:01<06:21,  1.21s/it]

https://hiring.cafe/job/k6f5ypy2js2uj8p8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\k6f5ypy2js2uj8p8.json.gz

 87%|████████▋ | 2089/2404 [43:02<06:13,  1.18s/it]

https://hiring.cafe/job/wfv5wv0b1wtpob8f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wfv5wv0b1wtpob8f.json.gz

 87%|████████▋ | 2090/2404 [43:03<06:00,  1.15s/it]

https://hiring.cafe/job/yf053j53j341v6lg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yf053j53j341v6lg.json.gz

 87%|████████▋ | 2091/2404 [43:04<06:01,  1.16s/it]

https://hiring.cafe/job/ipq6afd88pgqq8x4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ipq6afd88pgqq8x4.json.gz

 87%|████████▋ | 2092/2404 [43:05<06:08,  1.18s/it]

https://hiring.cafe/job/d18nszc9acmz96dl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\d18nszc9acmz96dl.json.gz

 87%|████████▋ | 2093/2404 [43:07<06:11,  1.19s/it]

https://hiring.cafe/job/3tmf4zhbsoi2fcjb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3tmf4zhbsoi2fcjb.json.gz

 87%|████████▋ | 2094/2404 [43:08<06:12,  1.20s/it]

https://hiring.cafe/job/aqm2swubtesd81z3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\aqm2swubtesd81z3.json.gz

 87%|████████▋ | 2095/2404 [43:09<06:08,  1.19s/it]

https://hiring.cafe/job/624zn8m4axmjr647
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\624zn8m4axmjr647.json.gz

 87%|████████▋ | 2096/2404 [43:10<06:03,  1.18s/it]

https://hiring.cafe/job/i5plp0uetbf3jxyb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i5plp0uetbf3jxyb.json.gz

 87%|████████▋ | 2097/2404 [43:11<05:47,  1.13s/it]

https://hiring.cafe/job/uq8j62txk2kg2wkh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uq8j62txk2kg2wkh.json.gz

 87%|████████▋ | 2098/2404 [43:13<06:02,  1.19s/it]

https://hiring.cafe/job/4qwmht6t9xat157u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4qwmht6t9xat157u.json.gz

 87%|████████▋ | 2099/2404 [43:14<06:39,  1.31s/it]

https://hiring.cafe/job/3zrtp781ru6dq6bx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3zrtp781ru6dq6bx.json.gz

 87%|████████▋ | 2100/2404 [43:15<06:37,  1.31s/it]

https://hiring.cafe/job/q2cruq0ee8jrh0ti
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q2cruq0ee8jrh0ti.json.gz

 87%|████████▋ | 2101/2404 [43:17<06:44,  1.34s/it]

https://hiring.cafe/job/s7ohrh55x2dw7g8u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s7ohrh55x2dw7g8u.json.gz

 87%|████████▋ | 2102/2404 [43:18<06:39,  1.32s/it]

https://hiring.cafe/job/zee867ze8px7f307
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zee867ze8px7f307.json.gz

 87%|████████▋ | 2103/2404 [43:19<06:41,  1.33s/it]

https://hiring.cafe/job/c12uwb7rh3mv7gt2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c12uwb7rh3mv7gt2.json.gz

 88%|████████▊ | 2104/2404 [43:21<06:22,  1.27s/it]

https://hiring.cafe/job/kjnpzdz59117hyp1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kjnpzdz59117hyp1.json.gz

 88%|████████▊ | 2105/2404 [43:22<06:32,  1.31s/it]

https://hiring.cafe/job/knmpdhs5eug9l14x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\knmpdhs5eug9l14x.json.gz

 88%|████████▊ | 2106/2404 [43:23<06:40,  1.34s/it]

https://hiring.cafe/job/9d4huas9l9emo456
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9d4huas9l9emo456.json.gz

 88%|████████▊ | 2107/2404 [43:25<06:34,  1.33s/it]

https://hiring.cafe/job/fxdtbwthssm8na2v
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fxdtbwthssm8na2v.json.gz

 88%|████████▊ | 2108/2404 [43:26<06:32,  1.33s/it]

https://hiring.cafe/job/0rom1lckr6wl38ue
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0rom1lckr6wl38ue.json.gz

 88%|████████▊ | 2109/2404 [43:27<06:27,  1.31s/it]

https://hiring.cafe/job/v2s9rtrefj25lu5x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v2s9rtrefj25lu5x.json.gz

 88%|████████▊ | 2110/2404 [43:29<06:31,  1.33s/it]

https://hiring.cafe/job/3d0r5opi9ree7yh7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\3d0r5opi9ree7yh7.json.gz

 88%|████████▊ | 2111/2404 [43:30<06:34,  1.35s/it]

https://hiring.cafe/job/2et12ug8hufwcptw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2et12ug8hufwcptw.json.gz

 88%|████████▊ | 2112/2404 [43:31<06:04,  1.25s/it]

https://hiring.cafe/job/ht2n49jjx11w1ntv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ht2n49jjx11w1ntv.json.gz

 88%|████████▊ | 2113/2404 [43:32<05:59,  1.24s/it]

https://hiring.cafe/job/vjielu8d1u15v7s6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vjielu8d1u15v7s6.json.gz

 88%|████████▊ | 2114/2404 [43:34<06:04,  1.26s/it]

https://hiring.cafe/job/ktgf1xxj62hsoi9o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ktgf1xxj62hsoi9o.json.gz

 88%|████████▊ | 2115/2404 [43:35<06:22,  1.32s/it]

https://hiring.cafe/job/du4gx9naivfpevws
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\du4gx9naivfpevws.json.gz

 88%|████████▊ | 2116/2404 [43:36<06:21,  1.33s/it]

https://hiring.cafe/job/yxmxakrdu8af3s9k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yxmxakrdu8af3s9k.json.gz

 88%|████████▊ | 2117/2404 [43:38<06:03,  1.27s/it]

https://hiring.cafe/job/exprkcvxtjkbkiyy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\exprkcvxtjkbkiyy.json.gz

 88%|████████▊ | 2118/2404 [43:39<06:21,  1.33s/it]

https://hiring.cafe/job/r849tq3w9r7sxw4z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\r849tq3w9r7sxw4z.json.gz

 88%|████████▊ | 2119/2404 [43:41<06:32,  1.38s/it]

https://hiring.cafe/job/hu0e853exv8hb3mx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hu0e853exv8hb3mx.json.gz

 88%|████████▊ | 2120/2404 [43:42<06:21,  1.34s/it]

https://hiring.cafe/job/4f8jnznsum6yyofd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4f8jnznsum6yyofd.json.gz

 88%|████████▊ | 2121/2404 [43:43<06:33,  1.39s/it]

https://hiring.cafe/job/q8qxhlko0tynjx3h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q8qxhlko0tynjx3h.json.gz

 88%|████████▊ | 2122/2404 [43:44<06:13,  1.32s/it]

https://hiring.cafe/job/ilvnkm53be7k7s0i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ilvnkm53be7k7s0i.json.gz

 88%|████████▊ | 2123/2404 [43:46<05:55,  1.27s/it]

https://hiring.cafe/job/x8dsw7rs8gi0lyhw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x8dsw7rs8gi0lyhw.json.gz

 88%|████████▊ | 2124/2404 [43:47<05:46,  1.24s/it]

https://hiring.cafe/job/za60jdtcg67m2rwe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\za60jdtcg67m2rwe.json.gz

 88%|████████▊ | 2125/2404 [43:48<05:33,  1.19s/it]

https://hiring.cafe/job/wtvl1kflyp33d4y2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wtvl1kflyp33d4y2.json.gz

 88%|████████▊ | 2126/2404 [43:49<05:18,  1.15s/it]

https://hiring.cafe/job/ny09ermnow6pgl12
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ny09ermnow6pgl12.json.gz

 88%|████████▊ | 2127/2404 [43:50<05:47,  1.25s/it]

https://hiring.cafe/job/bgq4nnp9sbxmqdde
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bgq4nnp9sbxmqdde.json.gz

 89%|████████▊ | 2128/2404 [43:52<05:39,  1.23s/it]

https://hiring.cafe/job/ozzlckqd6due2xpa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ozzlckqd6due2xpa.json.gz

 89%|████████▊ | 2129/2404 [43:53<05:25,  1.18s/it]

https://hiring.cafe/job/ssat3v8mdtej3114
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ssat3v8mdtej3114.json.gz

 89%|████████▊ | 2130/2404 [43:54<05:41,  1.25s/it]

https://hiring.cafe/job/48cq9o5k4ul0zbu1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\48cq9o5k4ul0zbu1.json.gz

 89%|████████▊ | 2131/2404 [43:55<05:47,  1.27s/it]

https://hiring.cafe/job/5ypma5iaig9oabzx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5ypma5iaig9oabzx.json.gz

 89%|████████▊ | 2132/2404 [43:57<05:48,  1.28s/it]

https://hiring.cafe/job/o3dod510x53epxdo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o3dod510x53epxdo.json.gz

 89%|████████▊ | 2133/2404 [43:58<05:50,  1.29s/it]

https://hiring.cafe/job/nng61pn7jgz0ysrs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nng61pn7jgz0ysrs.json.gz

 89%|████████▉ | 2134/2404 [44:00<06:20,  1.41s/it]

https://hiring.cafe/job/zl9foaiamhgwtwj9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zl9foaiamhgwtwj9.json.gz

 89%|████████▉ | 2135/2404 [44:01<06:10,  1.38s/it]

https://hiring.cafe/job/2l3nbmddbsomfmo7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2l3nbmddbsomfmo7.json.gz

 89%|████████▉ | 2136/2404 [44:02<06:06,  1.37s/it]

https://hiring.cafe/job/pamlqs5yofxtlheb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pamlqs5yofxtlheb.json.gz

 89%|████████▉ | 2137/2404 [44:04<05:53,  1.33s/it]

https://hiring.cafe/job/c8jg9lw0x1cdwfb0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c8jg9lw0x1cdwfb0.json.gz

 89%|████████▉ | 2138/2404 [44:05<05:59,  1.35s/it]

https://hiring.cafe/job/gu1uiae3d3koyuz4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gu1uiae3d3koyuz4.json.gz

 89%|████████▉ | 2139/2404 [44:07<06:22,  1.44s/it]

https://hiring.cafe/job/6ktshzxi2jjhia0h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6ktshzxi2jjhia0h.json.gz

 89%|████████▉ | 2140/2404 [44:08<06:12,  1.41s/it]

https://hiring.cafe/job/ppenj0pj6ru2icrv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ppenj0pj6ru2icrv.json.gz

 89%|████████▉ | 2141/2404 [44:09<06:04,  1.38s/it]

https://hiring.cafe/job/9hb58s0jkwcxu69r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9hb58s0jkwcxu69r.json.gz

 89%|████████▉ | 2142/2404 [44:10<05:39,  1.30s/it]

https://hiring.cafe/job/go0car094ztkn166
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\go0car094ztkn166.json.gz

 89%|████████▉ | 2143/2404 [44:12<06:00,  1.38s/it]

https://hiring.cafe/job/s1yarvm3y2mz2pg0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s1yarvm3y2mz2pg0.json.gz

 89%|████████▉ | 2144/2404 [44:13<05:57,  1.37s/it]

https://hiring.cafe/job/jg0pfdprn9t9wfe7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jg0pfdprn9t9wfe7.json.gz

 89%|████████▉ | 2145/2404 [44:14<05:36,  1.30s/it]

https://hiring.cafe/job/vztv3m7gm0n2do14
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vztv3m7gm0n2do14.json.gz

 89%|████████▉ | 2146/2404 [44:16<05:42,  1.33s/it]

https://hiring.cafe/job/wq0lnx2fm15y5kpg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wq0lnx2fm15y5kpg.json.gz

 89%|████████▉ | 2147/2404 [44:17<06:07,  1.43s/it]

https://hiring.cafe/job/4ujjs6a8z73ql28m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4ujjs6a8z73ql28m.json.gz

 89%|████████▉ | 2148/2404 [44:20<06:58,  1.63s/it]

https://hiring.cafe/job/x6yiqge99ma36nut
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x6yiqge99ma36nut.json.gz

 89%|████████▉ | 2149/2404 [44:21<06:07,  1.44s/it]

https://hiring.cafe/job/7n18qwwveyqumv4i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7n18qwwveyqumv4i.json.gz

 89%|████████▉ | 2150/2404 [44:22<05:40,  1.34s/it]

https://hiring.cafe/job/54ni2nd7ktqmsmti
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\54ni2nd7ktqmsmti.json.gz

 89%|████████▉ | 2151/2404 [44:23<05:40,  1.35s/it]

https://hiring.cafe/job/4nfn8nh3feolysi4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4nfn8nh3feolysi4.json.gz

 90%|████████▉ | 2152/2404 [44:24<05:28,  1.30s/it]

https://hiring.cafe/job/xjyzc0y33lin9hrb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xjyzc0y33lin9hrb.json.gz

 90%|████████▉ | 2153/2404 [44:26<05:42,  1.36s/it]

https://hiring.cafe/job/yrlsw3jf7vmpr4se
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yrlsw3jf7vmpr4se.json.gz

 90%|████████▉ | 2154/2404 [44:28<07:10,  1.72s/it]

https://hiring.cafe/job/pr1nd8ubnuhe49n1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pr1nd8ubnuhe49n1.json.gz

 90%|████████▉ | 2155/2404 [44:30<06:56,  1.67s/it]

https://hiring.cafe/job/7qsrjp2qsftz7xhx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7qsrjp2qsftz7xhx.json.gz

 90%|████████▉ | 2156/2404 [44:31<06:23,  1.55s/it]

https://hiring.cafe/job/fxbmvtxwhz2cjcxz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fxbmvtxwhz2cjcxz.json.gz

 90%|████████▉ | 2157/2404 [44:32<06:03,  1.47s/it]

https://hiring.cafe/job/8rze3e3v3q4t7mao
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8rze3e3v3q4t7mao.json.gz

 90%|████████▉ | 2158/2404 [44:35<07:05,  1.73s/it]

https://hiring.cafe/job/hfh69bd9vxy270c9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hfh69bd9vxy270c9.json.gz

 90%|████████▉ | 2159/2404 [44:37<08:01,  1.96s/it]

https://hiring.cafe/job/idivlr5bu6y9ttdr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\idivlr5bu6y9ttdr.json.gz

 90%|████████▉ | 2160/2404 [44:40<09:06,  2.24s/it]

https://hiring.cafe/job/uomr7sf3yw2o5z8a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uomr7sf3yw2o5z8a.json.gz

 90%|████████▉ | 2161/2404 [44:41<07:34,  1.87s/it]

https://hiring.cafe/job/7fntl5a89lqdtdib
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7fntl5a89lqdtdib.json.gz

 90%|████████▉ | 2162/2404 [44:43<07:21,  1.83s/it]

https://hiring.cafe/job/twi8avi6q9igpgvx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\twi8avi6q9igpgvx.json.gz

 90%|████████▉ | 2163/2404 [44:44<06:40,  1.66s/it]

https://hiring.cafe/job/4wblyqww3jeq4vy2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4wblyqww3jeq4vy2.json.gz

 90%|█████████ | 2164/2404 [44:45<06:10,  1.54s/it]

https://hiring.cafe/job/g651j8a9se4kdebg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g651j8a9se4kdebg.json.gz

 90%|█████████ | 2165/2404 [44:46<05:27,  1.37s/it]

https://hiring.cafe/job/01ppz1hfaydkvt4m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\01ppz1hfaydkvt4m.json.gz

 90%|█████████ | 2166/2404 [44:48<05:23,  1.36s/it]

https://hiring.cafe/job/7vwc1d92nooo23q8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7vwc1d92nooo23q8.json.gz

 90%|█████████ | 2167/2404 [44:49<05:18,  1.34s/it]

https://hiring.cafe/job/mdwxbmy41eca6tws
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mdwxbmy41eca6tws.json.gz

 90%|█████████ | 2168/2404 [44:50<05:20,  1.36s/it]

https://hiring.cafe/job/tojbxre82y79onun
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\tojbxre82y79onun.json.gz

 90%|█████████ | 2169/2404 [44:52<05:24,  1.38s/it]

https://hiring.cafe/job/bpyvug2j61mfhvo1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bpyvug2j61mfhvo1.json.gz

 90%|█████████ | 2170/2404 [44:53<04:55,  1.26s/it]

https://hiring.cafe/job/i6xy759q9rxyu3zt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\i6xy759q9rxyu3zt.json.gz

 90%|█████████ | 2171/2404 [44:54<04:56,  1.27s/it]

https://hiring.cafe/job/1u99jt0kg3xasaz8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\1u99jt0kg3xasaz8.json.gz

 90%|█████████ | 2172/2404 [44:56<05:08,  1.33s/it]

https://hiring.cafe/job/l8vaij4tsaaaafuk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l8vaij4tsaaaafuk.json.gz

 90%|█████████ | 2173/2404 [44:57<04:59,  1.30s/it]

https://hiring.cafe/job/cq4g1bgzazhsyo34
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cq4g1bgzazhsyo34.json.gz

 90%|█████████ | 2174/2404 [44:58<05:08,  1.34s/it]

https://hiring.cafe/job/g9ge4jd7tpj2agff
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g9ge4jd7tpj2agff.json.gz

 90%|█████████ | 2175/2404 [45:00<05:08,  1.35s/it]

https://hiring.cafe/job/gkxsj2jzv76mqgm1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gkxsj2jzv76mqgm1.json.gz

 91%|█████████ | 2176/2404 [45:01<05:14,  1.38s/it]

https://hiring.cafe/job/kzfm35qkij2l52vd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kzfm35qkij2l52vd.json.gz

 91%|█████████ | 2177/2404 [45:02<05:07,  1.35s/it]

https://hiring.cafe/job/ll5g0qxsz7lz65em
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ll5g0qxsz7lz65em.json.gz

 91%|█████████ | 2178/2404 [45:04<04:59,  1.33s/it]

https://hiring.cafe/job/t4q34peecddkwqep
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t4q34peecddkwqep.json.gz

 91%|█████████ | 2179/2404 [45:05<04:55,  1.31s/it]

https://hiring.cafe/job/2n400exheivszf0b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2n400exheivszf0b.json.gz

 91%|█████████ | 2180/2404 [45:06<04:59,  1.34s/it]

https://hiring.cafe/job/w6sjtp5qdwul9fwa
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w6sjtp5qdwul9fwa.json.gz

 91%|█████████ | 2181/2404 [45:08<05:00,  1.35s/it]

https://hiring.cafe/job/a37ew0wzbqxdlaxj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\a37ew0wzbqxdlaxj.json.gz

 91%|█████████ | 2182/2404 [45:09<04:46,  1.29s/it]

https://hiring.cafe/job/q3uv7jbnaeyrma0z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q3uv7jbnaeyrma0z.json.gz

 91%|█████████ | 2183/2404 [45:10<04:43,  1.28s/it]

https://hiring.cafe/job/6e80hd7yd1hgkf8k
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6e80hd7yd1hgkf8k.json.gz

 91%|█████████ | 2184/2404 [45:11<04:45,  1.30s/it]

https://hiring.cafe/job/z8rfstarxv242z6y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z8rfstarxv242z6y.json.gz

 91%|█████████ | 2185/2404 [45:13<05:05,  1.40s/it]

https://hiring.cafe/job/qwn09sp7qn6xac8x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qwn09sp7qn6xac8x.json.gz

 91%|█████████ | 2186/2404 [45:14<04:44,  1.30s/it]

https://hiring.cafe/job/slnygantp6k991fm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\slnygantp6k991fm.json.gz

 91%|█████████ | 2187/2404 [45:15<04:27,  1.23s/it]

https://hiring.cafe/job/kvkeyp77381p1tze
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kvkeyp77381p1tze.json.gz

 91%|█████████ | 2188/2404 [45:16<04:28,  1.24s/it]

https://hiring.cafe/job/f7cfeapucsqlct9f
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\f7cfeapucsqlct9f.json.gz

 91%|█████████ | 2189/2404 [45:18<04:41,  1.31s/it]

https://hiring.cafe/job/mfxezz16ygxrc7oy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mfxezz16ygxrc7oy.json.gz

 91%|█████████ | 2190/2404 [45:19<04:49,  1.35s/it]

https://hiring.cafe/job/295oc2hzg8pwc060
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\295oc2hzg8pwc060.json.gz

 91%|█████████ | 2191/2404 [45:21<04:39,  1.31s/it]

https://hiring.cafe/job/iujtx18ms5awfm3p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iujtx18ms5awfm3p.json.gz

 91%|█████████ | 2192/2404 [45:22<05:08,  1.45s/it]

https://hiring.cafe/job/75wc0eqzjwdx0dd3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\75wc0eqzjwdx0dd3.json.gz

 91%|█████████ | 2193/2404 [45:23<04:39,  1.32s/it]

https://hiring.cafe/job/vmq4evgjivd93q3o
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vmq4evgjivd93q3o.json.gz

 91%|█████████▏| 2194/2404 [45:25<04:37,  1.32s/it]

https://hiring.cafe/job/adqw4zx98o6pllun
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\adqw4zx98o6pllun.json.gz

 91%|█████████▏| 2195/2404 [45:26<04:45,  1.37s/it]

https://hiring.cafe/job/unu4bvj4w29k83io
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\unu4bvj4w29k83io.json.gz

 91%|█████████▏| 2196/2404 [45:27<04:31,  1.30s/it]

https://hiring.cafe/job/h0dhts4mdqmobzuc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h0dhts4mdqmobzuc.json.gz

 91%|█████████▏| 2197/2404 [45:28<04:05,  1.19s/it]

https://hiring.cafe/job/enrgpb48ek3pplc5
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\enrgpb48ek3pplc5.json.gz

 91%|█████████▏| 2198/2404 [45:30<04:08,  1.20s/it]

https://hiring.cafe/job/ex1gch07dyife4ay
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ex1gch07dyife4ay.json.gz

 91%|█████████▏| 2199/2404 [45:31<04:11,  1.23s/it]

https://hiring.cafe/job/v5s544z9bbhw91dx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v5s544z9bbhw91dx.json.gz

 92%|█████████▏| 2200/2404 [45:32<04:29,  1.32s/it]

https://hiring.cafe/job/ym67yrezseym4p0u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ym67yrezseym4p0u.json.gz

 92%|█████████▏| 2201/2404 [45:34<04:20,  1.28s/it]

https://hiring.cafe/job/82teatrkfdwscevi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\82teatrkfdwscevi.json.gz

 92%|█████████▏| 2202/2404 [45:35<04:16,  1.27s/it]

https://hiring.cafe/job/4izicfbopextmw1i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4izicfbopextmw1i.json.gz

 92%|█████████▏| 2203/2404 [45:36<04:15,  1.27s/it]

https://hiring.cafe/job/g3czgugykvhjyt9b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g3czgugykvhjyt9b.json.gz

 92%|█████████▏| 2204/2404 [45:37<04:19,  1.30s/it]

https://hiring.cafe/job/ez2vufkynbkggpb1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ez2vufkynbkggpb1.json.gz

 92%|█████████▏| 2205/2404 [45:39<04:29,  1.35s/it]

https://hiring.cafe/job/mrkmyhnkworrupri
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mrkmyhnkworrupri.json.gz

 92%|█████████▏| 2206/2404 [45:40<04:40,  1.42s/it]

https://hiring.cafe/job/2bnfmb58mo70l63r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2bnfmb58mo70l63r.json.gz

 92%|█████████▏| 2207/2404 [45:42<04:18,  1.31s/it]

https://hiring.cafe/job/9fmn2ou8q0gmb5zg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9fmn2ou8q0gmb5zg.json.gz

 92%|█████████▏| 2208/2404 [45:43<04:10,  1.28s/it]

https://hiring.cafe/job/m6612y3mojy1ogzk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\m6612y3mojy1ogzk.json.gz

 92%|█████████▏| 2209/2404 [45:44<04:00,  1.23s/it]

https://hiring.cafe/job/z3koj5rxrb8elw4m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z3koj5rxrb8elw4m.json.gz

 92%|█████████▏| 2210/2404 [45:45<04:14,  1.31s/it]

https://hiring.cafe/job/vuzmibf22dflvxc2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vuzmibf22dflvxc2.json.gz

 92%|█████████▏| 2211/2404 [45:47<04:18,  1.34s/it]

https://hiring.cafe/job/6p4buk17osxz5tiw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6p4buk17osxz5tiw.json.gz

 92%|█████████▏| 2212/2404 [45:48<04:20,  1.36s/it]

https://hiring.cafe/job/h6wq3jeo5l13wuu8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h6wq3jeo5l13wuu8.json.gz

 92%|█████████▏| 2213/2404 [45:49<04:07,  1.30s/it]

https://hiring.cafe/job/2gniz2zvjzmfohtn
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2gniz2zvjzmfohtn.json.gz

 92%|█████████▏| 2214/2404 [45:50<03:59,  1.26s/it]

https://hiring.cafe/job/ld49fxuonzd7zial
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ld49fxuonzd7zial.json.gz

 92%|█████████▏| 2215/2404 [45:52<03:54,  1.24s/it]

https://hiring.cafe/job/w6yeg9szr1b26852
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w6yeg9szr1b26852.json.gz

 92%|█████████▏| 2216/2404 [45:53<03:58,  1.27s/it]

https://hiring.cafe/job/al8bxhc1b0rxvkjt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\al8bxhc1b0rxvkjt.json.gz

 92%|█████████▏| 2217/2404 [45:57<06:34,  2.11s/it]

https://hiring.cafe/job/36f592nscg8w6hk2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\36f592nscg8w6hk2.json.gz

 92%|█████████▏| 2218/2404 [45:58<05:46,  1.86s/it]

https://hiring.cafe/job/485x8io27lwg40su
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\485x8io27lwg40su.json.gz

 92%|█████████▏| 2219/2404 [46:00<05:26,  1.76s/it]

https://hiring.cafe/job/vy7niwrzvia6ltu4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vy7niwrzvia6ltu4.json.gz

 92%|█████████▏| 2220/2404 [46:01<05:10,  1.69s/it]

https://hiring.cafe/job/7bmqkskfwu0g632w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7bmqkskfwu0g632w.json.gz

 92%|█████████▏| 2221/2404 [46:03<04:42,  1.54s/it]

https://hiring.cafe/job/nz1qpt9wckjhibu4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nz1qpt9wckjhibu4.json.gz

 92%|█████████▏| 2222/2404 [46:04<04:33,  1.50s/it]

https://hiring.cafe/job/kk3jgwpsx6ofhxhl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kk3jgwpsx6ofhxhl.json.gz

 92%|█████████▏| 2223/2404 [46:05<04:27,  1.48s/it]

https://hiring.cafe/job/2hoo6m6xje7aj529
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\2hoo6m6xje7aj529.json.gz

 93%|█████████▎| 2224/2404 [46:07<04:18,  1.43s/it]

https://hiring.cafe/job/y0nqvh7zz59b7ymt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\y0nqvh7zz59b7ymt.json.gz

 93%|█████████▎| 2225/2404 [46:08<04:15,  1.43s/it]

https://hiring.cafe/job/bjppma3fhz38373x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bjppma3fhz38373x.json.gz

 93%|█████████▎| 2226/2404 [46:09<04:03,  1.37s/it]

https://hiring.cafe/job/l9vlpojtc5ndv5vi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l9vlpojtc5ndv5vi.json.gz

 93%|█████████▎| 2227/2404 [46:11<03:53,  1.32s/it]

https://hiring.cafe/job/z9flswbftcxfclik
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z9flswbftcxfclik.json.gz

 93%|█████████▎| 2228/2404 [46:12<04:02,  1.38s/it]

https://hiring.cafe/job/u5lzlatiyqq71yg9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u5lzlatiyqq71yg9.json.gz

 93%|█████████▎| 2229/2404 [46:13<03:52,  1.33s/it]

https://hiring.cafe/job/mqkxcbfce3aatyep
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mqkxcbfce3aatyep.json.gz

 93%|█████████▎| 2230/2404 [46:15<03:43,  1.28s/it]

https://hiring.cafe/job/ivi9qwtuovis7tq3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ivi9qwtuovis7tq3.json.gz

 93%|█████████▎| 2231/2404 [46:16<03:48,  1.32s/it]

https://hiring.cafe/job/alapuhjfiibolbtp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\alapuhjfiibolbtp.json.gz

 93%|█████████▎| 2232/2404 [46:17<03:47,  1.32s/it]

https://hiring.cafe/job/on2jx73ym5csqk8l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\on2jx73ym5csqk8l.json.gz

 93%|█████████▎| 2233/2404 [46:18<03:36,  1.26s/it]

https://hiring.cafe/job/jelgltw2mgvy46a1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jelgltw2mgvy46a1.json.gz

 93%|█████████▎| 2234/2404 [46:20<03:34,  1.26s/it]

https://hiring.cafe/job/kiqwdehngkre4idu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kiqwdehngkre4idu.json.gz

 93%|█████████▎| 2235/2404 [46:21<03:40,  1.30s/it]

https://hiring.cafe/job/wp1040cxn6wfalyh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wp1040cxn6wfalyh.json.gz

 93%|█████████▎| 2236/2404 [46:22<03:45,  1.34s/it]

https://hiring.cafe/job/958l1kwhrh0z55vf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\958l1kwhrh0z55vf.json.gz

 93%|█████████▎| 2237/2404 [46:24<03:36,  1.30s/it]

https://hiring.cafe/job/mn5ay8s9u1kj1q6b
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mn5ay8s9u1kj1q6b.json.gz

 93%|█████████▎| 2238/2404 [46:25<03:23,  1.23s/it]

https://hiring.cafe/job/pbkyrsegn4y6hszv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\pbkyrsegn4y6hszv.json.gz

 93%|█████████▎| 2239/2404 [46:26<03:31,  1.28s/it]

https://hiring.cafe/job/vv1z18qwwmxplrah
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vv1z18qwwmxplrah.json.gz

 93%|█████████▎| 2240/2404 [46:27<03:31,  1.29s/it]

https://hiring.cafe/job/mkd2ll8kfxy0kyg6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mkd2ll8kfxy0kyg6.json.gz

 93%|█████████▎| 2241/2404 [46:29<03:20,  1.23s/it]

https://hiring.cafe/job/31j0v3uzridx045c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\31j0v3uzridx045c.json.gz

 93%|█████████▎| 2242/2404 [46:30<03:27,  1.28s/it]

https://hiring.cafe/job/b0u2vzymoys3c6tv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\b0u2vzymoys3c6tv.json.gz

 93%|█████████▎| 2243/2404 [46:31<03:25,  1.28s/it]

https://hiring.cafe/job/gszpfek1u1r6bx8s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gszpfek1u1r6bx8s.json.gz

 93%|█████████▎| 2244/2404 [46:32<03:22,  1.27s/it]

https://hiring.cafe/job/nrdlsygrsvjmhk9s
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nrdlsygrsvjmhk9s.json.gz

 93%|█████████▎| 2245/2404 [46:34<03:20,  1.26s/it]

https://hiring.cafe/job/hl4mzckz3jxq6990
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hl4mzckz3jxq6990.json.gz

 93%|█████████▎| 2246/2404 [46:35<03:07,  1.19s/it]

https://hiring.cafe/job/56isd28sgi3eeaiv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\56isd28sgi3eeaiv.json.gz

 93%|█████████▎| 2247/2404 [46:36<03:07,  1.20s/it]

https://hiring.cafe/job/itjbnxlafghedyjl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\itjbnxlafghedyjl.json.gz

 94%|█████████▎| 2248/2404 [46:37<03:20,  1.29s/it]

https://hiring.cafe/job/cz8gcrddqqlrx4u3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cz8gcrddqqlrx4u3.json.gz

 94%|█████████▎| 2249/2404 [46:39<03:25,  1.33s/it]

https://hiring.cafe/job/atkg808pc65i2r79
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\atkg808pc65i2r79.json.gz

 94%|█████████▎| 2250/2404 [46:40<03:25,  1.33s/it]

https://hiring.cafe/job/blhb1r8zkm0lj2gl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\blhb1r8zkm0lj2gl.json.gz

 94%|█████████▎| 2251/2404 [46:41<03:13,  1.27s/it]

https://hiring.cafe/job/ck6xpoea47i53miv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ck6xpoea47i53miv.json.gz

 94%|█████████▎| 2252/2404 [46:43<03:13,  1.27s/it]

https://hiring.cafe/job/h8f1muzxl0xm4mis
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h8f1muzxl0xm4mis.json.gz

 94%|█████████▎| 2253/2404 [46:44<03:09,  1.26s/it]

https://hiring.cafe/job/vsamscwjv2meic15
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vsamscwjv2meic15.json.gz

 94%|█████████▍| 2254/2404 [46:45<03:19,  1.33s/it]

https://hiring.cafe/job/37zp8g6lom2cynjo
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\37zp8g6lom2cynjo.json.gz

 94%|█████████▍| 2255/2404 [46:47<03:16,  1.32s/it]

https://hiring.cafe/job/l8ig1i0e2p3vyzkx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l8ig1i0e2p3vyzkx.json.gz

 94%|█████████▍| 2256/2404 [46:48<03:10,  1.28s/it]

https://hiring.cafe/job/zrcse1dccg9m3qjj
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zrcse1dccg9m3qjj.json.gz

 94%|█████████▍| 2257/2404 [46:49<03:07,  1.28s/it]

https://hiring.cafe/job/disz8hjoh6oy7wzh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\disz8hjoh6oy7wzh.json.gz

 94%|█████████▍| 2258/2404 [46:50<03:07,  1.28s/it]

https://hiring.cafe/job/0xcfre0duqn3xg9n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0xcfre0duqn3xg9n.json.gz

 94%|█████████▍| 2259/2404 [46:52<03:11,  1.32s/it]

https://hiring.cafe/job/xvrt3f0dvm00ug84
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xvrt3f0dvm00ug84.json.gz

 94%|█████████▍| 2260/2404 [46:53<03:18,  1.38s/it]

https://hiring.cafe/job/ddnahbewqbt86liz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ddnahbewqbt86liz.json.gz

 94%|█████████▍| 2261/2404 [46:54<02:52,  1.21s/it]

https://hiring.cafe/job/l01ux1p8k481msyh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\l01ux1p8k481msyh.json.gz

 94%|█████████▍| 2262/2404 [46:56<03:01,  1.28s/it]

https://hiring.cafe/job/okh0n0h80y0eye1h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\okh0n0h80y0eye1h.json.gz

 94%|█████████▍| 2263/2404 [46:57<03:06,  1.32s/it]

https://hiring.cafe/job/zkdc5xertr5wda3l
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zkdc5xertr5wda3l.json.gz

 94%|█████████▍| 2264/2404 [46:58<03:06,  1.33s/it]

https://hiring.cafe/job/mhnqo549lf8401tp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mhnqo549lf8401tp.json.gz

 94%|█████████▍| 2265/2404 [47:00<03:11,  1.38s/it]

https://hiring.cafe/job/0w6dud50muu7zntx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0w6dud50muu7zntx.json.gz

 94%|█████████▍| 2266/2404 [47:01<03:16,  1.43s/it]

https://hiring.cafe/job/hynio32e0zpf9ea8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hynio32e0zpf9ea8.json.gz

 94%|█████████▍| 2267/2404 [47:02<03:01,  1.32s/it]

https://hiring.cafe/job/iwl6d1p096n8u8yl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\iwl6d1p096n8u8yl.json.gz

 94%|█████████▍| 2268/2404 [47:04<03:13,  1.43s/it]

https://hiring.cafe/job/yovtovu8n8c4znj4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yovtovu8n8c4znj4.json.gz

 94%|█████████▍| 2269/2404 [47:05<03:00,  1.34s/it]

https://hiring.cafe/job/6ql2suy8pciur7ej
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6ql2suy8pciur7ej.json.gz

 94%|█████████▍| 2270/2404 [47:07<02:56,  1.32s/it]

https://hiring.cafe/job/6qwip8rji04uf0dh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6qwip8rji04uf0dh.json.gz

 94%|█████████▍| 2271/2404 [47:08<02:50,  1.28s/it]

https://hiring.cafe/job/oac8h9wejdsx4vra
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oac8h9wejdsx4vra.json.gz

 95%|█████████▍| 2272/2404 [47:09<02:51,  1.30s/it]

https://hiring.cafe/job/25c4jynzw78dnv5c
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\25c4jynzw78dnv5c.json.gz

 95%|█████████▍| 2273/2404 [47:10<02:41,  1.23s/it]

https://hiring.cafe/job/v1nm86kcac9tej98
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\v1nm86kcac9tej98.json.gz

 95%|█████████▍| 2274/2404 [47:11<02:37,  1.21s/it]

https://hiring.cafe/job/6tbklra9ozsuyfen
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6tbklra9ozsuyfen.json.gz

 95%|█████████▍| 2275/2404 [47:13<02:37,  1.22s/it]

https://hiring.cafe/job/zh9fiqzcg7z4iy1w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zh9fiqzcg7z4iy1w.json.gz

 95%|█████████▍| 2276/2404 [47:14<02:38,  1.24s/it]

https://hiring.cafe/job/kvh24c0m62ps2mcw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kvh24c0m62ps2mcw.json.gz

 95%|█████████▍| 2277/2404 [47:15<02:38,  1.24s/it]

https://hiring.cafe/job/mvf304pup20u2ynt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\mvf304pup20u2ynt.json.gz

 95%|█████████▍| 2278/2404 [47:17<02:45,  1.31s/it]

https://hiring.cafe/job/37zzz56zxqdk2cb3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\37zzz56zxqdk2cb3.json.gz

 95%|█████████▍| 2279/2404 [47:18<02:44,  1.32s/it]

https://hiring.cafe/job/wf6wf0as7am502i2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wf6wf0as7am502i2.json.gz

 95%|█████████▍| 2280/2404 [47:19<02:36,  1.26s/it]

https://hiring.cafe/job/efaplkh4l6j5ax9i
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\efaplkh4l6j5ax9i.json.gz

 95%|█████████▍| 2281/2404 [47:20<02:38,  1.29s/it]

https://hiring.cafe/job/qd62xffvu1tcqbal
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qd62xffvu1tcqbal.json.gz

 95%|█████████▍| 2282/2404 [47:22<02:40,  1.31s/it]

https://hiring.cafe/job/towd975xb21s8swb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\towd975xb21s8swb.json.gz

 95%|█████████▍| 2283/2404 [47:23<02:48,  1.39s/it]

https://hiring.cafe/job/eptb7gkthvapu9ih
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\eptb7gkthvapu9ih.json.gz

 95%|█████████▌| 2284/2404 [47:25<02:39,  1.33s/it]

https://hiring.cafe/job/5s026nmg80z0uy8e
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5s026nmg80z0uy8e.json.gz

 95%|█████████▌| 2285/2404 [47:26<02:44,  1.38s/it]

https://hiring.cafe/job/6357sghlrdqb68cs
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6357sghlrdqb68cs.json.gz

 95%|█████████▌| 2286/2404 [47:27<02:34,  1.31s/it]

https://hiring.cafe/job/37u15fbp7mial9ln
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\37u15fbp7mial9ln.json.gz

 95%|█████████▌| 2287/2404 [47:29<02:40,  1.37s/it]

https://hiring.cafe/job/yl0f4iiqrqn6pns1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yl0f4iiqrqn6pns1.json.gz

 95%|█████████▌| 2288/2404 [47:30<02:33,  1.33s/it]

https://hiring.cafe/job/bvwyvn5nekumf5fy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bvwyvn5nekumf5fy.json.gz

 95%|█████████▌| 2289/2404 [47:31<02:27,  1.28s/it]

https://hiring.cafe/job/7vil6q7mobep27ob
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7vil6q7mobep27ob.json.gz

 95%|█████████▌| 2290/2404 [47:32<02:25,  1.28s/it]

https://hiring.cafe/job/wf68ihmwaujnp9vp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wf68ihmwaujnp9vp.json.gz

 95%|█████████▌| 2291/2404 [47:34<02:30,  1.33s/it]

https://hiring.cafe/job/s25pii6lguswtdvr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\s25pii6lguswtdvr.json.gz

 95%|█████████▌| 2292/2404 [47:35<02:31,  1.36s/it]

https://hiring.cafe/job/xpbtp5n66re4usbc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xpbtp5n66re4usbc.json.gz

 95%|█████████▌| 2293/2404 [47:36<02:16,  1.23s/it]

https://hiring.cafe/job/qp9rpfqac340su0q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qp9rpfqac340su0q.json.gz

 95%|█████████▌| 2294/2404 [47:38<02:26,  1.33s/it]

https://hiring.cafe/job/oul0uxzut1fbewy8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\oul0uxzut1fbewy8.json.gz

 95%|█████████▌| 2295/2404 [47:39<02:32,  1.40s/it]

https://hiring.cafe/job/jmof8ayw2hsivn1r
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jmof8ayw2hsivn1r.json.gz

 96%|█████████▌| 2296/2404 [47:41<02:27,  1.36s/it]

https://hiring.cafe/job/994gs1ts7vbxwc5m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\994gs1ts7vbxwc5m.json.gz

 96%|█████████▌| 2297/2404 [47:42<02:16,  1.28s/it]

https://hiring.cafe/job/okym8lvoepntwdyu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\okym8lvoepntwdyu.json.gz

 96%|█████████▌| 2298/2404 [47:43<02:09,  1.23s/it]

https://hiring.cafe/job/o1oh2uqkh5yysgh7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\o1oh2uqkh5yysgh7.json.gz

 96%|█████████▌| 2299/2404 [47:44<02:08,  1.23s/it]

https://hiring.cafe/job/gg32rcery4025dr6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gg32rcery4025dr6.json.gz

 96%|█████████▌| 2300/2404 [47:45<02:10,  1.26s/it]

https://hiring.cafe/job/4h8qvq6igr9jc7a2
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4h8qvq6igr9jc7a2.json.gz

 96%|█████████▌| 2301/2404 [47:47<02:17,  1.34s/it]

https://hiring.cafe/job/8lkcxc2kmcmmhc9d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8lkcxc2kmcmmhc9d.json.gz

 96%|█████████▌| 2302/2404 [47:48<02:10,  1.28s/it]

https://hiring.cafe/job/54a4cf8puqx4spid
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\54a4cf8puqx4spid.json.gz

 96%|█████████▌| 2303/2404 [47:49<02:08,  1.27s/it]

https://hiring.cafe/job/yl7nzed2g7wneyoc
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yl7nzed2g7wneyoc.json.gz

 96%|█████████▌| 2304/2404 [47:50<01:57,  1.18s/it]

https://hiring.cafe/job/xijxngq59q7ruzr0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xijxngq59q7ruzr0.json.gz

 96%|█████████▌| 2305/2404 [47:51<01:54,  1.15s/it]

https://hiring.cafe/job/uutrfk9sd9pjchc6
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uutrfk9sd9pjchc6.json.gz

 96%|█████████▌| 2306/2404 [47:52<01:52,  1.15s/it]

https://hiring.cafe/job/wlh0zpr1hjvft98p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wlh0zpr1hjvft98p.json.gz

 96%|█████████▌| 2307/2404 [47:54<01:58,  1.22s/it]

https://hiring.cafe/job/q0v1824kj8lomels
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\q0v1824kj8lomels.json.gz

 96%|█████████▌| 2308/2404 [47:55<02:03,  1.28s/it]

https://hiring.cafe/job/lt8ourd04eddqnzk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lt8ourd04eddqnzk.json.gz

 96%|█████████▌| 2309/2404 [47:56<02:01,  1.28s/it]

https://hiring.cafe/job/4tmq1hspba82ne54
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4tmq1hspba82ne54.json.gz

 96%|█████████▌| 2310/2404 [47:58<02:01,  1.29s/it]

https://hiring.cafe/job/rch2qkdouhjjj5ie
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rch2qkdouhjjj5ie.json.gz

 96%|█████████▌| 2311/2404 [47:59<01:58,  1.28s/it]

https://hiring.cafe/job/w2nfac72coirdp2y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w2nfac72coirdp2y.json.gz

 96%|█████████▌| 2312/2404 [48:00<01:58,  1.29s/it]

https://hiring.cafe/job/c64umeb0r9mwrqcl
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\c64umeb0r9mwrqcl.json.gz

 96%|█████████▌| 2313/2404 [48:02<02:01,  1.33s/it]

https://hiring.cafe/job/g2xe42a0yrlaj3x4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g2xe42a0yrlaj3x4.json.gz

 96%|█████████▋| 2314/2404 [48:03<02:02,  1.37s/it]

https://hiring.cafe/job/yrgn4gie02pem1kx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\yrgn4gie02pem1kx.json.gz

 96%|█████████▋| 2315/2404 [48:04<01:56,  1.31s/it]

https://hiring.cafe/job/dnzyukg1zqnolmcr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dnzyukg1zqnolmcr.json.gz

 96%|█████████▋| 2316/2404 [48:06<01:51,  1.27s/it]

https://hiring.cafe/job/7u3rt4gh9ejb5g2n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7u3rt4gh9ejb5g2n.json.gz

 96%|█████████▋| 2317/2404 [48:07<01:56,  1.34s/it]

https://hiring.cafe/job/x9b40ycsyw60x6in
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x9b40ycsyw60x6in.json.gz

 96%|█████████▋| 2318/2404 [48:09<01:58,  1.38s/it]

https://hiring.cafe/job/0q2wr2zzvhcaw6uk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0q2wr2zzvhcaw6uk.json.gz

 96%|█████████▋| 2319/2404 [48:10<02:00,  1.42s/it]

https://hiring.cafe/job/8zd1m0b9rcaind4z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\8zd1m0b9rcaind4z.json.gz

 97%|█████████▋| 2320/2404 [48:11<01:56,  1.39s/it]

https://hiring.cafe/job/0ocbimfs8r6z3d0g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\0ocbimfs8r6z3d0g.json.gz

 97%|█████████▋| 2321/2404 [48:13<01:51,  1.34s/it]

https://hiring.cafe/job/w77q0shkm8as2hjg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w77q0shkm8as2hjg.json.gz

 97%|█████████▋| 2322/2404 [48:14<01:55,  1.40s/it]

https://hiring.cafe/job/5fyfigd13clf7du3
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5fyfigd13clf7du3.json.gz

 97%|█████████▋| 2323/2404 [48:15<01:46,  1.31s/it]

https://hiring.cafe/job/57wa6up6zwlfz904
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\57wa6up6zwlfz904.json.gz

 97%|█████████▋| 2324/2404 [48:17<01:47,  1.35s/it]

https://hiring.cafe/job/hrs6pghf5q5xx0gg
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hrs6pghf5q5xx0gg.json.gz

 97%|█████████▋| 2325/2404 [48:18<01:42,  1.29s/it]

https://hiring.cafe/job/9gzlydtywlj4nh0g
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9gzlydtywlj4nh0g.json.gz

 97%|█████████▋| 2326/2404 [48:19<01:40,  1.29s/it]

https://hiring.cafe/job/gr1ou0s7qq380qfe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\gr1ou0s7qq380qfe.json.gz

 97%|█████████▋| 2327/2404 [48:20<01:40,  1.30s/it]

https://hiring.cafe/job/w5ckydgvxomfe669
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w5ckydgvxomfe669.json.gz

 97%|█████████▋| 2328/2404 [48:22<01:34,  1.24s/it]

https://hiring.cafe/job/4xuglf3tbdlx9puz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4xuglf3tbdlx9puz.json.gz

 97%|█████████▋| 2329/2404 [48:23<01:34,  1.25s/it]

https://hiring.cafe/job/nelkd1xjt8y4l1wq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nelkd1xjt8y4l1wq.json.gz

 97%|█████████▋| 2330/2404 [48:24<01:35,  1.29s/it]

https://hiring.cafe/job/qx0z8uhi0pcp7h5t
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qx0z8uhi0pcp7h5t.json.gz

 97%|█████████▋| 2331/2404 [48:25<01:29,  1.23s/it]

https://hiring.cafe/job/jf4vj3bmhsko5f6a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jf4vj3bmhsko5f6a.json.gz

 97%|█████████▋| 2332/2404 [48:27<01:31,  1.26s/it]

https://hiring.cafe/job/26hn2zggp9odrdt0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\26hn2zggp9odrdt0.json.gz

 97%|█████████▋| 2333/2404 [48:28<01:30,  1.28s/it]

https://hiring.cafe/job/qq6ecrywljbjib0q
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qq6ecrywljbjib0q.json.gz

 97%|█████████▋| 2334/2404 [48:29<01:32,  1.32s/it]

https://hiring.cafe/job/26c1a8uk127oqao1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\26c1a8uk127oqao1.json.gz

 97%|█████████▋| 2335/2404 [48:31<01:29,  1.29s/it]

https://hiring.cafe/job/rkrn3k1up9d76sml
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\rkrn3k1up9d76sml.json.gz

 97%|█████████▋| 2336/2404 [48:32<01:39,  1.46s/it]

https://hiring.cafe/job/cytw52zgtn5cqven
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\cytw52zgtn5cqven.json.gz

 97%|█████████▋| 2337/2404 [48:34<01:33,  1.39s/it]

https://hiring.cafe/job/4t2sxmybtiz09908
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4t2sxmybtiz09908.json.gz

 97%|█████████▋| 2338/2404 [48:35<01:34,  1.43s/it]

https://hiring.cafe/job/e9u3a4jubonld6ai
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\e9u3a4jubonld6ai.json.gz

 97%|█████████▋| 2339/2404 [48:37<01:30,  1.40s/it]

https://hiring.cafe/job/uziyxs1o27bnindd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\uziyxs1o27bnindd.json.gz

 97%|█████████▋| 2340/2404 [48:38<01:31,  1.43s/it]

https://hiring.cafe/job/dhe1rr080ebni1en
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\dhe1rr080ebni1en.json.gz

 97%|█████████▋| 2341/2404 [48:39<01:29,  1.42s/it]

https://hiring.cafe/job/bhogkpufiy5vwv3u
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bhogkpufiy5vwv3u.json.gz

 97%|█████████▋| 2342/2404 [48:41<01:33,  1.51s/it]

https://hiring.cafe/job/lkr715d5rndvhkbz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lkr715d5rndvhkbz.json.gz

 97%|█████████▋| 2343/2404 [48:43<01:35,  1.57s/it]

https://hiring.cafe/job/t4pxy1hatda0e9wt
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\t4pxy1hatda0e9wt.json.gz

 98%|█████████▊| 2344/2404 [48:44<01:28,  1.47s/it]

https://hiring.cafe/job/vplt5mkhbvjbkedk
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\vplt5mkhbvjbkedk.json.gz

 98%|█████████▊| 2345/2404 [48:45<01:20,  1.36s/it]

https://hiring.cafe/job/resxm3h2yjxde5pd
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\resxm3h2yjxde5pd.json.gz

 98%|█████████▊| 2346/2404 [48:46<01:17,  1.33s/it]

https://hiring.cafe/job/alfj2n37qkt9k58d
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\alfj2n37qkt9k58d.json.gz

 98%|█████████▊| 2347/2404 [48:48<01:13,  1.29s/it]

https://hiring.cafe/job/ofmnbitjxu32iwsy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ofmnbitjxu32iwsy.json.gz

 98%|█████████▊| 2348/2404 [48:49<01:18,  1.39s/it]

https://hiring.cafe/job/me0cn60g2zzesxp0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\me0cn60g2zzesxp0.json.gz

 98%|█████████▊| 2349/2404 [48:51<01:19,  1.45s/it]

https://hiring.cafe/job/w7qh6htjum647b1p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\w7qh6htjum647b1p.json.gz

 98%|█████████▊| 2350/2404 [48:52<01:15,  1.40s/it]

https://hiring.cafe/job/862zn43jecjm9f00
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\862zn43jecjm9f00.json.gz

 98%|█████████▊| 2351/2404 [48:54<01:15,  1.42s/it]

https://hiring.cafe/job/wcgxm1hdqca15wg7
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wcgxm1hdqca15wg7.json.gz

 98%|█████████▊| 2352/2404 [48:55<01:13,  1.41s/it]

https://hiring.cafe/job/wef3uw1302rzsodw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wef3uw1302rzsodw.json.gz

 98%|█████████▊| 2353/2404 [48:56<01:08,  1.35s/it]

https://hiring.cafe/job/951675qxt3q2kbqx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\951675qxt3q2kbqx.json.gz

 98%|█████████▊| 2354/2404 [48:58<01:08,  1.36s/it]

https://hiring.cafe/job/xqjkmes6cidbxlxe
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\xqjkmes6cidbxlxe.json.gz

 98%|█████████▊| 2355/2404 [48:59<01:06,  1.36s/it]

https://hiring.cafe/job/79unoxcu667wvhme
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\79unoxcu667wvhme.json.gz

 98%|█████████▊| 2356/2404 [49:01<01:08,  1.43s/it]

https://hiring.cafe/job/wkcsajdfhz4qh2g9
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wkcsajdfhz4qh2g9.json.gz

 98%|█████████▊| 2357/2404 [49:02<01:03,  1.35s/it]

https://hiring.cafe/job/hrdi3qqy1z824aag
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\hrdi3qqy1z824aag.json.gz

 98%|█████████▊| 2358/2404 [49:03<00:59,  1.30s/it]

https://hiring.cafe/job/kb2gdjhj86m288n8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\kb2gdjhj86m288n8.json.gz

 98%|█████████▊| 2359/2404 [49:04<00:54,  1.20s/it]

https://hiring.cafe/job/qss5xli42p7s4p4w
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qss5xli42p7s4p4w.json.gz

 98%|█████████▊| 2360/2404 [49:05<00:51,  1.16s/it]

https://hiring.cafe/job/z1ndvo6s3rjab6t1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\z1ndvo6s3rjab6t1.json.gz

 98%|█████████▊| 2361/2404 [49:06<00:54,  1.27s/it]

https://hiring.cafe/job/00i3f8zulwhzb4ej
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\00i3f8zulwhzb4ej.json.gz

 98%|█████████▊| 2362/2404 [49:08<00:56,  1.33s/it]

https://hiring.cafe/job/76yapq2ktmg7nc7a
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\76yapq2ktmg7nc7a.json.gz

 98%|█████████▊| 2363/2404 [49:09<00:56,  1.37s/it]

https://hiring.cafe/job/7izcsl5tcmwxy3fx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7izcsl5tcmwxy3fx.json.gz

 98%|█████████▊| 2364/2404 [49:11<00:54,  1.37s/it]

https://hiring.cafe/job/bd00dt2r5y5k6wn8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bd00dt2r5y5k6wn8.json.gz

 98%|█████████▊| 2365/2404 [49:12<00:52,  1.33s/it]

https://hiring.cafe/job/854dgk8afslacg0y
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\854dgk8afslacg0y.json.gz

 98%|█████████▊| 2366/2404 [49:13<00:51,  1.37s/it]

https://hiring.cafe/job/9qpqk26z2acc52em
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9qpqk26z2acc52em.json.gz

 98%|█████████▊| 2367/2404 [49:15<00:49,  1.35s/it]

https://hiring.cafe/job/5fgd5o6oq4nnrdx8
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5fgd5o6oq4nnrdx8.json.gz

 99%|█████████▊| 2368/2404 [49:16<00:50,  1.40s/it]

https://hiring.cafe/job/fwz5q453mt0quu54
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fwz5q453mt0quu54.json.gz

 99%|█████████▊| 2369/2404 [49:18<00:48,  1.37s/it]

https://hiring.cafe/job/ntwvv9elvn8dby45
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ntwvv9elvn8dby45.json.gz

 99%|█████████▊| 2370/2404 [49:19<00:46,  1.36s/it]

https://hiring.cafe/job/nb76aqtwpqmoxckv
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\nb76aqtwpqmoxckv.json.gz

 99%|█████████▊| 2371/2404 [49:20<00:46,  1.40s/it]

https://hiring.cafe/job/g7qkuw0kmglguecf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\g7qkuw0kmglguecf.json.gz

 99%|█████████▊| 2372/2404 [49:22<00:43,  1.35s/it]

https://hiring.cafe/job/x7040uipnkgl2wef
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\x7040uipnkgl2wef.json.gz

 99%|█████████▊| 2373/2404 [49:23<00:43,  1.40s/it]

https://hiring.cafe/job/ajiaz6pog4sasj2m
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ajiaz6pog4sasj2m.json.gz

 99%|█████████▉| 2374/2404 [49:24<00:39,  1.33s/it]

https://hiring.cafe/job/236wstqur89188kr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\236wstqur89188kr.json.gz

 99%|█████████▉| 2375/2404 [49:26<00:38,  1.32s/it]

https://hiring.cafe/job/wfitxdb3borpjgaw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wfitxdb3borpjgaw.json.gz

 99%|█████████▉| 2376/2404 [49:27<00:35,  1.27s/it]

https://hiring.cafe/job/ezqs0ea5cb745g5n
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ezqs0ea5cb745g5n.json.gz

 99%|█████████▉| 2377/2404 [49:28<00:34,  1.29s/it]

https://hiring.cafe/job/7y3lzczsc9ra8ywu
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\7y3lzczsc9ra8ywu.json.gz

 99%|█████████▉| 2378/2404 [49:30<00:34,  1.31s/it]

https://hiring.cafe/job/4dgw2va8tx2oc41z
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\4dgw2va8tx2oc41z.json.gz

 99%|█████████▉| 2379/2404 [49:31<00:31,  1.24s/it]

https://hiring.cafe/job/9po7sdrply5g2756
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\9po7sdrply5g2756.json.gz

 99%|█████████▉| 2380/2404 [49:32<00:31,  1.33s/it]

https://hiring.cafe/job/h27ohuzkxmvxapai
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\h27ohuzkxmvxapai.json.gz

 99%|█████████▉| 2381/2404 [49:33<00:30,  1.31s/it]

https://hiring.cafe/job/jrvlcfyyiweolnsq
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jrvlcfyyiweolnsq.json.gz

 99%|█████████▉| 2382/2404 [49:35<00:30,  1.37s/it]

https://hiring.cafe/job/ca85eo41wtiydok1
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ca85eo41wtiydok1.json.gz

 99%|█████████▉| 2383/2404 [49:36<00:27,  1.29s/it]

https://hiring.cafe/job/6hm284dxluspvtpi
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6hm284dxluspvtpi.json.gz

 99%|█████████▉| 2384/2404 [49:37<00:25,  1.28s/it]

https://hiring.cafe/job/do2jaek1jboek6mr
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\do2jaek1jboek6mr.json.gz

 99%|█████████▉| 2385/2404 [49:38<00:23,  1.21s/it]

https://hiring.cafe/job/ktc2nuefgc5ygkiy
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ktc2nuefgc5ygkiy.json.gz

 99%|█████████▉| 2386/2404 [49:40<00:22,  1.24s/it]

https://hiring.cafe/job/chmnbq0e9tdwatnw
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\chmnbq0e9tdwatnw.json.gz

 99%|█████████▉| 2387/2404 [49:41<00:20,  1.22s/it]

https://hiring.cafe/job/qaz0ih0jh6ubikmh
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\qaz0ih0jh6ubikmh.json.gz

 99%|█████████▉| 2388/2404 [49:42<00:19,  1.23s/it]

https://hiring.cafe/job/padq6uxdckqpbbcb
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\padq6uxdckqpbbcb.json.gz

 99%|█████████▉| 2389/2404 [49:43<00:18,  1.23s/it]

https://hiring.cafe/job/5tt7c00kjwpb7d13
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5tt7c00kjwpb7d13.json.gz

 99%|█████████▉| 2390/2404 [49:44<00:16,  1.21s/it]

https://hiring.cafe/job/6y6dc9n6g86bgset
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6y6dc9n6g86bgset.json.gz

 99%|█████████▉| 2391/2404 [49:45<00:14,  1.13s/it]

https://hiring.cafe/job/jz47fc7abo5dv1xx
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jz47fc7abo5dv1xx.json.gz

100%|█████████▉| 2392/2404 [49:47<00:14,  1.20s/it]

https://hiring.cafe/job/6eky8dslnw5qhr2h
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\6eky8dslnw5qhr2h.json.gz

100%|█████████▉| 2393/2404 [49:48<00:13,  1.23s/it]

https://hiring.cafe/job/wkor6958av287qqm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\wkor6958av287qqm.json.gz

100%|█████████▉| 2394/2404 [49:49<00:12,  1.23s/it]

https://hiring.cafe/job/zlizz8aj8a80wppf
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\zlizz8aj8a80wppf.json.gz

100%|█████████▉| 2395/2404 [49:50<00:10,  1.18s/it]

https://hiring.cafe/job/ytxzvzyesya2hs0p
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\ytxzvzyesya2hs0p.json.gz

100%|█████████▉| 2396/2404 [49:51<00:09,  1.14s/it]

https://hiring.cafe/job/u15wxlh7eughj5xm
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\u15wxlh7eughj5xm.json.gz

100%|█████████▉| 2397/2404 [49:53<00:08,  1.18s/it]

https://hiring.cafe/job/5tnf0i4ajvj1dfnz
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5tnf0i4ajvj1dfnz.json.gz

100%|█████████▉| 2398/2404 [49:54<00:07,  1.23s/it]

https://hiring.cafe/job/bg2ujmc2u5paxr7x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\bg2ujmc2u5paxr7x.json.gz

100%|█████████▉| 2399/2404 [49:55<00:06,  1.25s/it]

https://hiring.cafe/job/5i05oeddwfk9va3x
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\5i05oeddwfk9va3x.json.gz

100%|█████████▉| 2400/2404 [49:57<00:05,  1.28s/it]

https://hiring.cafe/job/jog9f75uy73319g0
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\jog9f75uy73319g0.json.gz

100%|█████████▉| 2401/2404 [49:58<00:03,  1.28s/it]

https://hiring.cafe/job/twz3x4h3gqfws2kp
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\twz3x4h3gqfws2kp.json.gz

100%|█████████▉| 2402/2404 [49:59<00:02,  1.26s/it]

https://hiring.cafe/job/fgzu1yrbdug37j95
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\fgzu1yrbdug37j95.json.gz

100%|█████████▉| 2403/2404 [50:00<00:01,  1.22s/it]

https://hiring.cafe/job/lfa4iw7p25ejvdu4
Writing: C:\Users\Alex\Dev\job-search\data\cache\json\lfa4iw7p25ejvdu4.json.gz

100%|██████████| 2404/2404 [50:01<00:00,  1.25s/it]

In [371]:
url = 'https://hiring.cafe/job/2xztjhutpo56dvg9'

In [382]:
import json
import lxml.html

url_get_content = sc.requests_get(url)
root = lxml.html.fromstring(url_get_content)
_next_data_list = root.xpath("//script[@id='__NEXT_DATA__']")
if len(_next_data_list) == 0:
    jobs_dict = {}
else:
    _next_data = root.xpath("//script[@id='__NEXT_DATA__']")[0]
    jobs_dict = json.loads(_next_data.text_content())
    jobs_dict = jobs_dict.get('props', jobs_dict)

In [395]:
(P_json := jb.P_CACHE / 'json' / '2xztjhutpo56dvg9.json.gz').exists()

False

In [508]:
# glob_str = P_CACHE / 'jso
glob_str = '../data/cache/json/*.json.gz'
json_gz_paths = sorted([Path(path) for path in glob.glob(glob_str, recursive=True)])
# pl_df = pl.read_ndjson(json_gz_paths)
json_gz_list = []
for P_json_gz in tqdm(json_gz_paths):
    _json_gz_df = pd.read_json(P_json_gz, lines=True, compression='gzip')
    json_gz_list.append(_json_gz_df)
pl_df = pd.concat(json_gz_list)
_pageProps = pl_df['pageProps']

100%|██████████| 2402/2402 [00:19<00:00, 125.32it/s]

In [510]:
json_gz_df = pd.DataFrame({
    'hits': _pageProps,
})
json_gz_df['st_mtime'] = pd.to_datetime([p.stat().st_mtime for p in json_gz_paths], unit='s')
json_gz_df['st_size'] = [p.stat().st_size for p in json_gz_paths]
json_gz_df = json_gz_df[json_gz_df['hits'].str.len() == 1].reset_index(drop=True)

In [ ]:
df['hits']

,hits,st_mtime,st_size
0,{'job': {'id': 'ashby___zodl___cee86612-7f08-4...,2026-05-30 01:37:59.529092311,5923
1,{'job': {'id': 'grnhse___folxhealth___51379940...,2026-05-30 02:03:15.041346312,10616
2,{'job': {'id': 'utipro___bet1003beth___a446e30...,2026-05-30 01:31:02.924612761,4662
3,{'job': {'id': 'workday___medtronic-wd1-medtro...,2026-05-30 01:58:54.926348686,7709
4,{'job': {'id': 'workday___uw-wd5-uwhires___dat...,2026-05-30 01:20:11.853490114,7555
...,...,...,...
2392,"{'job': {'id': 'adhoc___amazon___10421923', 'b...",2026-05-30 01:52:35.829968691,4580
2393,{'job': {'id': 'grnhse___companycam___77484430...,2026-05-30 01:18:07.847062111,6029
2394,{'job': {'id': 'ttcportals___syneoshealthcaree...,2026-05-30 01:24:07.176661015,5840
2395,{'job': {'id': 'workday___roche-wd3-roche-ext_...,2026-05-30 01:35:51.281837940,5302
2396,{'job': {'id': 'workday___humana-wd5-humana_ex...,2026-05-30 01:34:02.561345577,4490

In [ ]:
df = json_gz_df#.explode('hits')
job = df['hits'].str['job']
job_info = job.str['job_information']
v5_processed = job.str['v5_processed_job_data']
v5_company_data = job.str['v5_processed_company_data'].apply(lambda x: x if isinstance(x, dict) else {})
company_data = job.str['enriched_company_data']

df['requisition_id'] = job.str['requisition_id']
df['job_id'] = job.str['id']
df['board_token'] = job.str['board_token'].astype(str)
df['source'] = job.str['source']
df['apply_url'] = job.str['apply_url']
df['collapse_key'] = job.str['collapse_key']
df['is_expired'] = job.str['is_expired']

# Job information
df['title'] = job_info.str['title']
df['job_title_raw'] = job_info.str['job_title_raw']
df['description'] = job_info.str['description']
df['core_job_title'] = v5_processed.str['core_job_title']
df['requirements_summary'] = v5_processed.str['requirements_summary']

# Structured data
df['technical_tools'] = v5_processed.str['technical_tools']
df['licenses_certifications'] = v5_processed.str['licenses_or_certifications']
df['role_activities'] = v5_processed.str['role_activities']
df['language_requirements'] = v5_processed.str['language_requirements']

# Degree requirements
df['associates_degree_requirement'] = v5_processed.str['associates_degree_requirement']
df['associates_degree_fields'] = v5_processed.str['associates_degree_fields_of_study']
df['bachelors_degree_requirement'] = v5_processed.str['bachelors_degree_requirement']
df['bachelors_degree_fields'] = v5_processed.str['bachelors_degree_fields_of_study']
df['masters_degree_requirement'] = v5_processed.str['masters_degree_requirement']
df['masters_degree_fields'] = v5_processed.str['masters_degree_fields_of_study']
df['doctorate_degree_requirement'] = v5_processed.str['doctorate_degree_requirement']
df['doctorate_degree_fields'] = v5_processed.str['doctorate_degree_fields_of_study']
df['is_high_school_required'] = v5_processed.str['is_high_school_required']

# Experience requirements
df['min_industry_role_yoe'] = v5_processed.str['min_industry_and_role_yoe']
df['is_min_industry_role_yoe_not_mentioned'] = v5_processed.str['is_min_industry_and_role_yoe_not_mentioned']
df['min_management_leadership_yoe'] = v5_processed.str['min_management_and_leadership_yoe']
df['is_min_management_leadership_yoe_not_mentioned'] = v5_processed.str['is_min_management_and_leadership_yoe_not_mentioned']

# Role details
df['job_category'] = v5_processed.str['job_category']
df['commitment'] = v5_processed.str['commitment']
df['role_type'] = v5_processed.str['role_type']
df['seniority_level'] = v5_processed.str['seniority_level']

# Workplace
df['workplace_type'] = v5_processed.str['workplace_type']
df['workplace_physical_environment'] = v5_processed.str['workplace_physical_environment']
df['formatted_workplace_location'] = v5_processed.str['formatted_workplace_location']
df['is_workplace_worldwide_ok'] = v5_processed.str['is_workplace_worldwide_ok']
df['workplace_cities'] = v5_processed.str['workplace_cities']
df['workplace_counties'] = v5_processed.str['workplace_counties']
df['workplace_states'] = v5_processed.str['workplace_states']
df['workplace_countries'] = v5_processed.str['workplace_countries']
df['workplace_continents'] = v5_processed.str['workplace_continents']
df['boundless_workplace_states'] = v5_processed.str['boundless_workplace_states']
df['boundless_workplace_countries'] = v5_processed.str['boundless_workplace_countries']
df['boundless_workplace_continents'] = v5_processed.str['boundless_workplace_continents']
df['number_of_workplace_cities'] = v5_processed.str['number_of_workplace_cities']
df['number_of_workplace_counties'] = v5_processed.str['number_of_workplace_counties']
df['number_of_workplace_states'] = v5_processed.str['number_of_workplace_states']
df['number_of_workplace_countries'] = v5_processed.str['number_of_workplace_countries']
df['number_of_workplace_continents'] = v5_processed.str['number_of_workplace_continents']

# Work conditions
df['oral_communication_level'] = v5_processed.str['oral_communication_level']
df['physical_labor_intensity'] = v5_processed.str['physical_labor_intensity']
df['physical_position'] = v5_processed.str['physical_position']
df['computer_usage'] = v5_processed.str['computer_usage']
df['cognitive_demand'] = v5_processed.str['cognitive_demand']
df['air_travel_requirement'] = v5_processed.str['air_travel_requirement']
df['land_travel_requirement'] = v5_processed.str['land_travel_requirement']
df['morning_shift_work'] = v5_processed.str['morning_shift_work']
df['evening_shift_work'] = v5_processed.str['evening_shift_work']
df['overnight_work'] = v5_processed.str['overnight_work']
df['on_call_requirement'] = v5_processed.str['on_call_requirement']
df['weekend_availability_required'] = v5_processed.str['weekend_availability_required']
df['holiday_availability_required'] = v5_processed.str['holiday_availability_required']
df['overtime_required'] = v5_processed.str['overtime_required']

# Compensation
df['yearly_min_compensation'] = v5_processed.str['yearly_min_compensation']
df['yearly_max_compensation'] = v5_processed.str['yearly_max_compensation']
df['monthly_min_compensation'] = v5_processed.str['monthly_min_compensation']
df['monthly_max_compensation'] = v5_processed.str['monthly_max_compensation']
df['weekly_min_compensation'] = v5_processed.str['weekly_min_compensation']
df['weekly_max_compensation'] = v5_processed.str['weekly_max_compensation']
df['hourly_min_compensation'] = v5_processed.str['hourly_min_compensation']
df['hourly_max_compensation'] = v5_processed.str['hourly_max_compensation']
df['biweekly_min_compensation'] = v5_processed.str['bi-weekly_min_compensation']
df['biweekly_max_compensation'] = v5_processed.str['bi-weekly_max_compensation']
df['daily_min_compensation'] = v5_processed.str['daily_min_compensation']
df['daily_max_compensation'] = v5_processed.str['daily_max_compensation']
df['is_compensation_transparent'] = v5_processed.str['is_compensation_transparent']
df['listed_compensation_currency'] = v5_processed.str['listed_compensation_currency']
df['listed_compensation_frequency'] = v5_processed.str['listed_compensation_frequency']

# Benefits
df['four_oh_one_k_matching'] = v5_processed.str['401k_matching']
df['generous_paid_time_off'] = v5_processed.str['generous_paid_time_off']
df['four_day_work_week'] = v5_processed.str['four_day_work_week']
df['tuition_reimbursement'] = v5_processed.str['tuition_reimbursement']
df['retirement_plan'] = v5_processed.str['retirement_plan']
df['generous_parental_leave'] = v5_processed.str['generous_parental_leave']
df['fair_chance'] = v5_processed.str['fair_chance']
df['visa_sponsorship'] = v5_processed.str['visa_sponsorship']
df['relocation_assistance'] = v5_processed.str['relocation_assistance']
df['military_veterans'] = v5_processed.str['military_veterans']

# Other
df['security_clearance'] = v5_processed.str['security_clearance']
df['is_driver_license_required'] = v5_processed.str['is_driver_license_required']
df['position_employer_type'] = v5_processed.str['position_employer_type']
df['company_sector_and_industry'] = v5_processed.str['company_sector_and_industry']

# Dates
_estimated_publish_date = v5_processed.str['estimated_publish_date']
# if isinstance(_estimated_publish_date, int):
#     _estimated_publish_date = datetime.fromtimestamp(_estimated_publish_date / 1000)
df['estimated_publish_date'] = _estimated_publish_date
df['estimated_publish_date_millis'] = v5_processed.str['estimated_publish_date_millis']

_v5_is_public = v5_company_data.str['is_public']
# _v5_org_type = {True: 'Public', False: 'Private'}.get(_v5_is_public)
# if v5_company_data.get('is_non_profit'):
#     _v5_org_type = 'Non-Profit'
_v5_org_type = _v5_is_public.map({True: 'Public', False: 'Private'})
_v5_org_type.loc[v5_company_data.str['is_non_profit'].astype(bool)] = 'Non-Profit'

df = pd.concat([df,
    # User interactions
    job_info.str['hiddenFromUsers'].rename('hiddenFromUsers'),
    job_info.str['viewedByUsers'].rename('viewedByUsers'),
    job_info.str['applied_from_users'].rename('applied_from_users'),

    # Enriched Company data (embedded)
    company_data.str['enriched_at'].rename('company_enriched_at'),
    company_data.str['status'].rename('company_status'),
    company_data.str['name'].fillna(v5_processed.str['company_name']).fillna(v5_company_data.str['name']).rename('company_name'),
    company_data.str['homepage_uri'].fillna(v5_processed.str['company_website']).fillna(v5_company_data.str['website']).rename('company_homepage_uri'),
    company_data.str['hq_country'].fillna(v5_company_data.str['headquarters_country']).rename('company_hq_country'),
    company_data.str['parent_company'].fillna(v5_company_data.str['parent_company']).rename('company_parent_company'),
    company_data.str['subsidiaries'].fillna(v5_company_data.str['subsidiaries']).rename('company_subsidiaries'),
    company_data.str['industries'].fillna(v5_company_data.str['industries']).rename('company_industries'),
    company_data.str['activities'].fillna(v5_processed.str['company_activities']).fillna(v5_company_data.str['activities']).apply(lambda x: x if isinstance(x, list) else []).rename('company_activities'),
    company_data.str['nb_employees'].fillna(v5_company_data.str['number_employees'].astype(float)).rename('company_nb_employees'),
    company_data.str['year_founded'].fillna(v5_company_data.str['year_founded'].astype(float)).rename('company_year_founded'),
    company_data.str['tagline'].fillna(v5_processed.str['tagline']).fillna(v5_company_data.str['tagline']).rename('company_tagline'),
    company_data.str['organization_type'].fillna(_v5_org_type).rename('company_organization_type'),
    company_data.str['latest_funding_investors'].fillna(v5_company_data.str['investors']).rename('company_latest_funding_investors)'),
    company_data.str['latest_funding_type'].fillna(v5_company_data.str['latest_funding_series']).rename('company_latest_funding_type'),
    company_data.str['latest_funding_year'].fillna(v5_company_data.str['latest_funding_year'].astype(float)).rename('company_latest_funding_year'),
    company_data.str['latest_funding_amount'].fillna(v5_company_data.str['latest_funding_amount'].astype(float)).rename('company_latest_funding_amount'),
    company_data.str['stock_exchange'].fillna(v5_company_data.str['stock_exchange']).rename('company_stock_exchange'),
    company_data.str['stock_symbol'].fillna(v5_company_data.str['stock_exchange']).rename('company_stock_symbol'),

    # Extract location arrays
    job.str['_geoloc'].apply(lambda x: x if isinstance(x, list) else []).apply(lambda x_list: [x.get('lon') for x in x_list] if not isinstance(x_list, float) else []).rename('location_longitudes'),
    job.str['_geoloc'].apply(lambda x: x if isinstance(x, list) else []).apply(lambda x_list: [x.get('lat') for x in x_list] if not isinstance(x_list, float) else []).rename('location_latitudes'),
], axis=1).drop(columns='hits').reset_index(drop=True)

In [540]:
hash_set = set(df['requisition_id'])

In [581]:
x_df = df.sort_values(['estimated_publish_date', 'requisition_id']).reset_index(drop=True).drop(columns=['st_mtime', 'st_size', 'is_expired'])
y_df = all_df.query('requisition_id in @hash_set').sort_values(['estimated_publish_date', 'requisition_id']).reset_index(drop=True).drop(columns=['st_mtime', 'st_size', 'is_expired'])

In [570]:
x_df.shape, y_df.shape

((2397, 119), (2397, 119))

In [571]:
x_df.columns[:1]

Index(['requisition_id'], dtype='object')

In [ ]:
# x_df[x_df.columns[118:]].equals(y_df[x_df.columns[118:]])

# x_df[x_df.columns[:9]].equals(y_df[x_df.columns[:9]])
x_df[x_df.columns[118:]].equals(y_df[x_df.columns[118:]])

True

In [610]:
eq_list = []
neq_list = []
for col in x_df.columns:
    if x_df[col].equals(y_df[col]):
        eq_list.append(col)
    else:
        neq_list.append(col)
eq_list = pd.Series(eq_list)
neq_list = pd.Series(neq_list)

In [606]:
len(eq_list), len(neq_list)

(58, 60)

In [628]:
x_df['hiddenFromUsers'] = x_df['hiddenFromUsers'].apply(lambda x: x if isinstance(x, list) else [])
y_df['hiddenFromUsers'] = y_df['hiddenFromUsers'].apply(lambda x: x if isinstance(x, list) else [])

In [646]:
nperc_list = []
for ncol in neq_list:
    if isinstance(x_df[ncol].iloc[0], list):
        nperc_list.append(sum(x_df[ncol].str.len() == y_df[ncol].str.len()))
    # elif isinstance(x_df[ncol].iloc[0], dict):
    #     nperc_list.append(sum(x_df[ncol].str.len() == y_df[ncol].str.len()))
    else:
        nperc_list.append(perc := sum(x_df[ncol] == y_df[ncol]))
    print(f'{ncol}: {perc/len(x_df):.2f}')

description: 0.00
technical_tools: 0.00
licenses_certifications: 0.00
role_activities: 0.00
language_requirements: 0.00
associates_degree_fields: 0.00
bachelors_degree_fields: 0.00
masters_degree_fields: 0.00
doctorate_degree_fields: 0.00
is_high_school_required: 1.00
is_min_management_leadership_yoe_not_mentioned: 1.00
commitment: 1.00
is_workplace_worldwide_ok: 1.00
workplace_cities: 1.00
workplace_counties: 1.00
workplace_states: 1.00
workplace_countries: 1.00
workplace_continents: 1.00
boundless_workplace_states: 1.00
boundless_workplace_countries: 1.00
boundless_workplace_continents: 1.00
number_of_workplace_cities: 1.00
number_of_workplace_counties: 1.00
number_of_workplace_states: 1.00
number_of_workplace_countries: 1.00
number_of_workplace_continents: 1.00
weekend_availability_required: 1.00
holiday_availability_required: 1.00
overtime_required: 1.00
monthly_min_compensation: 0.92
monthly_max_compensation: 0.92
weekly_min_compensation: 0.92
weekly_max_compensation: 0.92
hourly_min_compensation: 0.91
hourly_max_compensation: 0.91
biweekly_min_compensation: 0.92
biweekly_max_compensation: 0.92
daily_min_compensation: 0.92
daily_max_compensation: 0.92
is_compensation_transparent: 1.00
four_oh_one_k_matching: 1.00
generous_paid_time_off: 1.00
four_day_work_week: 1.00
tuition_reimbursement: 1.00
retirement_plan: 1.00
generous_parental_leave: 1.00
fair_chance: 1.00
visa_sponsorship: 1.00
relocation_assistance: 1.00
military_veterans: 1.00
is_driver_license_required: 1.00
estimated_publish_date_millis: 1.00
hiddenFromUsers: 1.00
viewedByUsers: 1.00
company_subsidiaries: 1.00
company_industries: 1.00
company_activities: 1.00
company_latest_funding_investors): 1.00
location_longitudes: 1.00
location_latitudes: 1.00

In [653]:
df_all = pd.concat([
    df,
    all_df.query('requisition_id not in @hash_set')
]).sort_values(['estimated_publish_date', 'requisition_id'], ascending=[False, True], ignore_index=True)
df_all

,st_mtime,st_size,requisition_id,job_id,board_token,source,apply_url,collapse_key,is_expired,title,...,company_tagline,company_organization_type,company_latest_funding_investors),company_latest_funding_type,company_latest_funding_year,company_latest_funding_amount,company_stock_exchange,company_stock_symbol,location_longitudes,location_latitudes
0,2026-05-30 01:15:46.931586981,4913,x1sbbwkw28y6qvrz,adhoc___meta___2082565018957406,meta,adhoc,https://www.metacareers.com/profile/job_detail...,fb54cc67bc7ac6dc83434a9f2757d7b4aa6a280ee4d859...,False,"Lead, Product Content Engineering",...,Meta develops social networking platforms and ...,Public,None,None,NaN,NaN,NASDAQ,META,"[-122.1491, -74.006, -122.4194]","[37.4542, 40.7128, 37.7749]"
1,2026-05-30 01:22:40.010107756,6778,iohikrbigmby2tgq,governmentjobs___iowa___5359123,iowa,governmentjobs,https://www.governmentjobs.com/careers/iowa/jo...,29b07a1d0db3d9708c6c24fa487578ec7277ded146e5fb...,False,Business Systems Analyst (SCA 111262),...,Provides government administration and public ...,Government,None,None,NaN,NaN,None,None,[-93.617],[41.5825]
2,2026-05-30 01:23:06.212635040,4689,459t9gaqb9umtx4w,successfactors___com___gainwellte___1357001600,com_gainwellte,successfactors,https://jobs.gainwelltechnologies.com/job/Any-...,1122d9601599bf11bf0874ac558479db718e9abd6b6f9b...,False,Senior Data Mining & Payment Integrity Analyst...,...,Delivers technology solutions for public healt...,Private,[Veritas Capital],Private Equity,2020.0,5.000000e+09,None,None,[],[]
3,2026-05-30 01:18:20.974421501,4726,fv9jmij90efjspne,icims2___aarp___7416,aarp,icims2,https://careers.aarp.org/jobs/7416?lang=en-us,5e4e29acf02c11b51245fdc80c66b3ed12e610ebf2f574...,False,"Engineer I, AI Agents",...,Nonprofit advocacy organization serving Americ...,Non-Profit,None,None,NaN,NaN,None,None,[],[]
4,2026-05-30 01:22:41.271778584,5134,p3vqx9j2xl4gx8j2,ashby___talkiatry___c20f10a0-b493-4109-866c-a6...,talkiatry,ashby,https://jobs.ashbyhq.com/talkiatry/c20f10a0-b4...,b41a4402361253056cb20147d1bfad1f86ec7180085a18...,False,Data Engineer,...,None,Private,[Perceptive Advisors],Series D,2026.0,2.100000e+08,None,None,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11109,2026-05-08 22:03:08.651313305,110361,3dp4i78lijqp9dkx,icims___treliantllc___b38ffd47-59cd-46dc-bb8a-...,treliantllc,icims,https://careers-treliant.icims.com/jobs/1803/j...,c4fdab5f4c0db0f98deddc1f7ef85e6e1b012975a7d200...,False,"Consultant, Risk Management",...,Provides compliance and risk management consul...,Private,[Huron Consulting Group],Corporate Round,2025.0,NaN,None,None,[],[]
11110,2026-05-08 22:03:08.651313305,110361,wbf5h3w5tz5zly01,taleo_careersection_s01stantec_230000P8,s01stantec,taleo_careersection,https://s01stantec.taleo.net/careersection/ex1...,cc10f9e7e974fb3278db4d585682047299deea5f615ebb...,False,Utility Economics & Financial Forecasting Analyst,...,Global engineering and architecture firm provi...,Public,None,None,NaN,NaN,New York Stock Exchange,STN,[],[]
11111,2026-05-08 22:03:08.651313305,110361,jxi8mno1sicbn9ks,icims___bottomline___118a1ead-c768-440f-8563-3...,bottomline,icims,https://careers-bottomline.icims.com/jobs/1471...,9d6296e83f0efd2f29f9367d5e63c75152c905ac230c30...,False,Director of Analytics and Reporting,...,Providing college access and graduation suppor...,Non-Profit,None,None,NaN,NaN,None,None,[],[]
11112,2026-05-08 22:03:08.651313305,110361,5l6h3w5mb45sm6wc,breezy___vianai-systems___2709786e7a57,vianai-systems,breezy,https://vianai-systems.breezy.hr/p/2709786e7a5...,6380e5f1d8f422da23a203da1d7a74653ba07a9b256354...,False,Data Scientist,...,Develops artificial intelligence software for ...,Private,[SoftBank Vision Fund 2],Series B,2021.0,1.400000e+08,None,None,[],[]
11113,2026-05-03 00:33:13.021711588,147925,aluhqzbqmbazyabk,smartrecruiters___walgreens7___09cd9a1a-0fd1-4...,walgreens7,smartrecruiters,https://jobs.smartrecruiters.com/Walgreens7/74...,332f7ff41341e4fed1423da10c5d6bd61d45747f5684d1...,False,"Senior Business Systems Analyst ""Hybrid""",...,Operates a retail pharmacy chain and provides ...,Private,[Sycamore Partners],Private Equity,2025.0,1.000000e+10,None,None,[-87.8445119],[42.1711365]

In [655]:
df_all_parquet_df = _process_df(df_all)
df_all_parquet_df.to_parquet(f'../data/cache/df.parquet')